### ISSUE TITLE
Century Egg showing wrong multiplier?

### ISSUE THREAD

**Issue by Treazer** [Aktanusa/CookieMonster#102]
I remember having more than 9% before the update as my run started about 55 days ago. However, it now shows 1.09% and I'm wondering whether this is a bug of CookieMonster, intended behaviour by Cookie Clicker (maybe because the eggs got tweaked) or even a Cookie Clicker bug.
If it's a problem regarding the new Cookie Clicker update and not one regarding CookieMonster, I'm sorry.

**Comment by Aktanusa** [comment]
Hmm, I'll take a look!

**Comment by Treazer** [comment]
Sure!

`Mi4wMDJ8fDE0NjQ1MTgyNjQ4MzM7MTQwNTE3NjA5MDkxMzsxNDY5NTMyMDU4MTc2O01hdXJpY2V8w6XCsMKIBnwzLjAwODI3NDQ1MDgyMDc5NThlKzMyOzkuNzg4ODE0MjkzMzExNTU1ZSszMjs2NDkzOzg5MzQ7Mi42NDU3MjM3NjU4Njc3MzhlKzMxOzE4NTEyODswOzE2OzMuNDQ3MTcyMzY4NjcxOTAxZSszMjsxOzA7MDswOy0xOzE5OzQ4Nzs3LjYxMzMxNzgwNjE4MjU2NGUrMzE7MjA0OzE0OzQxOy0xOzExOzsyLjcyNjgyNjA1ODQyMDUxMjVlKzMyOzEyOzcwMTE2NjI7NTY3OTA3OzY0NDM3NTU7MDswOzMxOTszMDY7MzIyOzMyMTstMTsyMTsxNTsxOzE7MTAwOzA7MDt8NDAwLDc1MCw2Ljc3NTUyNTA5NDEzMjg4MzVlKzI4LDA7NDAwLDc1MCw0LjU0Njk3Nzg4NDE2OTYzNjVlKzI2LDA7NDAwLDc1MCwyLjAyMDg3OTA1OTYzMjMyMWUrMjcsMDszMDAsNjUwLDUuMzQyNjk5MDEzODk2NDg1ZSsyNywwOzMwMCw2NTAsMi4yMjY5MTM5OTUwMTA0NDk4ZSsyOCwwOzMwMCw2NTAsOC4zNTA5Mjc0ODEyNjg3NmUrMjcsMDszMDAsNjUwLDMuOTQ1ODEzMjM0OTA3NTQ2N2UrMjgsMDszMDAsNjUwLDEuNzI4NTUyMTkzNzA3OTU3OGUrMjgsMDszMDAsNjUwLDguMzAzODUzODY5MzI5MTM1ZSsyNywwOzMwMCw2NTAsNC43MjUzNTc0MDI5MTY2OTNlKzI4LDA7MzAwLDY1MCwyLjc2NjMzODI2NDU1MDk1ODdlKzI5LDA7MzAwLDY1MCwxLjc0Mjc5MzEwNjY2NzA5NjRlKzMwLDA7MjkwLDY0MCw5LjM2MDA2NDYyMTA0Mzc3MmUrMjksMDsyNjAsNjEzLDUuNTMzODA1NjQ2NzYwMDI5ZSszMCwwO3zDp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/DpsKAwo/Dp8KzwrzDpMKMwr/DpMK/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wrPDp8K/wr/Dp8K/wr/Dp8Kzwr/Dp8K/wr/Dp8K/wr/Dp8K/wrzDp8K/wr/Dp8K/wr/DpsKqwo/Dp8K/wr/Dp8K/wr/Dp8K/wrLDp8K/wr/Dp8K/wr/Dp8K+wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8Kzwr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K8wr/Dp8K4wq/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wq/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/DocK/woB8w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6XCv8Kfw6fCv8K4w6TCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8Kzw6fCv8K/w6fCscK/w6fCv8K7w6fCv8KA%21END%21`

**Comment by Aktanusa** [comment]
Oh, I see the error, thanks!

**Comment by Treazer** [comment]
Ah, thanks for the quick replies! :) You're doing a great job!

**Comment by Aktanusa** [comment]
No problem, and thanks for the kind words! =)

**Comment by Aktanusa** [comment]
Fixed in Version 2.002.2.
