### ISSUE TITLE
Century Egg - Showing as 1% forever, after ascending.

### ISSUE THREAD

**Issue by JeraSpites** [Aktanusa/CookieMonster#103]
My century egg multiplier is showing as 1%.  It started as 1% after I upgraded to 2.002, and used your beta, and then swapped to the live version for 2.002.  It's supposed to start at 0.01%, was my understanding and slowly work to 10%, but it is stuck at 1%.  Here's my save.

Mi4wMDJ8fDE0Njk0ODgxMDA1NTk7MTQ2ODg2ODAwMjMzMDsxNDY5NTk2NDY3MjU0O0plcmF8w6TCuMKgBXwyLjQ3NjE1NjAxOTY4OTUxOTVlKzMzOzcuMjE4OTk4MDM4ODc3ODA4ZSszNDsxMjkxMDA2MTsxNjk1NDs2LjYwNTkwNDU2MDQ1NjAzNGUrMzQ7OTswOzE0OzMuNDAxNTgwMjQzOTE2MzgyZSszNTswOzI3OzQzNjkwOzA7LTE7MTA7MTA2OTsxLjUxOTkwNjAzMTUzMTkxMDVlKzMwOzcyOzE0OzQzOzIzMzg0ODc7Njtmb29sczswOzA7Njk4MDYxMzE7MzgxNTMxMjk7MzE2NTMwMDI7MDswOzE4OTszMjI7MzE5OzIyNjs1MzsyMTsxOzE1OzA7MDswOzA7fDUwNyw4NTcsMS4zMTAxNzY2NjY1NDc5MzMyZSszMSwwOzUxNSw4NjUsMy4wNDIzMTk1MzA4NDMyNjFlKzI5LDA7NDg0LDgzNCw3LjUwMzc1NjM0MjU0OTYxZSsyOSwwOzQ0OCw3OTgsMi40MjQzNzk0MDY2MDY1MTUyZSszMCwwOzQ1Miw4MDIsOC42MTQxNDIyMTcyMjY0NmUrMzAsMDs0MzAsNzgwLDIuMzg2NTE4OTQ0MTU0NTA1NGUrMzAsMDs0MjIsNzcyLDEuMDE4MjIzNzYyNjc2MTMzM2UrMzEsMDs0MDAsNzUwLDQuNTgwNTE4NDc0Mzk4MDc0ZSszMCwwOzM3NCw3MjQsMi4wMDY2Mjg3MTM1NDI2NTdlKzMwLDA7MzUyLDcwMiw5Ljc2MTg4MTUwODcxMjIzM2UrMzAsMDszNDUsNjk1LDUuODI1ODMwMjU3NDMwMTcyZSszMSwwOzMzMSw2ODEsMy40MjkzMTM2Mzk1NjM4NDRlKzMyLDA7MzA2LDY1OCwxLjc1MTA1NTk0MjUxODYwNThlKzMyLDA7MzAxLDY1NiwxLjAwMzg2MDc0Mzk3OTY3MzNlKzMzLDA7fMOnwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8OnwrPCvMOmwr/Cv8Okwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cs8Onwr/Cv8Onwr/Cv8OnwrPCv8Onwr/Cv8Onwr/Cv8Onwr/CvMOnwr/Cv8Onwr/Cv8OmwqvCj8Onwr/Cv8Onwr/Cv8Onwr/CssOnwr/Cv8Onwr/Cv8Onwr7Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8OnwrvCr8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cr8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Ohwr/Cv3zDp8K/wr/Dp8K/wr/DpsK/wr/Dp8K/wr/Dp8K/wr/DpcK/wp/Dp8K/woDDpMK/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K7wr/Dp8K/wr/Dp8K/wr/Dp8K/wrPDp8K/wr/Dp8K9wr/Dp8K/wr/Dp8K/wr4%3D%21END%21

I don't know if I am breaking any rules have to post saves in some fancy way, but that's it.  Anyways, felt I should report it.  Oh, Everytime I ascend and get the century egg again, it starts at 1% and stays there.

**Comment by Aktanusa** [comment]
You might want to look at issue #102...

**Comment by Aktanusa** [comment]
Fixed in Version 2.002.2
