### ISSUE TITLE
No green building upgrades, only yellow and red

### ISSUE THREAD

**Issue by Jaaap** [Aktanusa/CookieMonster#1030]
### Bug description

As can be seen int he screenshot below, there are no green building upgrades anymore.
So i don't know which building to upgrade next.

### To reproduce

Play CookieClicker for a while with CookieMonster enabled

### Screenshot

<img width="316" alt="image" src="https://user-images.githubusercontent.com/243016/143053916-3c3c9498-8105-4b9d-9a4b-67ab5aea18a1.png">

### Save file

Mi4wMzF8fDE2MzY4MjkwMzAxNjM7MTYzNjgyOTAzMDE2MzsxNjM3NjgxNjMxMzIzO0hlY3RpYyBHcmFuZG1hO2FqeGpmfDAwMTEwMDAwMTAwMDAwMTAwMTAwMHwzMzQ5NTczNDM5MjAwMjc1OzgxOTkwMjQ3NDE5MzIyMTA7MjQxNzs2NjQ7MTAxMTE1Mzg5NTgxOTk1Mi4yOzA7MDswOzA7MDswOzA7MDswOzA7NjY0OzA7MDswOzA7MDswOzswOzA7MDswOzA7MDswOy0xOy0xOy0xOy0xOy0xOzA7MDswOzA7NTA7MDswOzE5Mzg7ODsxNjM3NjA5MTk5MDQ0OzM0NTI7MDs7NDE7MDswOzQ1MDAwNjAwODI4LjcxOTIyO3wxNDAsMTQwLDI3Mjk1MDM4MDY4NywyLCwwLDE0MDsxNzMsMTczLDE4NDcxNjAzNzcyNDcsMSwsMSwxNzM7MTAwLDEwMCwzNjUwMzI1OTQ3NywxMCwxNjM3NjgxNjg5MzM1OjE6MTYzNzQyNDUxMzUyNTowOjQ3OjQ3OjE6MDoxNjM3NDE2ODU3NjcwOiAxMTExMDAwMDAwMDAwMTAwMDAwMDAwMDEwMDAwMDAwMDAwIDI0OjU3OjA6MDoyNDo3NTowOjA6MDowOjA6MDozOjMwOjA6MDozOjMzOjA6MDowOjA6MDowOjA6MDoyNDo2MDowOjA6MDowOjA6MDoyNDoxOTowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDosMCwxMDA7MTAwLDEwMCw4NDczOTk3MjY3OSwwLCwxLDEwMDs4MCw4MCwyOTE2OTY5NTk3MDksMCwsMSw4MDs3MSw3MSwxMjQxOTM4Njg4MTU1LDEsMDowOjE6MDowOiA0NzY6MjotMjc6MjQxOjA6MDowITQxNTM6MTozNjoyODowOjA6MCE1NTUzOjE6NjI6MjE0OjA6MDowITQ2NzI6MjotNDI6MjEyOjA6MDowITY0NTg6MTo0MjoxMDc6MDowOjAhNDIxMjoyOi01Mzo5OTowOjA6MCE1NTU6NDotMTczOjI4MTowOjA6MCE4NjI3OjU6NDI6MTc0OjA6MDowITk3NjQ6MTo0OjQ4MzowOjA6MCExMDY0OToxOjc6MTM6MDowOjAhMTE1ODk6MToxMDo3NDc6MDowOjAhOTgzNjoyOi01NDo0MTk6MDoxOjAhMTAxMTY6MjotNDM6NDgwOjA6MTowITEzNTE5OjU6MjI6NDI3OjA6MTowITE0MTExOjU6LTYwOjE4MTowOjE6MCE3MzIzOjQ6LTIzODozNTA6MDoxOjAhIDAsMSw3MTs2Myw2Myw0Mzg4OTgwODgwODI3LDEsMS80LzEwIDMgMTYzNzQ0MTg4NjM1OSAxLDEsNjM7NTEsNTEsMTI0OTgyMjEwNDEyMDcsMyw3LjkwMzMxMTI4OTI2NzEyMyAyOCAyOCAxLDAsNTE7NDQsNDQsNTMwMjc4NDIwNzkwMzEsMTAsLDEsNDQ7MzgsMzgsMjAyMzAyOTQyNjM0MjY0LDksLDEsMzg7MzEsMzEsNTAxMTk1NTk3NjM3NTg2LDEwLCwxLDMxOzE5LDE5LDQ4MzQ4NzA5NjQ3NDY3NywxMCwsMSwxOTs1LDUsMzAxNzQ0MzQ4OTUxOTk1LDEwLCwxLDU7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDt8MTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMDAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTEwMDExMTEwMDAwMDAwMDExMDAxMTExMTEwMDEwMDAwMDAwMDAwMDAwMTAxMDAwMDAwMDEwMTAxMDEwMDAwMDExMTEwMDExMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDEwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTAwMDAxMTExMTExMTAwMDAxMTExMTExMDAwMDAxMTExMTEwMDAwMDAxMDEwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExfDExMTExMTExMTEwMDAwMDAxMTExMTExMTExMDAwMDExMTExMTExMDAxMTExMTExMTAxMTExMDAxMDAxMDAxMDAwMDAxMTEwMTExMTEwMTAwMDEwMDAwMDEwMDAwMDAwMDAwMDAxMTAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDExMDAwMTEwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDEwMTExMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDB8fENvb2tpZU1vbnN0ZXI6eyJzZXR0aW5ncyI6eyJDUFNNb2RlIjowLCJBdmdDUFNIaXN0IjozLCJBdmdDbGlja3NIaXN0IjowLCJDYWxjV3JpbmsiOjAsIlNjYWxlIjoyLCJTY2FsZURlY2ltYWxzIjoyLCJTY2FsZVNlcGFyYXRvciI6MCwiU2NhbGVDdXRvZmYiOjk5OTk5OSwiVGltZUZvcm1hdCI6MiwiRGV0YWlsZWRUaW1lIjoxLCJQUERpc3BsYXlUaW1lIjowLCJCdWlsZENvbG91ciI6MSwiUFBPbmx5Q29uc2lkZXJCdXlhYmxlIjowLCJQUEV4Y2x1ZGVUb3AiOjAsIlBQUmlnaWRlbE1vZGUiOjAsIlBQU2Vjb25kc0xvd2VyTGltaXQiOjAsIkNvbG91ckJsdWUiOiIjNGJiOGYwIiwiQ29sb3VyR3JlZW4iOiIjMDBmZjAwIiwiQ29sb3VyWWVsbG93IjoiI2ZmZmYwMCIsIkNvbG91ck9yYW5nZSI6IiNmZjdmMDAiLCJDb2xvdXJSZWQiOiIjZmYwMDAwIiwiQ29sb3VyUHVycGxlIjoiI2ZmMDBmZiIsIkNvbG91ckdyYXkiOiIjYjNiM2IzIiwiQ29sb3VyUGluayI6IiNmZjE0OTMiLCJDb2xvdXJCcm93biI6IiM4YjQ1MTMiLCJCb3RCYXIiOjAsIlRpbWVyQmFyIjoxLCJUaW1lckJhclBvcyI6MCwiVGltZXJCYXJPdmVybGF5IjoyLCJBdXRvc2F2ZVRpbWVyQmFyIjowLCJVcEJhckNvbG91ciI6MSwiVXBncmFkZUJhckZpeGVkUG9zIjoxLCJTb3J0QnVpbGRpbmdzIjowLCJTb3J0VXBncmFkZXMiOjAsIlVwZ3JhZGVzTmV2ZXJDb2xsYXBzZSI6MCwiRHJhZ29uQXVyYUluZm8iOjEsIkdyaW1vaXJlQmFyIjoxLCJHQ1RpbWVyIjoxLCJGYXZpY29uIjoxLCJXcmlua2xlckJ1dHRvbnMiOjEsIkhpZGVTZWN0aW9uc0J1dHRvbnMiOjAsIlRvb2x0aXBCdWlsZFVwZ3JhZGUiOjEsIlRvb2x0aXBBbW9yIjowLCJUb29sV2Fybkx1Y2t5IjoxLCJUb29sV2Fybkx1Y2t5RnJlbnp5IjoxLCJUb29sV2FybkNvbmp1cmUiOjEsIlRvb2xXYXJuQ29uanVyZUZyZW56eSI6MSwiVG9vbFdhcm5FZGlmaWNlIjoxLCJUb29sV2FyblVzZXIiOjAsIlRvb2xXYXJuQm9uIjoxLCJUb29sV2FyblBvcyI6MSwiVG9vbHRpcEdyaW0iOjEsIlRvb2x0aXBXcmluayI6MSwiVG9vbHRpcEx1bXAiOjEsIlRvb2x0aXBQbG90cyI6MSwiVG9vbHRpcFBhbnRoZW9uIjoxLCJUb29sdGlwQXNjZW5kQnV0dG9uIjoxLCJTdGF0cyI6MSwiTWlzc2luZ1VwZ3JhZGVzIjoxLCJNaXNzaW5nQWNoaWV2ZW1lbnRzIjowLCJVcFN0YXRzIjoxLCJIZWF2ZW5seUNoaXBzVGFyZ2V0IjoxLCJTaG93TWlzc2VkR0MiOjEsIlRpdGxlIjoxLCJHZW5lcmFsU291bmQiOjEsIkdDTm90aWZpY2F0aW9uIjowLCJHQ0ZsYXNoIjoxLCJDb2xvdXJHQ0ZsYXNoIjoiI2ZmZmZmZiIsIkdDU291bmQiOjEsIkdDVm9sdW1lIjoxMDAsIkdDU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy82Ni82NjcxN185MzE2NTUtbHEubXAzIiwiRm9ydHVuZU5vdGlmaWNhdGlvbiI6MCwiRm9ydHVuZUZsYXNoIjoxLCJDb2xvdXJGb3J0dW5lRmxhc2giOiIjZmZmZmZmIiwiRm9ydHVuZVNvdW5kIjoxLCJGb3J0dW5lVm9sdW1lIjoxMDAsIkZvcnR1bmVTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzE3NC8xNzQwMjdfMzI0MjQ5NC1scS5tcDMiLCJTZWFOb3RpZmljYXRpb24iOjAsIlNlYUZsYXNoIjoxLCJDb2xvdXJTZWFGbGFzaCI6IiNmZmZmZmYiLCJTZWFTb3VuZCI6MSwiU2VhVm9sdW1lIjoxMDAsIlNlYVNvdW5kVVJMIjoiaHR0cHM6Ly93d3cuZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyMS8xMjEwOTlfMjE5MzI2Ni1scS5tcDMiLCJHYXJkRmxhc2giOjEsIkNvbG91ckdhcmRGbGFzaCI6IiNmZmZmZmYiLCJHYXJkU291bmQiOjEsIkdhcmRWb2x1bWUiOjEwMCwiR2FyZFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTAzLzEwMzA0Nl84NjE3MTQtbHEubXAzIiwiTWFnaWNOb3RpZmljYXRpb24iOjAsIk1hZ2ljRmxhc2giOjEsIkNvbG91ck1hZ2ljRmxhc2giOiIjZmZmZmZmIiwiTWFnaWNTb3VuZCI6MSwiTWFnaWNWb2x1bWUiOjEwMCwiTWFnaWNTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzIyMS8yMjE2ODNfMTAxNTI0MC1scS5tcDMiLCJXcmlua2xlck5vdGlmaWNhdGlvbiI6MCwiV3JpbmtsZXJGbGFzaCI6MSwiQ29sb3VyV3JpbmtsZXJGbGFzaCI6IiNmZmZmZmYiLCJXcmlua2xlclNvdW5kIjoxLCJXcmlua2xlclZvbHVtZSI6MTAwLCJXcmlua2xlclNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTI0LzEyNDE4Nl84MDQzLWxxLm1wMyIsIldyaW5rbGVyTWF4Tm90aWZpY2F0aW9uIjowLCJXcmlua2xlck1heEZsYXNoIjoxLCJDb2xvdXJXcmlua2xlck1heEZsYXNoIjoiI2ZmZmZmZiIsIldyaW5rbGVyTWF4U291bmQiOjEsIldyaW5rbGVyTWF4Vm9sdW1lIjoxMDAsIldyaW5rbGVyTWF4U291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNTIvMTUyNzQzXzE1NjYzLWxxLm1wMyIsIkJ1bGtCdXlCbG9jayI6MSwiRmF2b3VyaXRlU2V0dGluZ3MiOjF9LCJoZWFkZXJzIjp7IkZhdm91cml0ZSI6MSwiQ2FsY3VsYXRpb24iOjEsIk5vdGF0aW9uIjoxLCJDb2xvdXJzIjoxLCJCYXJzRGlzcGxheSI6MSwiVG9vbHRpcCI6MSwiU3RhdGlzdGljcyI6MSwiTm90aWZpY2F0aW9uIjoxLCJOb3RpZmljYXRpb25HZW5lcmFsIjoxLCJOb3RpZmljYXRpb25HQyI6MSwiTm90aWZpY2F0aW9uRkMiOjEsIk5vdGlmaWNhdGlvblNlYSI6MSwiTm90aWZpY2F0aW9uR2FyZCI6MSwiTm90aWZpY2F0aW9uTWFnaSI6MSwiTm90aWZpY2F0aW9uV3JpbmsiOjEsIk5vdGlmaWNhdGlvbldyaW5rTWF4IjoxLCJNaXNjZWxsYW5lb3VzIjoxLCJMdWNreSI6MSwiQ2hhaW4iOjEsIlNwZWxscyI6MSwiR2FyZGVuIjoxLCJQcmVzdGlnZSI6MSwiV3JpbmsiOjEsIlNlYSI6MSwiQWNoaWV2cyI6MSwiTWlzYyI6MSwiaW5mb01lbnUiOjEsIm9wdGlvbnNNZW51IjoxfSwiZmF2b3VyaXRlU2V0dGluZ3MiOltdLCJsb2NrZWRNaW5pZ2FtZXMiOltdLCJ2ZXJzaW9uIjoiMi4wMzEuMTAifTtjb29raWVNb25zdGVyRnJhbWV3b3JrOnsic2V0dGluZ3MiOnt9LCJoZWFkZXJzIjp7ImluZm9NZW51IjoxLCJvcHRpb25zTWVudSI6MX0sImZhdm91cml0ZVNldHRpbmdzIjpbXX07%21END%21

### Browser / Steam / Version

Safari 15.1 (16612.2.9.1.30, 16612)
macOS Big Sur 11.6.1

**Comment by DanielNoord** [comment]
The green `10` indicates that there is an optimal building, but that is not to buy `1` of a building but instead `10`. Likely because you'll get an achievement if you do so.
You'll see a green building when you switch to the `10` column!

**Comment by Jaaap** [comment]
Ah like that!
Thank you for the explanation.
