### ISSUE TITLE
Buildings Saying "Done" When They Aren't

### ISSUE THREAD

**Issue by argentangel** [Aktanusa/CookieMonster#104]
It seems for some reason, right after I started the Grandmapocalypse this reset my buildings have been stating that they are ready to built even if they have a lot of cookies to go. This did not happen the first time I triggered the Grandmapocalypse. This is happening with upgrades too, it will say "Done!" even if they aren't sometimes. Thank you for your time.

![error](https://cloud.githubusercontent.com/assets/20775042/17297739/9bb36012-57cc-11e6-9894-cd962b9fe956.png)

**Comment by argentangel** [comment]
I just realized that this is likely due to the amount of cookies after popping all of the Wrinklers. I apologize for any time I have wasted. Thank you again for your time.

**Comment by Aktanusa** [comment]
Yep, you got it.  Unfortunately it wasn't clear to some, so you're not the first to have the same question.  I may have to think of something to make it more clear.

**Comment by argentangel** [comment]
I've been thinking about this and maybe you could move the button from the Options page to the Stats page under the Wrinklers heading. Since the only other button there is the Pop All button it would stand out more. Just a thought. Thanks for your reply, by the way.

**Comment by Aktanusa** [comment]
Hmm, I was more thinking of changing some color or tooltip.

**Comment by argentangel** [comment]
Hmmm, what about having Done! be in a different color like red (initally #ff0000) if it's with Wrinklers on with a grey (or#b3b3b3) explanation like "With all Wrinklers popped." next to Done! if Done! is in fact equal whatever color they have set as red, such as #ff0000. Plus, the normal green (or #00ff00) if it's with them off. That way it would be a distinct difference between having the toggle switch counting Wrigglers (with the red Done! and a lighter tooltip explaining why) and not counting the Wrinklers(with the green Done!)

I swear this makes sense in my head, but I'm not entirely sure if I'm explaining it correctly. Basically what I'm trying to say is make Done! red when they're counting the Wrinklers and green when they're not. This may even add functionality as a tooltip may be able to change Done! from red to green when the current amount of cookies, without popping any Wrinklers, is greater than or equal to the number of cookies for an upgrade or a building to be Done.

**Comment by Aktanusa** [comment]
Yea I was thinking along the same lines of color coding the Done or something.  I'll contemplate it more when I get some free time.

**Comment by Aktanusa** [comment]
Should this be reopened and renamed to something like making it more clear that bank is ready with or without wrinklers?

**Comment by argentangel** [comment]
Something you might do is default the switch to "off" and perhaps reopen the issue (just as a reminder for you and info to perhaps keep others from posting) at least until you find a satisfactory option for this issue.

**Comment by Aktanusa** [comment]
You're the second person to say that this option isn't newbie friendly.  I think I'll just make it clearer so I don't have to change the default to be off, lol.

**Comment by argentangel** [comment]
Honestly, it's whatever you think is best. You created the mod so you get to decide. I just tend to get bored sitting at home and get crazy ideas that I feel the need to pass on sometimes, lol. I know a little java, some html, and I can look up damn near anything I don't know, so if you need any help with random ideas or whatever feel free to email me anytime at admin@argentangel.com. I've used CookieMonster anytime I get back into Cookie Clicker, so I'd be glad to help in any way I can.

**Comment by Aktanusa** [comment]
Thanks for the help!
