### ISSUE TITLE
Negative tooltip after buying Decillion fingers

### ISSUE THREAD

**Issue by Andreasvb** [Aktanusa/CookieMonster#1049]
### Bug description

Bonus income shows negative when buying, what I think causes it: **Decillion fingers** (500 cursors).

### To reproduce

Buy the upgrade Decillion fingers.

### Screenshot

before: 
![image](https://user-images.githubusercontent.com/3948747/153326110-7de42d27-5e3e-42f9-bc20-b0ca25a46f11.png)
![image](https://user-images.githubusercontent.com/3948747/153326313-66e1fd2f-00d8-4334-a9cc-9aa4133a59d1.png)

after:
![image](https://user-images.githubusercontent.com/3948747/153326467-d4f8a3f3-cd9f-4892-8c13-4693af530923.png)

### Save file

```Mi4wNDR8fDE2NDQ0NTk2MTkzMTQ7MTY0MDY3NTIyNjA0NjsxNjQ0NDYwODQ5NDE0O2dvZ2dlbDtkYWNianwwMTExMTExMTEwMDExMTEwMDEwMTAxMTAwMHw0LjI3MzIwMDk5NDgyNjkyOWUrMzg7Ni44NTExMDc3MTI1ODA3NjZlKzM4OzA7NDAxODswOzQ0MDE7MDsxODsxLjQ5NjE4MTcxNDQ4MTY2NTJlKzQzOzA7MDswOzA7LTE7MTA7MTswOzA7MDswOzA7MDt2YWxlbnRpbmVzOzA7MDsyNDY0MTE3Njk1ODs4MDQ1OTA0OTc7MjM4MzY1ODY0NjE7MDswOzQ5NDs0NjI7NDQyOzQyNTstMTswOzA7MDswOzMxOzA7MDs0OzQ1OzE2NDQ0MjM2NjA5NTc7MDswOzIyNzs0MTswOzA7MS41NjM4OTY5OTc5NDMxOTgzZSszNjs1MDt8NTAwLDYwMiwzLjQ5MzM5MzM4OTI4NDE2ODNlKzM3LDUsLDAsNTAxOzUwMCw1MDAsMS43MjA5NTg3NDkzMDQ2OTRlKzM1LDIsLDAsNTAwOzUwMCw1MDAsMy4xMjYxMDcyMDIwNDY1NjRlKzM0LDEsMTY0NDQ2MDg1MDI4OTowOjE2NDQ0NTk2MTkzMjM6MDowOjE0OjA6MDoxNjQ0NDU5NjE5MzIzOiAxMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwIDA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOiwwLDUwMDs1MDAsNTAwLDIuMDc0NjE4MjMzMjk3NzI4MmUrMzUsMiwsMCw1MDA7NTAwLDUwMCwyLjAxNzQ0ODYyODc5Mjc1NTVlKzM0LDEsLDAsNTAwOzUwMCw1MDAsNi4zODI1NDAxMjMxNTgyMjRlKzMzLDEsMDowOjA6MDoxOiAxMjY0OjE6ODoxNzM6MDowOjAhMTQ2NjoyOi0xOTozNzM6MDowOjAhMzMwOToxOjg6OTM6MDowOjAhMzgxMToyOi0zMTo1NzI6MDowOjAhNDkxMToxOjY6OTcyOjA6MDowITU3NjY6MDotMTo4NTk6MDowOjAhNzY1MToxOjU0OjkyNzowOjA6MCE4NjYyOjE6NDg6NDk4OjA6MDowITk1NjA6MTo0OToxOTg6MDowOjAhMTAxMzE6MDotMTI6MjE2OjA6MDowITkxMjk6NDotMTExOjEwMzowOjA6MCExMjQ0MzowOi0xOjI0OTowOjA6MCExMjg0OToxOjIxOjU2NDowOjA6MCExMzc4ODowOi0yOjQxODowOjA6MCExNDg1MDowOi03OjUzNDowOjA6MCExNjU4Nzo1Oi0zMTo5MzowOjA6MCExNjM4MToyOi0yNzoxMTE6MDowOjAhIDAsMCw1MDA7NDAwLDQwMCwxLjEwNzc2NDY2NDU3MTMyMzhlKzM1LDEsLTEvLTEvLTEgMyAxNjQ0NDU5NjE5MzI2IDAsMCw0MDA7NDAwLDQwMCw1LjAyMzQ2MzQ4NTUzODU4OGUrMzMsMSwyMC45MTk5NDA5NTYwNDI1MjQgMCA3IDAsMCw0MDA7NDAwLDQwMCwxLjk5OTY3NTA2MzY4MTIxNDJlKzMzLDEsLDAsNDAwOzQwMCw0MDAsMS4wODEwNDU2MDkwNTA1NjE3ZSszNCwxLCwwLDQwMDs0MDAsNDAwLDYuODgzMDczOTUzOTA5MzkyZSszNSwyLCwwLDQwMDszMDAsMzAwLDcuNjI0MDM2NzMyNTExMTM2ZSszNCwxLCwwLDMwMDszMDAsMzAwLDYuNzgwODg1MzgxNDYwNDM1ZSszNSwxLCwwLDMwMDszMDAsMzAwLDMuNTY0OTk2MTc4OTM1MTg0NmUrMzYsMSwsMCwzMDA7MzAwLDMwMCw5LjYzNTEyMDA1NDUzNjc1MmUrMzYsMSwsMCwzMDA7MzAwLDMwMCw2LjcwNjgwNDYyMjk2NjE0OWUrMzcsMSwsMCwzMDA7MjAwLDIwMCw3LjY0NjYyMDc3NzM2NDJlKzM2LDEsLDAsMjAwOzIwMCwyMDAsNS4zMTcwOTgxNDg4MTAxMzNlKzM3LDIsLDAsMjAwOzIwMCwyMDAsNC42MTk3NTk4NzYwMzk1NzRlKzM4LDEsLDAsMjAwO3wxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMDAwMDAwMTEwMDExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTAwMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAxMTAwMTEwMDAwMTEwMDAwMDAxMTExMDAwMDAwMDAwMDExMDAwMDAwMDAxMTExMDAwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMDEwMTAwMDExMTExMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTAwMDAwMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDEwMDAxMDExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTEwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMTExMTExMTExMTExMTExMTExMTEwMDAwMDAxMDExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTEwMDAwMDAxMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTEwMDAwMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDEwMTAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTEwMDAwMTExMTExMTExMTExMTExMTAwMDAwMDAwMTExMTAwMDAwMDAwMDAxMTEwMDAwMDAwMDAxMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAxMTExMDAwMDExMTExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMTEwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTAwMTAwMDEwMDB8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMDExMTExMTAxMTExMTEwMDAwMDAwMDExMTEwMTExMTExMTExMDExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTAxMTAxMTAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTExMDExMTExMTExMTExMTExMTEwMTExMTExMTEwMDAwMDAxMTExMTEwMDExMDAwMDAxMTEwMDExMDAwMDAwMDAxMTExMTExMTAwMDAwMDAxMTExMTExMTAwMDExMDAwMDExMDExMTExMTEwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAxMDExMTEwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAxMTExMTExMDAwMDAwMTEwMDExMTEwMDAwMDAwMDAxMTExMTEwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDB8fENvb2tpZU1vbnN0ZXI6eyJzZXR0aW5ncyI6eyJDUFNNb2RlIjowLCJBdmdDUFNIaXN0IjowLCJBdmdDbGlja3NIaXN0IjowLCJDYWxjV3JpbmsiOjEsIlNjYWxlIjowLCJTY2FsZURlY2ltYWxzIjoyLCJTY2FsZVNlcGFyYXRvciI6MCwiU2NhbGVDdXRvZmYiOjk5OTk5OSwiVGltZUZvcm1hdCI6MCwiRGV0YWlsZWRUaW1lIjoxLCJQUERpc3BsYXlUaW1lIjowLCJCdWlsZENvbG91ciI6MSwiUFBPbmx5Q29uc2lkZXJCdXlhYmxlIjoxLCJQUEV4Y2x1ZGVUb3AiOjAsIlBQUmlnaWRlbE1vZGUiOjAsIlBQU2Vjb25kc0xvd2VyTGltaXQiOjAsIkNvbG91ckJsdWUiOiIjNGJiOGYwIiwiQ29sb3VyR3JlZW4iOiIjMDBmZjAwIiwiQ29sb3VyWWVsbG93IjoiI2ZmZmYwMCIsIkNvbG91ck9yYW5nZSI6IiNmZjdmMDAiLCJDb2xvdXJSZWQiOiIjZmYwMDAwIiwiQ29sb3VyUHVycGxlIjoiI2ZmMDBmZiIsIkNvbG91ckdyYXkiOiIjYjNiM2IzIiwiQ29sb3VyUGluayI6IiNmZjE0OTMiLCJDb2xvdXJCcm93biI6IiM4YjQ1MTMiLCJCb3RCYXIiOjAsIlRpbWVyQmFyIjoxLCJUaW1lckJhclBvcyI6MCwiVGltZXJCYXJPdmVybGF5IjoyLCJBdXRvc2F2ZVRpbWVyQmFyIjowLCJVcEJhckNvbG91ciI6MCwiVXBncmFkZUJhckZpeGVkUG9zIjowLCJTb3J0QnVpbGRpbmdzIjowLCJTb3J0VXBncmFkZXMiOjAsIlVwZ3JhZGVzTmV2ZXJDb2xsYXBzZSI6MCwiRHJhZ29uQXVyYUluZm8iOjEsIkdyaW1vaXJlQmFyIjoxLCJHQ1RpbWVyIjoxLCJGYXZpY29uIjoxLCJXcmlua2xlckJ1dHRvbnMiOjAsIkhpZGVTZWN0aW9uc0J1dHRvbnMiOjAsIlRvb2x0aXBCdWlsZFVwZ3JhZGUiOjEsIlRvb2x0aXBBbW9yIjoxLCJUb29sV2Fybkx1Y2t5IjowLCJUb29sV2Fybkx1Y2t5RnJlbnp5IjowLCJUb29sV2FybkNvbmp1cmUiOjAsIlRvb2xXYXJuQ29uanVyZUZyZW56eSI6MCwiVG9vbFdhcm5FZGlmaWNlIjowLCJUb29sV2FyblVzZXIiOjAsIlRvb2xXYXJuQm9uIjoxLCJUb29sV2FyblBvcyI6MSwiVG9vbHRpcEdyaW0iOjEsIlRvb2x0aXBXcmluayI6MCwiVG9vbHRpcEx1bXAiOjEsIlRvb2x0aXBQbG90cyI6MSwiVG9vbHRpcFBhbnRoZW9uIjoxLCJUb29sdGlwQXNjZW5kQnV0dG9uIjoxLCJTdGF0cyI6MSwiTWlzc2luZ1VwZ3JhZGVzIjowLCJNaXNzaW5nQWNoaWV2ZW1lbnRzIjowLCJVcFN0YXRzIjoxLCJIZWF2ZW5seUNoaXBzVGFyZ2V0IjoxLCJTaG93TWlzc2VkR0MiOjAsIlRpdGxlIjoxLCJHZW5lcmFsU291bmQiOjEsIkdDTm90aWZpY2F0aW9uIjoxLCJHQ0ZsYXNoIjoxLCJDb2xvdXJHQ0ZsYXNoIjoiI0ZGRDUwMCIsIkdDU291bmQiOjEsIkdDVm9sdW1lIjozMSwiR0NTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzY2LzY2NzE3XzkzMTY1NS1scS5tcDMiLCJGb3J0dW5lTm90aWZpY2F0aW9uIjoxLCJGb3J0dW5lRmxhc2giOjEsIkNvbG91ckZvcnR1bmVGbGFzaCI6IiNmZmZmZmYiLCJGb3J0dW5lU291bmQiOjEsIkZvcnR1bmVWb2x1bWUiOjYyLCJGb3J0dW5lU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNzQvMTc0MDI3XzMyNDI0OTQtbHEubXAzIiwiU2VhTm90aWZpY2F0aW9uIjoxLCJTZWFGbGFzaCI6MSwiQ29sb3VyU2VhRmxhc2giOiIjRkY0NTQ1IiwiU2VhU291bmQiOjEsIlNlYVZvbHVtZSI6MTYsIlNlYVNvdW5kVVJMIjoiaHR0cHM6Ly93d3cuZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyMS8xMjEwOTlfMjE5MzI2Ni1scS5tcDMiLCJHYXJkRmxhc2giOjEsIkNvbG91ckdhcmRGbGFzaCI6IiNmZmZmZmYiLCJHYXJkU291bmQiOjEsIkdhcmRWb2x1bWUiOjE0LCJHYXJkU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMDMvMTAzMDQ2Xzg2MTcxNC1scS5tcDMiLCJNYWdpY05vdGlmaWNhdGlvbiI6MCwiTWFnaWNGbGFzaCI6MSwiQ29sb3VyTWFnaWNGbGFzaCI6IiNmZmZmZmYiLCJNYWdpY1NvdW5kIjoxLCJNYWdpY1ZvbHVtZSI6MzgsIk1hZ2ljU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8yMjEvMjIxNjgzXzEwMTUyNDAtbHEubXAzIiwiV3JpbmtsZXJOb3RpZmljYXRpb24iOjAsIldyaW5rbGVyRmxhc2giOjAsIkNvbG91cldyaW5rbGVyRmxhc2giOiIjZmZmZmZmIiwiV3JpbmtsZXJTb3VuZCI6MSwiV3JpbmtsZXJWb2x1bWUiOjIxLCJXcmlua2xlclNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTI0LzEyNDE4Nl84MDQzLWxxLm1wMyIsIldyaW5rbGVyTWF4Tm90aWZpY2F0aW9uIjowLCJXcmlua2xlck1heEZsYXNoIjoxLCJDb2xvdXJXcmlua2xlck1heEZsYXNoIjoiI2ZmZmZmZiIsIldyaW5rbGVyTWF4U291bmQiOjEsIldyaW5rbGVyTWF4Vm9sdW1lIjoyMiwiV3JpbmtsZXJNYXhTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzE1Mi8xNTI3NDNfMTU2NjMtbHEubXAzIiwiQnVsa0J1eUJsb2NrIjoxLCJGYXZvdXJpdGVTZXR0aW5ncyI6MX0sImhlYWRlcnMiOnsiRmF2b3VyaXRlIjoxLCJDYWxjdWxhdGlvbiI6MSwiTm90YXRpb24iOjEsIkNvbG91cnMiOjEsIkJhcnNEaXNwbGF5IjoxLCJUb29sdGlwIjoxLCJTdGF0aXN0aWNzIjoxLCJOb3RpZmljYXRpb24iOjEsIk5vdGlmaWNhdGlvbkdlbmVyYWwiOjEsIk5vdGlmaWNhdGlvbkdDIjoxLCJOb3RpZmljYXRpb25GQyI6MSwiTm90aWZpY2F0aW9uU2VhIjoxLCJOb3RpZmljYXRpb25HYXJkIjoxLCJOb3RpZmljYXRpb25NYWdpIjoxLCJOb3RpZmljYXRpb25XcmluayI6MSwiTm90aWZpY2F0aW9uV3JpbmtNYXgiOjEsIk1pc2NlbGxhbmVvdXMiOjEsIkx1Y2t5IjoxLCJDaGFpbiI6MCwiU3BlbGxzIjoxLCJHYXJkZW4iOjAsIlByZXN0aWdlIjoxLCJXcmluayI6MSwiU2VhIjoxLCJBY2hpZXZzIjowLCJNaXNjIjoxLCJpbmZvTWVudSI6MSwib3B0aW9uc01lbnUiOjB9LCJmYXZvdXJpdGVTZXR0aW5ncyI6WyJCb3RCYXIiLCJUaW1lckJhciIsIlVwQmFyQ29sb3VyIiwiTWlzc2luZ0FjaGlldmVtZW50cyIsIk1pc3NpbmdVcGdyYWRlcyIsIlN0YXRzIiwiQnVsa0J1eUJsb2NrIiwiUFBEaXNwbGF5VGltZSIsIkNQU01vZGUiXSwibG9ja2VkTWluaWdhbWVzIjpbXSwidmVyc2lvbiI6IjIuMDMxLjEwIn07Y29va2llTW9uc3RlckZyYW1ld29yazp7InNldHRpbmdzIjp7fSwiaGVhZGVycyI6eyJpbmZvTWVudSI6MSwib3B0aW9uc01lbnUiOjF9LCJmYXZvdXJpdGVTZXR0aW5ncyI6W119Ow%3D%3D%21END%21```

### Browser / Steam / Version

Browser v.2.044 beta

**Comment by Andreasvb** [comment]
Also the new Dragon aura **Supreme Intellect** causes it to be negative.

![image](https://user-images.githubusercontent.com/3948747/153704714-c23601dc-cdce-42ef-9dd3-e08954faf3f2.png)

**Comment by Andreasvb** [comment]
Could be it needs general support for the new building, think the Kitten admins upgrade changed it as well.

![image](https://user-images.githubusercontent.com/3948747/153775829-bc9ad4ad-4801-4e99-a888-95b99991fb70.png)
![image](https://user-images.githubusercontent.com/3948747/153775879-aa06c497-7bd6-4fcb-890d-24b93cfa50d4.png)

**Comment by DanielNoord** [comment]
I think that might be the problem indeed. I would welcome any PR that tries to do so, I'm quite busy myself currently and don't have much time to actively contribute code to the project anymore. PR reviewing will be possible though!

**Comment by jack980517** [comment]
Is 2.048.10 supposed to solve this? I'm still affected by this bug.

**Comment by jack980517** [comment]
Is 2.048.10 supposed to solve this? I'm still affected by this bug.

**Comment by DanielNoord** [comment]
I think so. @domoddball added support for `2.048`.

Perhaps they can comment on whether this should be solved, or is solved for them?

**Comment by domoddball** [comment]
the updates i made should have resolved this for all cases that do not involve unshackled upgrades.
im still trying to implement unshackled upgrades, but the expected bonus income doesn't match up to the actual income change in testing. will push a fix once ive finally tracked down where my math is wrong.

![image](https://user-images.githubusercontent.com/32601481/171645597-d264d55f-4420-430a-abdc-f4abbfa5c940.png)
![image](https://user-images.githubusercontent.com/32601481/171647255-b7960a3d-6184-476e-80b1-03a79300eb61.png)

this is from the save provided on this bug report, running on CookieMonster 2.048, without any unshackled upgrades. 

if you are still seeing issues, please provide a new save and i can give it a look when i have free time

**Comment by jack980517** [comment]
OK, I thought unshackled things were fixed as well. That must have been the issue. The save provided by OP works now.
