### ISSUE TITLE
Add option for custom warnings in tooltip

### ISSUE THREAD

**Issue by Kidsheldon** [Aktanusa/CookieMonster#105]
I'm wanting to keep enough cookies for the Max Frenzy Chain reward since it's over 5x the Max Frenzy Lucky reward, and it's inconvenient having to manually check if my next purchase will keep me over 311.111 Tr cookies. I imagine it would be an off-by-default feature, since most people don't consider storing so much for such a small-chance reward worth it.

**Comment by Aktanusa** [comment]
Maybe I'm misunderstanding what you want, but isn't this statistic already there in Cookie Monster under Cookie Chains?

**Comment by Kidsheldon** [comment]
Yeah, just like the "Caution" and "Warning" for Max Lucky requirements.

**Comment by dhouck** [comment]
Actually, there are a lot of optional warnings you might want (for example, 25,200x CPS for frenzied queenbeet reward); can you add a "custom warning" feature? Either this could be specifying "*x* times CPS" or "*t* minutes with *buff*", the latter being harder to implement but easier to use.

**Comment by Aktanusa** [comment]
I am planning on making it completely custom caution/warning, but as you said, it will be harder to implement.  This was originally planned for only the cookies needed stats for buffs in the stats page, but has now been extended to also the warnings...

**Comment by DanielNoord** [comment]
I think it is a good idea to create a possibility to make custom warnings based on something like "x times CPS"
