### ISSUE TITLE
Option to calculate if popping wrinkler to quickly purchase building/upgrade is more efficient

### ISSUE THREAD

**Issue by HeroicKatora** [Aktanusa/CookieMonster#106]
I wanted to propose a new feature that would tell you when to pop wrinklers.
This could only be beneficial when buying some kind of upgrade as popping a wrinkler will effectively decrease your Cps for the time it takes for him to respawn. Let's look at a concrete example:

Suppose you want to buy a Kitten Upgrade for 500 B which would boost your 20 M CpS by 50%. Now you could wait 50*500 = 25000  seconds then buy the upgrade.
But let's look at the same situation in case you have 10 wrinklers active for simplicity suppose that one of those has the necessary amount to let you buy it instantly. This will drop your wrinkler multiplier from ~7 to ~6 until it has respawned, which will take 3300 ticks ~ 110 seconds on average with no upgrades.
If you choose the wrinkler route, you will "lose" 20M CpS for 110 seconds but at the same time you gain 6 \* 10M in the first 110 seconds and for the remaining time up to 25000 you will even gain 7 \* 10 M, which equals to 1,747,800M cookies gained in total if you pop the wrinkler.

This is in fact a rather extreme case and I did not yet consider that your effective CpS and your real CpS differ quite drastically. Golden Cookie earnings are boosted during the period as well and you will not have to wait for them but on the other hand the numbers I have just given are rather extreme but very tedious to calculate by hand.

Now I would propose an extra "warning" (maybe coloured in Blue) that will let you know it might be more efficient to pop a Wrinkler instead of waiting for an upgrade when you hover over it. Since popping is only advisable when you buy the upgrade directly afterwards, the function should keep the highest golden cookie warning in mind and not pure affordability.

Additionally, a switch that automatically pops wrinklers and then makes the purchase could be included in the options, disabled by default.

**Comment by Aktanusa** [comment]
Hmm, interesting idea, and I'm guessing the extra notice will be on the tooltip?  I should really figure this out myself, but how did you get the average 110 seconds for a wrinkler to spawn?  If I remember correctly in code, it goes in a loop and trying to spawn each wrinkler, so the amount already spawn won't effect each individually, but as a whole, you are most likely to get wrinklers when there are none on screen than when there is one left.  Another question is, your example is for 1 wrinkler, but how about popping 2 total that has enough to buy, or 3, or 4... etc.  Shouldn't I calculate that also?  Would it be worth it to pop all wrinklers to buy a highly efficient upgrade like kittens (which usually give a maximum boost around 180%)?  To me, the cost of no wrinklers for on average around 110 seconds is minimal vs waiting for kitten to be affordable.

The auto pop wrinkler and buy option I consider too automated so I don't think I'll implement that.

**Comment by HeroicKatora** [comment]
[Reference for Wrinkler spawn time, it's the official wiki but it might be slightly outdated](http://cookieclicker.wikia.com/wiki/Wrinkler)

It would be extremely nice if popping 2,3,.. would be calculated as well, as the respawn time for 12 Wrinklers is about 100k ticks to fill all 12 slots (though you obviously your Wrinkler CpS will be regained gradually as each respawns) which will likely be worth it for Kittens.

Golden Wrinklers will probably have to be excluded for now as their respawn isn't guaranteed thus losing CpS indefinitely.

**Comment by Aktanusa** [comment]
So to me, if I'm calculating 2, 3, I would think I should calculate all of them (up to 12).  Thanks for the link, it will help me calculate the chance easier.  I'm not sure I'll do this yet, as I'm not much of a math person, lol.

**Comment by HeroicKatora** [comment]
I could do the math for you there, calculating the expected time for the current chances of spawning a Wrinkler. I might not immediately find a closed form in terms of the chance but for a given chance it shouldn't be a problem. As long as Orteil doesn't decide to change the values this should be fine.

**Comment by Aktanusa** [comment]
What do you mean by not being able to find a closed form in terms of the chance?

**Comment by svschouw** [comment]
I think he means a formula where you can plug in the chance of wrinklers spawning. So if Orteil ever decides to change the percentage, you should be able to just plug in the new percentage. Except that that might not be possible.

Also, I think that even though the chance of a wrinkler spawning when there are no wrinklers is higher then when there are 11, I think the chance of that same one returning is about the same. The biggest problem here is that the amount gained from wrinklers is quadratic in terms of the amount of wrinklers, not linear. So I'm guessing that will be the hardest part of the equation.

**Comment by HeroicKatora** [comment]
I'll post a pull request in the next couple of days with means to calculate expected respawn time and also expected loss of CpS, which will utilize the former.

**Comment by Aktanusa** [comment]
Sounds, good!

**Comment by lramati** [comment]
Do you think similar logic could be used to make a probabilistic guess at the expected payback time of golden cookie upgrades?

**Comment by HeroicKatora** [comment]
Much harder, as that would require a near perfect prediction of production increase. The effects of golden cookie upgrades are very diverse, compared to wrinklers. 

If you are invested in the general topic, it might interesting to hear that the recovery time of spells [can be calculated directly](https://www.reddit.com/r/CookieClicker/comments/70e4ay/the_grimoire_deciphered_spell_recovery_time/), without requiring simulation of all game ticks. Though I am unsure as to how accurate this still is, an update might have changed something.

**Comment by DanielNoord** [comment]
I have decided to close this issue as even with the correct calculation of wrinkler spawn time there is still a lot of chance involved. Currently all PP calculations involve static data and there is no luck or chance involved in any of the calculations. Adding this functionality would always make the PP calculation more variable and therefore we might be giving incorrect suggestions to the user. Although I can think of cases where calculating the wrinkler respawn time might be useful I don't see how we can include the functionality discussed in this topic without including some factor of chance into our calculations.
