### ISSUE TITLE
Negative PP calculation

### ISSUE THREAD

**Issue by jackwoodside** [Aktanusa/CookieMonster#1085]
### Bug description

After the update to 2.048 everything was working fine. Then I ascended and bought the new "unshackled" heavenly upgrades (not sure if this is the cause, but it did work fine before), and now nearly every PP calculation is negative, so most things are grey, with a couple purples, but nothing lower than that.

### To reproduce

Unlock new heavenly upgrades? (possibly)

### Screenshot

![image](https://user-images.githubusercontent.com/20267593/171628820-c83cb30d-e3c2-4bef-a245-b6d7618470d4.png)

### Save file

```Mi4wNDh8fDE2NTQxNjk5MTg2MjA7MTYyOTA5MDA4ODAwMzsxNjU0MTcyNzk2NjgxO0phY2s7emtoZ3d8MDExMTEwMTAxMDAwMDAwMDAxMTAwMTEwMDAxfDEuMDIwNTkzOTIxNzIwNjg5OGUrNDk7Mi4wNDEzOTQwMzc0NDYxMjc3ZSs0OTs1NjsxMDM0OzUuOTYxNzQ1MDY3NjE0NDM2ZSs0NTszMzQ7MjM7MDs4LjU3MDQ3MjM3NTU1NjMxOWUrNTE7MDswOzA7MDstMTsxMjM7NDswOzA7MTQ7MTsyNTc2OTU3OzM7ZWFzdGVyOzA7MDsyMDQ2NDUyMTEyMzk3NDszMzU0NTM2NDg5NTk2OzE3MTA5OTg0NjM0Mzc4OzA7MDs3NjY7NjQxOzc0MDs0Nzg7NDc5OzI2OzE1OzE7MzswOzA7MDsxMDE7MzAyOzE2NTQwOTk0NjUwNDY7MDswOzIyNzs0MTswOzA7MS44ODM4NzYzODM2MzE5OTI0ZSs0Njs1MDt8NzQ3LDEwOTcsMS4zMDY5MzEyODI1ODEwODdlKzQ5LDEyLCwwLDc0Nzs3MjcsMTA3Nyw1LjY2NzYxODIwNTAyMDUyOWUrNDUsMCwsMSw3Mjc7NzAzLDEwNTMsMS4zMDE5Mjg2NDE2NzUxMzE4ZSs0NiwxMCwxNjU0MTcyOTM2OTYxOjE6MTY1NDE3MjQ2MjYwNjowOjA6MTcyOjE6MDoxNjU0MTY5OTE4NjQ4OiAxMTAwMDAwMDAxMTExMTAwMDAwMDAwMDEwMDAwMDAwMDAwIDA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOiwwLDcwMzs2OTMsMTA0Myw0LjM5NjUwNjU1NjUyOTA0OTZlKzQ2LDAsLDEsNjkzOzY2OSwxMDE5LDUuMTE4OTEyODEwMzI1NjI3ZSs0NSwwLCwxLDY2OTs2NTcsMTAwNyw5LjM5NTk1NzkwODA2MjYyNmUrNDQsMSwwOjA6MTowOjA6IDU3MDo1OjM2NTo1MjowOjA6MDowITk2ODowOjE4NDo1Njk6MDowOjA6MCE1Mjk4OjU6LTUzOjQ1MzowOjA6MDowITUwMTc6MToyNDU6Mzk2OjA6MDowOjAhNDU0Njo1OjE3ODo0ODE6MDowOjA6MCE1MjUzOjM6MjcwOjE4OjA6MDowOjAhNjA1MDo1OjYyOjY1NDowOjA6MDowITY4Nzc6MjotNTk6MTgwOjA6MDowOjAhMzUzMjowOjQ6NDM5OjA6MDowOjAhMTM0ODQ6MToyMzQ6MjY3OjA6MDowOjAhNTQzNDoxOjI4NjoxOTE6MDowOjA6MCExMjUwNDo1OjI4NDo1MDY6MDowOjA6MCExMzIyODo0OjYyOjQyODowOjA6MDowITk5ODQ6MDotMzg6NjYzOjA6MDowOjAhMTIxMDY6NTotMzE6Mjk1OjA6MDowOjAhMTczNzk6NTozNDg6NjA1OjA6MDowOjAhMTQzNjg6NTo3MTo0MzQ6MDowOjA6MCEgMCwwLDY1Nzs2MzcsOTg3LDIuNzYwNjU4MjI5OTc1NTc2MmUrNDUsMSwyLzgvNiAwIDE2NTQxNzAwOTYyNDMgMCwwLDYzNzs2MTcsOTY3LDQuMzgwMjgwNjExNDM5Mzc4NWUrNDMsMSwyNi44ODY3MTY2MzE4MjMxMDIgMCAxNTggMSwwLDYxNzs1OTYsOTQ2LDEuMzU0NjY3MzAwNDc5MzgyOGUrNDMsMCwsMSw1OTY7NTc4LDkyOCw2LjQ2NTQ4OTM1MDI2MTU1NWUrNDMsMCwsMSw1Nzg7NTU5LDkwOSw0LjEyNjg1Mjg0NzUwMjk5OTdlKzQ1LDAsLDEsNTU5OzU0MSw4OTEsMS4xNTU5Mzc4MzExNjIwNDllKzQ1LDAsLDEsNTQxOzUyMiw4NzIsMS4wMDcxNzIwOTQ1MTEzNDY5ZSs0NiwwLCwxLDUyMjs1MDYsODU2LDIuOTE5NTI2OTg4OTIwNjk5NmUrNDYsMCwsMSw1MDY7NDg4LDgzOCw3LjQ1NTA5ODIzMzMxODM0N2UrNDYsMCwsMSw0ODg7NDY5LDgxOSw0Ljg4NTExNjg0OTcxMjgxOGUrNDcsNCwsMCw0Njk7NDMzLDc4Myw3LjIxMDIxNjEyODEwMjAxOGUrNDYsMCwsMSw0MzM7NDA1LDc1NywyLjQzMTYzMDE0MjQ4MDU5ODNlKzQ3LDEwLCwxLDQwNTszODgsNzM4LDMuODgzNzMzOTM2OTIwODY1ZSs0OCwwLCwxLDM4ODt8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMTExMTExMTEwMDExMTExMTAwMDAwMDExMDAxMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTAxMDEwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMDAwMDAwMDAwMDAwMDAxMTAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDEwMTAxMTExMTExMTExMDAwMDAwMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAxMTAwMTExMTExMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMDAwMTExMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMTExMTExMTEwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDExMTEwMDExMTExMTAwMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExfDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTEwMTExMTExMDAwMDAwMDAxMTExMDExMDExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTEwMDEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDEwMDAwMDAwMDAwMDExMDAxMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTEwMDAwMTExMTExMTExMTExMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMDExMTAxMTExMDAxMDAxMDAwMDAwMDEwMTExMDAwMTExMTExMTExMTExMTExMDAwMDEwMTExMTExMTExMTAwMDAwMTExMTExMTExMTAwMDExMTExMTExMDEwMDAwMDAxMTExMTExMTExMDAwMDExMTAxMTExMTExMDAwMDAwMDAwMDAxMDAwMDAwMTEwMDAwMDF8MCw1MjUwLDM5NTUsNzt8Q29va2llTW9uc3Rlcjp7InNldHRpbmdzIjp7IkNQU01vZGUiOjAsIkF2Z0NQU0hpc3QiOjUsIkF2Z0NsaWNrc0hpc3QiOjAsIkNhbGNXcmluayI6MiwiU2NhbGUiOjAsIlNjYWxlRGVjaW1hbHMiOjIsIlNjYWxlU2VwYXJhdG9yIjowLCJTY2FsZUN1dG9mZiI6OTk5OTk5LCJUaW1lRm9ybWF0IjowLCJEZXRhaWxlZFRpbWUiOjEsIlBQRGlzcGxheVRpbWUiOjAsIkJ1aWxkQ29sb3VyIjoxLCJQUE9ubHlDb25zaWRlckJ1eWFibGUiOjAsIlBQRXhjbHVkZVRvcCI6MCwiUFBSaWdpZGVsTW9kZSI6MCwiUFBTZWNvbmRzTG93ZXJMaW1pdCI6MCwiQ29sb3VyQmx1ZSI6IiM0YmI4ZjAiLCJDb2xvdXJHcmVlbiI6IiMwMGZmMDAiLCJDb2xvdXJZZWxsb3ciOiIjZmZmZjAwIiwiQ29sb3VyT3JhbmdlIjoiI2ZmN2YwMCIsIkNvbG91clJlZCI6IiNmZjAwMDAiLCJDb2xvdXJQdXJwbGUiOiIjZmYwMGZmIiwiQ29sb3VyR3JheSI6IiNiM2IzYjMiLCJDb2xvdXJQaW5rIjoiI2ZmMTQ5MyIsIkNvbG91ckJyb3duIjoiIzhiNDUxMyIsIkJvdEJhciI6MCwiVGltZXJCYXIiOjEsIlRpbWVyQmFyUG9zIjowLCJUaW1lckJhck92ZXJsYXkiOjIsIkF1dG9zYXZlVGltZXJCYXIiOjAsIlVwQmFyQ29sb3VyIjoxLCJVcGdyYWRlQmFyRml4ZWRQb3MiOjEsIlNvcnRCdWlsZGluZ3MiOjAsIlNvcnRVcGdyYWRlcyI6MCwiVXBncmFkZXNOZXZlckNvbGxhcHNlIjowLCJEcmFnb25BdXJhSW5mbyI6MSwiR3JpbW9pcmVCYXIiOjEsIkdDVGltZXIiOjEsIkZhdmljb24iOjEsIldyaW5rbGVyQnV0dG9ucyI6MSwiSGlkZVNlY3Rpb25zQnV0dG9ucyI6MCwiVG9vbHRpcEJ1aWxkVXBncmFkZSI6MSwiVG9vbHRpcEFtb3IiOjAsIlRvb2xXYXJuTHVja3kiOjEsIlRvb2xXYXJuTHVja3lGcmVuenkiOjEsIlRvb2xXYXJuQ29uanVyZSI6MSwiVG9vbFdhcm5Db25qdXJlRnJlbnp5IjoxLCJUb29sV2FybkVkaWZpY2UiOjEsIlRvb2xXYXJuVXNlciI6MCwiVG9vbFdhcm5Cb24iOjEsIlRvb2xXYXJuUG9zIjoxLCJUb29sdGlwR3JpbSI6MSwiVG9vbHRpcFdyaW5rIjoxLCJUb29sdGlwTHVtcCI6MSwiVG9vbHRpcFBsb3RzIjoxLCJUb29sdGlwUGFudGhlb24iOjEsIlRvb2x0aXBBc2NlbmRCdXR0b24iOjEsIlN0YXRzIjoxLCJNaXNzaW5nVXBncmFkZXMiOjEsIk1pc3NpbmdBY2hpZXZlbWVudHMiOjEsIlVwU3RhdHMiOjEsIkhlYXZlbmx5Q2hpcHNUYXJnZXQiOjEsIlNob3dNaXNzZWRHQyI6MCwiVGl0bGUiOjEsIkdlbmVyYWxTb3VuZCI6MSwiR0NOb3RpZmljYXRpb24iOjAsIkdDRmxhc2giOjEsIkNvbG91ckdDRmxhc2giOiIjZmZmZmZmIiwiR0NTb3VuZCI6MSwiR0NWb2x1bWUiOjEwMCwiR0NTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzY2LzY2NzE3XzkzMTY1NS1scS5tcDMiLCJGb3J0dW5lTm90aWZpY2F0aW9uIjowLCJGb3J0dW5lRmxhc2giOjEsIkNvbG91ckZvcnR1bmVGbGFzaCI6IiNmZmZmZmYiLCJGb3J0dW5lU291bmQiOjEsIkZvcnR1bmVWb2x1bWUiOjEwMCwiRm9ydHVuZVNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTc0LzE3NDAyN18zMjQyNDk0LWxxLm1wMyIsIlNlYU5vdGlmaWNhdGlvbiI6MCwiU2VhRmxhc2giOjEsIkNvbG91clNlYUZsYXNoIjoiI2ZmZmZmZiIsIlNlYVNvdW5kIjoxLCJTZWFWb2x1bWUiOjEwMCwiU2VhU291bmRVUkwiOiJodHRwczovL3d3dy5mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTIxLzEyMTA5OV8yMTkzMjY2LWxxLm1wMyIsIkdhcmRGbGFzaCI6MCwiQ29sb3VyR2FyZEZsYXNoIjoiI2ZmZmZmZiIsIkdhcmRTb3VuZCI6MCwiR2FyZFZvbHVtZSI6MTAwLCJHYXJkU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMDMvMTAzMDQ2Xzg2MTcxNC1scS5tcDMiLCJNYWdpY05vdGlmaWNhdGlvbiI6MCwiTWFnaWNGbGFzaCI6MSwiQ29sb3VyTWFnaWNGbGFzaCI6IiNmZmZmZmYiLCJNYWdpY1NvdW5kIjoxLCJNYWdpY1ZvbHVtZSI6MTAwLCJNYWdpY1NvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMjIxLzIyMTY4M18xMDE1MjQwLWxxLm1wMyIsIldyaW5rbGVyTm90aWZpY2F0aW9uIjowLCJXcmlua2xlckZsYXNoIjowLCJDb2xvdXJXcmlua2xlckZsYXNoIjoiI2ZmZmZmZiIsIldyaW5rbGVyU291bmQiOjEsIldyaW5rbGVyVm9sdW1lIjoxMDAsIldyaW5rbGVyU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMjQvMTI0MTg2XzgwNDMtbHEubXAzIiwiV3JpbmtsZXJNYXhOb3RpZmljYXRpb24iOjAsIldyaW5rbGVyTWF4Rmxhc2giOjAsIkNvbG91cldyaW5rbGVyTWF4Rmxhc2giOiIjZmZmZmZmIiwiV3JpbmtsZXJNYXhTb3VuZCI6MSwiV3JpbmtsZXJNYXhWb2x1bWUiOjEwMCwiV3JpbmtsZXJNYXhTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzE1Mi8xNTI3NDNfMTU2NjMtbHEubXAzIiwiQnVsa0J1eUJsb2NrIjowLCJGYXZvdXJpdGVTZXR0aW5ncyI6MX0sImhlYWRlcnMiOnsiRmF2b3VyaXRlIjoxLCJDYWxjdWxhdGlvbiI6MSwiTm90YXRpb24iOjEsIkNvbG91cnMiOjEsIkJhcnNEaXNwbGF5IjoxLCJUb29sdGlwIjoxLCJTdGF0aXN0aWNzIjoxLCJOb3RpZmljYXRpb24iOjEsIk5vdGlmaWNhdGlvbkdlbmVyYWwiOjEsIk5vdGlmaWNhdGlvbkdDIjoxLCJOb3RpZmljYXRpb25GQyI6MSwiTm90aWZpY2F0aW9uU2VhIjoxLCJOb3RpZmljYXRpb25HYXJkIjoxLCJOb3RpZmljYXRpb25NYWdpIjoxLCJOb3RpZmljYXRpb25XcmluayI6MSwiTm90aWZpY2F0aW9uV3JpbmtNYXgiOjEsIk1pc2NlbGxhbmVvdXMiOjEsIkx1Y2t5IjowLCJDaGFpbiI6MCwiU3BlbGxzIjowLCJHYXJkZW4iOjAsIlByZXN0aWdlIjowLCJXcmluayI6MSwiU2VhIjoxLCJBY2hpZXZzIjowLCJNaXNjIjowLCJpbmZvTWVudSI6MSwib3B0aW9uc01lbnUiOjB9LCJmYXZvdXJpdGVTZXR0aW5ncyI6W10sInZlcnNpb24iOiIyLjA0OC4xMCIsImxvY2tlZE1pbmlnYW1lcyI6W119O2Nvb2tpZU1vbnN0ZXJGcmFtZXdvcms6eyJzZXR0aW5ncyI6e30sImhlYWRlcnMiOnsiaW5mb01lbnUiOjEsIm9wdGlvbnNNZW51IjoxfSwiZmF2b3VyaXRlU2V0dGluZ3MiOltdfTtDQ1NFOnsidmVyc2lvbiI6IjIuMDMzIiwiQWNoaWV2ZW1lbnRzIjp7fSwiVXBncmFkZXMiOnt9LCJCdWlsZGluZ3MiOnt9LCJCdWZmcyI6e30sIlNlYXNvbnMiOnt9LCJPdGhlck1vZHMiOnt9LCJ2YXVsdCI6W10sInBlcm1hbmVudFVwZ3JhZGVzIjpbLTEsLTEsLTEsLTEsLTFdLCJjaGltZVR5cGUiOiJDeW1iYWwiLCJtaWxrVHlwZSI6IkF1dG9tYXRpYyIsImJnVHlwZSI6Ik5pZ2h0In07Rm9ydHVuZSBDb29raWU6eyJzcGVsbEZvcmVjYXN0TGVuZ3RoIjoxMCwic2ltR0NzIjowLCJjb2xvck92ZXJyaWRlIjp7IkJ1aWxkaW5nIFNwZWNpYWwiOiIjRkYwMEZGIiwiQ2xpY2sgRnJlbnp5IjoiIzRCQjhGMCIsIkVsZGVyIEZyZW56eSI6IiNFMUM2OTkiLCJGcmVlIFN1Z2FyIEx1bXAiOiIjREFBNTYwIn0sImZvcmVjYXN0RHJhZ29uRHJvcCI6dHJ1ZX07SG9ydGljb29raWU6eyJhaE5ldyI6MCwiYWhKdWljeSI6MCwiYWhVcGdyYWRlIjowfTs%3D%21END%21```

### Browser / Steam / Version

Browser, version 2.048

**Comment by tvanantwerp** [comment]
I can confirm that I'm seeing the same thing. I have not ascended and purchased new upgrades, however—for me, it happened immediately the first time I ran CookieMonster after refreshing the browser to update to 2.048. Firefox 100.0.2 on macOS 12.2.1.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/2487968/171637078-939de40b-b7df-4ba1-822a-578705310dbd.png">
