### ISSUE TITLE
Unshackled javascript consoles heavenly upgrade can't be selected

### ISSUE THREAD

**Issue by faulk28** [Aktanusa/CookieMonster#1097]
### Bug description

After the new update I ascend, click on all available heavenly upgrade but the unshackled javascript consoled appears glitched. Can't select despite having a massive amount of heavenly chips.

### To reproduce

Very simple see above. Ascend and see you can't click on the upgrade.

### Screenshot

<img width="424" alt="Screenshot 2022-06-16 081654" src="https://user-images.githubusercontent.com/74863828/174067901-c6eb7b12-20e9-4bdf-aad1-eb4b20e7a9e9.png">

### Save file

[Faulk28Bakery - 2022-06-16T074647.423.txt](https://github.com/CookieMonsterTeam/CookieMonster/files/8918748/Faulk28Bakery.-.2022-06-16T074647.423.txt)

### Browser / Steam / Version

Google Chrome
Version 102.0.5005.115 (Official Build) (64-bit)

**Comment by faulk28** [comment]
Am I missing something? Could it be a glitch in my save file??

**Comment by domoddball** [comment]
![image](https://user-images.githubusercontent.com/32601481/174149719-b00b6d0a-47e7-4274-ba8e-904f17d615e6.png)
![image](https://user-images.githubusercontent.com/32601481/174149863-c41f714b-3851-4ad7-9538-551ba9516403.png)

screenshots taken from game loaded with save file provided
you have 4.674 quadrillion heavenly chips
upgrade costs 6.155 quadrillion heavenly chips

game and cookie monster are both working as intended

**Comment by faulk28** [comment]
Whoops. Thank you!

**Comment by faulk28** [comment]
My error
