### ISSUE TITLE
Fix scientific notation

### ISSUE THREAD

**Issue by Domo900** [Aktanusa/CookieMonster#110]
The exponent (ex: 12.89e+**15**) only can be a multiple of 3, which causes numbers such as 12.89e+15 to be written. The base (ex: **12.89**e+15) in scientific notation can be equal or greater than 1, but less than 10 for the number to be in proper scientific notation..

**Comment by Aktanusa** [comment]
I'll add another option to do this.

**Comment by Aktanusa** [comment]
Fixed in Version 2.0106.2
