### ISSUE TITLE
Building Timers

### ISSUE THREAD

**Issue by 0003c9fe** [Aktanusa/CookieMonster#112]
Currently, the timers when you mouse over a building that tell you how long it would take til you have enough cookies also include the cookies you have in wrinklers.

This means that if I don't want to pop my wrinklers yet, it may say I'm done even though I still have to wait for more cookies. It would be nice if there was maybe a settting to change this, or in the building mouseover it included 2 timers: 1 with wrinklers, and 1 without.

**Comment by Aktanusa** [comment]
The option "Calculate with Wrinklers ..." does what you want, but it is all or nothing kind of thing.  I may change it in the future.
