### ISSUE TITLE
No CPS, Still Has Time Left

### ISSUE THREAD

**Issue by 24680FPIC** [Aktanusa/CookieMonster#113]
I wanted to get True Neverclick as an achievement for fun, but after getting one Golden Cookie, the Time Left seemed to change. It still was quite long for even one cursor, (1m33s) but still, it has time left even when there were no buildings. 

How to reproduce:
Ascend.
Click on the cookie next to reincarnate and then click Born Again.
Reincarnate and wait for a Golden Cookie to spawn.
This part may be tedious as at this moment in the game, as Golden Cookies take a very long time to spawn.
Once you get a Lucky, you should have the weird Time Left stats at the bottom.

Game:
`Mi4wMDJ8fDE0ODM1NjM4Mjk1MTg7MTQ1NDM2NTAyMDEyMDsxNDgzNTY1MDQ5MjQyO01lZGlldmFsIEJvb3R5fMOnwr/CjQZ8MTM7MTM7MDsxNjU7MDsxMDM4OzA7MDsxLjMwNDM4OTQzNTczNDgzM2UrMjE7MDswOzA7MDswOzI7MjswOzA7MDswOzA7MDs7MDswOzEwOTI7NjI1OzQ2NzswOzE7MTA4Oy0xOy0xOy0xOy0xOzA7MDswOzA7NTA7MDswO3wwLDAsMCwwOzAsMCwwLDA7MCwwLDAsMDswLDAsMCwwOzAsMCwwLDA7MCwwLDAsMDswLDAsMCwwOzAsMCwwLDA7MCwwLDAsMDswLDAsMCwwOzAsMCwwLDA7MCwwLDAsMDswLDAsMCwwOzAsMCwwLDA7fMOkwoDCgMOkwoDCgMOkwoDCgMOkwoDCgMOkwoLCoMOkwoDCgMOkwoDCgMOkwoLCqMOkwoDCgMOkwoDCgMOkwoDCgMOkwoDCgMOkwojCgMOkwoDCgMOkwoDCgMOkwoLCgMOkwoDCgMOkwoDCgMOkwoDCgMOkwoDCgMOkwrDCgMOkwoDCgMOkwoDCgMOkwoDCgMOkwoDCgMOkwoDCgMOkwoDCiMOkwoDCgMOkwoDCgMOkwoDCgMOkwoDCgMOkwoDCgMOkwoDCgMOkwoDCgMOkwoDCgMOkwoDCgMOkwr/CgMOkwoDCjMOkwoDCgMOkwrzCgMOkwrzCgMOkwrDCgMOkwoDCgMOkwoDCgMOkwoDCgMOkwoDCiMOkwrDCs8OkwoDCgMOkwoDCgMOkwoDCgMOkwoPCsMOkwoDCg8OkwoDCgMOkwoDCgMOkwoDCgMOkwoDCgMOhwoDCsHzDp8K/wr/DpMK/wr/DpsK/wrvDp8K/wr/Dp8K/wr/Dp8K/wpfDpMK6woDDpMK/wqDDpMKcwobDpcKDwoDDpMKGwprDpMKHwqDDpMK+wr3Dp8KAwoDDpMKBwqDDpMKAwoDDpMKBwr7DpMKHwoDDpMKAwo4%3D%21END%21`

**Comment by Aktanusa** [comment]
The default method of calculating is average CPS in the past 10 mins.  Since you clicked on a Golden Cookie and it gave you cookies, it counts.  Hence why you see time left.

**Comment by 24680FPIC** [comment]
Ah, okay. Thanks.
