### ISSUE TITLE
Payback Period is broken in new version

### ISSUE THREAD

**Issue by SlaveredOnion** [Aktanusa/CookieMonster#1154]
### Bug description

Everything has a negative payback period after the update. Buying "Undecillion Fingers" seems to be what caused it.

### To reproduce

Open the game
Buy Undecillion Fingers

### Screenshot

![image](https://user-images.githubusercontent.com/14880007/236657150-fd49347d-9172-4b07-83f0-295615565ecc.png)

### Save file

```Mi4wNTJ8fDE2ODIzMDQxODg1Nzk7MTYwMDY2MTY0MDM5ODsxNjgzNDMyNTc3MTY0O1NsYXZlcmVkT25pb247dXBmeWU7MTUsMywxLDQsNiwxMywxNnwwMTExMDEwMDExMTAwMTExMDExMTAxMTAwMDF8NC4yMjk4MjMyNDA4MDc1MzllKzU2OzEuMTIzMjQ2NTEzNTc1NzY5OWUrNTc7MjY5MTs1MTY1OzguMDIwMDExMDEzMzQ2MjE3ZSs1NDsyODI4OzIzOzA7OC4zNzExOTgxOTAyODQ5NjdlKzU3OzM7MDswOzA7LTE7NTQ7OTs2LjQyMjI5MjUzMzgxMTIzNWUrNTU7MjgyOzE0OzM2Oy0xOzQ7OzIuNzk1NDI1OTE3Njg1Mjg4NGUrNTY7MTI7MjAzMDQ2NjcxNTQ5NDExMDszNjIxOTQ5MzQxMDgwNzA7MTY2ODI3MTc4MTM4NjA0MDswOzA7NTI7NTM7ODY7NDk3OzQ3OTsyNzszOzE3OzA7MTA7MDswOzMxOzc3MjsxNjgzNDMxNDkzNjA2OzA7MDsyMjcsMzM3LDQwMDs0MTsxOzE7My4wNzU3OTcxMzU1NjQ3MDhlKzUxOzUwOzA7MDt8NzkwLDI0OTAsOS4zNTQwMzExNjAxOTQ4MDdlKzU0LDEwLCwwLDg5MDs3OTAsMTM0MCw4LjkwODg4MDg3OTI2ODc2NGUrNTUsMTAsLDEsODkwOzc0MCwxMjkwLDIuMjYzOTIzMjYxMDEwODY5ZSs1MywxMCwxNjgzNDMyNzY1MDA1OjQ6MTY4MjMwNTAxMzYyNjowOjU6MjI0MDoxOjA6MTY4MjMwNDE4ODYxNTogMTExMTExMTExMDAxMTEwMDAwMDAwMDAxMTEwMDAwMTAwMCAwOjA6MjU6MTQ6MjU6NzQ6MDowOjI0OjY4OjA6MDowOjA6MjQ6MTA6MDowOjA6MDoyNTo5MjowOjA6MDowOjA6MDoyNToyNToyNDo1NjoyNToxODowOjA6MjQ6MzI6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MjU6ODowOjA6MDowOjA6MDoyNToyNjowOjA6MDowOjA6MDoyNTozMDoyNDozOTowOjA6LDAsODQwOzczMCwxMjgwLDYuNDk3MzgxNDE3NTg0NzA2ZSs1MywyLCwxLDgzMDs3MTAsMTI2MCw1LjUyMTY0NDkzODA3OTk1NmUrNTIsMiwsMSw4MTA7NjkwLDEyNDAsOC44MjEzMjYyMzMxMTcxMDRlKzUxLDEwLDQ6OTk6MTo0ODE3NjY4Ljk5NTcyMDA5OjE6IDMyODo0Oi02OjIzMjoxMTkwOjA6MDoxOTYhMTk4NToxOi02ODo3OTowOjE6MDozMDghMjMzOToyOi0xNzg6MTY4OjA6MTowOjM2OSExMDA6NDotMTU4OjQ0MToxMTQwOjA6MDoyODkhMTI2MTowOi0yODoyOTk6MTA1MDowOjA6NTE0ITQzOTU6MTotODM6NDE2OjA6MTowOjU1MSEyNTczOjQ6LTk5OjY0OToxMDAwOjA6MDoxNDYhNTI0Mzo1OjQyOjM3MTowOjE6MDo4MTkhNzc3Njo1Oi01MTo0MTowOjE6MDoxNzAhODgxMDoxOjEwOjYzNzowOjE6MDo2MTMhNzgyMTozOi01NDoxMDM6MDoxOjA6NDkxITkwNTo0Oi0xNDM6MTE3Ojk5MDowOjA6MTU4ITI5MTU6NDotMjk4OjIwMjowOjE6MDo3OTIhMTU1Mzc6MTotNTA6NDc1Ojk2MDoxOjA6NzA2ITE0NDIxOjU6MjQ6MTg1OjA6MTowOjk1MSE1MjU1OjQ6LTE0NzoyNTc6MDoxOjA6MCEyODY0OjQ6LTIxODo4NzowOjE6MDoxNjM3ITE4MDY4OjI6LTI3OjMyNDowOjE6MDowISAxLDAsNzkwOzY3MCwxMjIwLDYuODE5ODc0MTI3MTM4Njg4ZSs1MywzLDEwLzkvOCAzIDE2ODIzNzg2NjYzNzAgMSwxLDc3MDs2NTAsMTIwMCw1LjYxNDc5ODg1MDIyMjQ4N2UrNTEsMTAsMTAyLjg4NjY1OTg1OTA5MDA5IDE4NCAzODgwIDEsMCw3NTA7NjMwLDExODAsMS4wNDM1NzQwNzcxMTMyNjc4ZSs1MSwyLCwxLDczMDs2MTAsMTE2MCwzLjkxOTY4NzQ1MTgwMzIzNDRlKzUxLDIsLDEsNzEwOzYxMCwxMTYwLDQuNTAwNjI1Njg4MzcxNzczZSs1MywyLCwxLDcxMDs1ODAsMTEzMCw3LjA1MjEyNTI1OTc0OTYwOWUrNTIsMiwsMSw2ODA7NTYwLDExMTAsMS44MTMxMDk3ODQxMDc2MDA0ZSs1MiwxMCwsMSw2NjA7NTQwLDEwOTAsMS4wMTQ3NTE1ODQxNzIwMzU1ZSs1MywxMCwsMSw2NDA7NTIwLDEwNzAsMi4xOTc2NTQ3OTg1MDk4NzAzZSs1MywxMCwsMSw2MjA7NTEwLDEwNjAsMS40MTk4NTQyNDY3OTczMDk0ZSs1NCwxMCwsMSw2MTA7NDcwLDEwMjAsMS44MDI5MDI5Mjc1MDUwNTExZSs1MywxMCwsMSw1NzA7NDMwLDk4MCwxLjA1MDY2MDYxNzU4MzQyMzFlKzU0LDEwLCwxLDUzMDs0MDAsOTUyLDQuNTExNDI3NDczNTQ5MDg1ZSs1NCwxMCwsMSw1MDA7MzUwLDU1MCw3LjMxMDc0MjQ4MTE1OTgwNWUrNTEsMTAsLDEsNDUwO3wxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTAwMTExMTExMDAwMDAwMTEwMDExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMDEwMTAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAxMTExMDAxMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTEwMTAxMDAwMDAxMTExMTAxMDEwMTAxMDEwMTAxMDEwMTAxMDEwMTAwMDAwMDAwMDExMTExMTAwMDAwMDExMTAwMDAwMDAwMDAwMDAxMTExfDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTAxMTExMTEwMTExMTExMDAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDEwMTAwMDAxMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDEwMTExMTEwMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMDExMTAwMDExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTAwMDAxMDExMDAxMTExMDAwMDEwMDAwMDEwMDAwMDExMTExMTExMTEwMDAwMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDExMDB8fENvb2tpZU1vbnN0ZXI6eyJzZXR0aW5ncyI6eyJDUFNNb2RlIjowLCJBdmdDUFNIaXN0Ijo3LCJBdmdDbGlja3NIaXN0Ijo0LCJDYWxjV3JpbmsiOjIsIlNjYWxlIjo0LCJTY2FsZURlY2ltYWxzIjoyLCJTY2FsZVNlcGFyYXRvciI6MCwiU2NhbGVDdXRvZmYiOiI5OTk5OTkiLCJUaW1lRm9ybWF0IjowLCJEZXRhaWxlZFRpbWUiOjEsIlBQRGlzcGxheVRpbWUiOjAsIkJ1aWxkQ29sb3VyIjoxLCJQUE9ubHlDb25zaWRlckJ1eWFibGUiOjAsIlBQRXhjbHVkZVRvcCI6MCwiUFBSaWdpZGVsTW9kZSI6MSwiUFBTZWNvbmRzTG93ZXJMaW1pdCI6MCwiQ29sb3VyQmx1ZSI6IiM0YmI4ZjAiLCJDb2xvdXJHcmVlbiI6IiMwMGZmMDAiLCJDb2xvdXJZZWxsb3ciOiIjZmZmZjAwIiwiQ29sb3VyT3JhbmdlIjoiI2ZmN2YwMCIsIkNvbG91clJlZCI6IiNmZjAwMDAiLCJDb2xvdXJQdXJwbGUiOiIjZmYwMGZmIiwiQ29sb3VyR3JheSI6IiNiM2IzYjMiLCJDb2xvdXJQaW5rIjoiI2ZmMTQ5MyIsIkNvbG91ckJyb3duIjoiIzhiNDUxMyIsIkJvdEJhciI6MCwiVGltZXJCYXIiOjEsIlRpbWVyQmFyUG9zIjowLCJUaW1lckJhck92ZXJsYXkiOjIsIkF1dG9zYXZlVGltZXJCYXIiOjAsIlVwQmFyQ29sb3VyIjoxLCJVcGdyYWRlQmFyRml4ZWRQb3MiOjAsIlNvcnRCdWlsZGluZ3MiOjMsIlNvcnRVcGdyYWRlcyI6MSwiVXBncmFkZXNOZXZlckNvbGxhcHNlIjoxLCJEcmFnb25BdXJhSW5mbyI6MSwiR3JpbW9pcmVCYXIiOjEsIkdDVGltZXIiOjEsIkZhdmljb24iOjEsIldyaW5rbGVyQnV0dG9ucyI6MSwiSGlkZVNlY3Rpb25zQnV0dG9ucyI6MCwiVG9vbHRpcEJ1aWxkVXBncmFkZSI6MSwiVG9vbHRpcEFtb3IiOjAsIlRvb2xXYXJuTHVja3kiOjEsIlRvb2xXYXJuTHVja3lGcmVuenkiOjEsIlRvb2xXYXJuQ29uanVyZSI6MSwiVG9vbFdhcm5Db25qdXJlRnJlbnp5IjoxLCJUb29sV2FybkVkaWZpY2UiOjEsIlRvb2xXYXJuVXNlciI6MCwiVG9vbFdhcm5Cb24iOjEsIlRvb2xXYXJuUG9zIjoxLCJUb29sdGlwR3JpbSI6MSwiVG9vbHRpcFdyaW5rIjoxLCJUb29sdGlwTHVtcCI6MSwiVG9vbHRpcFBsb3RzIjoxLCJUb29sdGlwUGFudGhlb24iOjEsIlRvb2x0aXBBc2NlbmRCdXR0b24iOjEsIlN0YXRzIjoxLCJNaXNzaW5nVXBncmFkZXMiOjAsIk1pc3NpbmdBY2hpZXZlbWVudHMiOjEsIlVwU3RhdHMiOjEsIkhlYXZlbmx5Q2hpcHNUYXJnZXQiOiIwIiwiU2hvd01pc3NlZEdDIjoxLCJUaXRsZSI6MSwiR2VuZXJhbFNvdW5kIjoxLCJHQ05vdGlmaWNhdGlvbiI6MCwiR0NGbGFzaCI6MCwiQ29sb3VyR0NGbGFzaCI6IiNGNEY0MDAiLCJHQ1NvdW5kIjoxLCJHQ1ZvbHVtZSI6NTAsIkdDU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy82Ni82NjcxN185MzE2NTUtbHEubXAzIiwiRm9ydHVuZU5vdGlmaWNhdGlvbiI6MCwiRm9ydHVuZUZsYXNoIjowLCJDb2xvdXJGb3J0dW5lRmxhc2giOiIjZmZmZmZmIiwiRm9ydHVuZVNvdW5kIjoxLCJGb3J0dW5lVm9sdW1lIjo1MCwiRm9ydHVuZVNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTc0LzE3NDAyN18zMjQyNDk0LWxxLm1wMyIsIlNlYU5vdGlmaWNhdGlvbiI6MCwiU2VhRmxhc2giOjAsIkNvbG91clNlYUZsYXNoIjoiI2ZmZmZmZiIsIlNlYVNvdW5kIjoxLCJTZWFWb2x1bWUiOjMwLCJTZWFTb3VuZFVSTCI6Imh0dHBzOi8vd3d3LmZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMjEvMTIxMDk5XzIxOTMyNjYtbHEubXAzIiwiR2FyZEZsYXNoIjowLCJDb2xvdXJHYXJkRmxhc2giOiIjMDBCMDFEIiwiR2FyZFNvdW5kIjowLCJHYXJkVm9sdW1lIjo1MCwiR2FyZFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTAzLzEwMzA0Nl84NjE3MTQtbHEubXAzIiwiTWFnaWNOb3RpZmljYXRpb24iOjAsIk1hZ2ljRmxhc2giOjAsIkNvbG91ck1hZ2ljRmxhc2giOiIjMDBDM0ZGIiwiTWFnaWNTb3VuZCI6MSwiTWFnaWNWb2x1bWUiOjUwLCJNYWdpY1NvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMjIxLzIyMTY4M18xMDE1MjQwLWxxLm1wMyIsIldyaW5rbGVyTm90aWZpY2F0aW9uIjowLCJXcmlua2xlckZsYXNoIjowLCJDb2xvdXJXcmlua2xlckZsYXNoIjoiI2ZmZmZmZiIsIldyaW5rbGVyU291bmQiOjEsIldyaW5rbGVyVm9sdW1lIjo1MCwiV3JpbmtsZXJTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyNC8xMjQxODZfODA0My1scS5tcDMiLCJXcmlua2xlck1heE5vdGlmaWNhdGlvbiI6MCwiV3JpbmtsZXJNYXhGbGFzaCI6MCwiQ29sb3VyV3JpbmtsZXJNYXhGbGFzaCI6IiNmZmZmZmYiLCJXcmlua2xlck1heFNvdW5kIjoxLCJXcmlua2xlck1heFZvbHVtZSI6NTAsIldyaW5rbGVyTWF4U291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNTIvMTUyNzQzXzE1NjYzLWxxLm1wMyIsIkJ1bGtCdXlCbG9jayI6MSwiRmF2b3VyaXRlU2V0dGluZ3MiOjF9LCJoZWFkZXJzIjp7IkZhdm91cml0ZSI6MSwiQ2FsY3VsYXRpb24iOjAsIk5vdGF0aW9uIjowLCJDb2xvdXJzIjowLCJCYXJzRGlzcGxheSI6MCwiVG9vbHRpcCI6MCwiU3RhdGlzdGljcyI6MCwiTm90aWZpY2F0aW9uIjowLCJOb3RpZmljYXRpb25HZW5lcmFsIjowLCJOb3RpZmljYXRpb25HQyI6MCwiTm90aWZpY2F0aW9uRkMiOjAsIk5vdGlmaWNhdGlvblNlYSI6MCwiTm90aWZpY2F0aW9uR2FyZCI6MCwiTm90aWZpY2F0aW9uTWFnaSI6MCwiTm90aWZpY2F0aW9uV3JpbmsiOjAsIk5vdGlmaWNhdGlvbldyaW5rTWF4IjowLCJNaXNjZWxsYW5lb3VzIjowLCJMdWNreSI6MCwiQ2hhaW4iOjAsIlNwZWxscyI6MCwiR2FyZGVuIjowLCJQcmVzdGlnZSI6MSwiV3JpbmsiOjAsIlNlYSI6MCwiQWNoaWV2cyI6MCwiTWlzYyI6MSwiaW5mb01lbnUiOjEsIm9wdGlvbnNNZW51IjoxfSwiZmF2b3VyaXRlU2V0dGluZ3MiOlsiU29ydEJ1aWxkaW5ncyIsIlBQT25seUNvbnNpZGVyQnV5YWJsZSIsIkNhbGNXcmluayIsIlBQUmlnaWRlbE1vZGUiLCJVcGdyYWRlc05ldmVyQ29sbGFwc2UiXSwibG9ja2VkTWluaWdhbWVzIjpbXSwidmVyc2lvbiI6IjIuMDQ4LjEwIn07Y29va2llTW9uc3RlckZyYW1ld29yazp7InNldHRpbmdzIjp7fSwiaGVhZGVycyI6eyJpbmZvTWVudSI6MSwib3B0aW9uc01lbnUiOjF9LCJmYXZvdXJpdGVTZXR0aW5ncyI6W119Ow%3D%3D%21END%21```

### Browser / Steam / Version

Browser (Firefox) version 2.052

**Comment by DanielNoord** [comment]
Should be fixed with https://github.com/CookieMonsterTeam/CookieMonster/pull/1153
