### ISSUE TITLE
The "<0%" on golden cookie timer is almost never useful. Let's improve it

### ISSUE THREAD

**Issue by Krydax** [Aktanusa/CookieMonster#1160]
### Feature description

Currently, there is a "<0%" on the golden cookie timer bar that generally stays at <0% forever. I'm not sure if it's calculating the chance of a golden cookie *per tick*? or what? But I've only ever seen it get to 1% at the highest before a golden cookie spawned. So I'm guessing it's calculating the chance of a golden cookie for an extremely small time period.

My suggestion: Make it calculate the chance of a golden cookie in the next 5 seconds. This way the number will actually show something reasonably larger. And won't just be at 0 or 1 and then the golden cookie pops in.

**Comment by DanielNoord** [comment]
This is indeed the percentage per tick.. Closing in favour of https://github.com/CookieMonsterTeam/CookieMonster/issues/921.
