### ISSUE TITLE
When I click on Stats to open the Stats page, Cookie Clicker freezes and the page becomes unresponsive (Chrome, both Mac and PC)

### ISSUE THREAD

**Issue by jeffslutzky** [Aktanusa/CookieMonster#1162]
### Bug description

Starting this morning, when I click on Stats to try to open the Stats page, it doesn't open and instead Cookie Clicker freezes and the page becomes unresponsive. This happens using the Google Chrome browser, I tried it on both a Mac and a PC, both in a regular tab in an incognito tab with no Chrome extensions turned on.

### To reproduce

1. Start Cookie Clicker
2. Start Cookie Monster
3. Click on Stats

### Browser / Steam / Version

Chrome

**Comment by DanielNoord** [comment]
I merged this this morning https://github.com/CookieMonsterTeam/CookieMonster/pull/1161.

@grelca Can this be related?

**Comment by grelca** [comment]
@DanielNoord definitely could be since the change is on the stats page. i didn't see any issues when i was testing it in my local browser (chrome on mac) but probably worth to revert.

**Comment by EricC-59** [comment]
When stopping the frozen thread, it seems indeed stuck between CalculateLuckyLevels and CountSevens

**Comment by DanielNoord** [comment]
@grelca I won't be near a computer with my dev setup to do the revert for a couple of days. Could I ask you to create a PR reverting the change?
Or coordinate with @EricC-59 to find out what the bug is? I'd also be happy to merge a bug fix.

**Comment by grelca** [comment]
@DanielNoord opened a revert PR, won't have time to try and debug anything until after my workday ends. #1163

**Comment by grelca** [comment]
thinking about this a little, i have a feeling this is happening once the levels get high enough that float precision starts to be an issue

**Comment by DanielNoord** [comment]
Should be closed by https://github.com/CookieMonsterTeam/CookieMonster/pull/1179.
