### ISSUE TITLE
About the upgrade efficiency feature

### ISSUE THREAD

**Issue by Chapsteck4yurlipis** [Aktanusa/CookieMonster#117]
I usually use CookieMonster for this feature. However, occasionally I sometimes use the semi-broken TriggerCookies as an alternative. This is because the feature is a very off due to prisms being counted at the very beginning, as you will likely never see any orange-rated upgrades until then. Essentially, this mod works at its full glory when you have got to prism-level. This could be fixed by only counting bought buildings. Another thing that I find weird is that the red and green upgrade colors are only seen if the number is exactly the same as the best building or worst. This makes it where red and green are almost never used because an exact BCI match is almost impossible to achieve. I was thinking you could make red and green w/ the upgrades to be around worst and around best. Anyways, I'm done here. I hope you can take this into consideration!

**Comment by Aktanusa** [comment]
Hi there.  I don't understand how prisms being counted from the start is "very off."  Could you provide proof that TriggerCookies does this better?

As for the colors for upgrades, that is the point of having blue and purple color to show better than green and worse than red buildings.  I'm not exactly sure what you're suggesting.

**Comment by Chapsteck4yurlipis** [comment]
Okay, thanks for replying. Prisms being counted at the very start ends up in no orange or red-colored buildings, making the quick efficiency check rather pointless because of how high-up there prisms are, which affects the worst and best building function due to the prism outlier compared to what you have bought or can buy. Same goes for antimatter condensers etc. Now, TriggerCookies currently counts buildings that you have unlocked, which is better that what I had originally stated. It would be very useful if you could incorporate this into Cookie Monster so that you could quickly see the least efficient from the very beginning. Cursors in TriggerCookies are automatically counted as the best upgrade until grandmas are unlocked, in this case Cursors will switch to red and grandmas will be green usually due to grandmas having a higher efficiency at the moment.

Now, the thing that bugs me is the little upgrade counter on the top having green and red, I would not prefer them removed but simply edited to an around-best and around-worst, since it kind of gets on my OCD that blue goes straight to yellow then to orange then to purple on the upgrades. I just think it will make it a little bit aesthetically better, in a sense. (Plus, it would prove more useful.) ((oh, and I don't think this will be fixed by removing purple and blue, green and red would mean you would get a similar effect if you bought the green and red building and purple and blue would mean you would get a better or worse effect than the building))

**Comment by Aktanusa** [comment]
Okay, now I understand you better.  It's not that the calculations are "off", it's just that the color scheme is of low resolution and doesn't have enough "colors" to show off the difference in efficiency when the difference is huge, like when you are first starting off.  A solution, as you say TriggerCookies does, is to ignore the highly priced buildings (or maybe even upgrades) until they are within reach.  Hmm, I would have to think about that.  Another solution is to add more colors, lol.

As for your colors, I understand what you mean better, though I think you mean the progression from purple to blue could be better, not the other way, like you mention.  As for a solution, I was going to suggest removing green and red and merging them to blue and purple, but apparently you don't like that idea.  Have it close to green or red is another solution, but somehow I just don't like that idea.  I'll think about it.

**Comment by Chapsteck4yurlipis** [comment]
Thanks for the response! I'll keep in tune with the mod and see if you decide to do anything.

**Comment by Aktanusa** [comment]
Okay cool.  I will admit, I've mostly lost interest/lack of time to work on this, so it might be a while.  I did have another thought of taking the building closest to the average difference of worse efficiency to be set to red, and anything after to be purple so things like Prism wouldn't affect it as much.
