### ISSUE TITLE
Tooltip "Lucky" warning should not account for the extra CpS after buying the building/upgrade

### ISSUE THREAD

**Issue by damerell** [Aktanusa/CookieMonster#1171]
### Bug description

The tooltip warning that you won't have enough banked cookies for a full "Lucky!" golden cookie reward after buying a given upgrade or building calculates the needed banked amount after the purchase of the upgrade or building. This is not appropriate - if you don't buy it, you still won't get the additional maximum "Lucky!" reward, so keeping those extra cookies does you no good.

(eg, suppose I have n cookies. I would need 6000n cookies in the bank to get a full "Lucky!" reward. If the best upgrade-or-building costs m cookies, as soon as I have 6000n + m cookies, I should buy it. After I do so I'm below the new "Lucky!" threshold, but until I do buy it, I couldn't get to that threshold at all.)

### To reproduce

Turn on "Tooltip lucky warning". Mouse over building or upgrade.

### Browser / Steam / Version

Browser (Firefox), 2.052

**Comment by cryptk** [comment]
@damerell there is already an option for this.  Go to Options > Tooltips > "Calculate tooltip warning with bonus CPS" and if you set that to Off then the warning thresholds will not include the increased CPS from buying the building/upgrade

**Comment by damerell** [comment]
Yes, sorry, just found this now. Closing.
