### ISSUE TITLE
Support for v2.0034

### ISSUE THREAD

**Issue by D0han** [Aktanusa/CookieMonster#120]
v2.0034 just rolled out, but current mod produces curious results with it.

**Comment by Aktanusa** [comment]
I'm on vacation right now, but I should take a look at it by the end of this week.

**Comment by Aktanusa** [comment]
I'm back now and will take a look tonight, though doesn't mean it be finished tonight =p.

**Comment by Aktanusa** [comment]
Fixed in Version 2.0034.1
