### ISSUE TITLE
Shorter Short Scale

### ISSUE THREAD

**Issue by Kidsheldon** [Aktanusa/CookieMonster#122]
Instead of:
M, B, Tr, Quadr, Quint, Sext, Sept, Oct, Non, Dec, Undec, Duodec, Tredec
I propose these:
M, B, T, Qa, Qi, Sx, Sp, Oc, No, Dc, Udc, Ddc, Tdc
These are no longer than three letters and clearly represent their full-length words.
(I got this idea from Trimps btw)

**Comment by Aktanusa** [comment]
Interesting proposal, maybe I'll add the option instead so that we would have both!

**Comment by TakGalaman** [comment]
Another idea: add rounding options. I pretty much do nothing with the decimals shown to me. It would be much cleaner to show no decimals, or maybe a tenth's place.

So, I propose a setting to personalize rounding factors. Some people might like seeing the thousandth's place. I think I'd choose to show the first decimal.

**Comment by DanielNoord** [comment]
Similar to #268
