### ISSUE TITLE
Show grimoire RNG seeds

### ISSUE THREAD

**Issue by GC13** [Aktanusa/CookieMonster#123]
If they are accessible to Cookie Monster, it would be very helpful for the player to be able to see whether his upcoming spells will succeed or backfire, with and without Diminish Ineptitude being cast (and perhaps with Ineptitude Magnified as well).

As an addendum, letting you know the result of a Force the Hand of Fate or a Spontaneous Edifice would also be great.

**Comment by Hoten** [comment]
Keeping this optional would be nice. I think this is well within "cheating" territory, and I prefer avoiding that when playing.

**Comment by Aktanusa** [comment]
It would probably be in a category you can + or -

**Comment by GC13** [comment]
Think about it this way: it saves Orteil the bandwidth of me refreshing after checking what the result would be.

I've edited the original suggestion though: knowing what cookie you'll get from Force the Hand of Fate would be super helpful.

**Comment by Aktanusa** [comment]
Well there is a script someone already made which I've ask if I can copy, so I can see this being added soon.

**Comment by DanielNoord** [comment]
As this is more of a cheat, and already available in other mods I close this for now.
