### ISSUE TITLE
Use of Cyclius god affects bonus income calculation for all upgrades and buildings

### ISSUE THREAD

**Issue by Jarred10** [Aktanusa/CookieMonster#124]
Seems to be an issue with the following code: 

var godLvl = Game.hasGod('ages');
		if (godLvl == 1) mult *= 1 + 0.15 * Math.sin((Date.now() / 1000 / (60 * 60 * 3)) * Math.PI * 2);
		else if (godLvl == 2) mult *= 1 + 0.15 * Math.sin((Date.now() / 1000 / (60 * 60 * 12)) * Math.PI*2);
		else if (godLvl == 3) mult *= 1 + 0.15 * Math.sin((Date.now() / 1000 / (60 * 60 * 24)) * Math.PI*2);

The time difference between when the game calculates total cps and the sim calculates cps means every upgrade will have slightly inflated numbers. Clearly evident on upgrades that should have 0 bonus income like the elder covenenant and mouse upgrades. Hovering over the mouse shows it changing over time.

![image](https://user-images.githubusercontent.com/7507223/28385899-e4e0a3f0-6d1d-11e7-950a-c0b73da7ae53.png)

![image](https://user-images.githubusercontent.com/7507223/28386014-583b6ca4-6d1e-11e7-9efd-5071119067d0.png)

**Comment by Aktanusa** [comment]
Oops, yea, I know what's wrong.

**Comment by Aktanusa** [comment]
For a second, I thought I overlooked your fix on it, but nope, you have the same problem too, lol

**Comment by Aktanusa** [comment]
Fixed in Version 2.0034.2

**Comment by Aktanusa** [comment]
That should do it, let me know if it doesn't!

**Comment by pancholodbrok** [comment]
I was a about to post the same issue (detected it in kitten upgrades which showed incredibly high income increase). New release has fixed it, thanks!
