### ISSUE TITLE
Purchase recommendation only wants Shipments

### ISSUE THREAD

**Issue by unsolicitedcrap** [Aktanusa/CookieMonster#125]
Cookie monster is only recommending that I buy shipments. WIth each shipment purchase, the payback period becomes more and more negative, and therefore is recommended to keep buying more. I sold everything, then bought 1 of everything, and then followed cookie monster's recommendations and as you can see from the picture, it keeps saying to buy shipments. and nothing else. This doesn't seem right, nor what it used to recommend prior to the latest update.
![cc-cm](https://user-images.githubusercontent.com/6231629/28470964-75e53be0-6e09-11e7-9a12-de146998eecf.png)

**Comment by Rollermiam** [comment]
Upgrade to cookie monster v2.0034.2

**Comment by Aktanusa** [comment]
Like @Rollermiam somewhat said, you're using the older version of Cookie Monster not meant for the current version.  The warning should have notify you of that.  I've already updated Cookie Monster so this problem doesn't exist anymore plus a few bug fixes.  Just reload Cookie Monster.

**Comment by unsolicitedcrap** [comment]
Sorry. I thought reloading my browser would reload Cookie Monster with the new version, but I guess it's not.

**Comment by Aktanusa** [comment]
Weird, I would think to same too.  Are you using Userscript?

**Comment by Aktanusa** [comment]
Ah, now I see.  Yea I need to update the beta sometime.
