### ISSUE TITLE
Color coding for sugar lumps spending?

### ISSUE THREAD

**Issue by pancholodbrok** [Aktanusa/CookieMonster#127]
In the same fashion as building or upgrades, I would like Cookie Monster to show where it is best adviced to spend sugar lumps (1 on time machine or 2 on prisms ? Who knows?).
I know sugar lumps can be used somewhere else, but these usages could be ignored IMHO (I can't see why anyone would recharge magic with them).

**Comment by Aktanusa** [comment]
Yep, I plan to add this.  Thanks for making an issue for me! lol.

**Comment by Kidsheldon** [comment]
I feel like this is unnecessary. The best Lump investment right now is not what you want to invest in. You want to first, invest towards unlocking minigames, then level 10 of everything, then focus on the best late-game buildings.

**Comment by DanielNoord** [comment]
This is completely dependent on your "lump-strategy". In some nice cases there can be a "lump-PP" but I do not think that it is worth the effort to add this.
