### ISSUE TITLE
Adding Dotjeiess in Pantheon throws off Bonus Income (and therefore PP)

### ISSUE THREAD

**Issue by cmenning** [Aktanusa/CookieMonster#129]
I added the Dojeiess, Spirit of Creation to the Diamond Slot in my Pantheon. This seems to have disrupted the Bonus Income and PP calculations for all my buildings. 

My cheaper buildings are all now showing Bonus Incomes of roughly 9.5% income, which is far too high.

**Comment by Aktanusa** [comment]
Are you using the latest version?

**Comment by Aktanusa** [comment]
Fixed in Version 2.0034.3
