### ISSUE TITLE
Add Skruuia Wrinkler Bonus to Max Prestige and HC Calculation

### ISSUE THREAD

**Issue by Kidsheldon** [Aktanusa/CookieMonster#131]
It turns out that when you slot Skruuia in, your Wrinklers instantly have 15% more cookies (assuming Diamond slot), which can have quite an effect on max Prestige.

**Comment by Aktanusa** [comment]
It's already there.  Are you sure it's not?

**Comment by Kidsheldon** [comment]
"The MAX heavenly chips is calculated with the cookies gained from popping all wrinklers [with Skruuia in the diamond Pantheon slot], selling all buildings with Earth Shatterer aura, and buying Chocolate egg"

The bonus is applied retroactively (if you let Wrinklers eat cookies for any amount of time without Skruuia, slotting Skruuia adds 15% cookies to their total). If Cookie Monster does calculate the heavenly chips/prestige with the Skruuia bonus, the tooltip doesn't say.

**Comment by Aktanusa** [comment]
Well it was a given via the part of "popping all wrinklers".  I've both checked the code and tried it out and the numbers do change when I slot/unslot Skruuia.  Are you suggesting I just update the tooltip or does the bonus not change when you slot/unslot Skruuia?

**Comment by Kidsheldon** [comment]
I was suggesting you update the tooltip and, if it's not so already, calculate the MAX assuming Skruuia is slotted in diamond.

**Comment by Aktanusa** [comment]
Hmm, I can see the problem with max not really max now.  The other two Wrinkler sucking upgrades are there or not, which made it easy, but with Gods, you can change on a whim.  This is an interesting problem.  The same calculation is used to tell you current cookies you'd get from popping all, so I guess the solution is to add on the god bonus to max only if the god is not there already.  Okay, I see it as a problem.  I'm not sure if this is called a bug or enhancement though, lol.

**Comment by Kidsheldon** [comment]
oops

**Comment by Aktanusa** [comment]
Fixed in Version 2.0042.2
