### ISSUE TITLE
Version 2.0042 alignment

### ISSUE THREAD

**Issue by D0han** [Aktanusa/CookieMonster#134]
Hi, it seems that we have new 2.0042 clicker version ;)

**Comment by Sekhy2** [comment]
The negative "payback period" are back... :/

I think it came from the new kittens upgrade. The pp seemed to be fine before buying them. Nasty little kitten!

**Comment by jabenninghoff** [comment]
I too noticed the negative payback period after purchasing the kittens, which before didn't have a value associated with them (I assume since they're new).

**Comment by Mitsunee** [comment]
didn't think that'd happen. Are the new buildings and the new upgrade tier fine?

**Comment by jabenninghoff** [comment]
Everything seemed to work OK until purchasing the first Kitten, I haven't tested to verify.

**Comment by Aktanusa** [comment]
Well soon it won't matter, when I fix the script =p.  Give me a few hours.

**Comment by Mugen2411** [comment]
Sorry, I have poor English.
https://dl.dropboxusercontent.com/s/8xdjhbxj3vztwfb/CookieMonster.js
This has been updated by me informally.
If this Link has any problems ,I will I'll remove that immediately.
In addition, when CookieMonster is updated formally, I will I'll remove that immediately.

**Comment by Aktanusa** [comment]
Fixed in Version 2.0042.1

**Comment by Aktanusa** [comment]
@Mugen2411:  Thanks for the help, though it seems you removed your post very quickly, lol.

**Comment by Mugen2411** [comment]
​Sorry.
I think formally update comes quickly.
I would like to create Cookie Monster's new ​function.
I will learn Javascript to make that.
See you again.

2017-08-09 9:49 GMT+09:00 Aktanusa <notifications@github.com>:
