### ISSUE TITLE
"Lucky" cookie warning/caution for buildings/upgrades does not account for the increase in the "Lucky" minimum due to purchase

### ISSUE THREAD

**Issue by LiveBeef** [Aktanusa/CookieMonster#135]
I've noticed a few times after purchasing an upgrade or a building that did not have the warning/caution about falling below the level for the max reward for a Lucky cookie, that after purchasing the item, I fall below the maximum anyway. This is because purchasing buildings and upgrades raises the level for cookies required for a max Lucky reward. The warning/caution boxes should account for this and raise the items' deficits accordingly.

**Comment by Aktanusa** [comment]
Actually, the more efficient way is the default way, but there is an option to change it. under Calculations

**Comment by LiveBeef** [comment]
Ah, I didn't realize that's what that was. My mistake!
