### ISSUE TITLE
Provide ETA on Grimoire spell casting

### ISSUE THREAD

**Issue by Hoten** [Aktanusa/CookieMonster#136]
Would be nice to see an ETA on when a spell will be ready. Given that the recharge rate varies based on current mana amount, it would involve something more involved than a simple linear calculation.

If no one else is working on this, I could tackle it.

**Comment by Aktanusa** [comment]
DO you mean when the bar is full or when a spell is usable in tooltip or both?

**Comment by Hoten** [comment]
I was thinking just for when a spell is usable, in it's tooltip.

The same logic could be used to determine when the bar would be full, too. That's a good idea.

**Comment by Hoten** [comment]
Basically would have to develop a function "timeUntilMana(current, target)".

**Comment by Hoten** [comment]
Okay, it took me awhile to brush up on my calculus, but I believe I derived a strong estimate for this. I'd like to give implementing it myself a shot. But, I'll share the calculation code here now, just in case there is a bus in my future ...

https://gist.github.com/Hoten/0893154f49cf58389b570bf81611fb55

It won't work well for estimating times between 0 mana and onward, due to the "minimum mana/second". I basically ignored the piece-wise-nature of the mana/second relation, since 1) it is rare to get close to 0 mana and 2) it should only be inaccurate for a few seconds.

**Comment by Aktanusa** [comment]
Thanks for doing the work!

**Comment by Hoten** [comment]
You're welcome, I enjoyed it. If you're interested in an additional maintainer, I'd love to volunteer. Let me know how I could help!

**Comment by Aktanusa** [comment]
I'll think about it =p

**Comment by TakGalaman** [comment]
I'd just like to say I'm super stoked for this feature!

**Comment by Aktanusa** [comment]
Should (hopefully) be finished and released today.

**Comment by Aktanusa** [comment]
Well ran into problems that delayed this, but now it's done.  Added in Version 2.0042.2.
