### ISSUE TITLE
 Information about discounts in the tooltip

### ISSUE THREAD

**Issue by Naikoraptor** [Aktanusa/CookieMonster#137]
Would be nice to add information about cost of Bulding\Upgrade with Dotjeiess in Dimond slot and active Hgglers charm or Crafty pixies

**Comment by Aktanusa** [comment]
Thanks!

**Comment by Naikoraptor** [comment]
http://prntscr.com/g9tkhd
Some idea
Do you think that there is any sense in any "yes / no" marker that would calculate the discount by 2% for improvements and would compare with the 2 of the last building? (Because the aura needs to be removed after purchasing)

I do not even ask about the same aura working on buildings, because it's stupid, to lose the building that you were going to buy.

**Comment by Aktanusa** [comment]
Is this the same enhancement or something else?  If it's something else, I think it would be best to make a new issue to separate it.

**Comment by Naikoraptor** [comment]
Most likely this should not be combined with the rest of the discount calculations, because it is trivial to require other manipulations, but this is directly related to the same subject of discounts. Create a new topic or leave here, the choice is yours.

**Comment by Aktanusa** [comment]
I am unsure what you are suggesting, honestly.  Change the aura, lose an expensive building, in hopes it might lower a cost of an upgrade that will be be worth more than the cost of the building?

I already made my choice.  Please make a new topic if you want to talk about your suggestion.  I'm going to stop talking about it here.
