### ISSUE TITLE
Calculate of dragon aura

### ISSUE THREAD

**Issue by Naikoraptor** [Aktanusa/CookieMonster#139]
http://prntscr.com/g9tkhd
Some idea
Do you think that there is any sense in any "yes / no" marker that would calculate the discount by 2% for improvements and would compare with the 2 of the last building? (Because the aura needs to be removed after purchasing)

"Change the aura, lose an expensive building, in hopes it might lower a cost of an upgrade that will be be worth more than the cost of the building?" - Yes, exactly, does this idea have the right to exist? Because sometimes improvements for which you need 10-20 days of passive income, have such huge stakes that even 2% of it can recoup the loss of the 2 best buildings.

**Comment by Aktanusa** [comment]
Honestly, I don't know.  I does sound like an interesting idea to explore though.  I know in the past sometimes CM would recommend something super expensive (mostly kittens) that would take a while to get.  In those cases, this aura may help.

PS.  Thanks for making the issue.
