### ISSUE TITLE
Pop All But Shiny Wrinklers button

### ISSUE THREAD

**Issue by Hoten** [Aktanusa/CookieMonster#140]
would help in my dream of amassing 12 shinies

**Comment by Aktanusa** [comment]
hmm, I can see why one would want to do that, lol.

**Comment by TakGalaman** [comment]
Perhaps this should be implemented where if there is a shiny wrinkler present then the "pop all" button says "pop all non-shiny wrinklers" and next to it there is a checkbox that can be checked to change the button to be "pop ALL wrinklers." So the default would be to preserve your shiny wrinklers, and there's a very conscious step needed to pop the shiny ones. This might help people who don't know what shiny wrinklers realize they've got something special on their hands, too.

**Comment by Aktanusa** [comment]
With how rare a shiny is, I think it's safe to say you can always manually pop the shiny and not have the pop all ever pop a shiny.

**Comment by TakGalaman** [comment]
Fair enough

**Comment by Aktanusa** [comment]
Added to Version 2.0106.1

**Comment by Hoten** [comment]
Thanks!
