### ISSUE TITLE
Make Scientific Notation Correct

### ISSUE THREAD

**Issue by KQQM** [Aktanusa/CookieMonster#141]
This is a very small nitpick but the scientific notation is wrong. You need only 2 significant digits to the right of the decimal. I really want to use scientific but it throws me off to have that third digits.

**Comment by Aktanusa** [comment]
So this is different than Issue #110?

**Comment by KQQM** [comment]
It is not. But I noticed that it was from a year ago and thought to, maybe voice my opinion as well? It's just a feature I would really love to see. Apologies if this was unnecessary.

**Comment by Aktanusa** [comment]
No apologies needed, I should get around to doing all the easy ones.

**Comment by Aktanusa** [comment]
Finally working on this (yea, I'm late), I'm looking at the wiki, and can't find where it says that only 2 significant digits to the right of the decimal is the correct way for scientific notation.  What an I missing?

**Comment by KQQM** [comment]
Normalized standard notation is the standard I know everyone else uses
which is only two to the right. There's a number of possible ways to go
about this but the standard (at least taught here in the states) has always
been two decimals.

**Comment by Aktanusa** [comment]
Do you have a source somewhere besides just saying everyone knows?  I'll try to Google it also but like I said, Wikipedia doesn't mention anything like that for standard notation.

**Comment by omegacute** [comment]
I don't want to create another issue so I'll post it here.

https://en.wikipedia.org/wiki/Scientific_notation
According to this article, what you currently have is in fact engineering notation (the exponent is restricted to multiples of 3). I personally can't stand this notation in games like Cookie Clicker, so please rename what you currently have to engineering notation and add the proper scientific notation (meaning that the exponent can be any number and not just multiples of 3, and the coefficient is always between 1 and 10).

**Comment by Aktanusa** [comment]
That issue, as said earlier, is on #110.  Which has been fixed.  If you check the commit log for the dev branch, I did just as you said, rename to engineering (more like rewrote) and added real scientific.

**Comment by omegacute** [comment]
Ah, I see. I used the stable version so I didn't see the changes. I couldn't find a way to make it work with the dev version, so I guess I'll have to wait till you push it to stable.

**Comment by Aktanusa** [comment]
That's weird, the instructions on the readme should work in getting the dev version to load.  Are you saying those instructions are not working for you?

**Comment by omegacute** [comment]
Nevermind, I just didn't do it correctly. I tried the beta version and then tried the raw from this link:
https://raw.githubusercontent.com/Aktanusa/CookieMonster/dev/CookieMonster.js which doesn't work. So I somehow missed the instructions about the dev version in the bugs section. 🤦‍♂️ 
Now it's working fine for me. I am not sure if it's the latest version but at least the scientific notation works fine.

Sorry for bothering you. 🙇

**Comment by Aktanusa** [comment]
You can tell if you have the right one loaded if you get something like "..., Short Scale, Scientific Notation, Engineering Notation" (in that order) when pressing the button.
