### ISSUE TITLE
Option to disable bulk-buying if you can't afford the "full bulk" (10 or 100)

### ISSUE THREAD

**Issue by Treazer** [Aktanusa/CookieMonster#143]
To be more precise: Currently, if you can afford 6 grandmas for instance and you want to bulk-buy 10, the button will be grayed out. However, if you click on it, 6 grandmas will be bought anyway. I would like to have that disabled, so that there are only buildings bought if you can afford the selected amount. This would be useful for me when I quickly want to buy 10 units of a building consecutively.

**Comment by Aktanusa** [comment]
Do you think this option should be on by default?

**Comment by Treazer** [comment]
I think so, yes. In fact, I was surprised it worked this way when I first used the feature, it kinda defeats a part of its purpose in my opinion.

**Comment by TakGalaman** [comment]
I agree that a grayed out button should have no effect when clicked.

I also sort of like the ability to buy what you can.
I propose that when you can buy some of the bulk buy we show a little button superimposed that says "Buy <however many you could buy>". e.g. I have buy 10 selected and prisms are grayed out, but I have enough money to buy 3. The button would appear and explain "You don't have enough money to buy all 10, but if you want to buy as much as possible here's a way to do that."
