### ISSUE TITLE
Warning/Caution for buildings/numbers have incorrect value

### ISSUE THREAD

**Issue by Micman27** [Aktanusa/CookieMonster#144]
The warning/caution for buildings and upgrades that tell you how many cookies you need to have to not break the maximum cookies required for Lucky/Lucky Frenzy are incorrect. Actually, they are "correct", but they take in your current cps, not the cps you have after buying the upgrade.

If you have 100 cps and an upgrade gives +10%, the upgrade would show that you would need a bank of 600,013 cookies (plus the price of the upgrade) for a max Lucky!, but it doesn't take in that you would have 110 cps after buying the upgrade, so it should've shown that you needed a bank of 660,013 cookies (plus the price of the upgrade).

Probably not the largest bug in the world, but it's particularly annoying if you just hit the threshold for a kittens upgrade, and buying it suddenly puts you far under the Lucky Frenzy bank.

**Comment by Aktanusa** [comment]
The more efficient way is the default way, but if you want the other way, it is an option in settings under Calculations.

**Comment by Micman27** [comment]
Whoops

**Comment by Aktanusa** [comment]
Don't worry, I get this once in a while.  I'm not sure what I can do to make it more visible as honestly the default method is more efficient.
