### ISSUE TITLE
Make Grimoire always accessible (less scrolling)

### ISSUE THREAD

**Issue by TakGalaman** [Aktanusa/CookieMonster#145]
This is similar to issue #126. 
If a golden cookie comes up I want to have easy access to "Hand of Fate" in case I get a duration effect. Often I'm looking at stats though and I've scrolled down far, so in order to see my spells I have to close stats then scroll up to the Grimoire.

One way to do this might be an option to collapse certain building types on the building view of the center column so there's less content and no need to scroll. I don't _need_ to see my buildings that don't have minigames.

**Comment by TakGalaman** [comment]
I feel a little silly for not noticing this until now, but just zooming out on the page helps work around this.

**Comment by Aktanusa** [comment]
That is a workaround, but it won't be obvious to everyone.  I do see it being annoying, but when there are mini games for all buildings, the same problem may somewhat still be there.  I'll think about it.

**Comment by jacktose** [comment]
You can mute all the non-minigame buildings. Maybe that wasn't available when this bug was opened? It can probably be closed.

**Comment by Aktanusa** [comment]
That's true, does sound like this can be closed now.  I'll take a closer look before deciding.
