### ISSUE TITLE
Show current bonus from Century Egg in Tooltip

### ISSUE THREAD

**Issue by TakGalaman** [Aktanusa/CookieMonster#146]
After you've purchased the Century Egg you might be curious how much it's boosting you. The description just says you get more over time. 
My suggestion is that when you mouse over the Century Egg in your purchased upgrades it should show the Cookie production Multiplier it's giving you right now so it's more consistent with other cookies.

**Comment by Aktanusa** [comment]
This is already in stats.  I don't see a reason to add to the stats tooltip for this item.  Am I understanding this wrong?

**Comment by TakGalaman** [comment]
Oh, I didn't see it there. I think it's more intuitive to include it on the upgrade's tooltip, but
1. This isn't important since it's not really information that's going to help me make a decision and 
2. the information is already available elsewhere (like you pointed out)

**Comment by Aktanusa** [comment]
I don't think it be more intuitive as one would actually need to go looking for the upgrade in the sea of already bought upgrades.

**Comment by TakGalaman** [comment]
In any case, this suggestion is already done so I'll close this. :)
