### ISSUE TITLE
Display an overlay of numbers on the different sections of the timers in TimerBar

### ISSUE THREAD

**Issue by TakGalaman** [Aktanusa/CookieMonster#147]
I'd love if the timers in the top left showed the time of the gray bar as well as the overall time. My motivation is you want to know whether it's worth clicking the a cookie right now or waiting 10 seconds when it might line up with another cookie/reindeer. If there's no chance that waiting will be beneficial then I'll just click it now and go back to what I was doing on my other screen - a timer on the gray bar would help me make that decision.
![image](https://user-images.githubusercontent.com/31801070/30250259-c63a7c0c-9610-11e7-9986-324e4b467c0b.png)

This is similar to suggestion #73

**Comment by Aktanusa** [comment]
I get what you mean.  Okay, I'll add it to the list of enhancements =D

**Comment by Kidsheldon** [comment]
Suggestion for the formatting of this:

Next Cookie [graygraypurplepurplepurplepurplepurple] 20/168
Next Reindeer [graygraygraygrayorangeorangeorangeorange] 57/143
Clot [redredredredredredredredredredredredredred] 137

Any bars with no gray remaining wouldn't show the number to the left of the slash.
