### ISSUE TITLE
Option to give different colour to PP of buildings that cost less than "x seconds of CPS"

### ISSUE THREAD

**Issue by TakGalaman** [Aktanusa/CookieMonster#149]
I might be alone/weird in doing this, but rational or not, one of the things I do sometimes is buy everything that is relatively cheap. Usually I aim for things with a cost of 1 or 2 seconds of production, sometimes up to 10.

Example: My production is 780 Quintillion CPS and farms cost only 52 Quintillion each. I'm going to buy farms until their cost is ~1 sextillion.

Suggestion: It would be nice to have a color applied to upgrades and buildings that are "cheap-as-free" as defined by a user-entered number of seconds of production default this null - feature is off.

**Comment by Aktanusa** [comment]
I can see where you are coming from, it's an interesting suggestion.  Keep them coming, though it may be a while before I get to them ~_~.
