### ISSUE TITLE
Add an option to sort buildings in the Bottom Bar by their PP

### ISSUE THREAD

**Issue by netwizard2** [Aktanusa/CookieMonster#151]
My current most efficient building is a Chancemaker, but I can't afford it since it puts me so far under my L+F. That's why I buy the second most efficient building, if I can't allow it, third PP building.
Being able to sort buildings by PP could be very handy in this situation. I seriously need that option.

**Comment by netwizard2** [comment]
Issue partially solved. Using Chrome's extension "Click to remove element", I delete insignificant buildings making it easier to compare desired buildings. Now I can have as little as 2-5 of these in the Bottom Bar, which is very convenient!

**Comment by Aktanusa** [comment]
Hmm, sort building by PP is interesting.  I'll think about it.

**Comment by netwizard2** [comment]
Another wonderful option would be to sort buildings to the right by their cost. Each 50 of each building unlocks blue upgrade with very economical PP value. Sorting by cost allows you to quickly find the building that won't put under F+L threshold yet still provide you with that sweet blue colored upgrade. And maybe with an achievement, which is even more beneficial.

**Comment by Aktanusa** [comment]
Honestly, rearranging buildings may be a bit hard to do (it's all DOM manipulation) but that is a complete guess.  I've not actually looked into it yet.  There might be a lot of assumptions used in the original game as the placement of the building, but again I'm guessing.  When I get time, I will look, but sorry I can't really make any promises.
