### ISSUE TITLE
Add an option to display PP in hh:mm:ss format

### ISSUE THREAD

**Issue by netwizard2** [Aktanusa/CookieMonster#152]
Early in ascension it's beneficial to invest in your buildings rather than banking up for F+L combo.
If building's PP is less than time to said combo, it's worth buying it. 8 hours till the F+L combo and building's PP is 7500? Definitely worth buying.
Can we have an option to display 2h 5m rather than 7500? It'd be much more easier to compare them this way.

**Comment by netwizard2** [comment]
I also added more suggestions to my previous topic https://github.com/Aktanusa/CookieMonster/issues/151, not sure if you get notifications on that.

**Comment by Aktanusa** [comment]
The problem with PP in another format is that while PP is indeed time as a unit, it is a bit off.  I honestly forgot the exact reason why it's not really a direct time unit, but I think it's related to how it depends highly on the CPS and how CPS can change so much from something like a frenzy.  That's not to say it can't be done, but I'm on the fence for this idea.
