### ISSUE TITLE
Warning regarding cookies required for lucky 

### ISSUE THREAD

**Issue by derda17** [Aktanusa/CookieMonster#154]
The warning regarding cookies required for "Lucky!" seems to ignore the CPS of the purchase. I postponed the purchase of "Kitten engineer" until the warning in the tooltip of the upgrade disappeared. Nevertheless, I ended far below the optimal bank balance for Lucky. I suspect the 40% CPS boost of the Kitten upgrade were not considered in the calculation.

**Comment by Aktanusa** [comment]
It's a setting in CM...

**Comment by derda17** [comment]
Oh great to hear and sorry for the inconvenience. Found it!

**Comment by Aktanusa** [comment]
Nah, it's fine, I get it all the time, lol.  Honestly, the default way is more efficient, but I can see the other way.
