### ISSUE TITLE
Add an option to change preferred PP calculation

### ISSUE THREAD

**Issue by MarissaBlackwing** [Aktanusa/CookieMonster#157]
Currently, the Payback Period is calculated based on how long it will take a given building to pay for itself.

I would like to suggest an alternative option that can be toggled in the settings - basically, I'd like to option to see the PP as how long it will take for the current Cookies Per Second to pay for the building.

**Comment by Aktanusa** [comment]
Hmm, just to be perfectly clear, what would the formula be?  At first I thought you mean BCI, the old method, which is base cost per increase income, but I don't think you mean this at all.

**Comment by MarissaBlackwing** [comment]
I'll be the first to admit that formulas and the like aren't a big part of my skillset.

What I mean is, say you have, I don't know, 1 million cookies per second, and a building costs 50mil. Barring CPS increases, it would take 50 seconds to pay for, yeah? So instead of how long it takes for a building to pay for itself, it's how long you go back to turning a profit after shelling out for a building. I get that it's kind of simple and lazy, but sometimes simple is best for some people. The prices also start to get crazy in the mid- and late-game, so it's not a terrible thing to know without taking time out to calculate the weird numbers manually.

I'd come up with something more imaginative, but again, formulas are not really my thing.

**Comment by Aktanusa** [comment]
Doesn't the timers already tell you using current CPS how long before a building is ready to buy?  Are you suggesting I change the colors to whichever has the shortest time?  I mean what you can do easily is look which has the shortest time to finish that be your answer.

**Comment by MarissaBlackwing** [comment]
No, that tells you how long until your total cookies owned will be enough at the current cookies per second to pay the cost of the building.

I'm talking about how long until your current CPS will pay back the cost of a building, regardless of whether or not you can afford the building from your total. Once you've been buying several of a building, the cost is often much, much higher than your CPS, so it takes a bit before you're profiting again rather than just getting back to your previous total.

**Comment by DanielNoord** [comment]
I don't see a real benefit to adding this, other than providing extra information to the user.
However, I believe this information is fairly irrelevant (as it does not interact with the efficiency of a user's strategy) and is easy to compute by the user themself. Therefore, I value not cluttering the interfaces over adding this feature.
If somebody would really want us to add this, please go ahead and open an issue so we can discuss this further. For now I am closing this.
