### ISSUE TITLE
Negative PP is back (cc beta)

### ISSUE THREAD

**Issue by Sekhy2** [Aktanusa/CookieMonster#160]
With the new beta (2.0044), buildings show negative payback period.

I've bought all new upgrades and heavenly upgrades (missing a few christmas cookies), and I'm during Christmas season, if it helps. Strangely, everything was fine yesterday when I started testing this beta with cookie monster. Maybe buying things then reloading?

![cm_bug](https://user-images.githubusercontent.com/30840346/36630048-fff16758-195f-11e8-8ad3-327af78625ec.png)

I'm using firefox 58.0.2 on Linux Mint.

**Comment by Aktanusa** [comment]
Well, just found out there is a new version.  Give me time to update =D.

**Comment by Sekhy2** [comment]
It works now with the new update (as well as the live version). Thanks a lot ;)

**Comment by Aktanusa** [comment]
Well, I still need to backport it to beta, but it's not as important now., lol.  I'll leave this open until I backported

**Comment by Aktanusa** [comment]
Well since there is a new beta, this is obsolete, lol.
