### ISSUE TITLE
can cookiemonster tell us how many seasonal eggs we still need?

### ISSUE THREAD

**Issue by selaj** [Aktanusa/CookieMonster#165]
The easter egg upgrades and the xmas/valentine/halloween cookies. I would like to see a feature that tells us how many we have and how many we still need. 

For example it could say "You have 6/19 eggs" (or however many eggs there are)

It would save time going into stats and counting how many of each we have to see when we have the full set of each.

**Comment by Aktanusa** [comment]
It's already there in stats.  Take a closer look.
