### ISSUE TITLE
Legacy (first prestige upgrade) is very difficult to click due to bug

### ISSUE THREAD

**Issue by thonkang** [Aktanusa/CookieMonster#167]
I just ascended for the first time and the very first prestige upgrade is glitched out when cookie monster is loaded. Normally when you hover over a prestige upgrade the mouse changes to a clicking hand so you can click and buy it, but for some reason the legacy one changes to the normal mouse, making it unclickable. I did manage to click it while I was moving the mouse because for a split second it would actually let me click it. This isn't a problem with the other prestige upgrades. The same thing happens when you hover over it in the stats page, not just the ascention upgrade tree. The problem went away when I disabled cookie monster, and it doesn't happen with frozen cookies either.

**Comment by Aktanusa** [comment]
That's an interesting bug as I don't do much in the ascension screen.  What browser are you on?

**Comment by thonkang** [comment]
Sorry I forgot about this.
It was happening in firefox on gentoo linux, but I switched to arch linux so it doesn't happen anymore.

**Comment by Aktanusa** [comment]
Ah okay, still interesting bug.
