### ISSUE TITLE
Optional warning for spontaneous edifice to building/upgrade tooltip

### ISSUE THREAD

**Issue by Sekhy2** [Aktanusa/CookieMonster#168]
It would be nice to have a possible buying warning "if you buy this, you might not be able to cast spontaneous edifice".
You just need to check if the total amount of cookies is half the price of the most expensive building (assuming you don't have 400 or more of those, and it's not your most-built one. You can simplify this, because it's almost always about chancemakers).

Quite easy, but that would be cool. :)

(excellent job, by the way :+1: )

**Comment by Aktanusa** [comment]
Hmm interesting idea.  Not sure if I will add yet.
