### ISSUE TITLE
Add Heavenly Chips / seconds to the stats page

### ISSUE THREAD

**Issue by iasinme** [Aktanusa/CookieMonster#169]
Is it possible to add a Heavenly Chips per second stat?  Some of us are making HC so quickly that we get multiple every second.  Honestly, I just want to see how many HC I get every second on average.

**Comment by Aktanusa** [comment]
Sure.  Shouldn't be too hard to do.

**Comment by ingesiit** [comment]
Bump -- me too I'd like this feature
Kind regards, and thank you!

**Comment by ingesiit** [comment]
I wouldn't want to be too insistent .. but this feature may be veru interesting, so I'm bumping up this thread
Kind regards

**Comment by Aktanusa** [comment]
Yeah, I need to get around to adding more stuff.  Please be patient with me.

**Comment by ingesiit** [comment]
It doesn't work .. It always says 0 HC/sec, while I'm getting about 300.000 HC/s
If you need some debug info or a dump please let me know what you need
Regards
Alessandro

**Comment by DanielNoord** [comment]
Could you paste in your save file?

**Comment by ingesiit** [comment]
yes, it's here
[BorcsBakery.txt](https://github.com/Aktanusa/CookieMonster/files/6076287/BorcsBakery.txt)
Running Cookie Clicker on Chrome 87.0.4280.88 on Linux 
Thank you

**Comment by DanielNoord** [comment]
This is indeed a bug, I opened an issue to track it.
Thanks for reporting it!
