### ISSUE TITLE
CookieMonster doesn't accomodate customCPS and customCPSMult

### ISSUE THREAD

**Issue by DJKorchinski** [Aktanusa/CookieMonster#170]
The CM.Sim.cookiesPs doesn't take into account Game.customCPS and Game.customCPSMult (see lines 3361 and 3462 respectively in main.js for version 2.0045). 

What this means in practice, is that if new kitten upgrades are added by a mod (and implemented by modifying Game.customCPSMult) cookie monster incorrectly assessing the kitten upgrades as not having any effect.

**Comment by Aktanusa** [comment]
That's correct as I have not seen a mod that uses it yet.  I mean I guess I can put it back in.  Do you have a mod that does change the CPS?

**Comment by LiquidInsight** [comment]
I was on the wrong account when I posted this, but yes, I'm [developing such a mod](https://github.com/LiquidInsight/CookieBliss/blob/master/CookieBliss.js). My mod loads yours after I've finished adding new upgrades and modifying the base game, which largely seems to work, but for this.

**Comment by Aktanusa** [comment]
Ah, I see.  Okay, I'll add them back.

**Comment by LiquidInsight** [comment]
Thanks for the advice -- I've gone ahead and made a gh-page. Seems to be working!

If it's not terribly rude, I am going to try and fork CookieMonster to make the change suggested above, and make a pull request. I'm a bit of a GitHub newbie, so I think it might be good practice.

**Comment by Aktanusa** [comment]
That's fine.  Just expect a bit of time before I merge the pull request =p.  Also put it to dev branch.  Everything goes there first.

**Comment by LiquidInsight** [comment]
OK I've added support for the customCps multiplier for mods, have tested it against my mod, and have put in a pull request to the dev branch! Let me know if there's any problems, or you have any questions. The changes weren't very big, but I did try to include some comments to explain my thought process.

**Comment by Aktanusa** [comment]
Hmm, I took a quick look.  Indeed the mod functions may use other functions which is not part of the simulated model, as noted in your comments but you only accounted for the ones your mod uses.  This is a hard solution as it's not a general solution.  It works for your mod since you know you'll be using those, but this may not work for future mods.  I don't have an answer as any mod can do anything (maybe).  I would need to look hard into this.
