### ISSUE TITLE
Pop all wrinklers option which excludes shiny wrinklers

### ISSUE THREAD

**Issue by Au-Matt** [Aktanusa/CookieMonster#171]
I like popping wrinklers, but I don't like popping shiny wrinklers. 👍

**Comment by Aktanusa** [comment]
Yea I know.  I prob should have added this in the last release since it is very simple.

**Comment by Au-Matt** [comment]
Oh man. Sorry. Is there a way I can delete it?

**Comment by Aktanusa** [comment]
Nah, it's fine, I'll just close both when it's added.  It happens.

**Comment by Aktanusa** [comment]
Added to Version 2.0106.1
