### ISSUE TITLE
New beta (2.0055), negative PP back

### ISSUE THREAD

**Issue by Sekhy2** [Aktanusa/CookieMonster#173]
All is in the title! A new beta is running (new upgrades, new minigame, other things), and negative payback period is back.

Good luck fixing this! :)

**Comment by Aktanusa** [comment]
Aw man, more work =p.

**Comment by ahiddenwaffle** [comment]
I was literally just looking if there was a nightly build or something available to fix this! I've noticed the -PP only started happenning to me when i started using the Garden minigame, if that is any help.

**Comment by Aktanusa** [comment]
Sure, that helps, but usually I need to diff to see the changes.  Sorry, I'm not that quick to update.  It's not like I get to see the beta before anyone else, lol.

**Comment by Sekhy2** [comment]
It's ok. Take the time you need. We will make it :P. You're doing an amazing job, by the way. \o/

**Comment by Aktanusa** [comment]
Honestly, since beta changes so fast, I usually wait to see if it stays like a week before bothering to update it.  Since I don't want to update it to have it break the next day, lol.

**Comment by Aktanusa** [comment]
Well it has been a week and I don't think the beta has been updated much (correct me if I'm wrong), so I'll work on this soon.

**Comment by Aktanusa** [comment]
I put this on low priority since live is newer than beta and I've already fixed live.  Yes I know it's garden since it's in live.  I just need to backport sometime.  Did you know live is newer @itsjop?

**Comment by itsjop** [comment]
I did not! Hadn't seen an update in this thread so didn't know if it'd been addressed yet. Thanks again!

**Comment by Aktanusa** [comment]
Closing this as there is a newer beta and 2 new Issues on this (#223, #225).
