### ISSUE TITLE
issue not loading in chrome

### ISSUE THREAD

**Issue by metroid2002** [Aktanusa/CookieMonster#174]
![screenshot 436](https://user-images.githubusercontent.com/38188514/38470326-010156a8-3b2f-11e8-9ed8-39e08dd5a75c.png) 
i try'd using a number of different versions and none of them worked on chrome but they did work on firefox currently im using frozen cookies and it works on chrome

**Comment by metroid2002** [comment]
i just opan'd a new tap and the same thing happened, does cookie master stay installed after getting a new tap?

**Comment by Aktanusa** [comment]
Well I would need to see the error when Cookie Master was never loaded.  All I know is that the error you screenshot shows Cookie Master is conflicting.

**Comment by metroid2002** [comment]
![screenshot 440](https://user-images.githubusercontent.com/38188514/38644826-ed097cba-3daf-11e8-8e06-edf3ef797bb7.png)

**Comment by Aktanusa** [comment]
Cookie Master is still there (says ...okiemaster.min).  I think it's a Chrome extension.  You should remove that extension.

**Comment by metroid2002** [comment]
works great now, thanks :)

**Comment by Aktanusa** [comment]
Great!  Glad it works!  Closing this.
