### ISSUE TITLE
Computation of Ascension Levels Doesn't Work with Spontaneous Edifice

### ISSUE THREAD

**Issue by sugarfrosted** [Aktanusa/CookieMonster#175]
The number of levels granted doesn't take into account if buildings being sold would increase "Cookies in bank" to over "Cookies Baked (this ascension)", which would thus increase "Cookies Baked" to what "Cookies in Bank" would be.

**Comment by Aktanusa** [comment]
Hmm, if I understand you correctly, do you mean that buildings you got for free with Spontaneous Edifice does add to the total cookies Baked on selling, and because of that,the reset bonus stat is incorrect due to some achievements that can be gotten from the extra total cookies baked?

**Comment by sugarfrosted** [comment]
It can add to the total cookies baked and this does throw off the computation. This seems to be because the way it seems to work is as follows: Letting `total` be the "total number of cookies baked (this ascension)" and `bank` be the total cookies in your bank it does the following:
```
if total < bank:
    total = bank
```
So, if you sell everything and this exceeds your total cookies baked it exceeds it. I was thinking just letting `CE` being the maximum computed amount of cookies from the chocolate egg, and letting `Current` be the current computation, taking `max(Current,CE*21)` or `max(Current,CE*20)` to be used in computing chips should work.

**Comment by Aktanusa** [comment]
I would need to look more into this as right now I'm still not getting you.  Probably my reading comprehension is failing me right now, lol.  I'll reread it a few and get back.

**Comment by Aktanusa** [comment]
Okay, now that I have carefully reread it, I understand.  That does sound like a bug.  I need to find in CC code where this is happening.

**Comment by Aktanusa** [comment]
Found the line:

``Game.cookiesEarned=Math.max(Game.cookies,Game.cookiesEarned);```

**Comment by Aktanusa** [comment]
Fixed in Version 2.0106.2
