### ISSUE TITLE
Getting an error when I try to load this mod

### ISSUE THREAD

**Issue by MilosPH** [Aktanusa/CookieMonster#176]
ReferenceError: you is not defined
![image](https://user-images.githubusercontent.com/38293139/38629889-488d9f26-3d83-11e8-9455-e5eb18f52cf8.png)

**Comment by Aktanusa** [comment]
Need more info, like what browser, what line did you use, how did you enter the line... etc.

**Comment by MilosPH** [comment]
When I use the bookmarklet nothing appears to happen (though it does give me a warning now since the update about it being for an older version). When I check the console I have that error. This happens in Chrome, Firefox, and Edge. Used to work ok and stopped working seemingly randomly. Have tried the browsers mentioned and recreating the bookmark with the same result each time.
![image](https://user-images.githubusercontent.com/38293139/39097683-9cbf3584-462d-11e8-80d1-08d26e205da4.png)

**Comment by master2080** [comment]
What..is that code? It looks like a chunk of the entire thing.
This is the bookmarklet:
```
javascript: (function () {
	Game.LoadMod('https://aktanusa.github.io/CookieMonster/CookieMonster.js');
}());
```

**Comment by Aktanusa** [comment]
I still need to know exactly what you put in the bookmark.  It is interesting that 3 different browsers doesn't work as it be highly unlikely the same addon is on all three browsers, but just to make sure, list also all the addons installed on all three browser.  Both screenshots you have provided does not really help at all.

**Comment by DanielNoord** [comment]
I have looked at the code and can not reproduce this error, nor does it seem likely to occur.
The code snippet provided is from the `CM.Sim.InitData`, which is the first proper 'data-function' to be called.
I can not see a reason for it to fail, other than the mod not being loaded correctly by the user.
