### ISSUE TITLE
Not working correctly with new Cookie Clicker version [v2.0102+]

### ISSUE THREAD

**Issue by taholten** [Aktanusa/CookieMonster#179]
A new version of Cookie Clicker was launched today. 

Some purchases shows negative 'Bonus Income', and thus not showing the actual best purchase to do.

**Comment by Aktanusa** [comment]
Welp, now I can't make the excuse Beta is being updated fast, lol.  I'll work on this hopefully soon.

**Comment by taholten** [comment]
Changed the title to match the current version displayed in Cookie Clicker. I can also note that I no longer see any negative 'Bonus Income' for a purchase. WIll look out for it, thou. But hopefully less work for you to do :)

**Comment by danhd123** [comment]
The bonus income calculations are all wrong for me in 2.0102 with current version, all way larger than reality. Also, for each plant in the garden mini game, the tooltip flickers constantly and the plants are consequently nearly unclickable.

**Comment by Aktanusa** [comment]
That is a pretty big bug on the tooltip @danhd123.  Dang it, he changed tooltip again?!  Those are always a pain to fix...

**Comment by Aktanusa** [comment]
That's normally what he does.  I don't think he forgets...

**Comment by MrSapient** [comment]
Thanks for this awesome tool and here's to hoping its updated soon!

**Comment by EMBaudert** [comment]
Hint: When you freeze your garden, everything should be working correctly

**Comment by Aktanusa** [comment]
Actually, even when you freeze it, it's a little bit off.  Not as much, but still off.

**Comment by yuffstah** [comment]
Not sure if this is related, but i just purchased the "Kitten assistants to the regional manager" upgrade (the one for 1 udec) and every other upgrades and buildings now show around +10% cps than before, even the seasonal switches.
Anyway, keep up the good work Aktanusa. Love this add-on.

**Comment by Aktanusa** [comment]
Yep, it's one of the other minor changes.  Thanks for the compliment.

**Comment by Aktanusa** [comment]
Well, hopefully I found all the changes, let me know if it is still negative even if frozen.  Thanks for the kind words.

Fixed in Version 2.0106.1.
