### ISSUE TITLE
Garden improvements

### ISSUE THREAD

**Issue by normann1974** [Aktanusa/CookieMonster#180]
Could CM play a sound on every garden tick? Could CM implement setting alarms that go off after a certain number of garden ticks? This would make garden work a lot easier. :-)

**Comment by Aktanusa** [comment]
Yep, I had the same idea =).

**Comment by Aktanusa** [comment]
The sound every garden tick has been added to Version 2.016.2.  As for an alarm every x garden ticks, I'm not sure I'll add that in.  Do you really think it be helpful?

**Comment by mooop12** [comment]
It took me a whole day to figure out what was making this sound, please make it default to no sound...

**Comment by normann1974** [comment]
How about a compromise that only plays the tick sound when the garden is active (i.e. that there's something growing/planted). So there will be no ticks until you actually plant something for the first time.

**Comment by Aktanusa** [comment]
Hmm, interesting idea.  It won't ping when a mold shows up, but it will ping the tick after... lol.

**Comment by mooop12** [comment]
No offense, but if no one will know about the feature that means no one looked for that feature, and that means that feature may not have been necessary at all.

Enabling the sound only after planting in the garden still doesn't solve the issue, I was using the garden when I heard the ticks but I still didn't know what they were.

**Comment by Aktanusa** [comment]
None taken, but did you know I get features requested here, when it was already in the addon, just because it was turned off by default?

**Comment by mooop12** [comment]
That is a bummer. Hmm maybe you could put the sound toggle right on the farm ui itself? Would that be possible?

**Comment by Aktanusa** [comment]
That's possible, though not and easy fix.  I do have some thoughts.

1.  I could change the default sound to something else that may make it more obvious that it's for garden tick.
2.  I add a notification at the bottom that auto goes away so at least people know what happened if they looked at the notification.  I would do this for all current sound things and make it an option (golden cookies, reindeer, garden tick, fortune ticker).
