### ISSUE TITLE
Wrong calculations in v2.0106?

### ISSUE THREAD

**Issue by normann1974** [Aktanusa/CookieMonster#181]
Using the dev version of CM, at this point in the game, all my buildings have negative bonus income and negative payback period. That can't be right, right?

![billede](https://user-images.githubusercontent.com/598564/39116142-ece5daa2-46e3-11e8-8f65-f37826a97879.png)

Save:

Mi4wMTA2fHwxNTI0MjQ1ODM3OTE4OzEzODE5NTM2MDAwMDA7MTUyNDQ3MzQwNzMzNjtKYW47YnR4eWp8MDExMTAwMTAwMTAwMDAxMDB8Ny43NDkxMzIxODYwMzc3OTVlKzM5OzMuMDg2MTMzMzQwNzQ2NzEzZSs0MDs5MjU7MzE1MDM7Mi42ODgwMDcxMjY1MDU0OTI3ZSszODszODI2ODI7MDswOzcuODg5MjQ2Mzc3NTQ1NzU4ZSs0MDszOzA7MDswOy0xOzExNjs5OzIuMDAzMzkyNDgxMzM1MjM3NGUrMzk7NzA5OzE0OzEzMDszODEwODE7OTtjaHJpc3RtYXM7MS4xNjQ4NzUzODg4NDk2MzUzZSszODsxMjs0Mjg4ODkyNjE5OzE1NzkzODMyODY7MjcwOTUwOTMzMzswOzA7NDQyOzQ3Nzs0NzY7ODc7NDYyOzIyOzE1OzE7MTswOzA7MDs5MzszMDU7MTUyNDQzMjEwNjQ5NTswOzA7fDYwNiw5NTYsMi4zNzUzOTE5NDk0Mjk1MzA2ZSszNiwwOzU5OCw5NDgsMS45MzI3OTMwNjQ0NTE1OTZlKzM1LDA7NTc1LDkyNSw1LjU4MjAzMjEyNjEyODMyNWUrMzUsNywxNTI0NDMxOTEwOTM0OjE6MTUyNDMxMjc1OTI3NzoxOjU5OjE4MjoxOjA6IDExMDAwMDAwMDExMTExMDAwMDAwMDAwMTAxMDAxMDAwMDAgMDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjE6ODoyOjM3OjA6MDo0OjIyOjA6MDowOjA6MDowOjE6ODowOjA6Mzo2ODo0OjI3OjA6MDowOjA6MDowOjI6NDA6MDowOjA6MDowOjA6MTo4OjA6MDowOjA6Mjo0MDoxOjg6MDowOjA6MDoxOjk6MDowOjE6ODowOjA6OzU1OSw5MDksMy42Mjk5NDUyNTUyMTQ1Mzc2ZSszNywxOzU0MSw4OTEsNi40ODA1NjY5NDI4OTU5OTVlKzM2LDA7NTI0LDg3NCwxLjY2MDc0NTYzMzU4ODIxN2UrMzYsMzs1MDYsODU2LDYuODEwOTA0MjYwMjM2OTY1ZSszNiwyLDgvMC83IDMgMTUyNDMyOTUxNzY3OCAxOzQ4NCw4MzQsMi44MTM3Mzc1MDc1OTEwNDVlKzM2LDEwLDg3LjU5MzcyMjA3MjUwNzY5IDQ2IDI1NjMgMTs0NjQsODE0LDkuNjI2MDIyODg0NTUxNDg0ZSszNSwxOzQ0OCw3OTgsNC45MzEwNzQ2MjAwMTI4NjY2ZSszNiwxOzQyOCw3NzgsMi43NDk3OTcyMTkwNDgzOTM0ZSszNywxOzQxMCw3NjAsMS42MjM2MDYwNTU4ODMwNzhlKzM4LDE7NDAzLDc1MywxLjQwMzc5MDc2NzI3MjQ2NThlKzM5LDE7Mzc5LDcyOSw0LjM2NzcyNTcwNjk4OTUyMmUrMzgsMTA7Mzc2LDcyOCwxLjQ1MjcwMDY4NjQ3MjA4NTJlKzM5LDEwO3wxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTAwMTExMTExMDAwMDAwMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDEwMTAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMTExMTAwMDB8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAxMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMDAwMDExMTEwMDAwMDExMTAwMDAxMTAwMDAwMDAxMDB8%21END%21

**Comment by Aktanusa** [comment]
Fixed in Version 2.0106.1
