### ISSUE TITLE
Add cookies gained from harvesting plant to plant tooltip

### ISSUE THREAD

**Issue by AnnaSaysHi** [Aktanusa/CookieMonster#183]
How about telling the player how many cookies they'll get from crumbspore/doughshroom/(white) chocoroot/bakeberry/queenbeet/duketater, and how many banked they need to max out the rewards from those in regular frenzy, elder frenzy, and stacked frenzies.

**Comment by BoltonBailey** [comment]
This would be nice for Conjure Baked Goods as well.
