### ISSUE TITLE
Bulk-buy 50 buildings

### ISSUE THREAD

**Issue by Treazer** [Aktanusa/CookieMonster#184]
For me it would be quite useful to bulk-buy 50 buildings at once (in addition to the current options of 1, 10, 100 and max) and therefore to see if I would be able to afford 50 buildings at once. This feature comes in handy when I want to get the remaining "have X amount of building Y" achievements, considering that they come in steps of 50 units.

**Comment by Aktanusa** [comment]
I think this is a dup... too lazy to look right now, lol.
