### ISSUE TITLE
Add info on changing dragon aura in tooltip

### ISSUE THREAD

**Issue by joatmon3** [Aktanusa/CookieMonster#185]
It would be great to have some info presented when choosing an aura, like how much benefit it will provide, effect on CpS, time to recover spent building, or whatever else you think might be useful. Not all auras will have all of this type of info for them.

**Comment by Aktanusa** [comment]
Hmm, good idea, though not sure how hard to implement.

**Comment by DanielNoord** [comment]
I believe #251 does this, but I need to look at the PR

**Comment by DanielNoord** [comment]
<img width="534" alt="Schermafbeelding 2020-11-28 om 17 50 27" src="https://user-images.githubusercontent.com/13665637/100521212-7e65dd00-31a2-11eb-947a-7099c0f148c9.png">

I think an implementation like the picture would be best.
I have started with an implementation but this will take some additional work and will likely not feature in the next update.
