### ISSUE TITLE
Wrinklers and Heavnely Chips

### ISSUE THREAD

**Issue by TreyBTW** [Aktanusa/CookieMonster#186]
In the wrinklers “goodies” section under “rewards of popping” I think it would be amazing to have a section that is like “heavenly chips from popping” or something similar

**Comment by Aktanusa** [comment]
Maybe I'm missing something, but how will this info be useful?  I mean it probably isn't too hard to implement, but right now I don't see how it is a useful stat.

**Comment by DanielNoord** [comment]
We already show this in the stats page under "Heavenly Chips (CUR/MAX)"
