### ISSUE TITLE
Add warning to planting tooltips

### ISSUE THREAD

**Issue by Tntmister** [Aktanusa/CookieMonster#188]
It would be useful if there was a warning on planting seeds that it would put us under the number of cookies required for lucky/lucky (frenzy), just like it shows in buildings.

**Comment by Aktanusa** [comment]
I think this is like Issue #183

**Comment by BoltonBailey** [comment]
Actually, this is different from #183. #183 asks for a tooltip that tells the player how many cookies they will get from harvesting plants.

**Comment by Aktanusa** [comment]
oh, oops, thanks for pointing that out!

**Comment by DanielNoord** [comment]
This should be fairly easy to do. Just change the code on tooltips for planting to also consider all warnings as is done for the building/upgrade tooltips.
