### ISSUE TITLE
Show type of sugar lump that is growing

### ISSUE THREAD

**Issue by Barthon** [Aktanusa/CookieMonster#190]
Suggestion: As the type of the sugar lump is determined the moment the old one is harvested - but one has to wait for another 12 hours until one can see the type of the growing sugar lump (Normal, Bifructated, Meaty or Golden) - it might be great if one can see (by hovering over the lump for example?) what kind of sugar lump actually will be growing after the old one is harvested. This might be really useful for farming golden sugar lumps and other kinds. I think this might fit the theme of the add-on really well as it shows more than it actually cheats. (Great add-on btw)

**Comment by Aktanusa** [comment]
Thanks for the compliment.

**Comment by BONNe** [comment]
By hovering over the lump, before it is harvested, it only can show the chances for each sugar lump, as which one will be growing is determined by pure random. However, showing which one is growing before stage 5/6 I think is possible and useful.

**Comment by DanielNoord** [comment]
This has been added now!
