### ISSUE TITLE
Add info on rewards of popping only all normal wrinklers to stats page

### ISSUE THREAD

**Issue by troggnostupidhs** [Aktanusa/CookieMonster#196]
Currently 'Rewards of Popping' shows the number of cookies for popping all wrinklers. But, the button only pops normal wrinklers. It would be helpful to see the rewards of popping only normal wrinklers.

**Comment by Aktanusa** [comment]
yea that occur to me too, but to me, only if you are the lucky few to ever get a golden wrinkler would this be a problem, lol.

**Comment by DanielNoord** [comment]
This can be added in the same row, but is indeed a nice add-on
