### ISSUE TITLE
[Feature Request] Update Average CpS units

### ISSUE THREAD

**Issue by EricLarsenMN** [Aktanusa/CookieMonster#198]
Currently there are options to display Average CpS for past 1m, 5m, 10m, 15m, and 30m.  Please add an option for 30s and 10s, or other smaller units of your choice.

Reason for request:
Smaller units allow the user to see the difference that their big cookie clicking is making between the base CpS and what they are making overall.  I find this especially useful when attempting Speed Baking.

**Comment by Aktanusa** [comment]
Finally started to look at this, and with the way I set it up before, this isn't as easy as I once thought =(

**Comment by Aktanusa** [comment]
Added in Version 2.0106.2
