### ISSUE TITLE
[Feature Request] Setting for automatically buying buildings and upgrades

### ISSUE THREAD

**Issue by GHXX** [Aktanusa/CookieMonster#199]
Right now CookieMonster shows you what building or upgrade generates the most money relative to what it costs. Would it be possible to have a setting that tells CookieMonster to automatically buy the best building or upgrade?
It would be good to be able to ignore the research-upgrades and upgrades that take too long to unlock (im thinking about 2h+ or something along those lines), because the kitten upgrades can get quite expensive.
This would allow for complete idling 😄 
What do you think?

**Comment by Aktanusa** [comment]
Hmm, I'm not keen on the idea of automation.  It's like letting the addon play the game for you.  This may not happen at all or very low priority, sorry.  I'll consider it.

**Comment by GHXX** [comment]
I agree, it does automate most of the game, but this way you could just watch the game progress which could be pretty interesting.
I respect your decision though if you decide not to add it.

**Comment by jabenninghoff** [comment]
Frozen Cookies can autobuy. https://github.com/Chevron42/FrozenCookies

**Comment by GHXX** [comment]
Thank you for the link, but interestingly it doesn't work very well. In my current game it waits 16h for an upgrade that doesnt exist anymore because it was bought already. It also waits way longer for buying something than it has to wait - if it decides to buy anything at all. The stats also dont seem to update which is pretty wierd.
