### ISSUE TITLE
beta : cursor sometimes flicker between hand and pointer, cannot select seed for garden nor uproot plants

### ISSUE THREAD

**Issue by SThor** [Aktanusa/CookieMonster#202]
I'm using Firefox 60.0.2, and Cookie Clicker is in version v. 2.0066 beta, and Cookie Monster beta.

Some seeds *can* be selected, but it seems to change at random some times. It looks like the animation interfers with the hoverable zone, or that there is some sort of refresh too early.

I don't have this problemn when Cookie Monster is not loaded.

**Comment by Aktanusa** [comment]
This is fixed in live.  Is there a reason why you are using the older beta than live?

**Comment by SThor** [comment]
Oh alright. And no, I just thought that I was on the latest version. Thanks for the answer !

**Comment by Aktanusa** [comment]
No problem!  You do have a point, I need to back commit the live changes to beta so that it works with current beta, but it's low on my priority list.  Up to you if you want to reopen this.
