### ISSUE TITLE
Suggestion: Ability to exclude building type from PP ranking

### ISSUE THREAD

**Issue by hau5music** [Aktanusa/CookieMonster#203]
Could be helpful to be able to exclude a certain type of building from PP ranking. For example, though a farm may have the shortest PP, I may not necessarily want to buy another farm and would rather see a ranking based on building types allowed.

**Comment by Aktanusa** [comment]
I think this is a duplicate of another issue.

**Comment by hau5music** [comment]
Looks like it is, an 11/29/2017 thread.

**Comment by Aktanusa** [comment]
You didn't need to close it, I would just marked it as dup, oh well.
