### ISSUE TITLE
Option to show missing plant drops in stats menu

### ISSUE THREAD

**Issue by Aktanusa** [Aktanusa/CookieMonster#206]
Like missing season drops, add one for garden plant drops.  Unfortunately this requires a reorder of the stats menu, I think.

**Comment by BONNe** [comment]
It is added in Poll Request 192 (https://github.com/Aktanusa/CookieMonster/pull/192)

**Comment by ingesiit** [comment]
Sorry, just a question: do this feature was already added in the current version of CM? I can't find it (I'm talking about the list of missing Garden Cookies)
Kind regards

**Comment by Aktanusa** [comment]
It has not, since I've been slacking with pull requests.  Sorry =(.
