### ISSUE TITLE
2.0109: Kitten Analysts bonus income not calculated properly

### ISSUE THREAD

**Issue by danhd123** [Aktanusa/CookieMonster#208]
The bonus income (and thus payback period) for Kitten Analysts apparently randomly fluctuates between 0 and a small and incorrect number, similar to how the season switches do when there are buffs active, but in the case of Kitten Analysts, it's apparently at random, with some, but not 100% correlation with golden cookie and golden cookie effect state. 

Additionally, the season switches seem to get and lose bonus income values more frequently than in previous versions.

**Comment by Aktanusa** [comment]
Fixed in Version 2.0109.1.  Let me know if it's not the case.
