### ISSUE TITLE
Add more Lucky Cookies stats, garden harvest stats

### ISSUE THREAD

**Issue by danhd123** [Aktanusa/CookieMonster#210]
Feature Request

It would be useful to be able to see in the Stats panel how many cookies would be needed to get the full value of a Lucky Cookie, not just based on Frenzy, but also based on building specials, Elder Frenzy, and building specials + Frenzy. 

Similarly, it'd be cool if we had similar stats for mature Bakeberry, Chocoroot, White Chocoroot, Queenbeet, and Duketater harvesting, and for Crumbspore and Doughshroom explosions.

**Comment by Aktanusa** [comment]
Yea, this has been requested a few times.  Problem is, it's a big revamp, which is why I've been putting it off ~_~.  Sorry, might be a bit...

**Comment by dlauritzen** [comment]
Just want it on the record to include the warnings for when buying a seed will drop you below the Lucky/Frenzy thresholds. I keep accidentally doing that.

As you were :)

**Comment by DanielNoord** [comment]
Duplicate of #105
