### ISSUE TITLE
Selling price of buildings are miscalculated since the nerf

### ISSUE THREAD

**Issue by dashat** [Aktanusa/CookieMonster#212]
Prices for selling buildings still uses the old values of 50% of the price (and 85% with Earth Shatterer). 
Cookie Clicker version 2.0109 changed the sell price of a building to 25% of the current price (and 50% with Earth Shatterer).

Noticed it when I ascended with less prestige than expected after popping wrinklers with Skruuia in diamond, selling all buildings (with the aura) and buying Chocolate Egg.

**Comment by Aktanusa** [comment]
I thought I changed this since I knew about it.  Are you sure?  I'll check the code also, but I'm pretty sure I changed this.

**Comment by dashat** [comment]
My mistake, I just noticed a discrepancy when I ascended and checked the code quickly. I saw the old code with 0.5 and 0.85, but missed that it had been replaced and commented out. 

There still seems to be something wrong with the calculation though, or I'm missing something. Just tested by ascending again and checked the prestige level numbers before and after. Prestige level before ascending was ~17.429 billions and the estimated MAX was ~19.921 billions before doing the wrinklers, selling buildings and buying the egg. After ascending I only had ~19.868 billions prestige levels.

I'm using the version at https://aktanusa.github.io/CookieMonster/CookieMonster.js, which I assume is the most recent release.

**Comment by Aktanusa** [comment]
Do you have Pantheon?  It also assumes you put Skruuia in diamond slot (as said by the tooltip).  I just made that mistake my last ascension and also when tested today, lol.

**Comment by dashat** [comment]
I'm fairly certain I did have Skruuia in the diamond slot. However I could've missed it... Just tested once again and making sure to do it correctly, and this time the numbers were accurate.

**Comment by Aktanusa** [comment]
Okay, I guess reopen if you see it again.
