### ISSUE TITLE
Wrinkler hitboxes too high

### ISSUE THREAD

**Issue by KaosDragon** [Aktanusa/CookieMonster#213]
Lately I've been accidentally popping the bottom few wrinklers during cookie storms. It seems all the wrinklers get their hit boxes moved up a bit when CM loads.

**Comment by Aktanusa** [comment]
Since I don't change any of that, I don't think it's Cookie Monster.  Try without Cookie Monster?

**Comment by KaosDragon** [comment]
Without CM: https://i.gyazo.com/94ebe72d25ff670cf90980fcb37fe475.mp4
With CM: https://i.gyazo.com/194ae0a11557fa22dd4998845142a500.mp4

I think it might be because of the Timer Bar pushing down everything in that section. It doesn't happen with it disabled on or on the bottom.

**Comment by Aktanusa** [comment]
Hmm, now that does sound like a bug.  Thanks for adding the info with the timer bar.  As you noticed, it is probably the cause, now I have a good lead =D.

**Comment by Aktanusa** [comment]
Fixed in Version 2.012.2.  Let me know if you run into more problems.
