### ISSUE TITLE
Sound indicator for when mana is at max

### ISSUE THREAD

**Issue by Tyler799** [Aktanusa/CookieMonster#214]
Mana regenerates the quickest when you skim from the top (it regenerates faster the more full it is).

An indicator (a sound, similar to how golden cookies work) to let the player know when mana is maxed out might be helpful as an option.

**Comment by Aktanusa** [comment]
Yep, in the works.  Yep, I'm being slow, sorry D:

**Comment by DanielNoord** [comment]
Added with #336
