### ISSUE TITLE
"Better than best PP building" number is green instead of blue

### ISSUE THREAD

**Issue by tonyravioli** [Aktanusa/CookieMonster#218]
I'm on MacOS 10.13.6, running Chrome 69.0.3497.81, though this was happening in the previous version of Chrome as well.

In the upgrade bar above the upgrades, the far left number should be blue, but is set to display as green. I only noticed this when I watched my girlfriend play on a Windows 7 machine and noticed that her number was blue there.

I inspected it on my computer and found that the .CMTextBlue class has text color set to green (#00FF00) instead of blue. Here is a screenshot to better illustrate what I'm saying: https://i.imgur.com/VBJdxRo.png

I'm sorry if I'm missing something obvious.

**Comment by tonyravioli** [comment]
FWIW, this is happening with the dev build as well.

**Comment by jshepler** [comment]
Just to rule it out, did you verify the color set in options is #4bb8f0?

**Comment by Aktanusa** [comment]
Wow, Github notifications must be screwing up since I didn't even know about this.  My bad!  I would check what @jshepler mentioned first.

**Comment by tonyravioli** [comment]
Wow, yup, that's it. Not sure how I did that on accident, but @jshepler is right on the money - I had it set to green. Sorry to bug you guys!
