### ISSUE TITLE
Beta isn't working anymore

### ISSUE THREAD

**Issue by EJlol** [Aktanusa/CookieMonster#223]
As soon as you hover over the upgrades, the game freezes.

**Comment by Aktanusa** [comment]
I don't work on beta until it's more stable.  I would not like to changes things just to find out all my changes went invalid because beta got updated again.  This is why I wait.

**Comment by Anahkiasen** [comment]
You should maybe remove the beta userscript from the README for the moment, so less people open issues about it

**Comment by Aktanusa** [comment]
Nah, I plan to update the beta today or tomorrow.

**Comment by Aktanusa** [comment]
Fixed in Version 2.016.1
