### ISSUE TITLE
Broken on v2.016

### ISSUE THREAD

**Issue by randomdude999** [Aktanusa/CookieMonster#224]
The add-on doesn't load in Cookie Clicker v2.016. The first error that shows up is about `Game.getGrandmaSynergyUpgradeMultiplier` being undefined. If I comment that line out, hovering over an upgrade will error about the result of `Game.crate()` not being a function.

**Comment by Aktanusa** [comment]
Dang you are fast.  Yep.  I noticed the update.  Working on it shortly.

**Comment by talonos2** [comment]
I love how people are complaining about it being broken less than ten minutes after the new version comes out.

Aktanusa: _You_ are fast, my friend! Thank you for your lightning-fast work in maintaining this excellent mod! I was expecting to play without it for days!

**Comment by Aktanusa** [comment]
I don't think @randomdude999 was complaining per say, more like notifying me, though I just noticed it myself.

**Comment by talonos2** [comment]
If that's the case, then I apologize. My experience with Minecraft has obviously made me bitter and jaded. ;)

**Comment by randomdude999** [comment]
* fix usage of Game.crate()
* fix the grandma synergy simulation
* account for renaissance baker

Looked over a diff of the game code. I think this is all that needs to be fixed in CM. Should I fix them myself and submit a pull request?

**Comment by Aktanusa** [comment]
Nah, I'm looking at the diff also, it's okay, but thanks for the help and direction!

**Comment by Aktanusa** [comment]
Fixed in Version 2.016.1
