### ISSUE TITLE
Incorporate Force of Hand Seed / Cookie lookup.

### ISSUE THREAD

**Issue by pianoboy8** [Aktanusa/CookieMonster#226]
Basically talking about adding this in some way as a feature:
http://fthof-planner.s3-website.us-east-2.amazonaws.com/

**Comment by pianoboy8** [comment]
(I don't know how to label this as enhancement)

**Comment by Aktanusa** [comment]
I label it.  I already wrote the code to do this technically, my issue is that it may be too cheaty, but I'm leaning towards adding it and have it disabled by default.

**Comment by InSimpleTermsJordan** [comment]
I'd love this to be added (if disabled by default), and I'd also like some other parts to be toggleable as well (mainly those that have since been added as heavenly upgrades, such as golden cookie/reindeer sounds and wrinkler cookies digested)

**Comment by Aktanusa** [comment]
Those are already in settings...

**Comment by InSimpleTermsJordan** [comment]
oh right
i feel super dumb right now

**Comment by Aktanusa** [comment]
By the way, the Wrinkler cookie display is different, I show what you get on pop, the game shows what was eaten.  Those numbers are different as there may be a bonus on popping.

**Comment by DanielNoord** [comment]
This is already implemented by some of the more "cheaty" mods
