### ISSUE TITLE
Add all effects in tooltip of "harvest all"

### ISSUE THREAD

**Issue by pianoboy8** [Aktanusa/CookieMonster#227]
Basically, it would check to see how many cookies you'd earn from using harvest all with the current mature seeds planted, and what bank you would require to receive the maximum amount of cookies from the seeds you currently have planted by using harvest all, as well as check with a wrath equivalent and a frenzy equivalent.

I guess it should be done also in a way where you'd first pop all wrinklers as well to show the full max.

Hopefully this could be incorporated in some way.

**Comment by Aktanusa** [comment]
I think this has been requested already somewhere.  Too lazy to look, I'll do it later TODO.

**Comment by DanielNoord** [comment]
Similar to #183, but a different request
