### ISSUE TITLE
Add calculation for chain buying of buildings

### ISSUE THREAD

**Issue by potatonuggetz** [Aktanusa/CookieMonster#228]
Currently, it only shows the PP of the next building. It would be great if Cookie Monster could look further ahead in the calculations.

**Comment by Aktanusa** [comment]
It does show for buying 10x and buying 100x, but that's pretty limited.  It is planned as mentioned in Issue #4, but it's not easy to implement.

**Comment by DanielNoord** [comment]
This is a duplicate of #4
