### ISSUE TITLE
Change wording of "reset achievements"

### ISSUE THREAD

**Issue by rlesch** [Aktanusa/CookieMonster#229]
From the Description:
"The bonus income you would get from new prestige levels unlocked at 100% of its potential and from reset achievements if you have the same buildings/upgrades after reset"

Question:
 what shall "reset achievements" do here? You cant reset achievments unless you wipe the game. (at least for current v2016) Ascending leaves the Achievements untrouched, so why mention that?

basically a player wants to know how his CPS would be in the exact same situation as it is at the current moment with the assumed exact same buildings, #achievments, dragonaura and upgrades. 

thats means, the only variable thats gonna get changed is the Prestige-Multiplier. Anything else can be considered constant.

since -> "Calculating CpS is much simpler since version 2.0, since almost all percentage increases are multiplicative and independent instead of additive, with the exception of Easter eggs. " *edit: seems that wiki is wrong about the multiplicative nature of the prestige value, still, since mult=1 in the original code->. 

the calculation would be a simple  **current Cps *  (100+new_prestige_points%)/(100+current_prestige%) )**

this gives the **EXACT** values (tested on edited savegame), in opposite to the codes current calculation.

if (z=) Game.heavenlyPower*Game.GetHeavenlyMultiplier() are != 1, the formula would look like this:

  **current Cps *  ( (100+z * new_prestige_points%)/(100+z * current_prestige%) )**

**Comment by InSimpleTermsJordan** [comment]
"reset achievements" just refers to the achievements one gets from ascending with a certain number of cookies baked.

**Comment by rlesch** [comment]
> 
> 
> "reset achievements" just refers to the achievements one gets from ascending with a certain number of cookies baked.

right, that makes sense. 

just tested to be sure, my forumla is correct (and mathematically+testwise proven). the addoncode is not correct.

**Comment by Aktanusa** [comment]
As @InSimpleTermsJordan, that's what it refers to.  I just add on the amount of prestige you get calculated by the max prestige you would get and also add on any achievements and compare it to the current CPS.  I'd have to look again, but I think you are missing something.  As for your description, I don't ignore the additional achievement as resetting nets you that achievement and is really a bonus gain.

**Comment by rlesch** [comment]
For my considerations, i take the Prestige value thats actually displayed in CM as Max prestige Level. so anything there is about propery calculating the max prestige. 
For me the interesting question is, how would my current cps look like if id had the max prestige level instead of current prestige w/o ony additional influence factors.  
in math terms  
M_current = (1+Prestige_current*weight)*B*C*D*...  = (1+Prestige_current*weight)*Constant.
M_future = (1+(Prestige_current+Prestige_delta)*weight)*Constant
so Cps_current*(M_future/M_current) would result in Cps_future
 
So, yea, thats obviosuly not taking the Achievment(s) in count that you may get on ascension. 
Have to redo the test to see if the achievment explained the differences i encountered. 
The question then basically is, if you want the other factors constant or not on simulating the new prestige impact.

**Comment by rlesch** [comment]
@Aktanusa just tested with a save. did an ascension to see what achievments in total i have after. (just to be sure)

then put that save in a savegame editor (https://coderpatsy.bitbucket.io/cookies/editor.html for v2.016)
changed the achievments accordingly, added the total number of cookies to get the exact same nr of current active prestige  as was  max presige, and loaded that new save.

checked again- nr of achievments and new active prestige fitted, everything else that influences the mutliplier stayed  as it was- 

i had a higher current cps then estimated by cookie monster. 

did the same with +/- 1 achievment and didnt hit the exact estimation either. 
did the same with my forumla, with adjusted achievments and hit the exact nr. 

so, did i overlook something?

**Comment by Aktanusa** [comment]
You could post your save so I can try it out myself.

**Comment by rlesch** [comment]
wow, your fast :) - was just about to edit my post to add the saves + screenshot. Ill add them to this post, just a moment to prepare.

**Comment by rlesch** [comment]
any news on this?

**Comment by Aktanusa** [comment]
No, not until I get around to looking at it.

**Comment by Aktanusa** [comment]
So I finally took a look at this.  There is something fishy with your sample save.  If I took your first save and ascend ASAP, I get a prestige level of 17803.  Now if I just load your edited save, it says the prestige level is only 17432.  Of course the CPS of the unedited one (estimated) will be higher since it has more prestige.

**Comment by DanielNoord** [comment]
Although the calculation does not seem off, we do indeed need to change that wording
