### ISSUE TITLE
Graphs 

### ISSUE THREAD

**Issue by rlesch** [Aktanusa/CookieMonster#230]
Since this game is all about improvments all of the Dopamine comes from the impact of upgrades, and co.

so, to enjoy that more instead of just simple numbers, 'we' need graphs. (like the one in settlers 2 eg). 
so we can see production increase over time - eg for each buildings a graph can be added or removed from the diagram, and we can see the impact of each upgrade way more enjoyable  and clear than just by a changed number. the big bonus would be the overview over a bigger timeframe and not just the now-situation. :)

maybe in a new tab or in the info tab, the onfo there could be hidden by a button

**Comment by Aktanusa** [comment]
Yea, this is nice to have but really a big feature request, lol.  Probably will be a while...

**Comment by rlesch** [comment]
> Yea, this is nice to have but really a big feature request, lol. Probably will be a while...

ya definitely. though it may be easier then thought, if code from other tools can be 'abused'. played around with the fps counter in CCs dev-menu, but my js knowledge is way too limited.
Else thought about abusing diagram-plotters from administation tools like nagios/nagiosgrapher, theoretically the building cps could be exported and interpreted as performancedata, but then youd need a webserver locally to display them.  :)

**Comment by rlesch** [comment]
@Aktanusa on a second thought, i think a exrensive logging (to file) feature would be sufficient. logging any changes and their effect on the different cps values. This way ppl could use see exactly what changes had what impact (sometimes it happens just to fast) that data and import into excel or whatever.

**Comment by Aktanusa** [comment]
I don't think logging to file is not easy to do.  This is a web browser we are talking about.  Not a personal application.  There is a lot of security involved with all the virus you can download from the internet, I'm sure the limits of JavaScript will be there.  I rather not store a log in memory until you want to download it either...

**Comment by DanielNoord** [comment]
This is not something I think we are considering at this time
