### ISSUE TITLE
Show new cookies per click for tooltips of Mouse Upgrades

### ISSUE THREAD

**Issue by WesleyM77** [Aktanusa/CookieMonster#231]
When looking at the stats for a mouse upgrade (or an upgrade that affects the mouse), show a new line of data that reads 'Bonus Income Per Click' and show how much more the cookies per click will be affected.

**Comment by Aktanusa** [comment]
I like it!  Only thing is I would need to keep a database of all mouse upgrades to do this.  I don't think this will be easy to implement, but maybe in the future.

**Comment by WesleyM77** [comment]
Glad to see that this is coming soon. Thanks @DanielNoord and others for reviving this plugin!

**Comment by DanielNoord** [comment]
I missed this yesterday but #456 now implements this. You can expect to see this when we release the next version, or get it now by using the dev-version (and thereby help us testing it! :) )
