### ISSUE TITLE
Negative/infinite income for Century Egg

### ISSUE THREAD

**Issue by 3plus4i** [Aktanusa/CookieMonster#232]
I opened Cookie Clicker today after a long time, ascended right away and then got the Century Egg pretty soon on the new run. It showed to give a negative bonus income though. I'm playing live.

I wanted to test if it's probably because of the Garden or Pantheon. When I reloaded the page it showed "Infinity" as bonus income instead. Yes, bonus income and as PP as well. Freezing my Garden and unslotting spirits had no effect, unfortunately.

Everything else _seems_ to be calculated correctly, it's hard to tell though without manually calculating values to compare. Cookie upgrades are correct at least as they all show a neat, whole number.

**Comment by Aktanusa** [comment]
Can you post your save?  Does it also correct itself after a while?

**Comment by 3plus4i** [comment]
Attaching my save failed repeatedly so I'll just post it here:
`Mi4wMTZ8fDE1NDkzNzUzNDYyMzU7MTQ1NTIwODM4NzAxNTsxNTQ5NDY3NDIwNjEyO1BpbmtpZSBQaWU7ZXhqaXJ8MDExMTAwMDAwMDAwMDAxMTAxMDF8Ny43OTU4NDk2OTkzMDU1OTVlKzI5OzIuMjMxNjI2NDU3NjM4NzQxZSszMDs5MTA7NTI1NDs2LjczOTAxODgxMDU0ODEwNGUrMjk7Nzg4OzA7MDs0LjIyMTQ5MDgzODA2MTM0N2UrMjg7MTswOzA7MDstMTs0OzExOTs1LjY0OTcwMzc5OTg5MzUzOWUrMjg7MzI7MTQ7MDsyNTk3MTg7NDtoYWxsb3dlZW47Mi40NzY0NTM3MzMzOTUxMTdlKzI4Ozc7MzQ4MTk0OzMxNjk3OzMxNjQ5NzswOzA7MTg5OzMyMTs0MjE7LTE7LTE7MjI7MTQ7MDswOzUwOzA7MDs5NzszNDc7MTU0OTQ2MzU1ODk1NTswOzA7O3w0MTEsNTYxLDQuNjAyOTg5MTYyMzE0MDMwNmUrMjYsMCwsMDs0MjgsNTc4LDguMDczNzE2NTg2NzcxMTk1ZSsyNSwwLCwxOzM2MSw1MTEsNi45NzgyNjQ5MTI4MjI4ODllKzIyLDEwLDE1NDk0Njc1OTI1Njk6MToxNTQ5MzgwODA3NzYxOjA6NTQ6NTQ6MTowOjE1NDkzNzUzNDYyNDc6IDExMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAgMDowOjE6MTU6MDowOjI6NDU6MDowOjA6MDowOjA6MDowOjE6ODI6MTo4NzoyOjM1OjE6NjM6MDowOjE6MTY6MTo0MDowOjA6Mjo2NjoyOjk0OjA6MDo5OjYxOjE6MDoxOjg1OjE6MjU6MDowOjM6MTQ6Mjo0NjoyOjk5OjI6NjU6MTo4NzowOjA6MDowOjI6MjI6MDowOjE6MTQ6Mjo0MjowOjA6LDA7Mzc0LDUyNCw2LjcyMTc3MDE0MjU1MDkxNGUrMjUsMCwsMTszMzcsNDg3LDUuMDU3NTE3NjAyMDM1NjAzZSsyMiwwLCwxOzMyMCw0NzAsMi40NjM2MzMwNzAwNDkwNDllKzI0LDAsLDE7Mjg2LDQzNiw1LjcyNjg3NTk4NjcyNDg2OGUrMjMsMSwyLzYvLTEgMiAxNTQ5NDY3NDEyNTcyIDEsMDszMDksNDU5LDguMjkxNjI2NDE1Mzc5NzY1ZSsyNSwxLDgxIDEgMiAxLDA7MjU3LDQwNywxLjE2NTI2MDk0MTc4MzkwMTVlKzI1LDAsLDE7MjQwLDM5MCw2LjMzOTkzMTU2NDUxMjY2M2UrMjQsMCwsMTsyMTUsMzY1LDMuNTE5ODc3NjQ0NDU5NzU4ZSsyNSwwLCwxOzIwNSwzNTUsMS4wOTA5Nzk3NzI0ODUxMTc5ZSsyNiwwLCwxOzIwMCwzNTAsOC4wNjcxMzE3NTgzNjExMzZlKzI2LDcsLDE7MjEyLDM2Miw1LjQ0NDQyODE5MjA4NTMyM2UrMjgsMTAsLDE7MTg1LDMzNSwyLjQzMzc1NzMwNTA5OTY2NjZlKzI4LDEwLCwxOzE4MiwzMzMsMS40MDk0MDEwMDcyNjM5MjQ5ZSsyOSwxMCwsMTt8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMTExMTExMTEwMDExMTExMTAwMDAwMDExMDAxMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTEwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMDEwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDEwMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTEwMDExMTExMTExMDAwMDAwMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDExMTExMTExMTEwMDExMTEwMDAwMTExMDAwMDAxMTExMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMTEwMDAwMTExMTAwMTEwMDExMDAxMTAwMTEwMDExMDAxMTAwMTEwMDExMDAxMTAwMTEwMDExMDAxMTAwMTEwMDExMDAwMDAwMDAwMDExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTExMTAwMDAxMTEwMTExMTExMTExMTExMTEwMDExMDAwMDAwMDAwMDAwMDAxMDAwMTExMTExMTExMDAwMDAwMDAwMTAxMDEwMTAwMDAwMDAxMTExMTAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTEwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTExMTExMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDB8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTAxMTExMTExMDAwMDAwMDExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAxMTAwMDExMTExMTExMTAwMDAwMDExMTEwMDAwMTExMTExMTExMTEwMTExMDExMDExMTEwMTAwMDAwMDAxMTAxMTAxMDAwMDExMDAwMDAxMTAwMDAwMDAwMDAwMDExMTEwMDAwMDAwMDAwMTAwMDAwMDAwMDAxMDAwMDExMTEwMDAwMTAwMTExMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMDAwMDAwMDEwMDEwMDAxfA%3D%3D%21END%21`

I also loaded it in a private window (Firefox) and on Chromium, both showed the same issue. It also doesn't correct itself, I had it run for several hours now.

**Comment by Aktanusa** [comment]
Okay, I'll try to look at it soon.

**Comment by 3plus4i** [comment]
Thanks! I appreciate that. It's not a game-breaking issue, so no pressure.

**Comment by Aktanusa** [comment]
Well I just looked at it and I don't see the issue so far unfortunately.  I'll try a bit more but let me know if you see it in the new version I will release soon.  I doubt the changes I did to update to the newer version of Cookie Clicker would magically fix this.

**Comment by Aktanusa** [comment]
Fixed in Version 2.018.1
