### ISSUE TITLE
I can't purchase upgrades

### ISSUE THREAD

**Issue by Lucky13J** [Aktanusa/CookieMonster#236]
When I click on an upgrade I can afford nothing happens.

**Comment by Aktanusa** [comment]
What version of CC and what version of CM and are you sure you didn't run into the bug where the game thinks you are pressing shift or ctrl (fixed by pressing shift or ctrl again)?

**Comment by Lucky13J** [comment]
That worked, Thanks:)

**Comment by Aktanusa** [comment]
Welcome
