### ISSUE TITLE
I can't plant seeds

### ISSUE THREAD

**Issue by Lucky13J** [Aktanusa/CookieMonster#237]
When I click on a seed to plant in the garden it isn't highlighted and I can't move it to the garden and plant it.

**Comment by Aktanusa** [comment]
What version of CC and what version of CM and are you sure you didn't run into the bug where the game thinks you are pressing shift or ctrl (fixed by pressing shift or ctrl again)?

**Comment by Lucky13J** [comment]
That worked, Thanks:)

**Comment by Aktanusa** [comment]
Welcome
