### ISSUE TITLE
New version available

### ISSUE THREAD

**Issue by BigAl2357** [Aktanusa/CookieMonster#239]
Version 2.018 is now live.  An update of Cookie Monster to match is most appreciated.

**Comment by Aktanusa** [comment]
Yep, will work on it when I get some time.

**Comment by Aktanusa** [comment]
Fixed in Version 2.018.1

**Comment by iwhitt** [comment]
It seems like this is still an issue.

**Comment by Aktanusa** [comment]
If you mean it's not out yet, yes it's not OUT yet.  but it is fixed in dev =p
