### ISSUE TITLE
Wither and prestige

### ISSUE THREAD

**Issue by Doogie2K** [Aktanusa/CookieMonster#242]
I noticed that the countdown/cookies left for the prestige counter on the Stats screen falls out of sync with the one in the top corner of the main screen once Wrinklers began appearing. Is this due to a bug in accounting for wither with Wrinklers? Or is this somehow accounting for the 10% boon that comes from popping Wrinklers? (Assuming one pops all Wrinklers immediately before ascending?)

Thanks in advance.

**Comment by Aktanusa** [comment]
Try hovering over the ? in the Stats screen for prestige to see an explanation.

**Comment by Doogie2K** [comment]
Oh for crying out loud, apologies for missing that.

**Comment by Aktanusa** [comment]
No problem!  Everyone makes mistakes!
