### ISSUE TITLE
Add option to calculate with popping single fattest wrinkler

### ISSUE THREAD

**Issue by The-furf-of-July** [Aktanusa/CookieMonster#245]
Might be useful having an option for just one wrinkler to be included in the calculation... i.e. the average amount of cookies stored  between all wrinklers. I tend to keep 11 wrinklers at all times, and just pop one whenever another shows up. ticking the "calculate with wrinklers" would work if I was willing to pop all 12 for a single upgrade... it would be nice if I could know how long it would take to purchase a given thing if the biggest wrinkler and my bank cps counted.

This would add the cookies stored by the biggest or average wrinkler to the bank total, and use the increase in cookies stored by a single wrinkler (instead of all of them) in addition to normal cps, for calculating times and average cookies per second.

**Comment by The-furf-of-July** [comment]
Can't overstate how incredibly useful this would be

**Comment by Aktanusa** [comment]
I'm not sure what you can do.  Right now I'm already having a hard time in figuring what is the best way to make this an option.

**Comment by The-furf-of-July** [comment]
You could make it like the selection for the average cps window, where the "calculate with wrinklers" button cycles through three options (off, calculate with one, calculate with all). As for calculations, take the biggest wrinkler and add it to the bank total, find the rate of cookies gained by the wrinkler using the current cookies drained, and add that to the cps. ...I have limited understanding of how this works, but I'm trying my best to be helpful.

**Comment by DanielNoord** [comment]
We can just have the `CalcWrink` cycle through No, Yes, Yes but only popping single fattest wrinkler.
That would work I think
