### ISSUE TITLE
Sound notification for full wrinkler circle

### ISSUE THREAD

**Issue by The-furf-of-July** [Aktanusa/CookieMonster#246]
Since I get most of my cookies by waiting for a ring of 12 wrinklers, saving and loading to average them out, and popping one, so I stay at the 11 wrinkler bonus, it might be nice to have a sound cue to notify me when the ring is full, in case I'm playing actively at the time and want to buy some more things. Similar to the mana bar, you get more of a benefit if you only take one at a time, the more wrinklers you have the more they generate.

**Comment by Aktanusa** [comment]
Similar to #48
