### ISSUE TITLE
Calculate possible HCs if you sell all buildings and buy chocolate egg

### ISSUE THREAD

**Issue by The-furf-of-July** [Aktanusa/CookieMonster#249]
It would be very useful to know how many prestige levels I would get from selling all my buildings and getting the chocolate egg, so I can reach ascension goals sooner and more reliably as opposed to guessing how much I'd get from selling.

**Comment by Aktanusa** [comment]
That stat is already there...

**Comment by jacktose** [comment]
@The-furf-of-July, check out Statistics > Cookie Monster Goodies > Prestige > Heavenly Chips (MAX). It says:
> The MAX prestige is calculated with the cookies gained from popping all wrinklers with Skruuia god in Diamond slot, selling all buildings with Earth Shatterer aura, and buying Chocolate egg

![image](https://user-images.githubusercontent.com/12414794/56689969-2cd5a200-6691-11e9-8f1c-0ffc37c58b36.png)

**Comment by Aktanusa** [comment]
It is, but yes, the number is somewhat close.  I really hope to have more time to work on CM soon.
