### ISSUE TITLE
Display chance of random drops in stats or on tooltip

### ISSUE THREAD

**Issue by Treazer** [Aktanusa/CookieMonster#25]
This might be complicated, but it would be great if the add-on would be able to calculate the chances for the random drops, i.e. Christmas cookies, rare and common Easter eggs and all this stuff.
You would see the percentage (for both wrinklers, golden/wrath cookies and reindeers) next to the season specials stats.

**Comment by svschouw** [comment]
The calculations really are not that hard. Christmas and halloween cookies work exactly the same, only easter eggs are a bit harder.

You take the base fail rate and multiply with a bunch of multipliers based on unlocks (can easily be found in the source; lookup "halloween cookie drops" and "seasonPopup.spawn"). Then take _pSucces = 1 - failrate_. After that the chance to unlock a new cookie is _pSuccess * (1 - have/total)_.

As for easter eggs the calculations are as follows (for failRate calculations lookup "DropEgg" in the source):
Chance of normal drop first chance:
_pNormal1 = pSuccess * 0.9 * (1 - nHaveNormalEggs/nNormalEggs)_

Chance of rare drop first chance:
_pRare1 = pSuccess * 0.1 * (1 - nHaveRareEggs/nRareEggs)_

Chance to get redrop
_pRedropNormal = pSuccess * 0.9 * (nHaveNormalEggs/nNormalEggs)_
_pRedropRare = pSuccess * 0.1 * (nHaveRareEggs/nRareEggs)_
_pRedrop = pRedropNormal + pRedropRare_

Change of normal drop 2nd chance
_pNormal2 = pRedrop * 0.9 * (1 - nHaveNormalEggs/nNormalEggs)_

Change of rare drop 2nd chance
_pRare2 = pRedrop * 0.1 * (1 - nHaveRareEggs/nRareEggs)_

Chance of normal drop:
_pNormal = pNormal1 + pNormal2_

Chance of rare drop:
_pRare = pRare1 + pRare2_

I could probably make a branch and do a pull request.

**Comment by Aktanusa** [comment]
I'll get my head around this in a bit, too early in the morning =p
