### ISSUE TITLE
Support for v2.021 Beta

### ISSUE THREAD

**Issue by SlowLogicBoy** [Aktanusa/CookieMonster#256]
Currently having issues like this:
![image](https://user-images.githubusercontent.com/3121637/65017029-605de500-d92e-11e9-8534-b46e36c5a2ba.png)

My save: 
[BreakingTeethwithFingersBakery.txt](https://github.com/Aktanusa/CookieMonster/files/3619603/BreakingTeethwithFingersBakery.txt)

**Comment by Aktanusa** [comment]
2.02 is only in beta.  I only update the beta when it's been on beta for a while because I rather wait for a load of chances before making changes on CM.

**Comment by SlowLogicBoy** [comment]
Looks like this problems is caused by the new Cookie Dragon aura, everything is fine once I change aura to different one.

**Comment by Aktanusa** [comment]
Thanks for the tip!

**Comment by Aktanusa** [comment]
I'll edit the title to show it was the beta.  Kind of low priority now that the live version is out.

**Comment by SlowLogicBoy** [comment]
It works for me now, thanks for the hotfixes.

**Comment by Aktanusa** [comment]
You mean the live version works for the beta?  If so, good to know, but why are you playing the beta when the main version is the same or newer?

**Comment by SlowLogicBoy** [comment]
Oh no, I moved to stable.

**Comment by Aktanusa** [comment]
Oh, okay.
