### ISSUE TITLE
Make sound volume option changeable by click + holding and a text-field

### ISSUE THREAD

**Issue by Zukunftsmusik** [Aktanusa/CookieMonster#26]
I have to single click the cookie all the time, so please don't make me do it on the volume buttons in the settings. It would be nice, if you'd add click and hold on the volume buttons so that the volume will increase/decrease further when holding the left mouse button. Or make the display of the current volume an editable text field so that one can enter the preferred volume value instead of having to click several times.

**Comment by staticvariablejames** [comment]
Using a slider (like the vanilla volume slider) would be a better idea.

**Comment by DanielNoord** [comment]
@staticvariablejames's suggestion is good! I think we should try and do that.
As mentioned in #437 we should fix that bug with our implementation of this request!
