### ISSUE TITLE
Add effects for Fortune Cookie

### ISSUE THREAD

**Issue by Azmaeus** [Aktanusa/CookieMonster#260]
2.021 added Fortune Cookie, an event where the Ticker may display a "fortune" instead of news.

Looking at CC's main.js, line 6435, if if TickerEffect isn't 0 and TickerEffect type is 'fortune' then when the ticker is clicked you get a "fortune" (based on TickerEffect.sub).

I've created https://github.com/Azmaeus/CookieMonster/tree/2.021_fix with I hope everything needed to get a flash and sound similar to GC/Garden/Seasonal, I'm just verifying it works before submitting a PR, but you're welcome to go check it out and let me know if I'm missing anything.

update: I haven't yet added a countdown like GC, though I wonder if that's a possibility. I'm looking at CC's main.js line 6375, but it's getting late. I'll take a closer look again later.

Also, haven't yet had a fortune cookie (that I know of) so I don't know if this works. Also haven't yet figured out how to summon one to test.

**Comment by Azmaeus** [comment]
It doesn't seem to work, not sure why yet. I was able to expedite testing by repeating `Game.getNewTicker(false)` in the console until a fortune cookie appeared, but no flash/sound. While a fortune cookie was present I entered `if (Game.TickerEffect && Game.TickerEffect.type == 'fortune') {true} else {false}` and the result was 'true'. When the Ticker moved-on I could run the same command again and get 'false', so I know my logic is good. I don't know what I'm missing.

**Comment by Azmaeus** [comment]
Had a "well duh" moment, I had forgotten to put the call to the function in main.js. I did that, and ran Combine, but still it doesn't seem to chime, whether forced or when I wait for it to naturally occur... I'll keep trying, if anyone has a minute to look and see if they can spot what I'm missing I'd appreciate it.

**Comment by Aktanusa** [comment]
Keep it up!  I'm looking at the differences between the version now.  Then I'll try to add this, but if it looks too complicated, I'll just release the fix first.

**Comment by Azmaeus** [comment]
The "well duh" above was the solution for why it couldn't have worked. It didn't *appear* to fix it because I was getting a cached version of cdn.statically.io :( - does anyone know if there's a way to force cdn.statically.io to update, or is it a local caching issue?

Anyway, I've verified that my update DOES work, when the fortune is displayed I the screen flashes and the chimes sound, however it repeats each time the check is run, so instead of just once it repeatedly flashes and chimes until you click the fortune (which is difficult with all the flashing) or it goes away on its own. I'll try to figure it out on my own, but if someone knows an easy solution I'd love to hear it.

**Comment by wfentress** [comment]
@Azmaeus [Tack `?env=dev` on the end of the statically.io URL](https://statically.io/network#cache-behavior) to defeat caching.

**Comment by Azmaeus** [comment]
Thanks! I also remembered statefulness, so I got that fixed and am testing it now.

**Comment by Azmaeus** [comment]
Yes! It works great now. You can get it using
`javascript:(function() { Game.LoadMod('https://cdn.statically.io/gh/Azmaeus/CookieMonster/2.021_fix/CookieMonster.js?env=dev'); }());`

I'll be putting together a PR shortly.

**Comment by Azmaeus** [comment]
Submitted PR #262 with this enhancement.

Note: only this enhancement is in the PR, no other fixes, even the 2.021 crash fix, so if anyone pulls from that branch be sure to apply darkenvy's 2.021 fix as well, or just use my 2.021_fix branch.

**Comment by Azmaeus** [comment]
If anyone else is using this one, I've updated the Fortune Cookie effects to also update the title with [F] when a Fortune Cookie is present.

**Comment by waggz81** [comment]
Looking forward to this one, I am always too slow to click the fortune when I do notice them.

**Comment by Aktanusa** [comment]
Added in Version 2.021.2. Forgot to ping this in my commit.
