### ISSUE TITLE
Display the number of currently unlocked fortunes in the stats

### ISSUE THREAD

**Issue by Doogie2K** [Aktanusa/CookieMonster#263]
As the title suggests, two things I thought might be useful in the new version of Cookie Monster:

1. The number of Fortunes unlocked this ascension, akin to what's done for the various seasonal cookies. (It has been suggested elsewhere, I believe, to have a unique tone for when they pop up.)
~~2. The random drop chance. This is something that I have been trying to work out manually for a while now (and apparently was [once suggested](https://github.com/Aktanusa/CookieMonster/issues/25) many moons ago), but it would be nice to have the random drop percentages from the CC code surfaced in the Stats interface like the Lucky golden cookie stats and other things. When you're down to your last couple of eggs/reindeer cookies/ghost cookies/garden drops (if you need those), okay, what odds am I actually working with? What effect are my green rots having? Et cetera. (I believe fortunes were reported to be a flat 1%/2%, unaffected by other things, but those poking about in the code would know better than me.)~~ _Edit by @DanielNoord: This is a duplicate of #25_

Thanks as always for the work you put into this.

**Comment by Aktanusa** [comment]
Your first request would be pretty easy to add, but your 2nd one might not be that easy.  I will probably add the first request soon, but the 2nd request may be a bit.

**Comment by DanielNoord** [comment]
We have actually implemented point 1. Point 2 could be part of #25. Therefore closing this.
