### ISSUE TITLE
Implement fixed-length decimals for Sci/Eng Notation

### ISSUE THREAD

**Issue by raekuul** [Aktanusa/CookieMonster#264]
Would you consider forcing Scientific Notation and Engineering Notation to use three decimal places in all instances? Right now when the last digits are zero, they get truncated, which in the case of the Cookie Bank causes it to twitch and be hard to look at, especially early on in the game when your CpS is likely to be within a power of ten of your bank with regularity.

**Comment by Aktanusa** [comment]
hmm, good point.  Should be an easy fix.  Honestly, there has been a request to allow custom amount of decimal places also....  I dunno if I should wait until I get to that point.

**Comment by DanielNoord** [comment]
I think I might have actually implemented this with #399.

One problem I found though is that the Game source-code adds some 0's in the total-cookies counter when it thinks that is necessary. There are some cases where numbers beautified by CookieMonster get that treatment while it is not needed. Therefore I have currently set the standard number of decimals to be 3. In the future we should see if we can make this customizable and circumvent the game code.
