### ISSUE TITLE
Bonus income showing up as a negative number

### ISSUE THREAD

**Issue by Sir-Beatles** [Aktanusa/CookieMonster#265]
Not sure exactly what's causing it but whenever I load the mod everything I buy shows up as negative income gain. It all shows up as about -65-67% of my income too, even though  that's obviously not possible.

**Comment by Doogie2K** [comment]
This is a known issue with the addition of the new building. Aktan's working on it. :)

**Comment by Aktanusa** [comment]
I'm more surprise it doesn't crash like other people have mentioned.

**Comment by Sir-Beatles** [comment]
It seems to be caused by Kitten Executives if that helps

**Comment by Aktanusa** [comment]
Thanks!  I am almost done.  I need to figure out a few problems with the new aura, then it be out.

**Comment by Aktanusa** [comment]
Fixed in Version 2.021.1
