### ISSUE TITLE
Heavenly Chip stats overhaul

### ISSUE THREAD

**Issue by pianoboy8** [Aktanusa/CookieMonster#269]
Currently the HC system for CM is very useful for early/mid game outside of being somewhat inconvenient, so I wanted to suggest a few improvements to the system to make it more customizable and valuable during the late game.
First, "Cookies till Next Level" would be renamed to "Cookies till Next Heavenly Chip" for the formatting to fit.

Next in Settings, add two new options for Heavenly Chips.
-Being able to change "X Cookies till Next Heavenly Chip" to "X Heavenly Chips needed for Y Total Heavenly Chips", "X Heavenly Chips needed for Y Unspent Heavenly Chips", and "X Heavenly Chips needed for Y% RBI" (Both with timers that show how long it will take to reach the set HC total or RBI%).
*Note: For RBI, it will calculate how many HC are required to have a RBI of at least (>=) Y%.
-Being able to set the Y HC or RBI% amount for the new options above. So you can set it to 1,000,000 HCs, or 100% RBI, etc.

Besides that, a new statistic would be added, being "HCPS" (or Heavenly Chips / Second). Extremely useful for late game.

Combined with the above, whatever statistic that is being used, the time elapsed to reach that goal, the HCPS, and the RBI% you earn from ascending should be added to the tooltip for the Legacy button (so you don't need to view the statistics page to keep tabs on it).

"X Heavenly Chips needed for Y Unspent Heavenly Chips" can help for getting certain ascension upgrades, by showing you how much time you have to reach that goal.
"X Heavenly Chips needed for Y Total Heavenly Chips" can help for late game, when you are earning multiple HCs per second (in which the current cookies until next HC becomes completely obsolete). 
"X Heavenly Chips needed for Y% RBI" can help for seeing how many HCs you need to double, triple, or apply some multiplier of your current income so you can decide on when you want to ascend.

**Comment by Aktanusa** [comment]
I like that that extra @raekuul
