### ISSUE TITLE
Change Bulk Building Colors (Calculated Color) to be based on the Bulk PP Values

### ISSUE THREAD

**Issue by pianoboy8** [Aktanusa/CookieMonster#270]
Right now "Calculated Color" changes the color of bulk building purchases to be based on the PP of that bulk purchase of that building rather than the purchase of an individual building. Issue here is that basically all the colors will be either yellow or worse (since it's still comparing to the lowest PP of buying an individual building).

My suggestion is to change how colors are viewed with this setting enabled, by having the colors be based on the comparison of the lowest and highest PP bulk purchase of the current bulk setting.

So let's say you are currently on the x10 buy bulk option. Now the green color will be based on the lowest PP of buying 10x of a building, rather than buying only 1x of a building. Ditto for 100x (All could either be based on whatever max # of buildings you can purchase or just outright be ignored here).

Upgrade colors would also change to be based on the lowest bulk PP purchase (whether that's 10x or 100x).

This would help especially for late game, when bulk purchases are more likely to occur (and also helps with the Rigidel Spirit in the Pantheon, which requires your total # of buildings to end with 0 to function).

**Comment by Aktanusa** [comment]
Good idea.  I don't think it be too hard to implement this.
