### ISSUE TITLE
Suggestion: Fortunes left to unlock

### ISSUE THREAD

**Issue by Kidsheldon** [Aktanusa/CookieMonster#271]
Similar to the tracker of eggs left to buy, I think there should be a tracker for how many Fortunes you have left to get. It'd list the upgrades by their numbers, as well as Lucky Numbers (1 hr of CpS) and Lucky Day (GC spawn).

**Comment by Aktanusa** [comment]
Yep, has been suggested.  Thanks for allowing me to track it!

**Comment by Aktanusa** [comment]
Added in Version 2.021.2.

**Comment by Aktanusa** [comment]
Note, "Lucky Numbers" and "Lucky Day" are not needed to get the achievement "O Fortuna", so I have not included a check for them.

**Comment by Kidsheldon** [comment]
I just thought it'd be nice to include those two in case someone wants to make use of them but can't remember if they've already used them.

**Comment by Aktanusa** [comment]
Hmm, I can see that, maybe a separate one since this one is left to buy, and the other two is left to get.
