### ISSUE TITLE
Display cookies gained in tooltip of chocolate egg

### ISSUE THREAD

**Issue by Eggsukr** [Aktanusa/CookieMonster#272]
I don't know if it's possible, but it would be a nice feature.

**Comment by raekuul** [comment]
![image](https://user-images.githubusercontent.com/11349476/66617889-f3dcab80-eba4-11e9-8fab-773fe2449325.png)
It should be possible - Cookie Monster currently calculates how much it _should_ have if you optimally max out your bank before cracking it open.

**Comment by Aktanusa** [comment]
Hmm, what would be the benefit?  Also, you just reminded me to test to make sure the best way to sell buildings is to change both auras before selling.  I'm not sure right now.

**Comment by Kidsheldon** [comment]
Depends on your building prices. I know that if your highest building is far more expensive than the rest, it's sub-optimal. There's likely a bit of math that'd go into calculating if it's optimal or not at any given moment.

**Comment by Aktanusa** [comment]
I did a quick test, and seemly for late game, you do want both "Earth Shatterer" and "Reality Bending."  As for the math, an easy way is to try all combinations and see which gives the most, lol.

**Comment by DanielNoord** [comment]
This should preferably be displayed in the tooltip.
Mind that it should display current cookies gained, not optimal, as that is already in the stats
