### ISSUE TITLE
Bookmarklet script

### ISSUE THREAD

**Issue by aeros** [Aktanusa/CookieMonster#273]
I'm not certain if this applies universally across javascript engines (particularly older ones), but it's not required to use an anonymous function to load the mod. This applies to usage in both the bookmarklet and the browser console in the latest versions of Firefox and Chrome.

Instead of using:
```javascript
javascript: (function () {
	Game.LoadMod('https://aktanusa.github.io/CookieMonster/CookieMonster.js');
}());
```

This is adequate:
```javascript
javascript: Game.LoadMod('https://aktanusa.github.io/CookieMonster/CookieMonster.js');
```

The usual reason for the usage of anonymous functions is to avoid potential name collisions, but it doesn't seem necessary in this case since there's only a single function being called that is virtually guaranteed to be reserved to CookieClicker's `Game.LoadMod()` (assuming it's used on the correct page).

I would suggest recommending the trimmed down script by default, and leaving the other option as a backup for backwards compatibility issues. Unless of course there's a reason to use an anonymous function here that I'm not aware of.

**Comment by Aktanusa** [comment]
I'll take a look.

**Comment by bitsandbytes1708** [comment]
Using an anonymous function isn't necessary, but is generally considered good practice. Since no one has commented on this for a while, and no one seems that concerned about it, I'm going to go ahead and close the issue.
