### ISSUE TITLE
Issue: Eye of wrinkler

### ISSUE THREAD

**Issue by Eggsukr** [Aktanusa/CookieMonster#275]
I have purchased the eye of the wrinkler heavenly upgrade and shows less cookies than the ones shown from the cookie monster. Is there less because of the eye of the wrinkler?

**Comment by Antwelm** [comment]
> I have purchased the eye of the wrinkler heavenly upgrade and shows less cookies than the ones shown from the cookie monster. Is there less because of the eye of the wrinkler?

CM also calculates the bonus of popping it I think, whereas eye of the wrinkler only shows how much it has eaten.

**Comment by Aktanusa** [comment]
@Antwelm is correct.  I think the info of what you get from popping is more useful than what has been eaten.
