### ISSUE TITLE
v2.022

### ISSUE THREAD

**Issue by Antwelm** [Aktanusa/CookieMonster#276]
Small, silent/stealth, bug-fix update (v2.022) is live.

CM now shows a dialog of it being old when loaded:

'Cookie Monster version 2.021.2 is meant for Game version 2.021.  Loading a different version may cause errors.  Do you still want to load Cookie Monster?' y/n

**Comment by Aktanusa** [comment]
Yep, will add a fix sometime today.  Should be super simple as it's a minor change.

**Comment by vern1701** [comment]
Will you let us know when it is ready?  Discord or here works.

**Comment by Aktanusa** [comment]
I mean, I highly doubt there be a problem if you just the old version.  I guess I will announce it, but I didn't think it be a big deal.

**Comment by vern1701** [comment]
beats not knowing it's out.  And the endless "How long?" questions.

**Comment by Aktanusa** [comment]
Well, I'm going through it now, but might as well add some changes also.

**Comment by vern1701** [comment]
add x10 and x100 timers based on what buy slot is selected, in addition to the x1 timer...

**Comment by Aktanusa** [comment]
@vern1701 dude, wrong spot to post this.

**Comment by vern1701** [comment]
<smacks head> excited noob to the game here!

**Comment by Aktanusa** [comment]
Fixed in Version 2.022.1

**Comment by FWDekker** [comment]
It looks like this fix has not been deployed/released. Is this intentional?

**Comment by Aktanusa** [comment]
Yes, since I was planning to add some stuff before release since honestly there was a minor change so might as well add some features, but then I got sidetracked =(.  I may just release it to remove the popup.

**Comment by Aktanusa** [comment]
yeah, but you only see it on first load, so unless you load it all the time over and over, it shouldn't really be that annoying...

**Comment by FWDekker** [comment]
That's true. If it's intentional because of whatever reason I'm absolutely fine with that decision. I was just curious if it was intentional or an oversight.
