### ISSUE TITLE
Show x10/x100 PP values on BottomBar depending on selected buy mode

### ISSUE THREAD

**Issue by vern1701** [Aktanusa/CookieMonster#277]
New to the game, but wondering if you could add timers for x10 (Used frequently) and x100 (sparingly) on to the bottom statistics bar?  x1 is quite good, but don't use much.

**Comment by Aktanusa** [comment]
Interesting idea.  Shouldn't be too hard.

**Comment by vern1701** [comment]
Thanks, I have pretty much all free time to devote.
