### ISSUE TITLE
Calculate Payback Period including wrinkler-eaten cookies?

### ISSUE THREAD

**Issue by benjaminysmall** [Aktanusa/CookieMonster#278]
Would it be possible to made it so that Payback Period includes the cookies being eaten by wrinklers? 

Meaning, when I look at a building's tooltip, I would like the Payback Period to assume that at some point in the future, I will pop all current active wrinklers, and to take the contribution to those wrinklers from that building into account when calculating Payback Period.

It may be difficult, especially given that wrinklers can change how much they return with Skruuia, for example, but it would be really helpful for me (or players like me):

In each new ascension, I buy buildings for a while, then I let Cookie Clicker idle while it accumulates cookies (with wrinklers active). Once I've paid back all my buildings plus a bit extra, I pop the Chocolate Egg and ascend. If I ascend too early, I've "wasted" cookies by not paying the buildings back and losing out on Chocolate Egg cookies. Currently, there's no good way for me calculate how long I actually need to idle to pay back all my cookies, because the wrinklers accelerate that timeline.

Anyway, I realize this may be a bit complex, but figured I'd lodge it as a feature request. Thank you for maintaining this! If you think this is worthwhile but aren't planning to get to it any time soon, let me know. I could take a crack at a PR for it.

Sidenote, this is what I thought the "Calculate with Wrinklers" option did until I noticed what it actually did. As a smaller todo from this request, could you consider changing that option name to be more specific to what's getting re-calculated?

**Comment by Aktanusa** [comment]
It's already there, I think turned off by default.  Check the options to see if it's on.

**Comment by benjaminysmall** [comment]
Do you remember what it's called? I couldn't find anything in the options that looked like it did that.

**Comment by Aktanusa** [comment]
Calculate with Wrinklers ON

**Comment by benjaminysmall** [comment]
If that setting is supposed to do what I'm suggesting, then I think it might be bugged. Or I might just be dense, which is totally plausible. I've attached my save file here. 
[savefile_forupload.txt](https://github.com/Aktanusa/CookieMonster/files/3748643/savefile_forupload.txt)

With that setting off, a Fractal Engine takes 5.752M seconds to payback. With it on, it takes the same amount of time (at least, within rounding). I'd expect that since having 12 wrinklers is an effective 9x boost to CPS, that the time would go down to something like 600k seconds. I apologize if this really is just me being dense, but what am I missing?

**Comment by Aktanusa** [comment]
Oh, this is my bad for skimming.  Payback Period depends on the current CPS.  You are right it doesn't account for it.  Why do you want to account for it?

**Comment by raekuul** [comment]
The Calculate With Wrinklers ON setting is for the Lucky/Frenzy Lucky warning anyway. 

Payback Period doesn't account for your bank at all, does it?

**Comment by benjaminysmall** [comment]
I'm always running with wrinklers, and right before I ascend, I pop them all and then buy the Chocolate Egg (like the tooltip suggests). If I buy a building, I want to make sure it's paid for itself before I do all that; otherwise, I've wasted cookies (because my total bank would have been higher had I not bought the building). If the PP calculation took into account wrinklers, I could be more confident in knowing when it's "safe" to pop & choc egg. The adjusted PP would tell me how long I need to play the game without buying buildings before it's profitable to pop & choc egg.

**Comment by Aktanusa** [comment]
I understand.  The problem is is the real CPS changes depending if you get a golden cookie, or cast a spell, etc, etc. besides just wrinklers.  I think what you are asking is use something like "Average Cookies Per Second" to calculate the PP, but the PP numbers, which I think you will be fine with, will fluctuate like crazy all the time.

**Comment by benjaminysmall** [comment]
Ah yeah! Does "Average Cookies Per Second" include cookies eaten by wrinklers? If so, that sounds like it's exactly what I'm looking for. Totally understand that it would fluctuate, but I think that's fine, especially given that the use case I'm optimizing for involves very passive play.

**Comment by Aktanusa** [comment]
It does.  Okay, now I know what exactly you want.
