### ISSUE TITLE
Golden Cookie Timer is Misleading

### ISSUE THREAD

**Issue by Zamiell** [Aktanusa/CookieMonster#279]
Greetings,

Thanks for the useful add-on.

It is my understanding that Golden Cookies now spawn randomly, instead of at certain intervals. If this is true, shouldn't the Golden Cookie Timer feature of Cookie Monster be removed? It is misleading to the end-user that this option even exists.

**Comment by raekuul** [comment]
Even with GCs now spawning randomly, there is a minimum amount of time that has to pass between golden cookies (represented by the Gray portion of the timer bar) and a maximum amount of time that can pass between golden cookies (represented by the purple portion). Otherwise all of those "Golden Cookies spawn X more frequently" upgrades would be a waste of bank.

**Comment by Zamiell** [comment]
I would agree that the "Timer Bar" feature of Cookie Monster is marginally useful so that users can see how much of the gray bar is left. (Or, to phrase it in a different way, to see if it is currently possible for a Golden Cookie to even spawn.)

Allow me to rephrase my question. Currently, the "Next Cookie" number that is displayed on both the "Timer Bar" **and** the custom title is the value of the maximum-possible time that the Golden Cookie can appear.

Would it be more useful to swap the number out to instead show the user the minimum-possible time that the Golden Cookie can appear, instead of the maximum? In this scheme, a value of 0 would mean that the Golden Cookie can spawn any second.

**Comment by Aktanusa** [comment]
While it is random, the probability changes during the course  of the timer.  It is highly unlikely you would ever get a golden cookie the second the minimum timer is gone, but as the time counts down, the probability keeps increase.  There was plans to add that probability % that I never got around to adding, but usually a golden cookie spawns around the same time left range, that people get used to seeing.  So while it's not accurate, it still is somewhat helpful, as I can guess around XX time, a golden cookie will spawn any second.

**Comment by bitsandbytes1708** [comment]
I think all the questions have been answered, so I'll go ahead and close this issue.
