### ISSUE TITLE
Show income gain % / time to earn item

### ISSUE THREAD

**Issue by wmertens** [Aktanusa/CookieMonster#284]
I think it would be interesting to see the time to earn one item, and the bonus % divided by the amount of time it takes to earn one item.

For example, if 2 items  A and B have 2% and 5% bonus, but time-to-earn 1 minute and 5 minutes, they have 2 and 1 for the %/s metric, and it would be beneficial to choose to build A a few times.

**Comment by Aktanusa** [comment]
Hmm, are you saying this method would be more efficient than the current method?

**Comment by wmertens** [comment]
Not sure, I think that it would help in cases where getting 2-3 consecutive
upgrades of a cheaper item would lead to higher gains for the same price
due to compounding.

>

**Comment by TakGalaman** [comment]
Sounds like you'd be interested in enhancement #4 @wmertens

**Comment by DanielNoord** [comment]
This is indeed a duplicate of #4.
