### ISSUE TITLE
Display Golden Cookie countdown timer on GC's summoned by Force the Hand of Fate

### ISSUE THREAD

**Issue by NotQuiteAmish** [Aktanusa/CookieMonster#288]
Thanks for the useful plugin!

Pretty self-explanatory, Golden and Wrath cookies summoned by FtHoF do not show a countdown timer when it is enabled.

**Comment by Aktanusa** [comment]
Welcome!  It's too bad I don't have much time to work on this anymore.  Anyway, this is intended as those cookies you know are coming and the game itself identify them as forced GC.

**Comment by DanielNoord** [comment]
I disagree with Aktanusa and think we should in fact display the timer.
We should not do the Sound/Flash/Notification though for user-spawned cookies.
