### ISSUE TITLE
Include Dragon's Fortune and Reality Bending in Cookies Required calculations

### ISSUE THREAD

**Issue by EricLarsenMN** [Aktanusa/CookieMonster#289]
Currently, the calculations for both Chain and Lucky cookie requirements detect if the Golden Switch is on.  Could detection also be added for when the Reality Bending and/or Dragon's Fortune auras are active, and factor in the CPS boost they provide?

**Comment by Aktanusa** [comment]
That's a good idea!

**Comment by DanielNoord** [comment]
This might be solved as #347 gets solved, but I am not sure right now

**Comment by Chorizorro** [comment]
Unfortunately, this won't be solved along with #347 as it doesn't share any calculation method with it, as far as I could see.

**Comment by Chorizorro** [comment]
I'm not sure about what the issue really is: when a golden cookie pops on the screen, the Lucky/Chain stats already adjust in real time to factor in the CPS boost (and it works for multiple golden cookies on the screen too).

Is this about factoring in the +123% boost from DF (and +12.3% from RB) in the stats BEFORE the golden cookie even pops, because there will always be at least 1 cookie on the screen while triggering a Lucky/Chain?

**Comment by EricLarsenMN** [comment]
> Is this about factoring in the +123% boost from DF (and +12.3% from RB) in the stats BEFORE the golden cookie even pops, because there will always be at least 1 cookie on the screen while triggering a Lucky/Chain?

Yes, this.  I am actually experiencing this situation right now, where I have to pull out my phone's calculator to multiply the "Lucky Cookies Required (Frenzy)" by 1.123 because I am playing with RB and I want to know what threshold to keep my bank above when there isn't a GC actually on the screen at the time.

Since the only time this threshold value matters is when you are actually popping a GC, I feel it should reflect the value with multipliers related to the GC being on the screen.  The tooltip should also specify that the calculated value takes ONE GC on screen into the calculation, since Distilled Essence or Force the Hand can put more than one GC on the screen at a time and throw that number off.

**Comment by Chorizorro** [comment]
Thanks for the clarification! I see now why this is relevant.

> Since the only time this threshold value matters is when you are actually popping a GC, I feel it should reflect the value with multipliers related to the GC being on the screen. The tooltip should also specify that the calculated value takes ONE GC on screen into the calculation, since Distilled Essence or Force the Hand can put more than one GC on the screen at a time and throw that number off.

I was thinking about doing the following:
- If there is no GC on screen, show the requirements / rewards as if there was 1 GC on screen (+ update tooltip to specify this);
- Else (one or more GC on screen), show the actual requirements / rewards (what Cookie Monster is doing right now)

Is this what you were describing or did I miss the spot?

**Comment by EricLarsenMN** [comment]
That sounds like a good plan.  I am looking forward to seeing it work!

**Comment by Chorizorro** [comment]
I've pushed a fix for this issue! It should calculate both requirements and reward for both lucky and chain cookies. Would you be so kind to test it and tell me if this is working as expected?

You can load the add-on with `Game.LoadMod('https://chorizorro.github.io/CookieMonster/CookieMonster.dev-289.js')` to get the test version for this issue instead of the usual `Game.LoadMod('https://aktanusa.github.io/CookieMonster/CookieMonster.js');` one.

**Comment by EricLarsenMN** [comment]
A simple test of the Lucky calculations looks good.  I'm not really set up to do more sophisticated testing than that, however.

**Comment by Chorizorro** [comment]
No worries, thanks for the confirmation!
I've been doing some testing too and it looks alright.

**Comment by DanielNoord** [comment]
I will take a look at this tomorrow!
Knowing the work of @Chorizorro if have no doubt the fix will be perfect :)

**Comment by Chorizorro** [comment]
Aww thanks ☺️
Not that I want to prove you wrong, but I've just realized I still need to update the tooltip before this can be merged and closed (this shouldn't be long!)

**Comment by Chorizorro** [comment]
Should be all set now!

The tooltip changes from "Calculated with Golden Switch off" to "Calculated with Golden Switch off and at least one golden cookie on-screen" when Dragon's Fortune aura is in effect (via DF / RB).
