### ISSUE TITLE
Display the required bank and CpS to reach the next reward level for Cookie Chains in stats

### ISSUE THREAD

**Issue by killergege** [Aktanusa/CookieMonster#29]
Could you add to the Cookie Chain stats the required bank and CpS to the next reward level ?
Today, it displays the cookies required for the current chain, but it would be interesting to have information about when you'll get the next level.

This information is available on the [Golden Cookie table "Rewards for Cookie Chain" on the Wiki](http://cookieclicker.wikia.com/wiki/Golden_Cookie#Outcomes).

Thanks to your awesome addon, this is now the only "outside" information I search when playing Cookie Clicker !

**Comment by DanielNoord** [comment]
Moving this to later version as it turns out it is pretty difficult to compute this
