### ISSUE TITLE
Version 2.022

### ISSUE THREAD

**Issue by franciscoluiz** [Aktanusa/CookieMonster#290]
Any plans to upgrade to version 2.022? Great job. Congratulations!

**Comment by Aktanusa** [comment]
It's already in dev, I've just been real slow in updating.  There is no difference from version 2.021 for CM, which is why I didn't see it being too important to release.

**Comment by Mar2ck** [comment]
It would help to stop the pop-up every time the cookie clicker page is loaded

**Comment by starg09** [comment]
If not updating master branch for minor updates like these, maybe a "Don't notify of wrong version" option could be added to the add-on settings? Because I came here after a single day of coming back, and going through what mar2ck mentioned above (and I imagine using the dev branch script might not be the best idea for regular users, assuming you do work on it from time to time).

**Comment by Aktanusa** [comment]
@starg09 That is an interesting idea, though this is the first time I've taken this long to do an update.  Maybe I will just release an update to stop the notification then.

**Comment by dafzor** [comment]
It's been months, I already "fixed" it with a fork but would be nice to have it on the official version.

**Comment by Aktanusa** [comment]
sorry =(

**Comment by dafzor** [comment]
You have nothing to be sorry about. I was just making a suggestion =\

**Comment by SirJohnny-JB** [comment]
Hey, I understand that you are developing a 2.022 version, but it looks like some people managed to use it either way, is that actually possible? Because it said I was importing something from an older version and didn't import it, I was importing it via the Developer Tools Console.

**Comment by Aktanusa** [comment]
You can safely ignore the message as the game itself barely changed.  The issue for some people is that they are sick of the message, which is understandable.  Yes, I have taken way too long to release an update and I'm sorry for that.

**Comment by Spoonyman** [comment]
Ah good to know its jsut the pop-up and nothing is wrong. Just started again and went to use CM but the pop-ip made me worry. Take your time homie and thanks for the great addon.

**Comment by Aktanusa** [comment]
Thanks for the kind words.  I am sorry it is taking me this long.  I have some personal issues that I need to figure out first.  Please be patient with me.

**Comment by SirJohnny-JB** [comment]
Yea, no problem man, take your time. Personal issues should come first, I know this because I myself struggle with mental health, so take all the time you need bro.

**Comment by Aktanusa** [comment]
Thanks for understanding.
