### ISSUE TITLE
Suggestion: Heavenly Chip counter for hidden lucky upgrades

### ISSUE THREAD

**Issue by Viraden** [Aktanusa/CookieMonster#291]
It would be nice if there was an easier way for me to know approximately when I will have enough heavenly chips that when added to my prestige it will equal a total of 7, 777, or, in particular, 777,777.

**Comment by Aktanusa** [comment]
Technically the stat is already there under "Heavenly Chips (CUR /MAX).  You would need to change the number display to see all the numbers, if it's too big though.

**Comment by DanielNoord** [comment]
This has been implemented with #222
