### ISSUE TITLE
[Enhancement] Show Payback Period as a Time

### ISSUE THREAD

**Issue by raekuul** [Aktanusa/CookieMonster#292]
Since Payback Period is (presumably) how many seconds it would take for a building/upgrade to pay for itself, I would like the option to see Payback Period as a time value.

**Comment by Aktanusa** [comment]
It's mostly used for a comparison as the formula doesn't exactly show the time value.  I don't know how to exactly calculate it as a time value, but it's close enough.  Basically, do you know how to get the time value?  Are you suggesting to just use the formula cost/Δ cps?

**Comment by raekuul** [comment]
Payback Period is already by second (since it's already based around the CpS value), so we should be able to just directly (re)format it as a time value without modifying the underlying calculation.

**Comment by Aktanusa** [comment]
I'm not sure exactly what you want then if the information is already there.

**Comment by raekuul** [comment]
The option to show payback period as XX:XX:XX:XX:XX instead of X.XXeYY

**Comment by Aktanusa** [comment]
Oh, sometime similar to the option "Change the time format" but for payback period?

**Comment by raekuul** [comment]
Yes, that's what I was trying to ask for. (Note to self, next time include an example in the request)

**Comment by Aktanusa** [comment]
Got it.

**Comment by DanielNoord** [comment]
As PP is not really a time-unit we have said on a number of occasions that we are not likely to implement this
