### ISSUE TITLE
Suggestion: Displaying last 6 digits of prestige level for Lucky payout

### ISSUE THREAD

**Issue by ICubE-** [Aktanusa/CookieMonster#294]
I think it will be more comfortable if I can see last six digits of prestige level.
If your prestige level becomes larger than 1M, than you can't see last digits.

Here's a prototype code that I made.
[https://github.com/ICubE-/CookieMonster/commit/82b6f5522cc8b0ffafe75a5033d1860b11f0e416](url)

You can test with the command: 
`javascript: (function () { Game.LoadMod('https://icube-.github.io/CookieMonster/CookieMonster.js'); }());`

![주석 2020-04-09 012115](https://user-images.githubusercontent.com/8535190/78808479-6fa69c00-7a00-11ea-8454-14f82fa363e8.png)

**Comment by Aktanusa** [comment]
Cool, I'll take a look.

**Comment by DanielNoord** [comment]
This has been added with 2.031.1
