### ISSUE TITLE
Reorder the buildings by best to worse PP

### ISSUE THREAD

**Issue by Darlat** [Aktanusa/CookieMonster#295]
Is it possible to make a warning box for there being a upgrade with better payback period?

Like the Warning and Caution boxes on the tooltip when hovering over a building, preferably on a separate toggle from the others.

Requested so you don't have to scroll up all the time after buying a building lower down.

**Comment by Aktanusa** [comment]
I get what you mean, I also need to scroll up and down.  I think one solution is have the option to reorder the buildings by best to worse PP.  This would also solve some of the other issues also (which ones, I'm too lazy to look right now).  What do you think of that idea?

**Comment by Darlat** [comment]
I suppose that would work too, and be easier.

**Comment by bitsandbytes1708** [comment]
You can now do this! To activate sorting by PP, go to Options --> Cookie Monster Goodies --> Bars/Colors then toggle Sort Buildings.
