### ISSUE TITLE
Incorrect Warning/Caution calculation when buying building/upgrade

### ISSUE THREAD

**Issue by Greezye625** [Aktanusa/CookieMonster#296]
Cps increase after buying a building or upgrade isn't included in calculation, when displaying warning/caution banner about putting player under number of cookies required for lucky or frenzy. It takes into account bank balance after purchase but not Cps. If i have 
Cookies in the bank - 175 B
"Lucky" Cookies required - 160 B
and hover over upgrade costing 10B that will increase Cps by 30%, it doesn't show any warning about going under required limit. After purchasing i have 165B cookies in bank but obviously limit increases considerably and I'm under it. 
It seems to check current limit instead of calculating what the limit will be after Cps increase from purchase

**Comment by Aktanusa** [comment]
This is intended.  It's actually more efficient this way.  But for those who like the other way, the option is there.  It's called "Calculate Tooltip Warning/Caution With Bonus CPS ON/OFF".  Is that what you are looking for?

**Comment by Greezye625** [comment]
Yeah, thank you. Sorry for false alarm. Could you briefly explain why it's more efficient, or refer to some source on that?

**Comment by Aktanusa** [comment]
Hmm, I forgot the exact reason, but it's more efficient because if you compare the amount of time to gain the extra bank for the CPS increase with the old CPS vs the amount of time to gain the extra bank for the CPS increase with the new CPS, the time is shorter with the new CPS.  I hope I explained that clearly, lol.
