### ISSUE TITLE
Sextillions and Septillions confused

### ISSUE THREAD

**Issue by LazG2** [Aktanusa/CookieMonster#297]
I noticed that, in V 2.022 the script believes that sext are sept

<img width="813" alt="Ohne Titel" src="https://user-images.githubusercontent.com/65951360/82891813-adc73300-9f4e-11ea-9b4e-7e76793aad5f.png">

**Comment by Aktanusa** [comment]
I'm sorry, I don't see the problem right now.  My wild guess is that "Calculate with Wrinklers ON" is set and that the cookies you would get from popping all wrinklers would give enough cookies to make all the require statistics be green.

**Comment by Kidsheldon** [comment]
That sounds about right. From a technical standpoint, there's no way Cookie Monster could be confusing Sext and Sept, as it doesn't actually care about the word, just the raw number value.
