### ISSUE TITLE
Beta 2.026 released

### ISSUE THREAD

**Issue by CorruptComputer** [Aktanusa/CookieMonster#298]
https://orteil.dashnet.org/cookieclicker/beta/

The CM beta script looks for version 2.016.

**Comment by Aktanusa** [comment]
Thanks for the heads up.  I will need to make time for the eventual release to non beta.  I don't usually update the beta script until it's been stuck in beta for a while, since any changes I make can be changed again by Orteil.  So I usually wait.

**Comment by UltraCraftGames** [comment]
Would it still work in beta just not do anything for new stuff or would it completely break

**Comment by Aktanusa** [comment]
Since I never got around to updating the beta to current, I'm pretty sure it will break.  A better option is the current live script, but no guarantee it will not break since I don't know what changes have been made.  Bottom line, try any at your own risk, but I'm pretty sure both won't affect your save file.

**Comment by chiffon-rouge** [comment]
So far, using the release version script seems to work with the latest beta.

```
// ==UserScript==
// @name Cookie Monster Beta
// @namespace Cookie
// @include http://orteil.dashnet.org/cookieclicker/beta/
// @include https://orteil.dashnet.org/cookieclicker/beta/
// @version 1
// @grant none
// ==/UserScript==

var code = "(" + (function() {
    var checkReady = setInterval(function() {
        if (typeof Game.ready !== 'undefined' && Game.ready) {
            Game.LoadMod('https://aktanusa.github.io/CookieMonster/CookieMonster.js');
            clearInterval(checkReady);
        }
    }, 1000);
}).toString() + ")()";

window.eval(code);
```

**Comment by delciotto** [comment]
I've found the new dragon scale upgrade is the only thing so far that really screws things up in the beta.  It just causes all calculations to go negative.

**Comment by Aktanusa** [comment]
Thanks for the heads up!
