### ISSUE TITLE
A Getter for the worth object to buy

### ISSUE THREAD

**Issue by nokisenpai** [Aktanusa/CookieMonster#299]
Just add a getter like : CookieMonster.getWorthObject(); Or I don't know how to do. Create a documentation :D

I want make an auto-buy using your data.

Is it possible?

**Comment by Aktanusa** [comment]
Yes, you have direct access to the data.  Everything is in `CM.Cache`.

**Comment by nokisenpai** [comment]
Magic !

You're fast ! 

Thanks ! But I don't find which one getting me the worth object(or upgrade) to buy. 

CM.Cache.Objects give me an array with some objects.
CM.Cache.Upgrades do the same with upgrades.

What's the simple way to do? Am I to check each objects/upgrade to know which one is the worth?

**Comment by Aktanusa** [comment]
Nice, you found it.  Is the issue solved for you then?

**Comment by nokisenpai** [comment]
Yes, of course :)
