### ISSUE TITLE
[beta 2.027] new [Dragon Scale] Upgrade bugged

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Aktanusa/CookieMonster#302]
**Dragon scale upgdrade what is it:**
an upgrade that is unclocked by petting your dragon (new heavenly upgrade)
**Expected Behaviour:**
be caclulated as coockie upgrade (simply increase CPS)

**Bug#1;**
![image](https://user-images.githubusercontent.com/30759571/90945761-9c97a080-e42f-11ea-894f-bad285acf323.png)
NOTE: bug 1 does not always happen
**Bug#2;**
Once bought it causes all Building (not upgrades)  PP calculations to go haywire and they get negative values

**Temporary Fix for those expiriencing this bug**
`Game.UpgradesById[648].bought = 0;`
this is will "unbuy" the upgrade (no coockie refunds) after witch i recomend putting in your vault

**Other info**
The Dev version of coockie monster 2.022.2 was used, the beta 2.026.1 crashes the game

**Comment by Aktanusa** [comment]
Thanks for the heads up.

**Comment by Kallinteris-Andreas** [comment]
This bug persists in 2.028

**Comment by Kallinteris-Andreas** [comment]
I made a mistake in the original post purchusing [Dragon Scale] does also Break the math on PP caclucations for upgrades (thought it doesn't make them go negative)

**Comment by FWDekker** [comment]
Bug#2 is also caused by unlocking the _Milkhelp lactose intolerance relief tables_ prestige upgrade. You can remove the upgrade using `Game.PrestigeUpgrades[85].lose()`.

**Comment by DanielNoord** [comment]
We will now use #317 to discuss any missing upgrades or items as a result of CookieMonster not being updated for CookeClicker 2.031.
