### ISSUE TITLE
[2.029] bank's [loan 3] breaks the buff timer display (minor visual bug)

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Aktanusa/CookieMonster#304]
![image](https://user-images.githubusercontent.com/30759571/91026896-0bc5ee00-e604-11ea-8fc5-8485b3966a88.png)
![image](https://user-images.githubusercontent.com/30759571/91027278-8ee74400-e604-11ea-807f-deb50cacf2a4.png)

**How to replicate:**
step 1) buy a bank and level it up (to unlock the stop market minigame)
step 2) upgrade the bank office to max level (to unlock all loans)
step 3) buy loan 3

**Comment by Aktanusa** [comment]
Thanks for this!

**Comment by DanielNoord** [comment]
Postponing this issue as it will likely depend on the rewrite of the code necessary for #56.
When I start working on that one I will also fix this!
