### ISSUE TITLE
[2.029] Chocholate Egg & Stock Market integration

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Aktanusa/CookieMonster#305]
Current Behaviour: When Caclulating the Chocholate egg Bonus it caclulates based on current cookies balance + cookies obtained from sell all buildings

Wanted Behaviour:When Caclulating the Chocholate egg Bonus it caclulates based on current cookies balance + cookies obtained from sell all buildings **+ dumping all owned stock market stocks**

**Comment by Kallinteris-Andreas** [comment]
sorry i dont know javascript but this should work
`GetStockNetWorth(){
     var dollarsInStockMarket =0;
for (var i=0;i<Game.ObjectsById[5].minigame.goodsById.length;i++){
     dollarsInStockMarket += Game.ObjectsById[5].minigame.getGoodPrice(Game.ObjectsById[5].minigame.goodsById[i])
}
Return dollarsInStockMarket*$unbuffedCPS$; // couldn't figure out how to get unbuffed CPS
}
`

**Comment by Aktanusa** [comment]
Thanks for the heads up.  I am planning on making time to do some fixes.
