### ISSUE TITLE
[v2.029] Colour coding stuck on one building

### ISSUE THREAD

**Issue by FWDekker** [Aktanusa/CookieMonster#306]
The colour coding for which buildings/upgrades to buy keeps suggesting that Chancemakers are the best building to buy, but now I have 115 more Chancemakers than I have Javascript consoles, which can't possible be right. See the image.
![List of buildings to buy](https://user-images.githubusercontent.com/13442533/91618832-c26ef900-e98b-11ea-82b2-1159ce408d80.png)

I cheated my way towards buying 100 more Chancemakers, and Cookie Monster still suggests buying more. Reloading the page or importing the save in another browser does not resolve the issue. I suspect it's an issue with my particular save, as ascending seems to resolve the issue (at least temporarily). See also [buggy-save.txt](https://github.com/Aktanusa/CookieMonster/files/5144339/buggy-save.txt).

**Comment by Aktanusa** [comment]
It's probably due to the fact CM isn't updated to support the latest version yet.  Sorry, but you will have to wait.

**Comment by asimovitsch** [comment]
yeah, this is exactly the result of https://github.com/Aktanusa/CookieMonster/issues/302. @FWDekker there is also a temporary workaround in this link.

**Comment by FWDekker** [comment]
I'm fine with waiting, just wanted to make sure it was known. Thanks for the link, @asimovitsch.

**Comment by FWDekker** [comment]
This bug is also caused by the _Milkhelp lactose intolerance relief tables_ prestige upgrade. You can remove the upgrade using `Game.PrestigeUpgrades[85].lose()`.

**Comment by FWDekker** [comment]
I'll close this issue because it is basically a duplicate of #302.
