### ISSUE TITLE
[v2.029] There's a new Heart Biscuit that CM doesn't yet recognize for Valentines

### ISSUE THREAD

**Issue by Kidsheldon** [Aktanusa/CookieMonster#308]
![image](https://user-images.githubusercontent.com/17099837/91781824-4eba2f80-ebc9-11ea-8e93-c708ce416c3e.png)

**Comment by DanielNoord** [comment]
We will now use #317 to discuss any missing upgrades or items as a result of CookieMonster not being updated for CookeClicker 2.031.
