### ISSUE TITLE
Feature Request: Show a browser notification on golden cookie or reindeer

### ISSUE THREAD

**Issue by PurpleMyst** [Aktanusa/CookieMonster#313]
Per the title, when a golden cookie or a reindeer appears, CM could show a browser notification to allow clicking on it to be brought to the tab immediately.

**Comment by PurpleMyst** [comment]
I'd be willing to undertake this if you're okay with the feature.

**Comment by Aktanusa** [comment]
Sorry for the late response.  Sure!  That be a great feature!

**Comment by DanielNoord** [comment]
This has now been added to the dev-branch!
