### ISSUE TITLE
Add a "stop mod" and "restart mod" button

### ISSUE THREAD

**Issue by chivracq** [Aktanusa/CookieMonster#32]
Hi Aktanusa,

Nice Add-on for CookieClicker, CookieMonster BTW, thanks a lot...

I like your Add-on for the Stats and the Calculations (especially for how many Cookies to keep like the ""Lucky!" Cookies Required (Frenzy) : 52.989 Sext" (even if I think the Calculation might be wrong...), but your Add-on when loaded sucks about 30% of the Resources of the JS Engine on FF or PM (Pale Moon).

And the only way to get rid of it is to save and then reload the Game and start all my other Scripts running on the Game... (1 .js Script and 1 iMacros Script on the CookieClicker Page, + other iMacros Scripts running on other Pages running each in different Browser (=PM) Instances.)
=> So I miss an easy 'Kill me' Button (from the CC 'Menu' Page)...
=> As well as an easy way to land on your GitHub Repository (Forum), instead of having to google "CookieMonster"...

The other .js Script I use (not really public, made by a Friend, I first need to check with him if that Info can be disclosed...) has a RealTime CPS Calculator, and CPS go down instantly from Max 100cps to Max 60cps (hum => 40% JS Engine "Suck" actually) as soon as CookieMonster is loaded...
This Friend of mine has already implemented a few things that are on your Requests List (like Buying the Most Profitable Building) and he found a few flaws in your Code, you might be interested to get in contact if he agrees... (but he doesn't really want to go public...)

(Your 'Next Cookie' and 'Next Reindeer' Time Calculations are always wrong BTW...)

(Using CookieMonster v.0466 (+v.0465) on Pale Moon v.24.6.2 (=FF31), Win7-64. + CookieMonster running from your Server, latest Version I reckon, even if it's difficult to find the Version...)

**Comment by TakGalaman** [comment]
I think if there are actionable pieces in here they should be split into their own suggestions, or this whole thing should be closed since this is quite old and quite verbose.

**Comment by chivracq** [comment]
> I think if there are actionable pieces in here they should be split into their own suggestions, or this whole thing should be closed since this is quite old and quite verbose.
Euh..., yep you're right, and that was actually my "Intention" indeed as well, hum..., 3 years ago already...!?, but I never took the time/courage to open the separate Threads...

Original Thread was about the "'Kill me' Button" (or 'Pause'), that I still miss (sometimes, ah-ah...!), while running now (Septb 2017) CC v2.0042 + running the corresponding Cookie Monster Version from your Server directly.
(With 18,000 Buildings (1350 Cursors - 1088 Chancemakers), 2 10^40 Tredec Cookies (=2 10^82 Cookies) in Bank, 1.3048378574739092e+32 Tredec (=1.3,048,378,574,739,092e+74) per Second.)
Legacy started : 1160 days, 3 hours, 44 minutes, 6 seconds ago, with 23 ascensions
Run started : 159 days, 0 hours, 57 minutes, 25 seconds ago (Running 24/7)
Buildings owned : 18,000

I would say, if you want to keep this current Thread open, only focus on the 'Kill me' Functionality if it will be implemented one day, all other Items could/should become separate Threads, but I've been living already 3 years without the 'Kill me' Button, so I'm not dieing for it, ah-ah...!, and I can understand if you simply want to close the Thread, no problem...

And I still love Cookie Monster, ah-ah...!
