### ISSUE TITLE
Feature Request: Sort Buildings/Upgrades by Payback Period

### ISSUE THREAD

**Issue by abednego** [Aktanusa/CookieMonster#320]
(Sorry if this is the wrong way to use Github.)

I'd like to be able to sort (separately if possible) Buildings and Upgrades by payback period.  It would minimize a lot of the scrolling around I have to do to select the next thing to purchase.

If this is already available and I missed it my apologies!

Thank you for this addon.  Love it!

**Comment by patricksjackson** [comment]
#253 implements this functionality but hasn't been merged. Hopefully that can be merged in after some more people are added to help out with maintaining this project (#315)

**Comment by bitsandbytes1708** [comment]
@patricksjackson Aktanusa should add me and DanielNoord as collaborators soon, I think #253 will be one of the first that I look at.

**Comment by bitsandbytes1708** [comment]
We have merged #253 into the dev branch, and it should be merged into Master very soon(today or tomorrow). I'll close this issue when that happens.

**Comment by bitsandbytes1708** [comment]
Now it has been merged! To activate sorting by PP, go to Options --> Cookie Monster Goodies --> Bars/Colors then toggle Sort Buildings.

**Comment by patricksjackson** [comment]
Awesome! Thanks

**Comment by bitsandbytes1708** [comment]
You're welcome!

**Comment by haninouya** [comment]
Hi, i know it's closed, but is it possible to recalculate and reorder if I want to build 10 or 100 buildings, currently it's just working for 1 building. The list doesn't reorder if I want build 10 or 100 at once.
