### ISSUE TITLE
Development bookmarklet doesn't work in Chrome or Internet Explorer.

### ISSUE THREAD

**Issue by AndrioCelos** [Aktanusa/CookieMonster#33]
Apparently, due to the way Github serves the script file, Cookie Monster is failing to load via that file.
The following appears in the console in Chrome:
`Refused to execte script from https://raw.githubusercontent.com/Aktanusa/CookieMonster/dev/CookieMonster.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`

**Comment by Aktanusa** [comment]
A solution is to use rawgit.com instead.  Since not meany people will be using dev branch, I think this will be fine.

**Comment by Aktanusa** [comment]
I've changed the README to point to rawgit now.
