### ISSUE TITLE
Add Conjure Baked Goods to Stats overview

### ISSUE THREAD

**Issue by DanielNoord** [Aktanusa/CookieMonster#333]
With update to 2.031.1 #321 became obsolete.
However, it built upon #316 and additional commits.

The dev branch now has an option to add an "Conjure Baked Goods" warning.
Furthermore, I have rewritten most of the warning-code to be more accessible for any future warnings.

Only thing left is to add this to the stats overview.
I will get to this when I have time.

**Comment by Michiocre** [comment]
Really appreciate someone is still working on this. Keep up the good work 😄

**Comment by DanielNoord** [comment]
:)

I hope others will start working on this as well, now that we are making a real effort with responding to issues and PR's.
There are more than 100 issues still open, most of which are unimplemented enhancements.
So whoever is looking for a nice and easy javascript project should be able to find something!

**Comment by DanielNoord** [comment]
With #334 this has been added to the dev branch.
