### ISSUE TITLE
"Time Left" Calculation doesn't factor in wrinkler bonuses.

### ISSUE THREAD

**Issue by cekstedt** [Aktanusa/CookieMonster#34]
The "Time Left" calculations in building and upgrade tooltips seem to just be based on the current, fully-withered, cps. This just makes things look like they would take up to twelve times longer to buy. Would it be possible to toggle the calculations to be based on cookie bank + potential popped wrinklers in addition to just bank?

**Comment by Aktanusa** [comment]
Finally added in Version 2.5!
