### ISSUE TITLE
Cookie Monster not loading at all

### ISSUE THREAD

**Issue by wmcelheney** [Aktanusa/CookieMonster#342]
Earlier today, everything worked fine. I don't know if it has to do with the new update. But I just pulled CC back up and hitting my CM bookmark did nothing. I tried removing the "javascript:" text as suggested, still didn't work. I double checked I had the correct js function in the bookmark, and I did, as it worked fine up until 20 minutes ago.

I also tried using the 'dev' code provided and it didn't pull anything up either.

Not sure what to try at this point. any help would be great

**Comment by c-kirkeby** [comment]
I get the same issue, and receive the error below when loading the mod via a bookmarklet:
```
Loaded the mod https://aktanusa.github.io/CookieMonster/CookieMonster.js, CookieMonster. main.js:1579:12
Loading failed for the <script> with source “https://aktanusa.github.io/CookieMonster/CookieMonster.js”.
```

When I navigate directly to this page, it seems the GH page is non-existent.

**Comment by Aktanusa** [comment]
That was weird, but GitHub Pages was disabled.  I've re-enabled it but it may take time for the HTTPS version to work.  It works on HTTP right now, aka [http://aktanusa.github.io/CookieMonster/CookieMonster.js](http://aktanusa.github.io/CookieMonster/CookieMonster.js) works.

**Comment by wmcelheney** [comment]
I tried the HTTP and it still is not loading for me.

**Comment by wmcelheney** [comment]
i tried the HTTPS, however, and it does work!

**Comment by Aktanusa** [comment]
Yeah, I forced HTTPS now, and it seems to work.  I'll close this for now.
