### ISSUE TITLE
Dragon Auras are not computed correctly

### ISSUE THREAD

**Issue by Chorizorro** [Aktanusa/CookieMonster#347]
While working on #305 , I noticed a strange behaviour on Chocolate Egg Cookies value, leading to incorrect simulated value.

This is most likely caused by the "Reality bending" Krumblor aura not being handled properly while simulating building selling in `CM.Sim.BuildingSell`.

I think I'll be able to look a bit further into this issue in the next days.

---

<details><summary><strong>Test save for import (click to expand)</strong></summary>
Mi4wMzF8fDE2MDQ0OTQ4MzM0MDU7MTU5OTE2NTg3MDY1ODsxNjA2MzEwMTU2MDA1O0Nob3Jpem9ycm8gdGVzdDtjZ2xxaXwwMTExMTAwMTAxMDEwMDEwMDEwMTB8MS4xMjIxMDg0MzczNjA1NzU2ZSs1MzsyLjk2NTM4ODg0ODY3MDQ0OWUrNTM7MjI0NzU7MTI4NzE7MS44NTcxNjYwMjE1NzY3MzQ0ZSs1Mzs2NTU1OzA7MDsyLjU5MzQzNTkwNTc0NzA3NzdlKzUxOzA7MTswOzA7LTE7MTAyOzQwNTQ7OC40MTU4NDI4ODMwODY1MDRlKzQ4OzExNzsxNDsyMDstMTs0OzswOzA7MTM3MzkxMDcwMTkxNzI7MTE1NTIyNTY4MzEwODA7MjE4Njg1MDE4ODA5MjswOzA7MDsxOzI7Mzs0OzI1OzE7MjswOzUwOzA7MDs2OzE1MTsxNjA2MjM4NjI5NDUyOzA7MTsxMjksMjI3OzQxOzE7MTs3LjgwNTk0MTQwMTg3NTg4NmUrNDQ7fDgzMCwxNDgxLDYuODgxOTY0MTI4MjY5NDY1ZSs0OSw3LCwwLDgzMDs4MTAsMTE2MCw2LjEwODI5MDE4Njk2MzIyZSs0OSwxLCwwLDgxMDs3NTAsMTEwMCwyLjM3NzY5NzMxNjUyMjU5OTRlKzQ2LDEwLDE2MDYzMTAyMTU5NTQ6MjoxNjA2MzEwNzE0MjYyOjA6OTA2OjMxMTk6MTo0OjE2MDQ0OTQ4MzM0MTg6IDExMTExMDEwMDExMTExMDAwMDEwMDAwMTEwMDAwMDAwMDAgMzoxOjA6MDozOjA6MDowOjM6MDowOjA6MzoxOjA6MDozOjA6MDowOjM6MDowOjA6MzoxOjM6MDozOjA6MDowOjM6MDowOjA6MzoxOjA6MDozOjA6MDowOjM6MDowOjA6MzowOjA6MDozOjA6MDowOjM6MDowOjA6MzowOjA6MDozOjA6MDowOjM6MDowOjA6LDAsNzUwOzc1MCwxMTAwLDEuOTQ4MTcxMzI4NDc5OTg4ZSs0OCwwLCwxLDc1MDs3MjAsMTA3MCwyLjUyMTYyMDEwNTg4MzgxMzhlKzQ3LDAsLDEsNzIwOzcxMCwxMDYwLDUuNDM4ODc0NjgxOTU1ODNlKzQ2LDEsMjoyODoxOjk4MTc4Ny4zNTAwOTUwNzA0OjA6IDI0MzA6NTo4NDo1MDowOjA6MiE2MDc6MjotMjg6NTI3OjA6MDoyITg2MDoyOi0zNjoxMDA6MDowOjIhMzg0MDo1OjIwOjU0OjA6MDoyITY4NDE6MTo1NDo3MjowOjA6MiE2MTEzOjA6MTY6MTc2OjA6MDoyITQ1NTM6MjotNDE6NDU1OjA6MDoyITgxMDk6NTo2NzoxNjA6MDowOjIhOTkxNjoxOjE2OjMyNzowOjA6MiE5Njk1OjA6LTEyOjU3MjowOjA6MiExMTMxOTo1OjI6MjM0OjA6MDoyITI1MTU6NDotMTkyOjM2MzowOjA6MiE1MTMzOjQ6LTIyNDo2Mjg6MDowOjIhMTIxMDU6MjotNDE6MTI5OjA6MDoyITE1MDU4OjA6LTEwOjc5NzowOjA6MiExNDQyOTo1Oi0yODo0OTU6MDowOjAhIDEsMCw3MTA7NzAwLDEwNTAsMi40NTA1MDMyMDQxNjQ3ODI0ZSs0NywxLDEwLzgvNiAzIDE2MDQ5MjAwMzk1NTIgMSwwLDcwMDs2ODAsMTY3MCw3LjE2Nzg1NTAxNzE0MzE5OGUrNDYsMTAsMTEzIDIwOCAxMTI0IDEsMCw2ODA7NjQwLDk5MCwxLjkwODYwNDgzMDY4MjM1OGUrNDYsMCwsMSw2NDA7NjMwLDk4MSwxLjAwODEyMDEzNzY2MjM4OTZlKzQ3LDEsLDEsNjMwOzY0MCw5OTAsMS41MTI2MTE2NDM3MDIzNTMyZSs0OSwxLCwxLDY0MDs2MDAsOTUwLDMuNDA3Mzc0NDI0MDk1ODM2ZSs0OCwwLCwxLDYwMDs2MDAsOTUwLDMuMzc4MzYzNTc3NzU4NzAxZSs0OSwwLCwxLDYwMDs1ODAsOTMwLDEuOTQ0MDIwMDI1NTQ0ODU1N2UrNTAsMCwsMSw1ODA7NTYwLDkxMCw0LjYwNTY3MjI4NzY5NjU1NWUrNTAsMCwsMSw1NjA7NTYwLDkxMCwzLjEzNDY4MjQ5OTg0MDIzM2UrNTEsMCwsMSw1NjA7NTEwLDg2MCw2LjIxMjQ3ODA5MTI5NjY5MWUrNTAsMCwsMSw1MTA7NDkwLDg0NiwyLjQ5MzA2ODE2MDUyMTU5NmUrNTEsMSwsMSw0OTA7fDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMDAxMTExMTEwMDExMTAxMTAwMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDEwMTAxMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTEwMTAxMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMDAwMDAwMDAxMTExMTExMXwxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMDExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMDAwMDEwMDAwMDAxMTEwMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTEwMTExMTEwMTAxMTExMDAwMDAxMDExMDAwMDExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMDAwMDExMTExMTExMTEwMDAxMTEwMTExMTAwMDAwMDAwfHw%3D%21END%21
</details>

**Context + how to reproduce**

To keep the testing as simple as possible, this save doesn't have wrinklers / stock market goods.

The 2 initial auras are not relevant for chocolate egg computation (Dragon Cursor and Breath of Milk).
Here is a simple summary of the chocolate egg simulated value upon aura switch :

| Action | Earth Shatterer | Reality Bending | Sim chocolate egg | Real chocolate egg
| ------------- | ------------- | ------------- | ------------- | ------------- |
| _Initial_ | No  | No | 7.693 Sexdec | 7.793 Sexdec |
| Switch 1 aura to Earth Shatterer from _Initial_ | Yes  | No | 7.693 Sexdec | 7.793 Sexdec |
| Switch 1 aura to Reality Bending from _Initial_ | No | Yes | 7.689 Sexdec | 7.793 Sexdec |
| Switch both auras to Earth Shatterer + Reality Bending from _Initial_ | Yes | Yes | 7.793 Sexdec | 7.793 Sexdec |

The last simulation is the only one correct.
Both initial and switch to ES have the same computed value, whereas switch to RB has a lower value (probably because of the building sold to switch auras).

**Comment by DanielNoord** [comment]
I believe this is similar to the problem @Aktanusa mentions in #266.
Perhaps a general review of the calculation of aura's is needed. I have not looked at that part of the code much since assuming maintainer-ship, so I am not quite sure about the state of it. However, as @Aktanusa mentioned elsewhere, we need to tread carefully here, as it is very easy to make crucial mistakes within the `Sim` code.

**Comment by Chorizorro** [comment]
You're right, this is indeed caused by aura calculations within the `CM.Sim.BuildingSell` method.

I was able to identify 2 issues in it:
- The sell building multiplier (`giveBack`) can be emulated for Earth Shatterer aura only, not for Reality Bending or ES + RB auras;
- The `Game.modifyBuildingPrice` called to calculate the individual selling price of a building uses the "Fierce Hoarder" aura multiplier in its calculations, which is wrong unless the player's current auras are Reality Bending + anything but Fierce Hoarder.
The first issue is quite simple to solve, however the second one is way more tricky. I've been finally able to have the correct choco egg value by hardcoding values to bypass the Fierce Hoarder aura problem in my test case, but I'll need to work a bit more on it to find a generic and elegant way to have these calculations right in any case.

As per the `Sim` code, I am well aware of how critical it is to the whole plugin.
You (and @Aktanusa ) may be reassured to know that I took the time to fully understand the `CM.Sim.BuildingSell` method before making any changes (mostly by comparing it with the game's `Game.Object.sell` method on which this sim is based) 😉

I'll keep on working on this issue tomorrow!

**Comment by Chorizorro** [comment]
It has been a bit more complicated than I thought, but it should be OK now.

However, you might want to rename the issue as it doesn't solve any other issue that could be related to dragon auras, sadly.

**Comment by DanielNoord** [comment]
I will take a look a your fix in a minute and then use it check all other auras to fully squash this issue.
Thanks for your hard work!

**Comment by DanielNoord** [comment]
I have gone through `CM.Sim.CalculateGains` and all functions and variables it calls.
I have not found any other mistakes other than the ones fixed in #361, and are therefore closing this issue.

**Comment by Aktanusa** [comment]
Thanks for the hard work both of you!
