### ISSUE TITLE
Doesn't work in Edge

### ISSUE THREAD

**Issue by bitsandbytes1708** [Aktanusa/CookieMonster#348]
According to several people on the reddit update announcement, this latest update has made Cookie Monster stop working on Edge. I looked through the code, but didn't find anything that would stop it from working on Edge.

**Comment by DanielNoord** [comment]
Have you tested it in Edge?
There seemed to be a problem with GitHub Pages yesterday, but this has now been resolved and I saw most people on the reddit mention that the mod worked again.

**Comment by bitsandbytes1708** [comment]
Yes, people said that it works, but I'm still getting complaints about Edge specifically, saying that it works in other browsers but not Edge.

**Comment by DanielNoord** [comment]
I am not in possession of a windows computer so I can't test this.
Can you? Or somebody else?

**Comment by bitsandbytes1708** [comment]
@DanielNoord I do not currently have access to a Windows computer, but I will in ~1 hour. In the meantime, I edited the post asking for someone to post the console error they're getting...hopefully someone will, but if not, I can look at it soon.

**Comment by Chorizorro** [comment]
I just checked it, everything seems to be working fine on my end (both for a new game and for my actual current game).

**My Edge version:**
Microsoft Edge 44.19041.423.0
Microsoft EdgeHTML 18.19041

**Comment by bitsandbytes1708** [comment]
@Chorizorro Huh, ok. Although that does look like a slightly outdated version of Edge, you're probably right if it works. I guess I'll close this issue for now, might open it up later if it's messing up on the latest version.

**Comment by Chorizorro** [comment]
@bitsandbytes1708 Haha you're right, it was really outdated.
After updating Edge to the latest version (Version 87.0.664.47), everything still works fine in both case.

**Comment by DanielNoord** [comment]
Then I am closing the issue.
If the reddit-user comes back with a more specific issue we can open a new issue.
