### ISSUE TITLE
Maximize garden income

### ISSUE THREAD

**Issue by BigAl2357** [Aktanusa/CookieMonster#358]
Looking for something that calculates the amount in cookies need in your bank in order to maximize income from the garden.  There could be separate calculations for a garden full of queenbeets, duketakers, or bakeberries.  I know there a lot of variables with this based on the combinations of buffs stacked with a frenzy (another cookie boost, shimmering veil, golden switch, pawn shop loan).  I'm thinking there could be a value calculated for the amount necessary to have in the bank to maximize income from harvesting a full garden based on
1.  the current cps,
2.  the current cps plus all possible buffs you can control (shimmering veil, golden switch, pawn shop loan - I'm not sure the pawn shop loan will result in a larger amount given the cost)
3.  the theoretical max cps based on all possible stacked buffs (frenzy + whichever other buff maximizes cps + the buffs above)

This would result in 9 calculations with each outcome for each type of plant.

**Comment by DanielNoord** [comment]
I am not really sure what you want us to add. Could you please explain a little bit more?
If I understand it correctly you want us to calculate the amount of cookies needed in the bank to satisfy the requirement for the highest reward possible for harvesting, for example, queen beets (+ 1 hour of CPS, with a cap of max 4% of bank).
Is that correct?

If the above is true I am not sure we can implement this completely as there are so many variables that need to be included in calculating the max possible cps. We could certainly take a look though!

**Comment by BigAl2357** [comment]
Your description is correct.  Of the 3 situations I described, I figured the second one would be like the calculation for the chocolate egg since that number is based on the player taking several steps to maximize income.  In this case, instead of selling all buildings, etc., it would include activating the shimmering veil, golden switch, which soil type (clay with bakeberries but woodchips with queenbeets), and possibly one of the pawn shop loans.

For the third situation, I'm thinking there is a way to determine which building special (or elder frenzy) stacked on top of a frenzy plus the items above would give the highest cps since those are a set percentage based on the number of each building owned.

Thanks for taking a look at this.  For those of us at the end game, it would really help.

**Comment by DanielNoord** [comment]
This has been implemented to some degree and can now be seen in the statistics section. I am hesitant to add any extra "configuration" as it would clutter that section (similar to how the "Lucky" and "Chain Cookies" sections are cluttered).
Additional configurations could be added, but I'll do those if they are requested and if they are feasible. Adding them for every configuration possible sadly is not.
