### ISSUE TITLE
Make 'Seconds till autosave' more precise

### ISSUE THREAD

**Issue by DanielNoord** [Aktanusa/CookieMonster#375]
#374 adds the functionality of a countdown until the next autosave.
However, sometimes it hangs and does not display the next second (ie., 34, 33, ..., 31).
After some testing, I believe this is due to the CM.Loop not being called in that specific second (in the example the 32st).
Therefore the StatsMenu does not get updated, even though the user might have selected `CM.Config.UpStats` to be 1 second.

For now, I have added the non-optimal feature to the dev-branch to gage user-feedback and collect ideas and possible solutions in this topic.
Even if it is not perfect I still think the current feature serves its purpose, but it would be nice if we could find a way to make it seems less "broken" to the unknowing user.

**Comment by DanielNoord** [comment]
https://www.reddit.com/r/CookieClicker/comments/k6aca9/how_to_check_when_the_game_auto_saves/

Apparently we can use the stock market tick to display time till autosave? Might be worth investigating!

**Comment by Chorizorro** [comment]
Found the following lines in the stock market minigame code:

```javascript
if (Game.drawT%10==0) {
	// [...] Some irrelevant code
	l('bankNextTick').innerHTML='Next tick in '+Game.sayTime((Game.fps*M.secondsPerTick)-M.tickT+30,-1)+'.';
}
```

I'll see if I can use this to improve the timer.

**Comment by DanielNoord** [comment]
Should I merge my rework of `Disp.js` with the dev-branch so you can work off of it?

**Comment by Chorizorro** [comment]
Yes I think it's a good idea, to avoid merge headaches

**Comment by DanielNoord** [comment]
Hmm I just did but also found a number of bugs I did not find yesterday...
Oh well, that's why we have the dev-branch.

Feel free to report any you see or push PR's that could fix them!

**Comment by Chorizorro** [comment]
I've pushed a PR that:
- fixes an issue breaking the stats menu
- improves the autosave timer

I've used the new game modding API (using hooks) to hook on the "draw" action so that the timer is refreshed more regularly (3 times per second, in the fashion of what is done in the minigames timers).

Because the timer is refreshed in 2 different ways (1 when the whole stats menu is refreshed in `CM.Disp.AddMenuStats`, and one in the hooked `CM.Disp.Draw`), it can still seem clunky sometimes (some seconds being displayed for less than 1 full second), but at least it doesn't skip seconds at all now.

**Comment by DanielNoord** [comment]
This is a very good solution!

I have added some comments. Very minor details, but with the rewrite of `Disp.js` (and hopefully later on all other documents) I think it will be good te be a little bit stricter on the state and organization of our code.
It is quite a mess to get a grasp of initially and making it as organized as possible will go a long way.

**Comment by Chorizorro** [comment]
Thanks! And good job to you for the rewrite, this was pretty much needed!

**Comment by DanielNoord** [comment]
Yeah, it was a much bigger job than I initially anticipated but it is now almost done. Only the stats-page left. 

I found a lot of problems and weird code. I also prepared functions whenever I could for some of the issues I could remember, so it should be much easier and straight-froward in the future to implement stuff related to `CM.Disp`
