### ISSUE TITLE
Lucky/Chain cookies rewards stats are incorrect

### ISSUE THREAD

**Issue by Chorizorro** [Aktanusa/CookieMonster#379]
I was starting to work on #289 when I noticed the displayed rewards for Lucky/Chain cookies in the stats were always a bit lower than what I earned.

After investigating a bit, it looks like the CM calculation doesn't factor in a multiplier gained by some auras / upgrades:

```javascript
var mult=1;
//if (me.wrath>0 && Game.hasAura('Unholy Dominion')) mult*=1.1;
//else if (me.wrath==0 && Game.hasAura('Ancestral Metamorphosis')) mult*=1.1;
if (me.wrath>0) mult*=1+Game.auraMult('Unholy Dominion')*0.1;
else if (me.wrath==0) mult*=1+Game.auraMult('Ancestral Metamorphosis')*0.1;
if (Game.Has('Green yeast digestives')) mult*=1.01;
if (Game.Has('Dragon fang')) mult*=1.03;
if (!me.wrath) mult*=Game.eff('goldenCookieGain');
else mult*=Game.eff('wrathCookieGain');
```

This multiplier is then factored in the cookies earned from Lucky cookies like this:

```javascript
var moni=mult*Math.min(Game.cookies*0.15,Game.cookiesPs*60*15)+13;//add 15% to cookies owned (+13), or 15 minutes of cookie production - whichever is lowest
Game.Earn(moni);
popup='Lucky!<div style="font-size:65%;">+'+Beautify(moni)+' cookies!</div>';
```

**Comment by DanielNoord** [comment]
As always, nice work catching the bug!
Will you fix this with #289? Or would you like to keep the bugs separate?

**Comment by Chorizorro** [comment]
Thank you!
I'll start by fixing this issue (I should be able to push a fix soon) and I'll go back to #289 a bit later, so we can keep them separated

**Comment by DanielNoord** [comment]
Okay!
By the way, as the number of issues for the next releases is decreasing it might be good to comment whenever you start on an issue. I, or any of the other maintainers, can then assign you to the issue. That way we don't double work :)

**Comment by Chorizorro** [comment]
Yes that's right, I will do that for the next issues I'll start working on!
