### ISSUE TITLE
Improve buildings "Production left till next achievement" refresh rate

### ISSUE THREAD

**Issue by Chorizorro** [Aktanusa/CookieMonster#389]
From #89 

The refresh rate of the game's building total production counter is way higher than the refresh rate for "Production left till next achievement".

It may be good to have a refresh rate similar (or closer at least) to the production counter.

**Comment by Chorizorro** [comment]
@DanielNoord Well I don't know if I've messed something up during my first test (browser lagging?), but it looks like the refresh rate for "Production left till next achievement" is OK (it's even higher than the game's production counter), so this issue doesn't need to be addressed.

Can you check it and tell me if the "Production left till next achievement" refresh rate is also good on your side?

**Comment by DanielNoord** [comment]
I didn't see any problems during testing. Guess it might be fine then? Could also be due to lagging because of "showing missing upgrades", see #386

**Comment by Chorizorro** [comment]
Definitely looks fine to me!
Yup maybe it's because of #386, or maybe it's because I had too many tabs opened!

I'm closing this.
