### ISSUE TITLE
Indicate in the title bar whether it is a golden or a wrath cookie

### ISSUE THREAD

**Issue by louiswins** [Aktanusa/CookieMonster#39]
I often stop buying research center upgrades right before Elder Pact so that I can still get golden cookies. I like the title bar countdown timer, but I would like it even more if it told me whether it was a golden cookie or a wrath cookie that was active.

It looks easy to do, since `Game.goldenCookie` has a `wrath` member that you can switch on.

**Comment by Aktanusa** [comment]
Yep, it should be easy to do, I'm guessing G for Golden and W for Wrath should be fine?

**Comment by Aktanusa** [comment]
Added in Version 1.0466.2
