### ISSUE TITLE
Possibilty to choose decimal and thousands separators

### ISSUE THREAD

**Issue by RaydenX93** [Aktanusa/CookieMonster#392]
Would it be possible to customize the separators for decimal and thousands?
I'm italian and here we use comma as decimal separator and point as thousands separator.

**Comment by DanielNoord** [comment]
I will take a look at this for the next release.
However, I can not promise anything. I think the separators are determined by the browser/language of the browser so I am not sure if we can change anything about this.

Anyway, I will let you know via this issue after seeing what we can do!

**Comment by RaydenX93** [comment]
I'm not sure I understand what you mean but my browser is set to italian but I'm still getting non - italian separators. 
If it is easier you could make 2 text boxes in which you specify the two separators you want,without considering any regional setting of the browser

**Comment by DanielNoord** [comment]
I must confess I don't really know how HTML/CSS/JavaScript handle separators.
On the top of my head I would say that we currently don't specify what spectators to use (thus leaving that to either the browser or one of the coding languages). 

But this does not mean that we can not force a type of separator and include this as a setting.
I will have to look more carefully into to this.

I hope to find a fix! _in bocca luco_ :)

**Comment by Chorizorro** [comment]
As far as I know, in Javascript, as long as `Number.toLocaleString` (or any other formatting method) method is not called, the default number format (`.` as decimal separator, no thousands separator) is used in any browser. 
As we're not using this method anywhere in CM, the only formatting method in effect is `CM.Disp.Beautify` so it shouldn't be too hard to enable separators customization, I suppose!
