### ISSUE TITLE
Game freezes when I use the script

### ISSUE THREAD

**Issue by hr24** [Aktanusa/CookieMonster#40]
Hi, I follow all the steps as outlined on the Wiki and whenever I click the bookmark the game freezes. I have tried both scripts in the Wiki and also tried adding the userscript. As soon as the script is enabled the game freezes.

I am using Google Chrome version 43.0.2357.124 m

Any ideas?

Thanks.

**Comment by Aktanusa** [comment]
Are you playing on Live or Beta?  When you said you tried both, both meaning Live and Beta, or both meaning Live and Dev?

**Comment by hr24** [comment]
Sorry, I meant Live and dev.

**Comment by Aktanusa** [comment]
And you are playing on Live or Beta?

**Comment by hr24** [comment]
Playing on Live

**Comment by Aktanusa** [comment]
Can you give me your save?

**Comment by Aktanusa** [comment]
Heck, you can try the simple, thing of exporting the save, then importing it again and try the addon again.

**Comment by hr24** [comment]
OK just tried exporting then importing. Same result. Would you like me to post my save data?

**Comment by Aktanusa** [comment]
Yep

**Comment by Aktanusa** [comment]
I may not have time until later to look at it though

**Comment by hr24** [comment]
MS4wNDY2fHwxNDMzODQ3MDM0NTEzOzE0MzM4NDcwMzQ1MTM7MTQzNDAzNDEwNDc2NztCZWFyZGVkIEdpem1vfDExMTExMTAxMTAwfDEyMzA2MTIwMTY3OC42OTMxNjsyMjcwMDk2NTY4MTcwNi40MTsxMjEyNjsxNDsxNDE4Mzg2MjA2MDI0LjcxMDI7Mjc4Oy0xOy0xOzA7MTswOzA7NzE7NDg4MzQ7MDsxNDsxNzkwMjE2NjYyMDIuMDk4MTg7MTk7MDswOzA7MDs7NTExNjkxNTQ4NDsxO3wxMDMsMTAzLDMwNjkzMjE3OTI5LDA7MTAxLDEwMSwyNTA3Nzk3MDc3MzgsMDsxMDIsMTAyLDEyMjY3ODc5MzgsMDsxMDAsMTAwLDI5NDkzODA0OTgsMDsxMDAsMTAwLDEwMjIxOTQ4NTUxLDA7MTAwLDEwMCwyMzAwMjE1NzUzOSwwOzEwMCwxMDAsMjg5MjkwNDgwMjcsMDs4MCw4MCwzOTc4MDA4Mjc1OTYsMDs1OCw1OCwyNTY2MDQ3MTk1NTMyLDA7MzYsMzYsNTE4NzkwMzk4NTU5NiwwOzE5LDE5LDExOTk4NDg3MzEwNjI3LDA7fDQ1MDM1OTk2MjczNDU5MTk7NDUwMzE4NzMxMDUxMDA3OTsyMjYwNTk1OTA2NzA2MDQ3OzM5NDA2NTI0OTI1MzIyMjM7MjI1MjM1ODE1NzM4MDQ5NTsyMjUxNzk5ODEzNjg1MjQ5OzIyNTE3OTk4MTM2ODUyNDk7MjI1MTc5OTgxMzY4NzM0MzsyMjUxNzk5ODEzNjg1MjQ5OzMyNzY5fDQ1MDE5NDgyNDU4ODQ5Mjc7MjI1MjA5NjI5MzA5MTMyNzsyMjUxODE3MDEwMzMxNzQ3OzQxOTQzMDU%3D%21END%21

**Comment by hr24** [comment]
That's fine, it's bedtime in my timezone!
Thanks for looking

**Comment by Aktanusa** [comment]
Hmm, works fine here... and I'm on the same version of Chrome

**Comment by Aktanusa** [comment]
Do you have temples in your game?

**Comment by hr24** [comment]
Temples?

**Comment by Aktanusa** [comment]
Just making sure you really are on live... sorry =p

**Comment by hr24** [comment]
Ha. Could there be other settings within Chrome that would cause Cookie Monster to not work?

**Comment by Aktanusa** [comment]
Yes, like no script.  Try with no extensions.

**Comment by hr24** [comment]
I found it, I had an old extension of a similar app to yours when I was playing a long time ago. It was running, but obviously not working. Sorry that the issue was mine, and thanks for your help.

**Comment by Aktanusa** [comment]
No problem, glad to be of help
