### ISSUE TITLE
All calculations are off when a golden cookie appears

### ISSUE THREAD

**Issue by DanielNoord** [Aktanusa/CookieMonster#400]
There is something going wrong with all calculations whenever a golden cookie appears on screen.
I had not time to investigate but this is a pretty important bug so should be fixed asap.

Perhaps @Chorizorro knows if something changed with the general calculations after the we merged the changes related to the Lucky/Chain calculations when cookies appear?

I made a new branch `fix/gcbug` where a hotfix to this issue should be applied to.

**Comment by Chorizorro** [comment]
I couldn't reproduce any bug of the sort on the current `master` or `dev` branches.

By any chance, are you talking about the "production" one? As the `gh-pages` branch hasn't been updated with the 2.031.2 commits, this would be normal.
If not, could you please send me your save file so that I can investigate the bug?

**Comment by DanielNoord** [comment]
Hm, this is really weird I can't seem to produce it myself too.
Perhaps I left some old code running from an older debugging process which made the calculations incorrect.

However, on line 1299 of `CookieMonster.js` I did actually find a bug.
The code refers to `um` there, which should be `num`. This breaks the Engineering notation.
I have to go away now so I won't be able to fix this just now, but this should be fixed before #396 is merged

**Comment by Chorizorro** [comment]
Let's hope it was some debugging artefacts then! I'll keep an eye on this during my "real" game to make sure there is no bug.
I've fixed the `um` thing and created a PR for `master` but I don't even know if this is the way to fix it (+ this will need to address it in the `dev` branch as well)

**Comment by DanielNoord** [comment]
This is fine! I will merge your request and then re-base the dev branch to master.
Thanks for your help!
