### ISSUE TITLE
Automatic Save Export

### ISSUE THREAD

**Issue by RaydenX93** [Aktanusa/CookieMonster#403]
Hello,
I came up with an idea for a new feature. Hopefully, it can be implemented.

I believe it could be nice to have an automatic save export option that would automatically backup my game in a specified folder on my compter every X time (I'd save it in my OneDrive folder, for example).

Keep up the great work!

**Comment by DanielNoord** [comment]
Hi,
Thanks for your suggestion! I do not know at this time if we will add it but we will certainly consider it!

**Comment by DanielNoord** [comment]
Sadly, this is not something we are likely to add. This not something for which such a basic Javascript mod as CookieMonster is best suited. If you have any experience with Javascript you might want to have a look at [FileSaver.js](https://github.com/eligrey/FileSaver.js) and see if you can create your own script.
Sorry for disappointing you!
