### ISSUE TITLE
Coockie Monster not compatible with the HTTPS version of Cookie Clicker

### ISSUE THREAD

**Issue by Toncino** [Aktanusa/CookieMonster#404]
Hi all, not sure if this only a problem I have, but if I load the HTTPS of Cookie Clicker, the Cookie Monster addon is not loaded.
Is this a know issue or just something I do wrong?

Thanks in advance

**Comment by DanielNoord** [comment]
We have experienced some issues with HTTPS and GitHub Pages after previous updates.
What link are you using?
When I load https://aktanusa.github.io/CookieMonster/CookieMonster.js the code does show for me.

**Comment by Toncino** [comment]
My bad, I was loading the HTTP rather than the HTTPS version of the mod, now everything works as intended! Thanks a lot!
