### ISSUE TITLE
Negative PP registering as best

### ISSUE THREAD

**Issue by bitsandbytes1708** [Aktanusa/CookieMonster#406]
Not sure why this is happening, but negative PP buildings are showing up as the best instead of worse.

**Comment by DanielNoord** [comment]
Can you share the save?
How is a building on negative pp anyway?

**Comment by bitsandbytes1708** [comment]
I'm not sure why a building is negative PP...but I just tested it on dev, and the issue is gone. Oops :). I guess I'll close the issue now.

**Comment by DanielNoord** [comment]
Hmm, no leave it open because the dev-branch is quite far from being published (the CM.Disp rework is taking quite a bit of time).
The mod shouldn't even produce negative values. So this is weird. Please do share the save file!

**Comment by bitsandbytes1708** [comment]
Ok, here it is Mi4wMzF8fDE2MDIyNTgyNzg3NTE7MTYwMjI1ODI3ODg4NzsxNjA3MDk5MTkwMTYwO0dhYnJpZWw7ZGF4Z2l8MTExMTEwMDExMDAxMDAxMDAxMDEwfDI4NjU0ODA2NzgyODUyMi40NDszMDExNzg0NDg3MTAwMDM1OzE5MjEwMjs1MDk7MTAzNjk2MTY3MzkxMTIxOS45OzE2MzswOzA7MDswOzA7MDswOy0xOzA7NTA5OzA7MDswOzA7MDswOzswOzA7MDswOzA7MDswOy0xOy0xOy0xOy0xOy0xOzA7MDswOzA7NTA7MDswOzE7NTY7MTYwNzA4Mzc1NDYyNDswOzA7OzQxOzA7MDs5OTAwMDAwMDAwMDE2NTYuNDt8MTM1LDEzNSwyNDMzMTU4NDAzMzUsMSwsMCwxMzU7MTg4LDE4OSwyMDc3NTUwMzA4NjQwLDgsLDAsMTg4OzE1MCwxNTAsMzIwOTM4NjkxNDQsMywxNjA3MDk5MjIxNTQyOjE6MTYwNjc0ODc0NDUwOTowOjk6OToxOjA6MTYwMjQzMjU3NTAwMDogMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCAwOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjU6MDowOjA6MDowOjA6MDowOjA6MDowOjE6NjM6NDo1MDoxOjYxOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDosMCwxNTA7MTAzLDEwMywxMTgwMzIyNzU5ODIsMiwsMCwxMDM7MTA1LDEwNSw1MzI3NjczMTcwOTQsMSwsMCwxMDU7NjksNjksMTA2MjE2NzUwODE0NywxLDA6MDoxOjA6MTogMzk3OjQ6LTEwMDoyMjc6MDowOjAhNDIyMjoxOjQzOjc2OjA6MDowITUwNDoyOi01Njo0MDE6MDowOjAhNDY3OjQ6LTgyOjU2OjA6MDowITUzMTE6MDo4OjE0OjA6MDowITY0Mzc6MDoxOjEwMTowOjA6MCExODE4OjQ6LTE3Mjo2NDM6MDowOjAhODY5NDo1OjI4OjYzODowOjA6MCE4MjYwOjQ6LTExMDo4MzowOjA6MCE3NDgwOjI6LTQ4OjIzNTowOjA6MCE4ODk5OjI6LTI2OjEyODowOjA6MCE5NjM1OjI6LTQ5OjM2MjowOjE6MCExMjg2MDowOjA6MTc4OjA6MTowITEyMjYzOjI6LTQyOjM1MjowOjE6MCExNTcyNDoxOjIxOjE1MDowOjE6MCExNjc1ODo1Ojc0OjE0NzowOjE6MCEgMCwwLDY5OzYxLDYxLDQyMTE3MjAwODkyNjYsMSwtMS8tMS8tMSAzIDE2MDI2NzYxNzkzMjggMCwwLDYxOzQ4LDQ4LDEwMzUzNjQ2NDQ2MjU5LDEsMzUgMSAxIDAsMCw0ODs0MSw0MSw0NTAyNDUyNDQ4MTA5MCwxLCwwLDQxOzM1LDM1LDE2MzExNDA1OTIyMTIyMiwxLCwwLDM1OzI0LDI0LDI1MDU4MjY1NzY1ODUyMCwxLCwwLDI0OzEyLDEyLDE4ODI5NTY3OTczNjQwNCwxLCwwLDEyOzIsMiw2ODQ4NTk4OTAxNjg5MiwxLCwwLDI7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDt8MTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTEwMDAxMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMDAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMDAxMTEwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTEwMDExMTEwMDAwMDAwMDExMDAxMTExMTAwMDEwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDEwMTAxMDEwMTAwMDExMTExMTExMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDEwMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTAwMDAxMTExMTExMTAwMDAxMTExMTEwMDAwMDAxMTExMTEwMDAwMDAxMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExfDExMTExMTExMTEwMDAwMDAxMTExMTExMTExMDAwMDExMTExMTExMDExMTExMTExMTExMTExMDAxMDAxMDAxMDAwMDAxMTExMTExMTExMTAwMDEwMDAwMDEwMDAwMDEwMDAwMDAxMTAwMTAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMTExMDAwMTEwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMTEwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDB8fA%3D%3D%21END%21

It's the grandma, farm, and cursors that are negative.

**Comment by wschnicke** [comment]
Having a very similar issue on my save

```
Mi4wMzF8fDE2MDY4NDk2MTYzODQ7MTYwNjg0OTYxNjM4NDsxNjA3MDk5Mzg4ODYzO0ZsdWZmaGVhZDt1aWRuYnwwMTExMTAxMTAwMTAwMDExMDExMTB8MzE1MTk4OTg2NDc2MTc4MjAwOzgyMTcwNjk0NzM3OTg4MDgwMDs0Njg4MDs2MDI7MTM0Nzg1Njc0NTc1NzUxNTgwOzI3NDswOzA7MDsxOzA7MDswOy0xOzA7NjAyOzIzNDA3MTM3MTk2OTc0OTA0OzEzOzA7MDswOzA7OzExNTA5NDU5Mzg2NzgyMTE3MDsxMDswOzA7MDswOzA7LTE7LTE7LTE7LTE7LTE7MDswOzA7MDswOzA7MDswOzM7MTYwNzA5NTA4MjcxOTswOzA7OzQxOzA7MDsyNjkzNDQ2NjgwMjc3LjIyNTt8MjIwLDIyMCw1MDAxMjM3ODY1NzA0OTMsMCwsMCwyMjA7MjIwLDIyMSwxMDAzMDU3MzMwMDY5MTIzLDAsLDAsMjIwOzE4MCwxODAsMjgyNTk3ODE0OTkwLDEsMTYwNzA5OTU3NzcyNDowOjE2MDcwOTgwMjEyMDY6MDoyOjI6MTowOjE2MDcwOTUwOTM0NjM6IDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAgMDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDoxOjQ4OjA6MDowOjA6MDowOjA6MDowOjA6MTo2MjowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDosMCwxODA7MTYwLDE2MCw5ODQwMjM3NjI1MjIsMCwsMSwxNjA7MTUwLDE1MCwyMjgzMzc1NDc0MzA4LDAsLDEsMTUwOzEzMCwxMzAsODc2NjIyMzExNjQzNywwLCwwLDEzMDsxMTAsMTEwLDM4MjYyNTI2OTExMjkyLDEsNS8xLzQgMyAxNjA3MDk0MzUzMzg4IDEsMCwxMTA7MTAwLDEwMCw5MDk5MDI4NDc4MzAwNCwxLDQ4LjAyMzY0OTI3MTc1MTAyIDM1IDM1IDEsMCwxMDA7NzAsNzAsMzY1NzM0MTE0MTg4MTc2LDAsLDAsNzA7NTAsNTAsODU5MTA0NDAyNTc5OTQ3LDAsLDAsNTA7NDAsNDAsMzgyNjQ3MTU4NTIyNjkwMywwLCwwLDQwOzM1LDM1LDE1ODQwMjg0ODU1MDMxMTU0LDAsLDEsMzU7MjQsMjQsMzM2NDk4NzI4NjY1Mzk3NDgsMCwsMSwyNDsxNCwxNCwyNjc4NTQ0NDg3ODA2MDg1MCwwLCwwLDE0OzUsNSwyOTYyMzg0MDEwNzgxNDM3NiwwLCwwLDU7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7fDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDExMTExMTExMDAxMTExMDAwMDAwMDAxMTAwMTExMTExMDAxMTAwMDAwMDAwMDAwMDExMTEwMDAwMTExMTExMTExMTExMDAxMTExMTExMTAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMDExMTExMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMTAwMTExMTExMTExMTAwMTExMTExMTExMDAwMTExMTExMDAwMDAwMTAxMDEwMTAxMDEwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMXwxMTExMTExMTExMTAwMDAwMTExMTExMTExMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTEwMTEwMTAwMTAwMDAwMTExMDExMTExMTEwMDAxMDEwMDAxMDAxMDAxMDAwMDAwMTExMDAxMDAwMDAwMDAwMTExMDAwMDAxMDAwMDAwMDAxMTAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDExMTEwMDExMTAwMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwfHw%3D%21END%21
```

**Comment by wschnicke** [comment]
<img width="992" alt="Screen Shot 2020-12-04 at 11 30 35 AM" src="https://user-images.githubusercontent.com/20305277/101188980-708ddd00-3624-11eb-8ff0-1bf2843f982c.png">
Screenshot showing negative values for cursor, grandma, and farm, with grandma highlighted as the best (light blue is best for me)

**Comment by bitsandbytes1708** [comment]
That's weird...if I remove all Baker's wheat from my garden, it goes back to normal.

**Comment by rosenbergj** [comment]
I was also seeing this, and it also got better for me when I cleared my garden (I had 2 chocoroots and nothing else in 12 plots).

**Comment by DanielNoord** [comment]
Based on those two reports I think I know which area of code might create this bug.
Let me see if I can fix this tonight!

**Comment by wschnicke** [comment]
I just tested this as well, and removing Baker's wheat also fixes it for me.

**Comment by DanielNoord** [comment]
This should now be fixed upon reloading the mod.
Please let me know if anything else is broken!
