### ISSUE TITLE
Missed golden cookies

### ISSUE THREAD

**Issue by erriperry** [Aktanusa/CookieMonster#41]
Hi, nice add-on. I only miss one feature: too see how many golden cookies I have missed. You can see it by typing "Game.missedGoldenClicks" (without quotes) in the console. Other add-ons have it so I am sure you could add it too.

**Comment by Aktanusa** [comment]
Ah, so you do already know about that stat command.  I guess I can add it but maybe I'll have it as a setting or hidden as I know my OCD would not be happy with how many I've missed, lol.

**Comment by Aktanusa** [comment]
Finally added thanks to @Alhifar.  Will be released in Version 2.3
