### ISSUE TITLE
Challenge Mode Bonus Income broken

### ISSUE THREAD

**Issue by VincentThierry** [Aktanusa/CookieMonster#414]
![image](https://user-images.githubusercontent.com/47110987/101240292-abf4de00-36ee-11eb-8237-309bb4dfa0e4.png)

**Comment by DanielNoord** [comment]
Could you explain what is wrong? I don't immediately see the bug from this picture.

**Comment by VincentThierry** [comment]
It says that the bonus income is 4138 when purchasing a farm when it is 8 in actuality. Does this for every building.

**Comment by DanielNoord** [comment]
This is because you have selected the "buy 100" mode. 
It is at the top of the building column. If you change this to 1 or 10 you will see that CookieMonster displays the bonus income for purchasing 1 or 10 of a building.

**Comment by VincentThierry** [comment]
The 100x mode is only active because I used the shift key when taking the screenshot. It's still completely wrong in single mode

**Comment by VincentThierry** [comment]
[VincentBakery (2).txt](https://github.com/Aktanusa/CookieMonster/files/5647391/VincentBakery.2.txt)
If you want to take a look for yourself :)

**Comment by DanielNoord** [comment]
Ah okay, my bad! I'm away from my computer right now but if you give me your save I will try to fix this tonight!

**Comment by VincentThierry** [comment]
I think it might not ignore the hc upgrades.

**Comment by VincentThierry** [comment]
Thanks!

**Comment by DanielNoord** [comment]
Could you check if the new version fixed it? I believe it does :)

**Comment by VincentThierry** [comment]
It's fixed, thanks!
