### ISSUE TITLE
displays sell price for building purchase price

### ISSUE THREAD

**Issue by mrooney** [Aktanusa/CookieMonster#416]
Hello there and thanks for this awesome tool! I just noticed that buildings are showing the "sell" price for their "buy" price for some reason. If I load my save in a fresh tab, the numbers match up. As soon as I load Cookie Monster again in that new tab, it goes back to the screenshot where they don't match and it's showing the sell price (and no little cookie icon).
![Screenshot 2020-12-05 084346](https://user-images.githubusercontent.com/123717/101246052-6debc000-36d6-11eb-96a5-a28ba8940824.png)

Sorry if this is some expected behavior / option, I looked through them all and couldn't find it.

**Comment by DanielNoord** [comment]
Could you share your save-file?
I can't seem to reproduce this in my own current save-file. What do you do to before this bug happens? Or does it happen on initialization?

**Comment by mrooney** [comment]
> Could you share your save-file?
> I can't seem to reproduce this in my own current save-file. What do you do to before this bug happens? Or does it happen on initialization?

It happens on initialization for me upon loading Cookie Monster. I can repro in Chrome and Brave with this file, but not a private window in either. So I'm not sure if this means there's some local data / cookie / setting that is impacting it? The Brave was a clean install so the only thing I've done is play Cookie Clicker and configure some Cookie Monster settings on it. Thanks for any help!

[SexyBaobBakery (8).txt](https://github.com/Aktanusa/CookieMonster/files/5647541/SexyBaobBakery.8.txt)

**Comment by DanielNoord** [comment]
Could you try resetting your cookies?
I got the following result with loading the save you provided, which seems fine to me.
Perhaps there is something wrong with any local data. If that is not the case we might need to delve deeper.

<img width="617" alt="Schermafbeelding 2020-12-05 om 23 07 31" src="https://user-images.githubusercontent.com/13665637/101266382-a9c26c00-374e-11eb-9811-4b2d108f78dd.png">

**Comment by mrooney** [comment]
I can reproduce it now in an Private tab:

1. load the save file
2. load Cookie Monster
3. turn Building Colors off

Now the price is wrong and re-enabling building colors doesn't revert it either. Hope this helps!

**Comment by DanielNoord** [comment]
Step 3 seems crucial. I failed to notice it was off in your screenshot.
When I get time today I will look into this and see if I can find the problem/fix!

**Comment by DanielNoord** [comment]
This should now be fixed! Sorry for the inconvenience
