### ISSUE TITLE
confusion by heavenly chips reset bonus income

### ISSUE THREAD

**Issue by 3plus4i** [Aktanusa/CookieMonster#42]
I only (relatively) recently started playing Cookie Clicker (with Cookie Monster, of course). After two weeks and currently about 620Qa CBAT I still haven't reset once, because Cookie Monster told me I would only get a bonus of about 5.6 % from heavenly chips, which really didn't seam to be worth it. Even though I was confused because the general advice was to reset when getting 500 HC and the percentage didn't raise at all even with new heavenly chips, I only just realized, that this only refers to the bonus from **achievements** and not to the bonus gained from the chips themselves!

Even though most people don't seam to have this problem, I'd like to make two suggestions:
 1. Rephrase the tooltip to make it more clear, that only achievements are counted in here.
 2. Add a calculation of how much bonus the new heavenly chips will give as a percentage of the current CpS. Since it doesn't stack with most other bonuses, it's not exactly easy to estimate the actual benefit.

**Comment by Aktanusa** [comment]
Hmm, as far as I know, the bonus from the chips themselves is suppose to be calculated into it also.  I'll check the code.

**Comment by Aktanusa** [comment]
Okay, I see the problem.  You see, as the tooltip says, it only calculates the gain you will get with the same upgrades you have currently bought.  Since you have never resetted, you never bought the upgrades to unlock the chip bonuses (25%, 50%, 75%, 100%) since you can't even buy that until you have at least 1 chip.  Hence the chip bonus is not included in the reset bonus!  Now as to how to fix this, I need to think about it, but I guess the best solution is to always assume you are going to buy the upgrades to enable the chip bonus.

**Comment by 3plus4i** [comment]
So it **is** supposed to show the actual bonus including everything.
> Since you have never resetted, you never bought the upgrades to unlock the chip bonuses (25%, 50%, 75%, 100%) since you can't even buy that until you have at least 1 chip. Hence the chip bonus is not included in the reset bonus!

Ah, I didn't even think about this possibility.

> but I guess the best solution is to always assume you are going to buy the upgrades to enable the chip bonus.

I totally agree with that. Seams simple and effective.

Oh, an as a side note, it would also make sense to include the cookies stored by wrinklers into the calculation of HC and the bonus.

**Comment by Aktanusa** [comment]
> Oh, an as a side note, it would also make sense to include the cookies stored by wrinklers into the calculation of HC and the bonus.

I guess, since they do auto pop before you reset?  Actually I'm not sure of that.

**Comment by 3plus4i** [comment]
Just discovered, that they actually don't auto pop, at least not in the sense of adding their cookies. Hm, didn't really expect that. In this case it might be confusing or misleading to calculate them in just like that. Now what? The reason why I would like a calculation with wrinklers somewhere is, that I often end up with more cookies stored in wrinklers than I have baked in total. Under these circumstances it makes a big difference in HC whether you count them in or not.

A solution might be, to simply add the number of HC with wrinklers counted in after a slash:
`Heavenly Chips (MAX) : 767/1,088 (1,535%/2,176%)`
The more information the better, isn't it? Well, most of the time at least.

**Comment by Aktanusa** [comment]
Maybe.  I'll think about it.  The info tooltip would need to have a lot more writing, lol.

**Comment by Aktanusa** [comment]
With the way beta is going, this may become a non-issue in the future...

**Comment by Aktanusa** [comment]
Since I've removed HC stats as they are useless now, I'll close this.  Please reopen if you think otherwise.
