### ISSUE TITLE
Negative Bonus Income when golden cookie is on the screen 

### ISSUE THREAD

**Issue by VincentThierry** [Aktanusa/CookieMonster#426]
![image](https://user-images.githubusercontent.com/47110987/101286383-7df4c400-37ea-11eb-8a6c-e2f031b40f3a.png)
My best guess is that Dragon's Fortune is not considered in the calculations

**Comment by DanielNoord** [comment]
Could you provide the save-game? Once again I am sadly unable to reproduce this in my own game.
Is there a difference between cookies between the Grimoire-minigame or the random cookies, or do they all break the calculations?

**Comment by VincentThierry** [comment]
[VincentBakery (6).txt](https://github.com/Aktanusa/CookieMonster/files/5649373/VincentBakery.6.txt)
Haven't tried it with the grimoire minigame. Random cookies break it. I just realized that I wrote Dragon's Fortune, when Reality Bending is probably the cause. (It has 1/10th of the Dragon's Fortune and may not be considered in the calc)

**Comment by DanielNoord** [comment]
That does indeed seem to be the case. I will get back to this as soon as possible, hopefully somewhere tomorrow.
If somebody else could look into this in the meantime, please go ahead!

**Comment by Chorizorro** [comment]
@DanielNoord I'm on it!

**Comment by DanielNoord** [comment]
Thanks to the work of @Chorizorro this should now be fixed :)

**Comment by Chorizorro** [comment]
Good catch btw, this was indeed due to Dragon's Fortune mult from Reality Bending not being calculated properly!
