### ISSUE TITLE
problem with number display

### ISSUE THREAD

**Issue by 3plus4i** [Aktanusa/CookieMonster#43]
When Cookie Monster is active, fractional digits aren't displayed anymore, no matter which format you chose in the options. It doesn' matter at all in the later game play but is pretty adverse at the very beginning.

**Comment by Aktanusa** [comment]
There is an option to turn off Cookie Monster formatting.  It's called "Game's Setting Scale".

**Comment by 3plus4i** [comment]
That's what I meant. At least with choosing said "Game's Setting Scale", fractional digits should be shown, but they aren't; at least with me. Though I think, they should always be shown, no matter which of the options you choose.

Fractional digits are shown, when I deactivate Cookie Monster, just checked to make sure.

**Comment by Aktanusa** [comment]
Hmm, I see.  Well I'm on vacation right now, but I'll look when I get back.  Only thing I can think of is return the old formatting option in CM.  At least I think there is that setting, lol.

**Comment by Aktanusa** [comment]
Whoa it's been a month, and I totally forgot about this.  I'll look at it soon!

**Comment by Aktanusa** [comment]
Okay, I've taken a look at it, and I see the problem.  Will fix shortly!

**Comment by Aktanusa** [comment]
Added in Version 1.0466.2
