### ISSUE TITLE
Please Change Page's FavIcon to Gold Cookie when Gold Cookie Appears

### ISSUE THREAD

**Issue by NickDaly** [Aktanusa/CookieMonster#44]
Hi Aktanusa, it'd be handy if the page's favicon's appearance changed when a gold cookie appeared.  That way, I could see that something was going on even if the tab was pinned (with only the favicon displaying, without showing the page's title).

(In a similar vein: adding an option to only change the page's title when gold cookies appear, so that the pinned tab isn't continuously highlighted, would be nice.)

**Comment by Aktanusa** [comment]
I'm not getting the bottom part.  Does the pinned tab highlight every time the title changes?

**Comment by NickDaly** [comment]
Yes, pinned tabs are highlighted whenever their titles change.

**Comment by Aktanusa** [comment]
Hmm, I wonder if it still highlights when I change the title to the same exact title as before.  Currently it's on a timer to just redo the title from scratch.  This was how it was implemented by Oreil.

**Comment by Aktanusa** [comment]
The Favicon part has been added in Version 2.3, but your second part is not done yet.  I'm not sure I can fix that at all.

**Comment by Aktanusa** [comment]
Doing more research, indeed to stop the highlighting is to change the title back to the same thing.  I guess I could add this feature.

**Comment by Aktanusa** [comment]
Do you want the title to change when a reindeer shows also?

**Comment by NickDaly** [comment]
Reindeer falls under the same category as cookie, so yeah, that makes sense.

**Comment by Aktanusa** [comment]
Well doing a bit more research, it's still iffy it I can do your second request.  I'll let you know when I've figured out if I can do it or not.

**Comment by Aktanusa** [comment]
2nd part finally added in Version 2.5
