### ISSUE TITLE
Feature Request: UI tweaks in the Notification section of CM Settings

### ISSUE THREAD

**Issue by ScriptForAll** [Aktanusa/CookieMonster#445]
I don't know if other users have stumbled with this issue but since day one I've struggled a bit with looking at the notifications settings and knowing immediately what I'm actually tweaking. I reckon it's because all notifications are displayed in a row without separators making it less readable to the user.

I propose that for each notification there should be a title so that it makes easier to read for the user since it separates into categories.

**Comment by DanielNoord** [comment]
This would be quite easy to implement, but I am not sure it would actually improve the UI.
It might actually clutter the UI even more.

Right now all toggles and sliders already include the name of the notification. Doesn't that tell you which setting you are tweaking? Or am I missing something?

Also note that the new version will include sliders for the volume settings, which also include a title of the settings that is being changed. As shown in the following screenshot:
<img width="561" alt="Schermafbeelding 2020-12-18 om 15 26 33" src="https://user-images.githubusercontent.com/13665637/102625205-6c45e180-4145-11eb-9f1b-41030ad42333.png">

**Comment by ScriptForAll** [comment]
This problem happens because the option that grabs my attention is the sound URL. This is due to the fact of being the only one that has always a white text. This is worsen by the fact that not every type of notification has the same number of options (e.g. Golden Cookie (6) options vs Max Magic (4) options) and the position of this option isn't always the last.

I reckon that one problem that might appear with this solution is that it can make the UI more cluttered. However, this could be solved if the sub-section text is smaller than the section text and bigger than the options text.
Also, having a sub-section with a tittle for each notification would shorten several options' descriptions which overall would require less text.  (e.g. "~~Fortune Cookie~~ Notification").
Finally, by implementing sub-sections, each option would be compartmentalised, which would make the whole section easier to read. Going further with this idea, a hiding feature could be also implemented.

**Comment by DanielNoord** [comment]
Yeah implementing it while also removing some texts from the labels seems to be the way to go forward.
Making them hide-able should also be an option.
Should not be too difficult to implement this, but I think for now I will not add this to the next version and save it for the one after that.

**Comment by ScriptForAll** [comment]
That's alright! These are just details after all so I think they can wait :D

Once again, thanks for the work you've been doing.

**Comment by DanielNoord** [comment]
@ScriptForAll do you know how to load the dev-branch? If so, my latest pull request has implemented this.
What do you think of my solution?

**Comment by ScriptForAll** [comment]
Hmm, not really :sweat_smile:
I've tried to load from https://raw.githubusercontent.com/Aktanusa/CookieMonster/dev/CookieMonster.js but it did not work (it deployed a MIME error).

I assume I'm doing something utterly wrong :s
Care to explain how to do so? :D

**Comment by DanielNoord** [comment]
You have gotten the correct link!
In the future we will provide a way to load it through the `Game.LoadMod` function. What you can do right now is copy all code that is in that link (ctrl + A should work) and past it into the console of your browser when you are on the Cookie Clicker page. Most browser-consoles upon up by right-clicking the page and clicking "inspect source" or something similar. Make sure CookieMonster is not already running as in that case it won't load the dev-version.

**Comment by ScriptForAll** [comment]
Okay, I didn't try to copy paste it into the console. I was using the Mod Loader so it deployed that error into the console, I guess.

I've tried it out and seems good for me. However, I have some questions:
- Why are the "Favicon" and "Timer" options for the Golden Cookie under "Calculation"?
- The timer bar options were all put together as one and moved. Personally, I don't have a problem with this but wouldn't some users want to choose which timers they want integrated?

Maybe you could keep the all-in-one Timer Bar option under "Bar/Colours" but having it tweaked under "Notifications" (i.e. being able to choose which timers you want to see).

**Comment by DanielNoord** [comment]
I moved the `FavIcon` and `Timer` settings to Calculation as they didn't fit into Golden Cookie Notifications, but you are right Calculation is also not the right place. I might move them once again to another category, or make a new one for them.

What do you mean with the timer bar options? I guess you are referring to the fact that there is no longer a limit in the number of timers so now every form of buff gets a timer? If that is the case, I agree that this is not the optimal solution. With #388 I intend to rewrite all of the code for the TimerBar and possibly make the different timers configurable. I am not sure about the approach yet as I need to take a better look at the current code and possible new implementations.
For now I was rewriting/annotating most of the graphics code and stumbled upon the TimerBar and thought it would be a quick fix to make it possible for more than 4 timers to appear.

**Comment by ScriptForAll** [comment]
Damn, I got confused, my bad. I thought that GC Timer was a Timer Bar tweak which isn't true. 
I was about to change my reply but I now I'm too late :sweat_smile: .

Either way, I do agree that choosing which buffs get to appear on the Timer Bar is the way to go.

With that said, I don't think I have anything else to say regarding this closed issue. 
As always, thanks for the work! :+1:

**Comment by DanielNoord** [comment]
No problem, if you have any suggestions for categories of buffs please add them to the thread of #388.
I do not really play cookie clicker anymore (I just like this project to improve my coding) so I don't know which categories might feel most natural. 
I never encounter more than 2 buffs at a time anyway so for me cluttering the TimerBar is not even a real issue, but I have seen pictures of people having 10+ buffs which would certainly break the current code of TimerBar
