### ISSUE TITLE
Cookie monster not workng on new beta

### ISSUE THREAD

**Issue by Creeperman8362** [Aktanusa/CookieMonster#45]
it not workin on new beta 1.9

**Comment by Aktanusa** [comment]
You're too fast!  It just came out!  Give me time >_>

**Comment by 3plus4i** [comment]
I don't really have an idea, how large the necessary changes are. Do you have any approximation on how long it might take?

**Comment by Aktanusa** [comment]
The update kind of came at the wrong timing, since I was in the middle of a cold and I have other Christmas related things to worry about.  I plan to finish it tomorrow or more likely Christmas Day.

**Comment by Aktanusa** [comment]
The beta script is in a state where I think I can close this bug.

**Comment by 3plus4i** [comment]
Ouch, almost forgot this. Thanks for the update! Tbh, playing without Cookie Monster was rather painful (resp. exhausting).

Two general questions:
Can we talk about improvements now, too? There are quite a few new features which could use Cookie Monster support.
Is it save to assume that porting will be rather simple and fast once the beta goes live?

**Comment by Aktanusa** [comment]
I guess you can talk a bit about improvements, but I really have no idea if and when Orteil goes to live.  Nor do I know what gameplay changes he will do before then.  

It's pretty simple to port over as beta and live are on different branches, so there should be no problems really.

**Comment by 3plus4i** [comment]
I'll just post my suggestions and than we will see :blush:

According to Orteil we can expect an update pretty soon.

**Comment by Aktanusa** [comment]
We'll see if Orteil can keep his word....
