### ISSUE TITLE
[beta] heavenly chips/prestige calculation error

### ISSUE THREAD

**Issue by 3plus4i** [Aktanusa/CookieMonster#46]
The counter for the cookies needed for the next chip/level behaves oddly. It increases instead of decreasing. The requirement is calculated correctly immediately after a chip is earned (in other words, when the progress bar for the next chip is at the very beginning), but the more it progresses towards the next chip, the more it gets off, counting up instead of down. It's not exactly inverse concerning the amount, though.

I'm not sure, if it's even relevant, because the counter can actually be removed completely, since the game has it's own one now.

**Comment by Aktanusa** [comment]
Yep, this is a known bug.  I may change it to ascend information instead.  Not sure right now.  A list of known bugs is on my Reddit post here:

https://www.reddit.com/r/CookieClicker/comments/3ybta0/cookie_monster_for_19_beta/

**Comment by 3plus4i** [comment]
Ah, thanks, I didn't know about this list.

**Comment by Aktanusa** [comment]
Since I removed HC stats, should I change this to an issue requesting the addition of ascend information?

**Comment by Aktanusa** [comment]
Added in Version 2.3
