### ISSUE TITLE
Feature Request: CM Changelog

### ISSUE THREAD

**Issue by ScriptForAll** [Aktanusa/CookieMonster#473]
**Describe the function you'd like to see added to CookieMonster**
It would be nice to implement a changelog to "Info" similarly to what other mods do (e.g. Spiced Cookies and CCSE).
However, unlike the aforementioned mods, I would suggest CM to have its own tab inside "Info", which would make a clear distinction between the base game and mods/addons changes making the whole section less cluttered in my opinion.

I don't know how feasible this would be, therefore I would like to debate if it's something to consider or not.

**Comment by DanielNoord** [comment]
What do you mean with giving CookieMonster its own "tab"? Spiced Cookies currently adds a collapsable section to the info-page. Is that what you mean or did you have another implementation in mind?

Besides, what I don't really like about how Cookie Clicker and Spiced Cookies currently create the changelogs is that they just add the changelogs as strings to their source-code. This increases the size of the file (especially for longer changelogs such as Cookie Clicker itself), but also makes them less dynamic. I think it would be good if we could create a solution that gets/downloads the changeling from GitHub releases and then adds it to the desired section in the info-page. However, I have never done this so I am not sure if we are even able to do this.

**Comment by ScriptForAll** [comment]
I had, indeed, a different implementation in mind than those aforementioned mods currently have. However, like I said in the OP, I don't know how feasible it is.

What I had envisioned is a clickable tab (similar to the Info button) inside the Info section. (~~Which would be a sub-tab... I know I'm repeating myself here :laughing:~~)

Clicking it would show the changelog for this add-on. I believe this is a simple and non intrusive way to implement this feature. However, there's still a consideration yet to be made which is the "where do I put this feature"? I have some possible answers for this question:

1. A small button located at the bottom right corner of the Info section.
2. A button right under the "info" title at the top of the Info section.
3. A "CM" button appearing while hovering.


I don't know if creating a whole page for the changelog would be an easy task given the fact that most of this add-on is implemented on top of the base game instead of adding totally new elements.
Therefore, I understand that this is quite the small detail that might end up being quite laborious. I expect no less for this to be a low-priority implementation if that's the case.

**Comment by ScriptForAll** [comment]
Hmm, I had an idea that could ease up the implementation process.

Instead of having the changelog built into the code, the could a link to a CHANGELOG file at GitHub.

**Comment by DanielNoord** [comment]
I'm not sure what I think about the implementation you mentioned. The problem with making an extra button for CookieMonster is that it would not be possible to have multiple mods do this, as that would make the interface way too cluttered. I'm not in favour of giving CookieMonster a privileged position over other mods so then we would be looking at an implementation similar to that of the others.

Making a changelog file could solve some of the problems. However, then we would still have the problem of having to change both the release page and the changelog file. If that's the case we could as well just add the changelog to the CookieMonster.js file.
I'll keep it in mind and reconsider it when I get time to look at this issue. For now I'm focusing on the last issues left of V2.031.3.
