### ISSUE TITLE
Add and alert when a wrinkler shows up

### ISSUE THREAD

**Issue by FlyingKumquat** [Aktanusa/CookieMonster#48]
Would be nice to know when a wrinkler shows via an audio alert and/or screen flash.

**Comment by Aktanusa** [comment]
Dang you are fast =p  Not to kill your hopes, but I am slow with enhancements though... lol

**Comment by FlyingKumquat** [comment]
Naturally, bugs and performance issues > everything.

**Comment by TakGalaman** [comment]
Doesn't the game normally play a sound when a wrinkler arrives?

**Comment by Aktanusa** [comment]
Nope.
