### ISSUE TITLE
Cookie Monster causes errors in Cookie Clicker

### ISSUE THREAD

**Issue by mbsaerens** [Aktanusa/CookieMonster#486]
**Describe the bug**
After loading CookieMonster add-on as described on the cookie clicker wiki, Cookie Clicker might no long play some sounds or load some graphics.

**To Reproduce**
The steps needed to reproduce the behavior:
1. Load the http:// version of cookie clicker in incognito mode
2. Load the CookieMonster add-on.
3. Wait for a while, like 15-minutes.
4. Keep your dev console open
5. Start playing actively. It seems to work fine initially, but there'll be errors in the console
It might help to use a save file to speed things up.

**Screenshots**
![CM-bug](https://user-images.githubusercontent.com/4717905/104587648-7fc26a80-5667-11eb-9da9-27735dbf7ea9.png)

**Save file**
```
[BenjiBakery.txt](https://github.com/Aktanusa/CookieMonster/files/5814223/BenjiBakery.txt)

```

**Comment by DanielNoord** [comment]
I cannot seem to reproduce this error on my own. 
Do you get the same issue when you play the game in normal mode (so not in incognito)? Looking at the errors this might be the only thing I can currently think of that can cause these problems.

**Comment by mbsaerens** [comment]
Neither can I on a different machine. I guess it's device related.
I'll try your suggestion tomorrow.

**Comment by mbsaerens** [comment]
It is probably related to the CookieClicker cookie issue mentioned on Reddit: https://www.reddit.com/r/CookieClicker/comments/kdvgzn/orteil_update_do_not_delete_your_cookies/

After a page refresh I ran into the same problem as described here.

**Comment by DanielNoord** [comment]
Ah that could be it!
You closed the issue so I assume there are no further problems now?

**Comment by mbsaerens** [comment]
Not related to CookieMonster, no ;)
