### ISSUE TITLE
TypeError due to undefined field in object

### ISSUE THREAD

**Issue by r9pereira** [Aktanusa/CookieMonster#490]
Uncaught TypeError: CM.Sim.Objects.Temple.minigame is undefined
    hasGod https://aktanusa.github.io/CookieMonster/CookieMonster.js:4605
    mouseCps https://aktanusa.github.io/CookieMonster/CookieMonster.js:5378
    BuyUpgrades https://aktanusa.github.io/CookieMonster/CookieMonster.js:5125
    RemakeIncome https://aktanusa.github.io/CookieMonster/CookieMonster.js:404
    Loop https://aktanusa.github.io/CookieMonster/CookieMonster.js:4173
    Loop https://aktanusa.github.io/CookieMonster/CookieMonster.js:4118
    setTimeout handler*Game.Launch/Game.Loop https://orteil.dashnet.org/cookieclicker/main.js?v=2.089:14457
    Loop https://aktanusa.github.io/CookieMonster/CookieMonster.js:4117

Please tell me if you need more info

Best Regards,
Ricardo Pereira

**Comment by DanielNoord** [comment]
Can you give me your save-file? That would help me in finding the bug!

**Comment by DanielNoord** [comment]
This should now be fixed both on the official and dev branch. Let me know if the problem stille exists!

**Comment by r9pereira** [comment]
It's fixed now. Thank you!
