### ISSUE TITLE
CookieMonster is not working anymore for old 1.0466 version.

### ISSUE THREAD

**Issue by Yoyoshix** [Aktanusa/CookieMonster#51]
Hello !
I know you updated CookieMonster to make it runable on the last Version of CC. The problem is I dont want to play it now, so i'm still playing on the previous version which is :http://orteil.dashnet.org/cookieclicker/v10466/

Is there a way I could make it works again for the old version ?

Thanks for your work !

Note : I know I should maybe download the files on my computer of the old version and do something from my browser to tell him to use the files I have from my disk. But I dont know how :(

**Comment by Aktanusa** [comment]
There is no need to download to your computer as it will always be on github as an older version.  rawgit.com site though, I don't know will last forever.  You're the third person to ask this (not a bad thing, just saying =p) so I think I should write a note on the README soon.  Anyway the solution is to use this instead:

javascript:(function() {
    Game.LoadMod('https://cdn.rawgit.com/Aktanusa/CookieMonster/1.0466.1/CookieMonster.js');
}());

**Comment by Yoyoshix** [comment]
Ohhhhh Thanks you a LOT ! I knew it was something like that ^^
I'm glad to hear you didn't waste your time to fix this.

**Comment by Aktanusa** [comment]
Eh it wouldn't be a waste of time even if I did need to do something.  It's helping out people with the addon, which is what motivates me =).  I will note though, this is the final version for the older CC.  Any need enhancements I do not plan on putting back into this script for older CC.
