### ISSUE TITLE
Easy and powerful enhancement for BCI

### ISSUE THREAD

**Issue by tokiwarthoot** [Aktanusa/CookieMonster#52]
If you can't afford the "green" best BCI building, consider the building with the best BCI you can afford right now.

Now calculate an hypothetical time remaining for that original best BCI building provided you buy the best BCI building you can afford and compare it with the current time remaining for that unaffordable best BCI building.

If buying the building you can actually afford will make it faster to get that one with better BCI but that you can't get, then it's optimal to get that one instead, and just make that one the green most recomended buy and push all others one spot in the color scale.

The math for doing this is pretty simple and doesn't really require a significant paradigm shift from the current normal BCI calculations, but would allow players to not waste time waiting if they would be better off buying something with worse BCI they can get right now.

**Comment by Aktanusa** [comment]
I believe this option was suggested in Issue #3.  Again, mostly when I stop being lazy...>_>

**Comment by tokiwarthoot** [comment]
haha okay don't be lazy :P

nah on a serious note, maybe you may work on this one day you are not feeling that lazy but not that inspired either as its pretty straightforward. anyways keep up the good work mate

**Comment by Aktanusa** [comment]
Thanks, and I'll try <_<

**Comment by Aktanusa** [comment]
Added in Version 2.4
