### ISSUE TITLE
CookieMonster Crashes the Game (Bookmarklet)

### ISSUE THREAD

**Issue by Nemanzin** [Aktanusa/CookieMonster#54]
Hello there!
So I've recently gotten back into Cookie Clicker as of the newest update, version 2, and I always used to play with Cookie Monster enabled. However, whenever I try to load the bookmarklet using:
javascript: (function () {
	Game.LoadMod('http://aktanusa.github.io/CookieMonster/CookieMonster.js');
}());
it simply crashes the game. The big cookie disappears, the cookie counter stops going up, and yet oddly I'm still able to purchase upgrades and buildings, though all of the option and stat menus have also disappeared other than the buttons that take you to those screens, so there's no actual way to save this progress. I've taken screenshots of these situations to perhaps aid you in identifying what's going on here, though I can't help but feel as though this is an error on my end. I've tried using both of the other bookmarklet codes, both to no avail, and I can't imagine TamperMonkey is the solution here. Thank you for reading, and hopefully I can figure out what's actually happening.
![screenshot 1](https://cloud.githubusercontent.com/assets/17252928/13051383/5c0c91bc-d3cf-11e5-8a1f-7402f9cf086a.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/17252928/13051397/721ebe8a-d3cf-11e5-94e6-fd219c8ce3ff.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/17252928/13051405/77c58332-d3cf-11e5-963d-8c0fd3d54815.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/17252928/13051408/7a67cd20-d3cf-11e5-8fcc-f6812601ebda.png)

**Comment by Aktanusa** [comment]
Since you are using Google Chrome, can you do this?

1.  Refresh the page so Monster isn't loaded
2.  Press F12 key to start console
3.  Load Cookie Monster
4.  See if there are errors in the console

**Comment by Nemanzin** [comment]
Thanks for the quick response!
![screenshot 6](https://cloud.githubusercontent.com/assets/17252928/13053558/842379fc-d3db-11e5-80ed-5071701bc3e1.png)
Other than the one "error" caused by Adblock, they're almost exclusively "Uncaught RangeErrors." That one that has 96 errors of the same variety isn't frozen there, by the way - the counter keeps going up at a rate of about twice per second. Maybe an error with whatever updates the cookie count? I can't think of anything else that'd update so frequently.

**Comment by Aktanusa** [comment]
According to the console, you also have Cookie **Master** loaded.  That's probably conflicting with Cookies **Monster**

**Comment by Aktanusa** [comment]
Also talk about a perfect timing on the screenshot with that Achievement, lol

**Comment by Nemanzin** [comment]
I'm an idiot. I'd simply installed the Cookie Master plugin and forgotten about it. Thank you very much, I'm sorry to bother you with such a silly problem.

**Comment by Aktanusa** [comment]
So I guess it works now?

**Comment by Aktanusa** [comment]
And no problem, we all make mistakes...

**Comment by Aktanusa** [comment]
Well I guess I'll close this.  Let me know if I was wrong in closing this.
