### ISSUE TITLE
Add ability to mute built-in sounds or decouple volume

### ISSUE THREAD

**Issue by tombakerjr** [Aktanusa/CookieMonster#567]
**Describe the function you'd like to see added to CookieMonster**

I usually play Cookie Clicker with the volume set to 0% so I don't have to hear the clicking sound. With the recent change to consider the general volume setting, I now have to choose between the annoying clicking sound or no sounds at all. It would be nice if I could either disable the cookie clicking sound effect altogether or have an option to decouple the addon volume from the general volume.

**Comment by jabenninghoff** [comment]
I also set the volume to 0% since that is needed to speed up CC on macOS Safari.

**Comment by DanielNoord** [comment]
An option to do this has now been added to the dev-branch and will be added in the next version!
