### ISSUE TITLE
Screen flashes/sound plays on startup despite being disabled

### ISSUE THREAD

**Issue by bobatealee** [Aktanusa/CookieMonster#569]
**Describe the bug**
I've turned off all of the flash and sound notification settings because they're pretty obnoxious. Despite this, every time I reload, it will still flash and sometimes even play a sound when the mod loads. I have the mod load automatically every time the page is loaded through a mod loader.

**To Reproduce**
The steps needed to reproduce the behavior:
1. Turn off every flash and sound setting for notifications
2. Start the game again

**Comment by DanielNoord** [comment]
This function will be added to the next version and is already available in the dev branch version.
There is no release date yet but expect it "soon". In the meantime you can use the version found on the dev-branch!

**Comment by Mitsunee** [comment]
still having this issue 3.5 years later on both Chromium and Firefox
