### ISSUE TITLE
Customize Building Colors

### ISSUE THREAD

**Issue by BlackTowerWA** [Aktanusa/CookieMonster#57]
Would it be possible to have customizeable building BCI colors? I'm colorblind and it's really difficult to tell the green best BCI building from the yellow(?) next best buildings. Reading the numbers works, but it'd be great for the "at a glance" factor.

**Comment by Aktanusa** [comment]
There is a setting for this already.  It's in Options.  Did you mean something else?

**Comment by Aktanusa** [comment]
Issue #20 was when this was added

**Comment by BlackTowerWA** [comment]
Whoops, my bad. I saw the light blue for the upgrades and didn't realize the ones below it were for the buildings and not just the upgrades. Thanks!

**Comment by Aktanusa** [comment]
No problem! =)
