### ISSUE TITLE
Game freeze ~5 seconds after selecting the "Stats" tab

### ISSUE THREAD

**Issue by darkazoid** [Aktanusa/CookieMonster#574]
**Describe the bug**
When I click the "Stats" tab, within about 5-10 seconds the entire game freezes and I have to reload the page.

I've tried different browsers, disabling all of my plugins/addons in each browser, and validating that this behavior does not occur without CookieMonster loaded.

**To Reproduce**
The steps needed to reproduce the behavior:
1. Open game
2. Use bookmark for CookieMonster
3. Click on Stats tab after CookieMonster is loaded

**Screenshots**
I opened the console and took a screenshot of an error message that I've seen each time this happens. 
![image](https://user-images.githubusercontent.com/79239169/108301511-28388280-7170-11eb-948e-67a07b5a098d.png)

**Save file**
```
If applicable please copy your save file here
```
[PirateDolphinBakery(3).txt](https://github.com/Aktanusa/CookieMonster/files/6000057/PirateDolphinBakery.3.txt)

**Comment by darkazoid** [comment]
It looks like this has already been noted and a workaround offered. I just didn't read as far into the "closed" issues as I should have. I'll close this out, thank you!

**Comment by DanielNoord** [comment]
Is the problem still occurring? I hoped that the hotfix I pushed yesterday had solved it, but this seems like it didn't..

**Comment by DanielNoord** [comment]
After a quick test I saw that this is still a bug. Hope to resolve this tonight!
