### ISSUE TITLE
Golden cookie timer broken

### ISSUE THREAD

**Issue by morkolen** [Aktanusa/CookieMonster#58]
For some reason the timer on the top of the screen for the GC is missing the bar where it should be is there but not the timer itself,also the timer thats on the page name just stays frozen at 204.

**Comment by Aktanusa** [comment]
Is Golden Switch on?  If so yea, the bar shouldn't be there and the time in the title should be gone, that's a known bug.

**Comment by Aktanusa** [comment]
I'm closing this due to no response.  If it's still a problem, feel free to reopen.
