### ISSUE TITLE
Show calc for 1 or 2 hours of CPS for Queenbeet and Duketater

### ISSUE THREAD

**Issue by faulk28** [Aktanusa/CookieMonster#584]
Queenbeet and Duketater (garden) give 1 (max 4% of bank) or 2 hours of CPS (max 8% of bank). Would like to see the calculation for this. How about when you mouse over a queenbeet it shows you how much bank is required to get the full 4 or 8%?

**Comment by DanielNoord** [comment]
This has already been implemented for the next version and can be seen/tested by using the dev-branch (See PR #524 and issue #183).
There is no release date yet, but expect it in the main version of the mod "soon".

**Comment by faulk28** [comment]
How do you download the dev-branch? I can't find the link. Any way you
could please post a link to the dev-branch js? Here is what I use to access
cookiemonster.

javascript: (function ()
{Game.LoadMod('https://aktanusa.github.io/CookieMonster/CookieMonster.js');}());

**Comment by DanielNoord** [comment]
You can load it by copying the `CookieMonster.js` file into the console of your browser.
The file can be found [here](https://github.com/Aktanusa/CookieMonster/blob/dev/CookieMonster.js). Just select all, copy, paste and press enter.
Do note that this version should be considered a beta version and is not stable.
