### ISSUE TITLE
Make it an option to change the bulk buy BCI colours 

### ISSUE THREAD

**Issue by lucmans** [Aktanusa/CookieMonster#59]
When you want to buy buildings in bulk, every building will appear in a not green colour.
This is obvious, because it's never optimal to buy in bulk. But when you just start out and have many heavenly chips, it's annoying to have to keep switching from 1 to bulk buy to see which is the best.

My suggestion is to make the best BCI building green for the selected amount. Not universally.

I hope my description wasn't to vague. 

I'm sorry but I have no idea how to label a suggestion. That's why there's no label.

**Comment by Aktanusa** [comment]
Actually, this isn't true.  If you have achievements of getting x buildings left, those buying in bulk would actually turn blue.

**Comment by Aktanusa** [comment]
I did think that some people may not like this, so maybe I'll set it as an option instead...

**Comment by lucmans** [comment]
That's true. I think it being a option is a good work around

**Comment by Aktanusa** [comment]
Added in Version 2.4
