### ISSUE TITLE
Create a 4%/8% of bank section at the top of Stats Screen

### ISSUE THREAD

**Issue by faulk28** [Aktanusa/CookieMonster#602]
The Queenbeet and Duketater will harvest for 1/2 hours of CPS for a max of 4% or 8% of bank.

Currently there are several sections at the top of stats for Lucky Cookies, Chain Cookies, etc.

Add another section called Garden Harvest

1 hour of CPS: xxxx
Max 4% of bank: yyyy
Time for bank to catchup with CPS
2 hour of CPS: xxxx
Max 8% of bank: yyyy
Time for bank to catchup with CPS

**Comment by faulk28** [comment]
Or how about some lines like this:
Total bank needed to max out 1 hour of CPS
Total bank needed to max out 2 hours of CPS

**Comment by DanielNoord** [comment]
The next version, which I hope to publish tonight, will feature tooltips for these plants.
I will think about also adding a section to the stats page. Should not be too hard to do, but might clutter the screen a bit..

**Comment by faulk28** [comment]
Where is the " User can now set a custom tooltip warning ("x times cps") in
the settings"

I don't see this setting in the options. Thank you for adding the new
features!

**Comment by DanielNoord** [comment]
It should be under the section "Tooltips and additional insights".
Is it not there?
