### ISSUE TITLE
Game freezing

### ISSUE THREAD

**Issue by david-ma** [Aktanusa/CookieMonster#608]
Cookie Clicker version: 2.031

Cookie Monster version: 2.031.4

Chrome version: Version 88.0.4324.150 (Official Build) (x86_64)

The game freezes sometimes in Chrome.

I think it is something to do with tooltips.

It is reproducible by mousing over the chocolate egg when you have 9 sexdecillion cookies.

This causes a javascript error:
<img width="716" alt="Screen Shot 2021-02-24 at 7 44 44 pm" src="https://user-images.githubusercontent.com/3320713/108974660-c761fa80-76d9-11eb-93eb-af69033cf481.png">

If you keep mousing over tooltips and generating these errors, the game will freeze.

Here is my save data, to help reproduce the error:

`Mi4wMzF8fDE2MTQxMjY3OTk3NDU7MTYxMjkzNDIzMjUzNTsxNjE0MTU2NTYxNTk5O0Zyb3N0aWNrbGU7ZmJnamx8MDExMTAwMDAwMDAwMDAwMDAxMDEwfDkuMDc1NDE5OTE0ODI0MzY2ZSs1MTs2Ljg2NzgyNjYzMTg4Mzk4NmUrNTI7MTMzMTk4OzE2NDM7Ni43OTUxMzU4MjM1NTY4MzllKzUyOzI4Njc7MzswOzUuMDQyMzk1MDUxMDk1Mjc1ZSs0OTszOzM7MDswOy0xOzQ7MjQxOzIuMzM1MDYwMDg1Nzc0NTIwOGUrNDk7ODM7MTQ7NzQ7MTkyNzUzODs1O2NocmlzdG1hczsyLjc5NzUwMDg2ODI3NDY2MjVlKzUwOzEyOzM2OTQ0MTQ1MjEzNTc7MTQ1NzI0NDUyMzA0MjsyMjM3MTY5OTk4MzE1OzA7MDs2MTM7ODY7NDk0OzIyNjsyMjI7MjU7MTsxNTswOzUwOzA7MDszOzE1OzE2MTQxMTE0Nzc4MDc7MDszOzIyNyw2NTM7NDE7MTsxOzIuNjA4MjU2OTcwNTQzNDcxNWUrNDQ7fDgwNCwxNTE2LDEuNTk1NDA3NzI5ODgzMjJlKzQ4LDIsLDAsODA0OzgxMiwxNDIyLDEuMzk3MTgxNzE4ODIwNTIxN2UrNDgsMCwsMSw4MTI7NzUwLDEzMDAsMS4xNzcyODcwMjM1NDcxNzA3ZSs0NCwzLDE2MTQxNTY3MTg0MDg6NDoxNjE0MTQ3OTYyOTA5OjA6NDo1NjoxOjA6MTYxNDEyNjc5OTc3NDogMTExMDAwMDAxMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMCAwOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjM6NjowOjA6MDowOjA6MDowOjA6MDowOjE6MDoxOjYyOjE6ODowOjA6MDowOjA6MDoxOjgzOjE6MzE6MTo4NzowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6LDEsNzUwOzc1MCwxMjk2LDkuNzk1NTUyMTUwMjI2MTQxZSs0NSwwLCwxLDc1MDs3NTAsMTI3OSw2LjEyMjUwMzgzNTMyNjg3ZSs0NSwwLCwxLDc1MDs3MDIsMTIxMiwxLjIyNzQwNjcxNjQzMTI3MzNlKzQ1LDEsMTo4MjoxOi0xMDY2NDIuOTIyMzYxMTk1NzowOiA2MDY6NDotODY6NDg4OjgwNTowOjAhNDgwNDoxOjQ1OjU2MTowOjA6MCE2Mjg0OjE6NDg6MzQyOjA6MDowITM2NzQ6MDowOjM4MDo3Mzc6MDowITE1NDc6NDotMTMyOjUyMTo3MzU6MDowITkwMTk6MTo2Nzo1MjM6MDowOjAhNDMyODoyOi00NTo2NzI6Njc1OjA6MCE4NzI5OjU6NTM6NjY0OjA6MDowITYzMjo0Oi0xMDE6MzkyOjY0MTowOjAhNzUzODowOi0zMjo4NDE6MDowOjAhMTA3MzM6NTotNTY6NDA1OjA6MDowITEyMzMyOjE6NjoxNTk6MDowOjAhMTkyOTo0Oi0yMjQ6MTYxOjU3ODowOjAhMTQ0ODg6MToxMTo0Njg6MDowOjAhNTY0ODo0Oi0yMTY6MTM2OjUzMDowOjAhMTY1NzU6MToxMjoyNTg6MDowOjAhIDEsMSw3MDI7NzAwLDExNzEsNS4zMzE3NTE4OTAzNzEwMzRlKzQ1LDEsOC85LzMgMSAxNjE0MTQ4Njc0NTE5IDEsMSw3MDA7NjUwLDE1NTQsMy4xNTYzMTMzODI4MjI1MDRlKzQ0LDEsMTA5IDExIDUyOCAxLDEsNjUwOzY1MCwxMTAwLDQuOTU3OTY2MTgyMTQ3OTg4ZSs0NCwwLCwxLDY1MDs2NTAsMTA2MCwxLjY2NDkxMDgwNjQxODIxOWUrNDUsMCwsMSw2NTA7NjMwLDEwNzAsMy40OTIwMDY1MTEwNjg0ODllKzQ3LDAsLDEsNjMwOzYwMCw5OTAsOC43NzE0NzkwNDE0NTQyOTRlKzQ2LDAsLDEsNjAwOzYwMCw5ODAsOC4wODI1OTM3NzU4MzAzMzFlKzQ3LDAsLDEsNjAwOzU3MCw5NTAsMy4yNTYzMDk3MjUyMzQ5MjFlKzQ4LDAsLDEsNTcwOzU1Myw5MDMsMS4xMzg4MDA2NjU0NjgzNTQ0ZSs0OSwwLCwxLDU1Mzs1NTYsOTA3LDcuNjYxMDQ0MTQxMjgyNDQ0ZSs0OSwwLCwxLDU1Njs1MDUsODU1LDEuMTEyNTAxNDE3MDY0NjEyMWUrNDksMCwsMSw1MDU7NDczLDgyNiw0LjA3MjU0MTczMzM2NDAyZSs0OSwwLCwxLDQ3NDt8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTEwMDExMTExMTAwMTAwMDExMDAxMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMDEwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMDAxMTAwMDAxMTExMDAxMTExMDAxMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTAxMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMTExMTExMTEwMDAwMDAwMDExMTExMTExfDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTEwMTExMTExMDAwMDAwMDAxMTExMDExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTAwMTAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDExMDAxMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTAwMDAwMTExMTExMTExMTExMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTAxMTExMTExMTExMTExMTAxMTExMDAwMDAxMTAwMDAwMDEwMTEwMDAwMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTEwMDAwMTExMTExMTExMTAwMDExMTAxMTExMDAwMDAwMDB8fENvb2tpZU1vbnN0ZXI6eyJzZXR0aW5ncyI6eyJCb3RCYXIiOjAsIlRpbWVyQmFyIjoxLCJUaW1lckJhclBvcyI6MCwiQnVpbGRDb2xvciI6MSwiQnVsa0J1aWxkQ29sb3IiOjEsIkNvbG9yUFBCdWxrTW9kZSI6MCwiVXBCYXJDb2xvciI6MSwiVXBncmFkZUJhckZpeGVkUG9zIjoxLCJDYWxjV3JpbmsiOjAsIkNQU01vZGUiOjEsIkF2Z0NQU0hpc3QiOjMsIkF2Z0NsaWNrc0hpc3QiOjAsIlRvb2xXYXJuQm9uIjowLCJHQ05vdGlmaWNhdGlvbiI6MSwiR0NGbGFzaCI6MSwiR0NTb3VuZCI6MSwiR0NWb2x1bWUiOjEwMCwiR0NTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzY2LzY2NzE3XzkzMTY1NS1scS5tcDMiLCJGb3J0dW5lTm90aWZpY2F0aW9uIjoxLCJGb3J0dW5lRmxhc2giOjEsIkZvcnR1bmVTb3VuZCI6MSwiRm9ydHVuZVZvbHVtZSI6MTAwLCJGb3J0dW5lU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNzQvMTc0MDI3XzMyNDI0OTQtbHEubXAzIiwiU2VhTm90aWZpY2F0aW9uIjowLCJTZWFGbGFzaCI6MCwiU2VhU291bmQiOjAsIlNlYVZvbHVtZSI6MTAwLCJTZWFTb3VuZFVSTCI6Imh0dHBzOi8vd3d3LmZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMjEvMTIxMDk5XzIxOTMyNjYtbHEubXAzIiwiR2FyZEZsYXNoIjowLCJHYXJkU291bmQiOjAsIkdhcmRWb2x1bWUiOjEwMCwiR2FyZFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTAzLzEwMzA0Nl84NjE3MTQtbHEubXAzIiwiTWFnaWNOb3RpZmljYXRpb24iOjEsIk1hZ2ljRmxhc2giOjEsIk1hZ2ljU291bmQiOjEsIk1hZ2ljVm9sdW1lIjoxMDAsIk1hZ2ljU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8yMjEvMjIxNjgzXzEwMTUyNDAtbHEubXAzIiwiV3JpbmtsZXJOb3RpZmljYXRpb24iOjAsIldyaW5rbGVyRmxhc2giOjAsIldyaW5rbGVyU291bmQiOjAsIldyaW5rbGVyVm9sdW1lIjoxMDAsIldyaW5rbGVyU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMjQvMTI0MTg2XzgwNDMtbHEubXAzIiwiV3JpbmtsZXJNYXhOb3RpZmljYXRpb24iOjEsIldyaW5rbGVyTWF4Rmxhc2giOjAsIldyaW5rbGVyTWF4U291bmQiOjEsIldyaW5rbGVyTWF4Vm9sdW1lIjoxMDAsIldyaW5rbGVyTWF4U291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNTIvMTUyNzQzXzE1NjYzLWxxLm1wMyIsIlRpdGxlIjoxLCJUb29sdGlwSW5mbyI6MSwiVG9vbHRpcEFtb3IiOjAsIlRvb2xXYXJuTHVja3kiOjEsIlRvb2xXYXJuTHVja3lGcmVuenkiOjEsIlRvb2xXYXJuQ29uanVyZSI6MSwiVG9vbFdhcm5Db25qdXJlRnJlbnp5IjoxLCJUb29sV2FybkVkaWZpY2UiOjEsIlRvb2xXYXJuUG9zIjowLCJUb29sdGlwR3JpbSI6MSwiVG9vbFdyaW5rIjoxLCJUb29sdGlwTHVtcCI6MSwiRHJhZ29uQXVyYUluZm8iOjEsIlN0YXRzIjoxLCJNaXNzaW5nVXBncmFkZXMiOjEsIlVwU3RhdHMiOjEsIlRpbWVGb3JtYXQiOjAsIkRldGFpbGVkVGltZSI6MSwiR3JpbW9pcmVCYXIiOjEsIlNjYWxlIjowLCJTY2FsZURlY2ltYWxzIjoyLCJTY2FsZVNlcGFyYXRvciI6MCwiU2NhbGVDdXRvZmYiOjk5OTk5OSwiQ29sb3JzIjp7IkJsdWUiOiIjNGJiOGYwIiwiR3JlZW4iOiIjMDBmZjAwIiwiWWVsbG93IjoiI2ZmZmYwMCIsIk9yYW5nZSI6IiNmZjdmMDAiLCJSZWQiOiIjZmYwMDAwIiwiUHVycGxlIjoiI2ZmMDBmZiIsIkdyYXkiOiIjYjNiM2IzIiwiUGluayI6IiNmZjE0OTMiLCJCcm93biI6IiM4YjQ1MTMifSwiU29ydEJ1aWxkaW5ncyI6MSwiU29ydFVwZ3JhZGVzIjoxLCJHQ1RpbWVyIjoxLCJGYXZpY29uIjoxLCJXcmlua2xlckJ1dHRvbnMiOjEsIkhlYWRlciI6eyJCYXJzQ29sb3JzIjoxLCJDYWxjdWxhdGlvbiI6MSwiTm90aWZpY2F0aW9uIjoxLCJOb3RpZmljYXRpb25HZW5lcmFsIjoxLCJOb3RpZmljYXRpb25HQyI6MSwiTm90aWZpY2F0aW9uRkMiOjEsIk5vdGlmaWNhdGlvblNlYSI6MSwiTm90aWZpY2F0aW9uR2FyZCI6MSwiTm90aWZpY2F0aW9uTWFnaSI6MSwiTm90aWZpY2F0aW9uV3JpbmsiOjEsIk5vdGlmaWNhdGlvbldyaW5rTWF4IjoxLCJUb29sdGlwIjoxLCJTdGF0aXN0aWNzIjoxLCJOb3RhdGlvbiI6MSwiTWlzY2VsbGFuZW91cyI6MSwiTHVja3kiOjEsIlNwZWxscyI6MSwiQ2hhaW4iOjEsIlByZXN0aWdlIjoxLCJXcmluayI6MSwiU2VhIjoxLCJNaXNjIjoxLCJHYXJkZW4iOjEsIkluZm9UYWIiOjF9LCJUaW1lckJhck92ZXJsYXkiOjIsIlBQRXhjbHVkZVRvcCI6MCwiUFBTZWNvbmRzTG93ZXJMaW1pdCI6MCwiUFBPbmx5Q29uc2lkZXJCdXlhYmxlIjowLCJHZW5lcmFsU291bmQiOjEsIlRvb2x0aXBCdWlsZFVwZ3JhZGUiOjEsIlRvb2xXYXJuVXNlciI6MCwiVG9vbHRpcFdyaW5rIjoxLCJUb29sdGlwUGxvdHMiOjEsIlRvb2x0aXBBc2NlbmRCdXR0b24iOjEsIkhlYXZlbmx5Q2hpcHNUYXJnZXQiOjEsIlNob3dNaXNzZWRHQyI6MSwiQnVsa0J1eUJsb2NrIjowfSwidmVyc2lvbiI6IjIuMDMxLjQifTs%3D%21END%21`

**Comment by DanielNoord** [comment]
Found the problem! Will push a hot fix tonight.
In the meantime you can circumvent the problem by selecting a different scale (due to the way certain checks are ordered), that should allow you to keep playing without any problems until the hotfix. I will respond to this topic whenever the hot fix has been pushed.

**Comment by david-ma** [comment]
Thanks Daniel, I was just going to write about that work around here haha.

I was poking around to see if I could write a pull request for you... but it's good that you've figured out a fix.

I should probably not start writing mods. Cookie clicker has taken so much of my time already!

**Comment by DanielNoord** [comment]
You are always welcome to take up an open issue from this project!

**Comment by DanielNoord** [comment]
Should be fixed!
