### ISSUE TITLE
PP sorting order for upgrades bar not working

### ISSUE THREAD

**Issue by HumanMaybe** [Aktanusa/CookieMonster#609]
Cookie Clicker version: 2.031

Cookie Monster version: 2.031.4

So the option to sort upgrades according to PP does nothing at all. It's probably because of the new update, problem wasn't present yesterday.

Not sure if it's save specific, but here's mine: Mi4wMzF8fDE1OTgzNDE4MDg1NTE7MTU5ODM0MTgwODU2NDsxNjE0MTY0OTY1NTkzO0h1bWFuO2ZidGl3fDExMTExMTAxMDAxMTAxMDAwMTAxMHw1MDE3MDk5NjAyNTc1MTkuMjU7MzA5NjE0MTQzNjc4OTUwMzA7MTg0Njk7NTQ3OzE5MDk4Njk3MDUwMTY3MTM2OzU1MTswOzA7MDswOzA7MDswOzA7MDs1NDc7MDswOzA7MDswOzA7OzA7MDswOzA7MDswOzA7LTE7LTE7LTE7LTE7LTE7MDswOzA7MDs1MDswOzA7MDsyOzE2MTQxNDE4ODc1NDY7MDswOzs0MTswOzA7MjAwOTQyMjI2MDg3LjEwMDU7fDE0MCwxNDAsMzkxOTEzNDMxMzg0LDAsLDAsMTQwOzE4MiwxODIsMzYwNjgwODQ3OTcyOSwwLCwwLDE4MjsxMDIsMTAyLDQ0NTQ1MDEyMzk3LDAsLDEsMTAyOzg4LDg4LDk4MjI0MTUwMTY2LDAsLDEsODg7NzksNzksNDEyNDk2NzYxNjE3LDAsLDEsNzk7NzMsNzMsMTczMzk1MjI0NDEwNCwwLCwxLDczOzY2LDY2LDcxMDAxNDAwMTc3NDAsMSw1Ly0xLzMgMyAxNjE0MTQ1MDQ0ODMzIDEsMCw2Njs1OCw1OCwyMTUxOTI1NjM2MjE1MiwxLDE0LjYwODk2NDM2NjYxMTA5MiA5IDkgMSwwLDU4OzUwLDUwLDgyNDM4MDg2NDQ3MTUxLDAsLDAsNTA7MzksMzksMzA1MjIxNjUwNjE3NjQxLDAsLDAsMzk7MzQsMzQsODc2NzUzNTIwNzkyODg4LDAsLDAsMzQ7MjMsMjMsMTE3MTA2OTgzNDk0OTQ1OSwwLCwwLDIzOzE0LDE0LDE0OTI1NzkyMTExODk3OTMsMCwsMCwxNDszLDMsNjQwNzkzMzIzMjQwMjEwLDAsLDAsMzswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7fDExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTEwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMDAxMTExMDAwMDAwMDAxMTAwMTExMTExMDAxMTAwMDAwMDAwMDAwMDExMTEwMDAwMDAxMTExMTAxMDEwMDAxMTExMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTEwMDAwMTExMTExMTEwMDAwMTExMTExMTEwMDAwMTExMTExMDAwMDAwMTAxMDEwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMXwxMTExMTExMTExMDAwMDAwMTExMTExMTExMTAwMDAxMTExMTExMTAwMTExMTExMTEwMTEwMTEwMTAwMTAwMTAwMDAwMTExMDExMTExMTEwMDAxMDAwMDAxMDAwMDAxMTAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAxMTAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDExMTAwMDExMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwfHxDb29raWVNb25zdGVyOnsic2V0dGluZ3MiOnsiQm90QmFyIjowLCJUaW1lckJhciI6MCwiVGltZXJCYXJQb3MiOjAsIlRpbWVyQmFyT3ZlcmxheSI6MiwiQnVpbGRDb2xvciI6MSwiQnVsa0J1aWxkQ29sb3IiOjEsIlVwQmFyQ29sb3IiOjEsIlVwZ3JhZGVCYXJGaXhlZFBvcyI6MSwiQ2FsY1dyaW5rIjoxLCJDUFNNb2RlIjoxLCJBdmdDUFNIaXN0IjozLCJBdmdDbGlja3NIaXN0IjowLCJDb2xvclBQQnVsa01vZGUiOjAsIlBQRXhjbHVkZVRvcCI6MCwiUFBTZWNvbmRzTG93ZXJMaW1pdCI6MCwiUFBPbmx5Q29uc2lkZXJCdXlhYmxlIjowLCJUb29sV2FybkJvbiI6MCwiVGl0bGUiOjEsIkdlbmVyYWxTb3VuZCI6MSwiR0NOb3RpZmljYXRpb24iOjAsIkdDRmxhc2giOjAsIkdDU291bmQiOjEsIkdDVm9sdW1lIjoxMDAsIkdDU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy82Ni82NjcxN185MzE2NTUtbHEubXAzIiwiRm9ydHVuZU5vdGlmaWNhdGlvbiI6MCwiRm9ydHVuZUZsYXNoIjowLCJGb3J0dW5lU291bmQiOjEsIkZvcnR1bmVWb2x1bWUiOjEwMCwiRm9ydHVuZVNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTc0LzE3NDAyN18zMjQyNDk0LWxxLm1wMyIsIlNlYU5vdGlmaWNhdGlvbiI6MCwiU2VhRmxhc2giOjAsIlNlYVNvdW5kIjoxLCJTZWFWb2x1bWUiOjEwMCwiU2VhU291bmRVUkwiOiJodHRwczovL3d3dy5mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTIxLzEyMTA5OV8yMTkzMjY2LWxxLm1wMyIsIkdhcmRGbGFzaCI6MCwiR2FyZFNvdW5kIjowLCJHYXJkVm9sdW1lIjoxMDAsIkdhcmRTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEwMy8xMDMwNDZfODYxNzE0LWxxLm1wMyIsIk1hZ2ljTm90aWZpY2F0aW9uIjowLCJNYWdpY0ZsYXNoIjowLCJNYWdpY1NvdW5kIjoxLCJNYWdpY1ZvbHVtZSI6MTAwLCJNYWdpY1NvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMjIxLzIyMTY4M18xMDE1MjQwLWxxLm1wMyIsIldyaW5rbGVyTm90aWZpY2F0aW9uIjowLCJXcmlua2xlckZsYXNoIjowLCJXcmlua2xlclNvdW5kIjowLCJXcmlua2xlclZvbHVtZSI6MTAwLCJXcmlua2xlclNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTI0LzEyNDE4Nl84MDQzLWxxLm1wMyIsIldyaW5rbGVyTWF4Tm90aWZpY2F0aW9uIjowLCJXcmlua2xlck1heEZsYXNoIjowLCJXcmlua2xlck1heFNvdW5kIjowLCJXcmlua2xlck1heFZvbHVtZSI6MTAwLCJXcmlua2xlck1heFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTUyLzE1Mjc0M18xNTY2My1scS5tcDMiLCJUb29sdGlwQnVpbGRVcGdyYWRlIjoxLCJUb29sdGlwQW1vciI6MCwiVG9vbFdhcm5MdWNreSI6MCwiVG9vbFdhcm5MdWNreUZyZW56eSI6MCwiVG9vbFdhcm5Db25qdXJlIjowLCJUb29sV2FybkNvbmp1cmVGcmVuenkiOjAsIlRvb2xXYXJuRWRpZmljZSI6MCwiVG9vbFdhcm5Vc2VyIjowLCJUb29sV2FyblBvcyI6MSwiVG9vbHRpcEdyaW0iOjEsIlRvb2x0aXBXcmluayI6MCwiVG9vbHRpcEx1bXAiOjEsIlRvb2x0aXBQbG90cyI6MSwiRHJhZ29uQXVyYUluZm8iOjEsIlRvb2x0aXBBc2NlbmRCdXR0b24iOjEsIlN0YXRzIjoxLCJNaXNzaW5nVXBncmFkZXMiOjAsIlVwU3RhdHMiOjEsIlRpbWVGb3JtYXQiOjAsIkRldGFpbGVkVGltZSI6MSwiR3JpbW9pcmVCYXIiOjEsIkhlYXZlbmx5Q2hpcHNUYXJnZXQiOjEsIlNob3dNaXNzZWRHQyI6MCwiU2NhbGUiOjAsIlNjYWxlRGVjaW1hbHMiOjIsIlNjYWxlU2VwYXJhdG9yIjowLCJTY2FsZUN1dG9mZiI6OTk5OTk5LCJDb2xvcnMiOnsiQmx1ZSI6IiM0YmI4ZjAiLCJHcmVlbiI6IiMwMGZmMDAiLCJZZWxsb3ciOiIjZmZmZjAwIiwiT3JhbmdlIjoiI2ZmN2YwMCIsIlJlZCI6IiNmZjAwMDAiLCJQdXJwbGUiOiIjZmYwMGZmIiwiR3JheSI6IiNiM2IzYjMiLCJQaW5rIjoiI2ZmMTQ5MyIsIkJyb3duIjoiIzhiNDUxMyJ9LCJTb3J0QnVpbGRpbmdzIjoxLCJTb3J0VXBncmFkZXMiOjEsIkdDVGltZXIiOjEsIkZhdmljb24iOjEsIldyaW5rbGVyQnV0dG9ucyI6MSwiQnVsa0J1eUJsb2NrIjowLCJIZWFkZXIiOnsiQmFyc0NvbG9ycyI6MSwiQ2FsY3VsYXRpb24iOjEsIk5vdGlmaWNhdGlvbiI6MCwiTm90aWZpY2F0aW9uR2VuZXJhbCI6MSwiTm90aWZpY2F0aW9uR0MiOjEsIk5vdGlmaWNhdGlvbkZDIjoxLCJOb3RpZmljYXRpb25TZWEiOjEsIk5vdGlmaWNhdGlvbkdhcmQiOjEsIk5vdGlmaWNhdGlvbk1hZ2kiOjEsIk5vdGlmaWNhdGlvbldyaW5rIjoxLCJOb3RpZmljYXRpb25Xcmlua01heCI6MSwiVG9vbHRpcCI6MSwiU3RhdGlzdGljcyI6MSwiTm90YXRpb24iOjEsIk1pc2NlbGxhbmVvdXMiOjEsIkx1Y2t5IjoxLCJDaGFpbiI6MSwiU3BlbGxzIjoxLCJHYXJkZW4iOjEsIlByZXN0aWdlIjoxLCJXcmluayI6MSwiU2VhIjoxLCJNaXNjIjoxLCJJbmZvVGFiIjoxfX0sInZlcnNpb24iOiIyLjAzMS40In07%21END%21

**Comment by DanielNoord** [comment]
Your save seems to work for me. In your current save Cursors and Grandma's are actually number 1 and 2 and as third it shows Antimatted condensers. This makes it seem as if there is not sorting by PP, but it actually does (you can test this by changing to buy 10 or buy 100).
If this is not the case could you check if the console is throwing any errors?

**Comment by HumanMaybe** [comment]
*Upgrades*, not buildings

**Comment by DanielNoord** [comment]
Oh I'm sorry! Misread that part. I'll have another look!

**Comment by DanielNoord** [comment]
Found the bug and think already know what is wrong, sorry for the confusion.
Should be an easy fix, expect a hot fix somewhere tonight!

**Comment by HumanMaybe** [comment]
Ok, thanks!

**Comment by DanielNoord** [comment]
This has been fixed!
