### ISSUE TITLE
Style Error on Mouseover of Objects Causing Freezing

### ISSUE THREAD

**Issue by mattxd92** [Aktanusa/CookieMonster#612]
**Describe the bug**
There is a bug that causes the game to crash after a bit of moving the cursor over anything in the windows and clicking a few buildings to buy. Below is the error that appears in the console. Attaching screenshots of the error

**To Reproduce**

I load up the addon through the bookmarklet and on mouseover of objects in the window it will produce errors and then shortly after will freeze the page.

**Screenshots**
![CookieMonster Error](https://user-images.githubusercontent.com/79588794/109018966-8f7d9780-7686-11eb-96b0-3eb82fa0747e.png)

**Save file**
Mi4wMzF8fDE2MTQwODY1Mzg3Njg7MTYxMzU3ODA4ODMyNTsxNjE0MTc4NjQxNzQ2O01yIEF3ZXNvbWU7eWNmbHZ8MTExMTExMDExMDExMDAxMDAxMDEwfDUxNDIxMDg0Njk4NDAwODY0MDs0NjQxMjcyNDgwMzkyMjk0MDAwOzEyNTQ5Mzk7OTk5OzI3NjIxNjE2MjE0MTgzOTE2MDA7MTUyMjswOzA7OTgyMjc0OTA5MDc2ODQ5MzAwOzA7MDswOzY5OzIxNDU3OzM7NDA5OzA7MDswOzA7MDswOzswOzA7OTk7MTE7ODg7MDswOy0xOy0xOy0xOy0xOy0xOzE0OzM7MDswOzA7MDswOzE7NzsxNjE0MTcyNzc3MzgxOzA7MDs7NDE7MDswOzczNzIxNTQ1NzQ2NjgyLjY2O3wyMTAsMzEwLDExNDA5NDk3MTU3MTgzMDIsMiwsMCwyMTA7MjE3LDMxNywxMzI5MzkxNDEwNzI2NjExNiwxLCwxLDIxNzsxNzMsMjczLDY3MDg4NTcyNDk2NywwLCwxLDE3MzsxNTYsMjU2LDI0Mjg0MzcwNzQ3OTMsMCwsMSwxNTY7MTQ0LDI0NCw1OTY5OTg4Mzc3MTEyLDAsLDEsMTQ0OzEyMiwyMjMsMjIwNDkxOTg0NjUwNzYsMCwsMSwxMjI7MTAzLDIwNCw5NzMxOTk0ODExNDY5OSwwLCwxLDEwMzsxMDAsMjAxLDI0Nzg2MjYyMTQ0MDMyNywwLCwxLDEwMDsxMDAsMjAwLDExMzY1NjY2NjIzODAyNjEsMSwsMSwxMDA7NTcsNTgsMzAyMDYwNTc2MzMyNDk1NiwxLCwxLDU3OzQ0LDQ1LDExMjkxMjc1NzUzNjY1MzU0LDAsLDEsNDQ7MzgsMzgsNDgwMjg3Mjg0MjYyOTU4NjAsMCwsMSwzODszMiwzMiwxNjY2ODM3MzMzNTE5MDM1MjAsMCwsMCwzMjsyNCwyNCwyNjQwMDQzNDY1NDg1MTI2NzAsMCwsMCwyNDsxMywxMyw0MDU4NzU1NzM1OTA1MjY0NjAsMCwsMCwxMzs0LDQsMzc3MzU1MTEyNTQ5MDEwOTAwLDAsLDAsNDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwO3wxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAxMTExMTExMTAwMTExMTAwMDAwMDAwMTEwMDExMTExMTAwMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTAwMTExMTExMTExMTAwMDAwMDAwMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTEwMDAwMDAxMTAwMDAwMDAwMDAwMDEwMDAwMDExMTExMTExMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTEwMDExMTExMTExMTEwMDExMTExMTExMTEwMDExMTExMTExMDAxMTExMTExMTEwMTAxMDEwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTF8MTExMTExMTExMTExMDAwMDExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMDEwMDEwMDAwMDExMTAxMTExMTExMDAwMTAxMTAxMTAwMTAwMTAwMDAwMDExMTEwMDAwMDAwMDAwMDEwMTAwMDAwMTAwMDAwMDAwMTEwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAxMTExMDAxMTEwMDExMTAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAxMTAxMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMHwwLDQ2MjAsNDM1MCw3LDAsMDt8Q29va2llTW9uc3Rlcjp7InNldHRpbmdzIjp7IkJvdEJhciI6MSwiVGltZXJCYXIiOjEsIlRpbWVyQmFyUG9zIjowLCJCdWlsZENvbG9yIjoxLCJCdWxrQnVpbGRDb2xvciI6MCwiQ29sb3JQUEJ1bGtNb2RlIjowLCJVcEJhckNvbG9yIjoxLCJVcGdyYWRlQmFyRml4ZWRQb3MiOjEsIkNhbGNXcmluayI6MCwiQ1BTTW9kZSI6MSwiQXZnQ1BTSGlzdCI6MywiQXZnQ2xpY2tzSGlzdCI6MCwiVG9vbFdhcm5Cb24iOjAsIkdDTm90aWZpY2F0aW9uIjowLCJHQ0ZsYXNoIjoxLCJHQ1NvdW5kIjoxLCJHQ1ZvbHVtZSI6MTAwLCJHQ1NvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvNjYvNjY3MTdfOTMxNjU1LWxxLm1wMyIsIkZvcnR1bmVOb3RpZmljYXRpb24iOjAsIkZvcnR1bmVGbGFzaCI6MSwiRm9ydHVuZVNvdW5kIjoxLCJGb3J0dW5lVm9sdW1lIjoxMDAsIkZvcnR1bmVTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzE3NC8xNzQwMjdfMzI0MjQ5NC1scS5tcDMiLCJTZWFOb3RpZmljYXRpb24iOjAsIlNlYUZsYXNoIjoxLCJTZWFTb3VuZCI6MSwiU2VhVm9sdW1lIjoxMDAsIlNlYVNvdW5kVVJMIjoiaHR0cHM6Ly93d3cuZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyMS8xMjEwOTlfMjE5MzI2Ni1scS5tcDMiLCJHYXJkRmxhc2giOjEsIkdhcmRTb3VuZCI6MSwiR2FyZFZvbHVtZSI6MTAwLCJHYXJkU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMDMvMTAzMDQ2Xzg2MTcxNC1scS5tcDMiLCJNYWdpY05vdGlmaWNhdGlvbiI6MCwiTWFnaWNGbGFzaCI6MSwiTWFnaWNTb3VuZCI6MSwiTWFnaWNWb2x1bWUiOjEwMCwiTWFnaWNTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzIyMS8yMjE2ODNfMTAxNTI0MC1scS5tcDMiLCJXcmlua2xlck5vdGlmaWNhdGlvbiI6MCwiV3JpbmtsZXJGbGFzaCI6MSwiV3JpbmtsZXJTb3VuZCI6MSwiV3JpbmtsZXJWb2x1bWUiOjEwMCwiV3JpbmtsZXJTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyNC8xMjQxODZfODA0My1scS5tcDMiLCJXcmlua2xlck1heE5vdGlmaWNhdGlvbiI6MCwiV3JpbmtsZXJNYXhGbGFzaCI6MSwiV3JpbmtsZXJNYXhTb3VuZCI6MSwiV3JpbmtsZXJNYXhWb2x1bWUiOjEwMCwiV3JpbmtsZXJNYXhTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzE1Mi8xNTI3NDNfMTU2NjMtbHEubXAzIiwiVGl0bGUiOjEsIlRvb2x0aXBJbmZvIjoxLCJUb29sdGlwQW1vciI6MCwiVG9vbFdhcm5MdWNreSI6MSwiVG9vbFdhcm5MdWNreUZyZW56eSI6MSwiVG9vbFdhcm5Db25qdXJlIjoxLCJUb29sV2FybkNvbmp1cmVGcmVuenkiOjEsIlRvb2xXYXJuRWRpZmljZSI6MSwiVG9vbFdhcm5Qb3MiOjEsIlRvb2x0aXBHcmltIjoxLCJUb29sV3JpbmsiOjEsIlRvb2x0aXBMdW1wIjoxLCJEcmFnb25BdXJhSW5mbyI6MSwiU3RhdHMiOjEsIk1pc3NpbmdVcGdyYWRlcyI6MSwiVXBTdGF0cyI6MSwiVGltZUZvcm1hdCI6MCwiRGV0YWlsZWRUaW1lIjoxLCJHcmltb2lyZUJhciI6MSwiU2NhbGUiOjAsIlNjYWxlRGVjaW1hbHMiOjIsIlNjYWxlU2VwYXJhdG9yIjowLCJTY2FsZUN1dG9mZiI6OTk5OTk5LCJDb2xvcnMiOnsiQmx1ZSI6IiM0YmI4ZjAiLCJHcmVlbiI6IiMwMGZmMDAiLCJZZWxsb3ciOiIjZmZmZjAwIiwiT3JhbmdlIjoiI2ZmN2YwMCIsIlJlZCI6IiNmZjAwMDAiLCJQdXJwbGUiOiIjZmYwMGZmIiwiR3JheSI6IiNiM2IzYjMiLCJQaW5rIjoiI2ZmMTQ5MyIsIkJyb3duIjoiIzhiNDUxMyJ9LCJTb3J0QnVpbGRpbmdzIjowLCJTb3J0VXBncmFkZXMiOjAsIkdDVGltZXIiOjEsIkZhdmljb24iOjEsIldyaW5rbGVyQnV0dG9ucyI6MSwiSGVhZGVyIjp7IkJhcnNDb2xvcnMiOjEsIkNhbGN1bGF0aW9uIjoxLCJOb3RpZmljYXRpb24iOjEsIk5vdGlmaWNhdGlvbkdlbmVyYWwiOjEsIk5vdGlmaWNhdGlvbkdDIjoxLCJOb3RpZmljYXRpb25GQyI6MSwiTm90aWZpY2F0aW9uU2VhIjoxLCJOb3RpZmljYXRpb25HYXJkIjoxLCJOb3RpZmljYXRpb25NYWdpIjoxLCJOb3RpZmljYXRpb25XcmluayI6MSwiTm90aWZpY2F0aW9uV3JpbmtNYXgiOjEsIlRvb2x0aXAiOjEsIlN0YXRpc3RpY3MiOjEsIk5vdGF0aW9uIjoxLCJNaXNjZWxsYW5lb3VzIjoxLCJMdWNreSI6MSwiU3BlbGxzIjoxLCJDaGFpbiI6MSwiUHJlc3RpZ2UiOjEsIldyaW5rIjoxLCJTZWEiOjEsIk1pc2MiOjEsIkdhcmRlbiI6MSwiSW5mb1RhYiI6MX0sIlRpbWVyQmFyT3ZlcmxheSI6MiwiUFBFeGNsdWRlVG9wIjowLCJQUFNlY29uZHNMb3dlckxpbWl0IjowLCJQUE9ubHlDb25zaWRlckJ1eWFibGUiOjAsIkdlbmVyYWxTb3VuZCI6MSwiVG9vbHRpcEJ1aWxkVXBncmFkZSI6MSwiVG9vbFdhcm5Vc2VyIjowLCJUb29sdGlwV3JpbmsiOjEsIlRvb2x0aXBQbG90cyI6MSwiVG9vbHRpcEFzY2VuZEJ1dHRvbiI6MSwiSGVhdmVubHlDaGlwc1RhcmdldCI6MSwiU2hvd01pc3NlZEdDIjoxLCJCdWxrQnV5QmxvY2siOjB9LCJ2ZXJzaW9uIjoiMi4wMzEuNCJ9Ow%3D%3D%21END%21

**Comment by mattxd92** [comment]
I did see another bug submitted which looked similar but wanted to submit anyway since it was a different error.

**Comment by DanielNoord** [comment]
This should now be fixed!
