### ISSUE TITLE
Estimations not showing on hover (Cookie Dragon, Conjure Baked Goods)

### ISSUE THREAD

**Issue by gafydddafydd** [Aktanusa/CookieMonster#619]
Mousing over the various Cookie Dragon auras no longer shows the estimated CPS difference or how long it will take to rebuy the building it costs to change auras. 

Conjure Baked Goods also doesn't show how many cookies to be gained/lost anymore, only how long it will take until you have enough magic to cast it again.

Save file attached if needed.
[DafyddBakery.txt](https://github.com/Aktanusa/CookieMonster/files/6043387/DafyddBakery.txt)

**Comment by DanielNoord** [comment]
I know the reason for this. Mistake on my part, fixing an issue but creating another one (related to changes in #614).
I hope to fix this asap!
