### ISSUE TITLE
True Max Prestige Level

### ISSUE THREAD

**Issue by CptHampton** [Aktanusa/CookieMonster#62]
Currently, the maximum prestige level is only your current prestige + what ascending immediately would give you. Truly, maximum prestige should include the cookies from popping wrinklers and buying the chocolate egg. These are both values included, so it's just a matter of adding them on (selling buildings does NOT add to cookies baked all time, so there should be no need to worry about that statistic).

**Comment by Aktanusa** [comment]
I would probably need to add a tooltip to indicate that.

**Comment by Aktanusa** [comment]
So the reset bonus stat, should it be for true max prestige level too?

**Comment by CptHampton** [comment]
Probably, the other stat is meaningless unless there are people who ascend WITHOUT popping wrinklers and buying chocolate egg.

**Comment by Aktanusa** [comment]
But you know, some people do forget and don't even know about the trick (aka newbie)

**Comment by Aktanusa** [comment]
Oh god, I just realized the max will also fluctuate because the amount you get from Chocolate Egg also fluctuate since it's highly depended on the current bank.  Now to explain all that in the tooltip.... lol

**Comment by CptHampton** [comment]
Definitely good points. It might be beneficial to keep the current statistic in addition to the true max, that way it might help it be a little less confusing. And if people are okay with Chocolate Egg fluctuating/having a detailed tooltip, I don't see why this would be considerably more confusing.

**Comment by Aktanusa** [comment]
doing CUR/MAX/TRUE MAX seems too much info though.  I'll just do the tooltips and point to other tooltips for more info or something

**Comment by CptHampton** [comment]
I'll trust the decision you make, I just want the statistic available somehow :)

**Comment by Aktanusa** [comment]
Thanks. =)  The stat is already there implemented,  Like I said, the hardest part is the tooltip =p.

**Comment by CptHampton** [comment]
If you're satisfied with the Chocolate egg tooltip, you could just modify it for this. Just change "The amount of cookies you would get" to "The amount of prestige you would get"

**Comment by CptHampton** [comment]
Or "The level of prestige" if that makes a little more sense

**Comment by Aktanusa** [comment]
Added in Version 2.4
