### ISSUE TITLE
Show tooltip for "Pop Wrinker" buttons with the effect of clicking them/content of fattest wrinklers

### ISSUE THREAD

**Issue by TakGalaman** [Aktanusa/CookieMonster#628]
**Describe the bug**
The "Pop All Normal" and "Pop Single Fattest" wrinkler buttons at the bottom of the milk/cookie area aren't very useful because you can't decide whether to click on them without mousing over every single wrinkler to find the one with the most cookies or sum up the cookies across all the wrinklers. 

**To Reproduce**
The steps needed to reproduce the behavior:
1. Have 2 or more wrinklers
2. Set your heart on purchasing something very expensive (your next kitten upgrade, let's say)
3. Try to figure out if you could pop one or more wrinklers to be able to buy that expensive thing
4. Be sad, because cookie monster doesn't help you with this

**Suggested fix**
When I hover over the Pop All Normal or Pop Single Fattest buttons a tooltip should appear to show me how many cookies each of the buttons will yield.
or
Always show the number of cookies in each wrinkler and a cumulative total number of Cookies in the N fattest wrinklers.
That way you could look at the data and decide whether popping any number of wrinklers will fit your current need for cookies.
E.g.
Fattest Wrinkler - 3 Quadrillion - 3 Quadrillion
2nd Fattest - 2.8 Qdr - 5.8 Qdr
3rd fattest - 1 Qdr - 6.8 Qdr

**Save file**
There's nothing special about my save - I have 9 wrinklers active. I don't yet have a Fractal Engine. I've ascended only once.
If applicable please copy your save file here
Mi4wMzF8fDE2MTI4MjE1NTAzMjE7MTYxMDc0ODI4MzQ5NzsxNjE0Nzc5NjkyNjMzO0kgY2FuIHN0b3Agd2hlbmV2ZXIgSSB3YW50O2Fha29xfDExMTExMTAxMTAxMTAwMTAwMTAxMHw1MjQwMzgyNDMyOTcxNTg1MDs0MzUyNTUwMTMyNTQzMTA5MDA7MzQxMDQ7NDQzOzIyODkzMTY1NjI0OTcyMjYyMDszMzU2OzA7MDsyNDg5Mzk5NDg1MDQ4MTU0OzE7MDswOzA7LTE7MTsyOTc7MjM5MDM1OTM0MjM1MjgwMTA7MTswOzA7MDswOzsxNzEzNTc4ODk3NTc1MjMxNDA7OTsxMzsxOzEyOzA7MDstMTstMTstMTstMTstMTswOzA7MDswOzUwOzA7MDszOzQyOzE2MTQ3MTU0ODA1NTg7MDswOzs0MTswOzA7NDUyMTAwNTUxOTUxMy40OTg7fDIyMCwzMjAsMjg3NzI5NDg2ODg5NDE0LDIsLDAsMjIwOzIxNywyMTcsMTA5Mjc0MTI5MDUwODc5NywxLCwxLDIxNzsyMDAsMjAwLDMzMzk2NjYyOTIyOSw1LDE2MTQ3ODAwOTg4ODU6MjoxNjE0NjExNTA4NzQ3OjA6OTk6MTIyOjE6MDoxNjEyODIxNTUwMzMxOiAxMTExMTAwMDAxMTExMTAwMDAwMDAwMDEwMTAwMDAwMDAwIDA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDoxOjk1OjA6MDoxOjk4OjI0OjQ2OjA6MDowOjA6MTo5ODoxOjQ3OjM6NDE6MDowOjA6MDowOjA6MTowOjI0OjQxOjE6MzQ6MTo5NDowOjA6MDowOjI0OjU0OjE6OTg6MToxNjowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOiwwLDIwMDsxNzQsMTc0LDc3MzQ0MzQwNzUwMSwxLCwxLDE3NDsxNTcsMTU3LDIwMTk5MzE0NjMxMTksMSwsMSwxNTc7MTQwLDE0MCw3ODk0NTIxOTA0NzMwLDEsMToxOjE6MTAwOC45NTI4OTg4OTE2ODU3OjA6IDg2Njo1Oi04OjY4MjoyNzU6MDowITMzODI6MTo0MDo2NjU6MDowOjAhMzMwNjo1Oi00NjozOTU6MDowOjAhMzU0Mzo1OjMxOjY1OjEwMjowOjAhNzc3MzoxOjc0OjE4MDowOjA6MCE2MDQxOjU6Mzg6MTk2OjA6MDowITY4NjY6NTo3OTo2NTA6MDowOjAhMTAwNzQ6NTotMTI6MjU0OjA6MDowITIzOTA6NDotMTQ2OjU2MjowOjA6MCExMDYwMDoxOjExOjIzOTo1MDowOjAhMTEyMDU6MToxNzoyNjY6MDowOjAhMTE4MzU6NTo1OjI1OTowOjA6MCExMDExNzoyOi01Njo0NzI6MDowOjAhMTQ4MDg6MToxNzo4MDE6MDoxOjAhMTUyNjk6NTotNDQ6MzA5OjA6MTowITEzNDY0OjA6LTIzOjkyMDowOjE6MCEgMCwwLDE0MDsxMjIsMTIyLDMwNTA3NzIxNTMxMTg0LDEsOC83LzkvNSAzIDE2MTQ2OTI2NjY4NzMgMSwwLDEyMjsxMDAsMTAwLDc4NTA3NjAyNzM5NjM0LDEsNTAgNzQgMTE2IDEsMCwxMDA7ODIsODIsMzExMTA2NTAxNjI4OTA5LDEsLDEsODI7NjAsNjAsODE2OTE0NjE4MjYyMjM4LDEsLDEsNjA7NDIsNDIsMjk1NzI0MDkwODk0MzE0NiwxLCwxLDQyOzMyLDMyLDExNzUyMTIzMDI4OTU5NTcyLDIsLDEsMzI7MjMsMjMsMjcxNDk1ODIwNzE1NTI4OTIsMiwsMSwyMzsxMiwxMiwyNzk1MjczNDY5NzM4MzU0MCwyLCwxLDEyOzMsMywyNDg4NTk1NDE0MTc3OTc1MCwyLCwxLDM7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7fDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDExMTExMTExMDAxMTExMDAwMDAwMDAxMTAwMTExMTExMDAxMTAwMDAwMDAwMDAwMDExMTEwMDAwMTExMTExMTExMTExMDAxMTExMTExMTAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMTExMDExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMTAwMTExMTExMTExMTAwMTExMTExMTExMDAwMTExMTExMDAwMDAwMTAxMDEwMTAxMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMXwxMTExMTExMTExMTAwMDAwMTExMTExMTExMTExMTAxMTExMTExMTEwMTExMTExMTExMTExMTEwMTEwMTAwMTAwMDAwMTExMDExMTExMTEwMDAxMDEwMDExMDAxMDAwMDAwMDAwMTExMTExMDAwMDAwMDAwMTExMDAwMDAxMDAwMDAwMDAxMTAwMDAwMDAwMDAwMTEwMDAxMDAwMDAwMDAwMTAwMDAwMDAwMDExMTEwMDExMTAwMTExMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDExMDExMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwfHxDb29raWVNb25zdGVyOnsic2V0dGluZ3MiOnsiQm90QmFyIjoxLCJUaW1lckJhciI6MSwiVGltZXJCYXJQb3MiOjAsIkJ1aWxkQ29sb3IiOjEsIkJ1bGtCdWlsZENvbG9yIjowLCJDb2xvclBQQnVsa01vZGUiOjEsIlVwQmFyQ29sb3IiOjEsIlVwZ3JhZGVCYXJGaXhlZFBvcyI6MSwiQ2FsY1dyaW5rIjowLCJDUFNNb2RlIjoxLCJBdmdDUFNIaXN0Ijo2LCJBdmdDbGlja3NIaXN0IjoyLCJUb29sV2FybkJvbiI6MCwiR0NOb3RpZmljYXRpb24iOjAsIkdDRmxhc2giOjEsIkdDU291bmQiOjAsIkdDVm9sdW1lIjo4MCwiR0NTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzY2LzY2NzE3XzkzMTY1NS1scS5tcDMiLCJGb3J0dW5lTm90aWZpY2F0aW9uIjowLCJGb3J0dW5lRmxhc2giOjEsIkZvcnR1bmVTb3VuZCI6MSwiRm9ydHVuZVZvbHVtZSI6MTAwLCJGb3J0dW5lU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNzQvMTc0MDI3XzMyNDI0OTQtbHEubXAzIiwiU2VhTm90aWZpY2F0aW9uIjowLCJTZWFGbGFzaCI6MSwiU2VhU291bmQiOjEsIlNlYVZvbHVtZSI6MTAwLCJTZWFTb3VuZFVSTCI6Imh0dHBzOi8vd3d3LmZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMjEvMTIxMDk5XzIxOTMyNjYtbHEubXAzIiwiR2FyZEZsYXNoIjowLCJHYXJkU291bmQiOjEsIkdhcmRWb2x1bWUiOjEwMCwiR2FyZFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL3Blb3BsZS9GLk0uQXVkaW8vc291bmRzLzU1NDA4MS8jIiwiTWFnaWNOb3RpZmljYXRpb24iOjAsIk1hZ2ljRmxhc2giOjAsIk1hZ2ljU291bmQiOjAsIk1hZ2ljVm9sdW1lIjoxMDAsIk1hZ2ljU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8yMjEvMjIxNjgzXzEwMTUyNDAtbHEubXAzIiwiV3JpbmtsZXJOb3RpZmljYXRpb24iOjAsIldyaW5rbGVyRmxhc2giOjAsIldyaW5rbGVyU291bmQiOjEsIldyaW5rbGVyVm9sdW1lIjoxMDAsIldyaW5rbGVyU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMjQvMTI0MTg2XzgwNDMtbHEubXAzIiwiV3JpbmtsZXJNYXhOb3RpZmljYXRpb24iOjEsIldyaW5rbGVyTWF4Rmxhc2giOjAsIldyaW5rbGVyTWF4U291bmQiOjEsIldyaW5rbGVyTWF4Vm9sdW1lIjoxMDAsIldyaW5rbGVyTWF4U291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNTIvMTUyNzQzXzE1NjYzLWxxLm1wMyIsIlRpdGxlIjoyLCJUb29sdGlwSW5mbyI6MSwiVG9vbHRpcEFtb3IiOjAsIlRvb2xXYXJuTHVja3kiOjEsIlRvb2xXYXJuTHVja3lGcmVuenkiOjEsIlRvb2xXYXJuQ29uanVyZSI6MCwiVG9vbFdhcm5Db25qdXJlRnJlbnp5IjowLCJUb29sV2FybkVkaWZpY2UiOjAsIlRvb2xXYXJuUG9zIjoxLCJUb29sdGlwR3JpbSI6MSwiVG9vbFdyaW5rIjoxLCJUb29sdGlwTHVtcCI6MSwiRHJhZ29uQXVyYUluZm8iOjEsIlN0YXRzIjoxLCJNaXNzaW5nVXBncmFkZXMiOjEsIlVwU3RhdHMiOjAsIlRpbWVGb3JtYXQiOjAsIkRldGFpbGVkVGltZSI6MSwiR3JpbW9pcmVCYXIiOjEsIlNjYWxlIjoyLCJTY2FsZURlY2ltYWxzIjowLCJTY2FsZVNlcGFyYXRvciI6MCwiU2NhbGVDdXRvZmYiOjk5OTk5OSwiQ29sb3JzIjp7IkJsdWUiOiIjNGJiOGYwIiwiR3JlZW4iOiIjMDBmZjAwIiwiWWVsbG93IjoiI2ZmZmYwMCIsIk9yYW5nZSI6IiNmZjdmMDAiLCJSZWQiOiIjZmYwMDAwIiwiUHVycGxlIjoiI2ZmMDBmZiIsIkdyYXkiOiIjYjNiM2IzIiwiUGluayI6IiNmZjE0OTMiLCJCcm93biI6IiM4YjQ1MTMifSwiU29ydEJ1aWxkaW5ncyI6MCwiU29ydFVwZ3JhZGVzIjoxLCJHQ1RpbWVyIjoxLCJGYXZpY29uIjoxLCJXcmlua2xlckJ1dHRvbnMiOjEsIkhlYWRlciI6eyJCYXJzQ29sb3JzIjoxLCJDYWxjdWxhdGlvbiI6MSwiTm90aWZpY2F0aW9uIjoxLCJOb3RpZmljYXRpb25HQyI6MSwiTm90aWZpY2F0aW9uRkMiOjEsIk5vdGlmaWNhdGlvblNlYSI6MSwiTm90aWZpY2F0aW9uR2FyZCI6MSwiTm90aWZpY2F0aW9uTWFnaSI6MSwiTm90aWZpY2F0aW9uV3JpbmsiOjEsIk5vdGlmaWNhdGlvbldyaW5rTWF4IjoxLCJUb29sdGlwIjoxLCJTdGF0aXN0aWNzIjoxLCJOb3RhdGlvbiI6MSwiTWlzY2VsbGFuZW91cyI6MSwiTHVja3kiOjEsIlNwZWxscyI6MSwiQ2hhaW4iOjAsIlByZXN0aWdlIjowLCJXcmluayI6MSwiU2VhIjowLCJNaXNjIjoxLCJOb3RpZmljYXRpb25HZW5lcmFsIjoxLCJHYXJkZW4iOjEsIkluZm9UYWIiOjF9LCJUaW1lckJhck92ZXJsYXkiOjIsIlBQRXhjbHVkZVRvcCI6MCwiUFBTZWNvbmRzTG93ZXJMaW1pdCI6IjUiLCJQUE9ubHlDb25zaWRlckJ1eWFibGUiOjAsIkdlbmVyYWxTb3VuZCI6MSwiVG9vbHRpcEJ1aWxkVXBncmFkZSI6MSwiVG9vbFdhcm5Vc2VyIjowLCJUb29sdGlwV3JpbmsiOjEsIlRvb2x0aXBQbG90cyI6MSwiVG9vbHRpcEFzY2VuZEJ1dHRvbiI6MSwiSGVhdmVubHlDaGlwc1RhcmdldCI6MSwiU2hvd01pc3NlZEdDIjoxLCJCdWxrQnV5QmxvY2siOjB9LCJ2ZXJzaW9uIjoiMi4wMzEuNCJ9Ow%3D%3D%21END%21

**Comment by DanielNoord** [comment]
We already display this data in the statistics tab. Should be do-able to create a tooltip for the buttons that displays the same information.
I would say that this is more of an enhancement though and since I don't have much spare time in the near future I don't expect this to be added soon.
