### ISSUE TITLE
building colors for bulk buying never show green (best) - compares to single building purchase?

### ISSUE THREAD

**Issue by pbrooks42** [Aktanusa/CookieMonster#63]
it looks like the bulk buy colors for buildings never show green - they are (I assume) still comparing to single building purchases.  While technically correct, it would be nice to know which 10-pack of buildings is the most cost effective compared to other 10-packs of buildings, instead of just solo buildings.  not a huge issue, but switching back and forth between single and 10 to know which is most cost effective is a hassle.

**Comment by Aktanusa** [comment]
This was explained in Issue #59 as going to be an option.  Yea I probably should have made it an option from the start as a few people doesn't like it, lol

**Comment by pbrooks42** [comment]
my bad! didn't realize there was already an issue open for this.  Thanks for all the hard work on this!

**Comment by Aktanusa** [comment]
Added in Version 2.4
