### ISSUE TITLE
"Test" button for custom notification sound URLs

### ISSUE THREAD

**Issue by TakGalaman** [Aktanusa/CookieMonster#630]
**Describe the function you'd like to see added to CookieMonster**
In the Options where you can specify sound URLs to play for various notifications it would be helpful to have a "Test" button that attempts to play the sound when clicked. This would be nice so you don't have to wait for a golden cookie/garden tick to occur to see if the new URL you've added actually works.

**Additional files**
I plugged https://freesound.org/people/aji_/sounds/66136/download/66136__aji__ding30603-spedup.wav in as the sound URL for golden cookies and it's not playing and it would be faster to iterate if I could just click "Test" instead of waiting.  Here is a non-direct link to this audio file - https://freesound.org/people/aji_/sounds/66136/

**Comment by TakGalaman** [comment]
I'd actually be happier with a few good options to choose from on each sound. Maybe a few button options for the sound to use for each notification and then a final option for "insert your own URL"  which then causes the current sound URL field to appear. 

I'm trying to make the golden cookie sound less aggressive, and to make the garden tick sound a shovel scooping dirt. (This URL works for the shovel sound: https://www.freesound.org/data/previews/121/121099_2193266-lq.mp3)

**Comment by DanielNoord** [comment]
I'm going to add a test button to the settings page. I will not add a list of options, as I believe this will unnecessarily crowd the already crammed page. Planning this for next release!
