### ISSUE TITLE
Buying buildings in groups of 10 doesn't show next one to buy in priority

### ISSUE THREAD

**Issue by Haidee-hm** [Aktanusa/CookieMonster#631]
**Describe the bug**
I buy buildings in groups of 10 because I use Rigidel in the Pantheon as my first slot.  Initially I would get buildings in a blue colour indicating to buy them next, but now I have no blue at all to buy next.

**To Reproduce**
The steps needed to reproduce the behavior:
1. Set building buying to 10x at a time.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/44797604/110225323-75c33680-7f49-11eb-9885-fc590e2b7552.png)

**Save file**
```
If applicable please copy your save file here
[DiscoPirateBakery.txt](https://github.com/Aktanusa/CookieMonster/files/6096353/DiscoPirateBakery.txt)
```

**Comment by DanielNoord** [comment]
Have you set your settings to "Compare PP to single buy". I think in your particular case buying a single building has a lower PP than any of the options of buying 10. Therefore they will all be yellow or worse. Previously buying ten would have a lower PP than the optimal "single buy" option, which would have made them light blue.
Changing this setting to "bulk buy" will make PP colour dependent on the chosen bulk-mode and would thus colour the most optimal "buy 10" option accordingly.

**Comment by Haidee-hm** [comment]
Thank you, this fixed it DanielNoord.  I appreciate the support and clear instruction to fix it.

**Comment by DanielNoord** [comment]
No worries, glad to help!
