### ISSUE TITLE
numbers in descriptions of achievements messed up

### ISSUE THREAD

**Issue by mbsaerens** [Aktanusa/CookieMonster#636]
**Describe the bug**
Examples of CookieClicker without CookieMonster:
* Making some dough: Bake **1,000** cookies in one ascension.
* Cookie vortex: Bake **1 million** cookies per second.

With CookieMonster, they become:
* Making some dough: Bake **1000** cookies in one ascension.
* Cookie vortex: Bake **1.000 M** cookies per second.

The thousand seperator is gone and above starting from the millions, decimals up until the thousands are added.

**To Reproduce**
The steps needed to reproduce the behavior:
1. Load CookieMonster
2. Hover de achievements to see their description

**Screenshots**
Without CookieMonster
![noCM](https://user-images.githubusercontent.com/4717905/110599356-0df83000-8183-11eb-8bd8-a7cd6412b16d.png)
With CookieMonster
![withCM](https://user-images.githubusercontent.com/4717905/110599360-0e90c680-8183-11eb-8ad1-2ee96b5a6888.png)

**Comment by DanielNoord** [comment]
This is sort of intended behavior. The game calls a function to create beautified numbers which Cookie Monster replaces to make the choice in scale possibles. In the setting you can set the number from which Cookie Monster starts to use the scale to "beautify" the numbers. As the achievement requires exactly 1 million cookies baked, Cookie Monster displays this according to the selected scale.
Although I could understand that some users might want to keep the original text of the achievement, I actually believe this is better. It keeps the display of all numbers within the same scale. For example, it would be weird to have the full game set to scientific notification (1e66) and the achievement say you need 1 unvigintillion cookies baked. The user would then not know what is required of him or her.

We could add thousand separators, although this comes with the problem with different countries using either ',' or '.' as separator. I will think about that issue.

**Comment by mbsaerens** [comment]
As a Belgian, we are indeed used to see the '.' as a thousands seperator and the ',' for the decimals. That's been the root cause for this report, since I initially read this as "a thousand Million". I didn't had this weird interpretation before I used CM.
Since you've overwritten the method, I see where it comes from. I agree with the uniformity over the entire game.
Perhaps switch it to enhancement and put it as an option to choose between the cookieclicker way and the cookiemonster way?

**Comment by DanielNoord** [comment]
Just to let you know, there is an option to change the decimal separator. It is under the Miscellaneous section. Although I just noticed a bug there.

I will look into how difficult it is to implement this. I think it might take quite some time for little gain. I'll keep this issue open until I have made a decision.

**Comment by mbsaerens** [comment]
Fair enough. It's a visual thing, no high priority.

**Comment by DanielNoord** [comment]
I have changed some code and thousand separators should now show correctly based on the chosen separator in the settings. I'm updating the main version of Cookie Monster as we speak so please let me know if any (new) problems still exist.
