### ISSUE TITLE
Fix bank calculation if Golden Switch is active

### ISSUE THREAD

**Issue by CptHampton** [Aktanusa/CookieMonster#64]
Currently, the bank for lucky or frenzy/lucky is calculated solely based on CPS. Activating the golden switch makes the required bank go up, but there are no golden cookies to be clicked while GS is active. The bank calculation should ignore the 50% boost by GS to give an idea of what the required bank *will be* when GS is turned off and golden cookies are set to reappear.

**Comment by Aktanusa** [comment]
That's a good point.  Though while reading your description, I was thinking you were going to say I should hid the Golden Cookie stats completely while having Golden Switch.

**Comment by CptHampton** [comment]
No, it would still be useful to have it because I don't want to turn off the golden switch only to find that I've blown through my bank and have to build it up again. Plus people can always minimize sections they don't use.

**Comment by Aktanusa** [comment]
Sorry I wasn't clear.  I should have said I agree to just make the calculation without the Switch and keep the stats there.

**Comment by CptHampton** [comment]
I guess now I wasn't clear: that is exactly what I wanted out of this issue, do that haha.

**Comment by Aktanusa** [comment]
Fixed in version 2.4
