### ISSUE TITLE
Static Bonus Income

### ISSUE THREAD

**Issue by Silvermann17** [Aktanusa/CookieMonster#647]
**Bug Behavior**
The displayed bonus income for almost every possible purchase is showing up as around 33.8%. Purchasing more buildings changes this value slightly, but not by much, and the value is still the same across all bonus incomes.

**To Reproduce**
1. Turn on Cookie Monster
2. Enable Building/Upgrade Information Tooltip
3. Hover your mouse over multiple buildings/upgrades and compare the displayed bonus incomes

**Save file**
Shouldn't be applicable, but in case it is:
[PegasusBakery.txt](https://github.com/Aktanusa/CookieMonster/files/6136817/PegasusBakery.txt)

**Comment by Spart4n** [comment]
My Bonus income on many buildings is negative, and the projected timescale on any buildings not yet available to buy is infinity.
![Capture](https://user-images.githubusercontent.com/80633959/111072670-f20dca80-84b1-11eb-9919-c982417e912b.PNG)

**Comment by DanielNoord** [comment]
I believe this has been fixed with the hot fix I just pushed.
Please let me know if this is indeed the case!

**Comment by Silvermann17** [comment]
The bonus incomes aren't all the same anymore, but a lot of buildings now aren't showing the percentage-based part of the bonus income. Still much better though; thanks!

**Comment by DanielNoord** [comment]
Could you upload a screenshot of what you mean?

**Comment by Silvermann17** [comment]
Not really; I'm on a mac, and doing a screenshot requires holding shift, which brings things into x100 purchase -- but I think I've figured it out: if the bonus income is below 0.01%, then it just doesn't show the percentage. Which is actually fine

**Comment by DanielNoord** [comment]
That is indeed what is going on. We do not handle this correctly right now.
I will add something to handle these case, probably something along the lines of "less than 0.01%".
Keeping this issue open to trace process on that.
