### ISSUE TITLE
Show cost to rebuy all buildings (+50 or +200) for last Dragon upgrades in tooltip

### ISSUE THREAD

**Issue by KaosDragon** [Aktanusa/CookieMonster#65]
I just screwed myself over by getting the dragon cookie right after getting radiant appetite and not keeping an eye on my cookies. So this seems like it'd be pretty useful in hindsight.

**Comment by Aktanusa** [comment]
hmm, I'm not exactly getting what you want.  Right now, the game already tells you use will lose stuff.  What do you want the addon to show?  Can you give an example?

**Comment by KaosDragon** [comment]
I mean something like "It will cost X cookies to repurchase the sacrificed buildings".

**Comment by Aktanusa** [comment]
So, like for the last dragon upgrade, you want me to calculate how much to get +200 of every building again?  For example.

**Comment by KaosDragon** [comment]
Exactly!

**Comment by Aktanusa** [comment]
I guess I'll add as a misc stat
