### ISSUE TITLE
excessive reduplication? 

### ISSUE THREAD

**Issue by gwogobo** [Aktanusa/CookieMonster#651]
the frenzy timer bar and the hover on legacy duplicate themselves all the way down the screen repeatedly

it's doing this on this version I just opened cookie clicker and clicked the bookmark for monster

https://drive.google.com/file/d/1npIlj_2L2Lw3ckngx1MjEvgKrpxPEJQJ/view?usp=sharing

Mi4wMzF8fDE2MTU2NDczMTM3MDM7MTYxNDcxMzAzOTA0MjsxNjE1NzM0Nzk2NzU2O0xpemFiZWw7YmVobWZ8MDExMTExMDAxMDAwMDAxMDAxMTEwfDY2MTY2MDQwOTkzMTIyLjMzOzI2MTMwNTk4NjU5MzkzNy43ODszMTQ7MTQ5MDs1Mjk1MjE0NjQ2NC4wOTE4NzsyMjswOzA7MS4wNzA1MTc1MTQ1NDg3Nzg0ZSsyMTswOzA7MDswOzA7MTs1NjswOzA7MDswOzA7MDs7MDswOzEwMjI7NjA7OTYyOzA7MDstMTstMTstMTstMTstMTsxMTsxOzA7MDsyNTswOzA7MDsxMDsxNjE1NzI2MzUyNDUxOzA7MDs7NDE7MDswOzU5NDM0MjE1NzUxLjM3MjY0O3wxMzcsMzcwLDQ2ODEzMTI0NTM1NSwxLCwwLDEzNzsxNDcsMzU1LDk4MTQ2NDY5Mzk3MywwLCwxLDE0NzsxMDEsMjc2LDc2NTQ0MDc5MzY2LDEwLDE2MTU3MzQ5NjMxOTY6MjoxNjE1NzMzNTI3MDQxOjA6MjI6MTE3OjA6MDoxNjE1NjQ3MzEzNzU1OiAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIDA6MDoxOjE2OjA6MDowOjA6MToxODowOjA6MDowOjE6MTc6MDowOjA6MDoxOjE1OjA6MDowOjA6MToxNjowOjA6MDowOjA6MDozOjE1OjA6MDowOjA6MDowOjA6MDoxOjE4OjA6MDowOjA6MToxNjowOjA6MDowOjE6MTc6MDowOjA6MDoxOjE3OjA6MDozOjE0OjE6MTc6MDowOiwwLDEwMTs3OSwyMzgsMjEzNDg5MTQzMzI1LDAsLDEsMTAxOzcyLDIxOCw4NzY2MzIyMTkxNzksMCwsMSwxMDE7NjIsMjAyLDIxMzA4ODk3Mzk4ODAsMSwwOjA6MTowOjE6IDQ0Mjo0Oi03NjozMzk6MDowOjAhMjUxNzowOjEwOjIzNjowOjA6MCE0OTk2OjE6MzM6NjI1OjA6MDowITQ1MDc6MDotMTc6NDc6MDowOjAhNzU3MzoxOjUxOjE3NzowOjA6MCE4NzE0OjE6NjE6MjExOjA6MDowITk3OTI6MTo3OTo3OTQ6MDowOjAhMTM4NTo0Oi0xODI6NTQwOjA6MDowITkyODM6NTotNzo2MzU6MDowOjAhMTA3Mzk6MTo5OjQ5NDowOjA6MCExMDkzNDoxOjg6Mzc1OjA6MTowITEwNDM5OjA6LTk6NjowOjE6MCExMzM0MToxOjE0OjExMjowOjE6MCExNDQ0NjoxOjEyOjQ4MDowOjE6MCExNDY0NzowOi0xOTo0MjQ6MDoxOjAhMTU2NTI6MDotMTA6MjAyOjA6MTowISAwLDAsMTAwOzc5LDExMyw5NDU3ODcyNTA5ODMxLDEsNy8tMS8tMSAzIDE2MTU3MjYzNTI0NjggMCwwLDc5OzQxLDk2LDE4NTQ3NTc3NTA2NjM5LDEsMTUuMzk2NzI2NzY3NjI5NDEgNSAyMDYgMCwwLDQxOzIwLDgwLDUzNDk2NjQzODQ2ODYxLDAsLDEsMzQ7OCw0Myw4MTkyNDM4ODA2Mzc3OSwwLCwxLDIzOzEsMTIsMzc0MTIxNDMwNjUwMzQsMCwsMSwxMTsxLDEsMjE4OTI0NTQyMTgwODYsMCwsMSwxOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwO3wxMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTAwMDEwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTEwMDAwMDAwMDExMTExMDExMTExMTExMTExMTExMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTAwMTExMTAwMDAwMDAwMTEwMDExMTAxMDAwMTAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAxMDEwMTAxMDAwMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAxMDEwMTAxMTExMTExMTExMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTAwMDExMTExMTExMDAwMDExMTExMTAwMDAwMDExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTEwMDAwMDAwMDAwMTExMTAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMTExMTAwMTEwMDExMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMTExMTAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTF8MTExMTExMTExMTExMTEwMDExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDExMTExMTExMTExMDExMTExMTAxMTEwMTAwMTAwMDAwMDExMTExMTEwMDAwMDAwMDExMTAwMDAwMTAwMDEwMDAwMTEwMDAwMDAwMDAwMDExMDAxMTExMDAwMDAwMTExMTAwMDAwMDAxMTExMTAxMTExMDExMTAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAxMTAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMTEwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAxMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMHwwLDQ2MjAsNTEzLDc7OSwxODAwLDEzMjAsNS4xLDc7fENvb2tpZU1vbnN0ZXI6eyJzZXR0aW5ncyI6eyJCb3RCYXIiOjAsIlRpbWVyQmFyIjoxLCJUaW1lckJhclBvcyI6MCwiVGltZXJCYXJPdmVybGF5IjowLCJCdWlsZENvbG9yIjoxLCJCdWxrQnVpbGRDb2xvciI6MCwiVXBCYXJDb2xvciI6MSwiVXBncmFkZUJhckZpeGVkUG9zIjoxLCJDYWxjV3JpbmsiOjAsIkNQU01vZGUiOjEsIkF2Z0NQU0hpc3QiOjEsIkF2Z0NsaWNrc0hpc3QiOjAsIkNvbG9yUFBCdWxrTW9kZSI6MSwiUFBFeGNsdWRlVG9wIjowLCJQUFNlY29uZHNMb3dlckxpbWl0IjowLCJQUE9ubHlDb25zaWRlckJ1eWFibGUiOjAsIlRvb2xXYXJuQm9uIjoxLCJUaXRsZSI6MSwiR2VuZXJhbFNvdW5kIjoxLCJHQ05vdGlmaWNhdGlvbiI6MCwiR0NGbGFzaCI6MSwiR0NTb3VuZCI6MSwiR0NWb2x1bWUiOjEwMCwiR0NTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzY2LzY2NzE3XzkzMTY1NS1scS5tcDMiLCJGb3J0dW5lTm90aWZpY2F0aW9uIjowLCJGb3J0dW5lRmxhc2giOjEsIkZvcnR1bmVTb3VuZCI6MSwiRm9ydHVuZVZvbHVtZSI6MTAwLCJGb3J0dW5lU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNzQvMTc0MDI3XzMyNDI0OTQtbHEubXAzIiwiU2VhTm90aWZpY2F0aW9uIjowLCJTZWFGbGFzaCI6MSwiU2VhU291bmQiOjEsIlNlYVZvbHVtZSI6MTAwLCJTZWFTb3VuZFVSTCI6Imh0dHBzOi8vd3d3LmZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMjEvMTIxMDk5XzIxOTMyNjYtbHEubXAzIiwiR2FyZEZsYXNoIjoxLCJHYXJkU291bmQiOjEsIkdhcmRWb2x1bWUiOjEwMCwiR2FyZFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTAzLzEwMzA0Nl84NjE3MTQtbHEubXAzIiwiTWFnaWNOb3RpZmljYXRpb24iOjAsIk1hZ2ljRmxhc2giOjEsIk1hZ2ljU291bmQiOjEsIk1hZ2ljVm9sdW1lIjoxMDAsIk1hZ2ljU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8yMjEvMjIxNjgzXzEwMTUyNDAtbHEubXAzIiwiV3JpbmtsZXJOb3RpZmljYXRpb24iOjAsIldyaW5rbGVyRmxhc2giOjEsIldyaW5rbGVyU291bmQiOjEsIldyaW5rbGVyVm9sdW1lIjoxMDAsIldyaW5rbGVyU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMjQvMTI0MTg2XzgwNDMtbHEubXAzIiwiV3JpbmtsZXJNYXhOb3RpZmljYXRpb24iOjAsIldyaW5rbGVyTWF4Rmxhc2giOjEsIldyaW5rbGVyTWF4U291bmQiOjEsIldyaW5rbGVyTWF4Vm9sdW1lIjoxMDAsIldyaW5rbGVyTWF4U291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNTIvMTUyNzQzXzE1NjYzLWxxLm1wMyIsIlRvb2x0aXBCdWlsZFVwZ3JhZGUiOjEsIlRvb2x0aXBBbW9yIjowLCJUb29sV2Fybkx1Y2t5IjoxLCJUb29sV2Fybkx1Y2t5RnJlbnp5IjowLCJUb29sV2FybkNvbmp1cmUiOjAsIlRvb2xXYXJuQ29uanVyZUZyZW56eSI6MCwiVG9vbFdhcm5FZGlmaWNlIjowLCJUb29sV2FyblVzZXIiOjAsIlRvb2xXYXJuUG9zIjoxLCJUb29sdGlwR3JpbSI6MSwiVG9vbHRpcFdyaW5rIjoxLCJUb29sdGlwTHVtcCI6MSwiVG9vbHRpcFBsb3RzIjoxLCJEcmFnb25BdXJhSW5mbyI6MSwiVG9vbHRpcEFzY2VuZEJ1dHRvbiI6MSwiU3RhdHMiOjEsIk1pc3NpbmdVcGdyYWRlcyI6MCwiVXBTdGF0cyI6MSwiVGltZUZvcm1hdCI6MCwiRGV0YWlsZWRUaW1lIjoxLCJHcmltb2lyZUJhciI6MSwiSGVhdmVubHlDaGlwc1RhcmdldCI6MSwiU2hvd01pc3NlZEdDIjowLCJTY2FsZSI6MywiU2NhbGVEZWNpbWFscyI6MiwiU2NhbGVTZXBhcmF0b3IiOjAsIlNjYWxlQ3V0b2ZmIjo5OTk5OTksIkNvbG9ycyI6eyJCbHVlIjoiIzRiYjhmMCIsIkdyZWVuIjoiIzAwZmYwMCIsIlllbGxvdyI6IiNmZmZmMDAiLCJPcmFuZ2UiOiIjZmY3ZjAwIiwiUmVkIjoiI2ZmMDAwMCIsIlB1cnBsZSI6IiNmZjAwZmYiLCJHcmF5IjoiI2IzYjNiMyIsIlBpbmsiOiIjZmYxNDkzIiwiQnJvd24iOiIjOGI0NTEzIn0sIlNvcnRCdWlsZGluZ3MiOjAsIlNvcnRVcGdyYWRlcyI6MCwiR0NUaW1lciI6MSwiRmF2aWNvbiI6MSwiV3JpbmtsZXJCdXR0b25zIjoxLCJCdWxrQnV5QmxvY2siOjAsIkhlYWRlciI6eyJCYXJzQ29sb3JzIjowLCJDYWxjdWxhdGlvbiI6MCwiTm90aWZpY2F0aW9uIjowLCJOb3RpZmljYXRpb25HZW5lcmFsIjowLCJOb3RpZmljYXRpb25HQyI6MCwiTm90aWZpY2F0aW9uRkMiOjAsIk5vdGlmaWNhdGlvblNlYSI6MCwiTm90aWZpY2F0aW9uR2FyZCI6MCwiTm90aWZpY2F0aW9uTWFnaSI6MCwiTm90aWZpY2F0aW9uV3JpbmsiOjAsIk5vdGlmaWNhdGlvbldyaW5rTWF4IjowLCJUb29sdGlwIjoxLCJTdGF0aXN0aWNzIjowLCJOb3RhdGlvbiI6MCwiTWlzY2VsbGFuZW91cyI6MSwiTHVja3kiOjAsIkNoYWluIjowLCJTcGVsbHMiOjAsIkdhcmRlbiI6MCwiUHJlc3RpZ2UiOjAsIldyaW5rIjoxLCJTZWEiOjAsIk1pc2MiOjAsIkluZm9UYWIiOjF9fSwidmVyc2lvbiI6IjIuMDMxLjUifTs%3D%21END%21

**Comment by DanielNoord** [comment]
Going to fix this immediately!

**Comment by DanielNoord** [comment]
Should be fixed!
But let me know if a problem still persists!
