### ISSUE TITLE
All time deficits showing infinity

### ISSUE THREAD

**Issue by EmoBurrito** [Aktanusa/CookieMonster#657]
**Describe the bug**
All time deficits are showing as infinity.
![image](https://user-images.githubusercontent.com/22356231/111075291-f7b4e180-84ac-11eb-8c2d-1b54fb4d5445.png)

Mousing over the Legacy button causes the tooltip window to infinitely grow with the same information.
![image](https://user-images.githubusercontent.com/22356231/111075277-df44c700-84ac-11eb-911b-e2af105b39cd.png)

These bugs showed up on start as of this morning. I was not having this bug last night. I let the game run for 10 minutes to see if it maybe had something to do with a "last five minutes" timer but it seems to still be happening even after running for several minutes.

**To Reproduce**
The steps needed to reproduce the behavior:
1. Start Cookie Clicker
2. Turn on Cookie Monster

**Save file**
[666MAFIABakery.txt](https://github.com/Aktanusa/CookieMonster/files/6137038/666MAFIABakery.txt)

**Comment by DanielNoord** [comment]
The first bug you reported has been fixed with #654.
The repeating elements of the ascend tooltip have been fixed with #657

**Comment by EmoBurrito** [comment]
Just reloaded and confirming bugs are fixed. Thank you for your efforts and this helpful tool.
