### ISSUE TITLE
"Pop all wrinklers" button pops wrinklers who haven't yet reached the cookie

### ISSUE THREAD

**Issue by CptHampton** [Aktanusa/CookieMonster#66]
Just noticed this egg hunting. If you click "pop all," it also pops any wrinklers that might still be approaching the cookie. If a wrinkler hasn't reached the cookie yet, it doesn't have any chance to drop upgrades. It would be helpful (although, admittedly, only mildly so) to add a check that the button only pops wrinklers with cookies sucked > 0.

**Comment by Aktanusa** [comment]
I guess so... it is a minor thing about the button that I didn't think of implementing logic to fix.  Pretty good idea.

**Comment by Aktanusa** [comment]
Added in Version 2.4
