### ISSUE TITLE
Fortune appearance breaks Cookie Monster

### ISSUE THREAD

**Issue by jeffslutzky** [Aktanusa/CookieMonster#660]
**Describe the bug**
Whenever a green fortune appears at the top of the screen and I click on it, the game freezes. Then I reload the page, and the fortune is gone and I haven't obtained it.

**Comment by DanielNoord** [comment]
I will try to fix this asap.
Could you share your save? Makes it easier to debug the problem for me!

**Comment by jeffslutzky** [comment]
Sure, here you go:

Mi4wMzF8fDE2MTU3NDE3NzM0MDU7MTU5MTU1Nzk5OTI4NDsxNjE1NzQzMjE2MzI1O1Rpbm1hbmljO213YXp0fDAxMTEwMDAwMDAwMDAwMDAwMTAwMHw2LjU3Mjg2NDg4NTUyODIxM2UrNDk7NS43NTA0MzMwNjQ3NzI1NzM1ZSs1MDsyNTA7MzA4OTk7NS41MzU3MzgzMjkwNzk3MTllKzUwOzk0MDQ7MTsyMjs3Ljc4MTg3MjA5OTc3OTk5MmUrNTY7MTswOzA7NzA7Mjk2MzsxMTE7MzsyLjIxMTM5NDk4OTg0ODkwODNlKzQ2OzA7MTQ7NDsyNTU0MzA3OzI7Y2hyaXN0bWFzOzIuODcyMzU0Nzc0MjU3NjI4N2UrNDY7Mjs5MTk4MDI3MzQxNjE3NjQ7OTE3NjE1ODgzOTczNjcyOzIxODY4NTAxODgwOTI7MDswOzY3OTs2NTg7NDk3OzcxNjs2Nzg7MjU7MTU7MTsxOzM0OzA7MDsxOzM0MjsxNjE1Njc3MjgyNjQ2OzA7MDs7NDE7MDswOzguNjc3ODA4OTg1NjcyNDY4ZSs0NTt8NzgwLDI1NjAsMS41MjcxODMwNDA3MDcxMzc4ZSs0Nyw0LCwwLDc4MDs3NzAsMTEyMCwzLjY5MzkwNTA2NjMwNTU3ZSs0NSw0LCwxLDc3MDs3MzAsMTA4MSw0LjY3MzczNDY2MjE2OTQ3M2UrNDMsMTAsMTYxNTc0MzI3MzU2NDoyOjE2MTU3NDI4NTczMTg6MDowOjE2MjY6MToyOjE2MTU3NDE3NzM0MzA6IDExMTExMTAwMDAwMTAxMDAwMDAwMDAwMTAwMDAwMDAwMDAgNjoxODo2OjIzOjY6MTM6NjoyMTo2OjIwOjY6MjA6NjoxOTo2OjE1OjY6MTM6NjoyMDo2OjE2OjY6MTY6NjoxNjo2OjE5OjY6MjI6NjoxNjo2OjIzOjY6MTY6NjoyNTo2OjI1OjY6MjQ6NjoyNTo2OjIxOjY6MjQ6NjoyNjo2OjE1OjY6MjI6NjoyNjo2OjEwOjY6MTg6NjoyMTo2OjIxOjY6MTg6NjoxOTo2OjE4OjY6MTg6LDAsNzMwOzcyMCwxMDcwLDQuMjU3OTM1NDc2ODg5MjAxZSs0NSwzLCwxLDcyMDs3MDAsMTA1MCw1LjU3NTI5NTg0MjEyNDQ5MzVlKzQ0LDMsLDEsNzAwOzY4MCwxMDMwLDEuMTY3MjI0NTkzODE2NzYyZSs0NCwzLDA6MDoxOjA6MDogMTEwNzo1OjM6NDUxOjA6MDowITI3MDc6MTo0OjMxOjA6MDowITMzODE6MDoxOjgyMjowOjA6MCEzNjM0OjI6LTQ4OjkxMDowOjA6MCE0OTgxOjI6LTYzOjYxOjA6MDowITU5Mzg6MjotMTI6OTQxOjA6MDowITY2ODY6MjotMjI6MjUwOjA6MDowITg2MjQ6MTozNDoxMDowOjA6MCE4NTE3OjI6LTU2OjgzNzowOjA6MCE3OTI2OjQ6LTEwNDoxODY6MDowOjAhMTE1MTc6MToyMjo1OTQ6MDowOjAhMTIyNzE6MTo0OjE3MTowOjA6MCExMzUwOToxOjE1OjQ2NDowOjA6MCExNDY2ODoxOjMyOjI4MTowOjA6MCExNDU5NjoyOi0zMjo3MjY6MDowOjAhMTY4NDI6NTo1Njo3NzY6MDowOjAhIDAsMSw2ODA7NjcwLDEwMjAsNC42MjY0MzkyMDAwOTEzMTRlKzQ0LDMsMi8xMC8tMSAxIDE2MTU3NDE4MzE1MDMgMSwxLDY3MDs2NDAsOTkwLDEuNTEyNzM0MjEwOTI4MDcyNGUrNDQsMTAsNjEuNDI5OTU4MjgwODQ0MDUgMCAyMTE4IDEsMCw2NDA7NjMwLDk4MCw0LjM4MTQ0Nzk5NDkwMzQwMmUrNDMsMywsMSw2MzA7NjEwLDk2MCwyLjIxNjYzMjA3NjYyMzA1N2UrNDQsMywsMSw2MTA7NTkwLDk0MCwyLjkwODg3MzgyNDQ0MDY2MTVlKzQ2LDMsLDEsNTkwOzU3MCw5MjAsNy40ODExMTM0MzQ0Njg4N2UrNDUsNCwsMSw1NzA7NTUwLDkwMCw2Ljk1OTQxOTg1MzM4NzgzN2UrNDYsNCwsMSw1NTA7NTMwLDg4MCwzLjcyMzMwNzYxODk3ODU3NGUrNDcsNCwsMSw1MzA7NTEwLDg2MCw5LjAyNjIxNzI3NzM0Mjc3N2UrNDcsNCwsMSw1MTA7NTAwLDg1MCwzLjIyNTkwODIzNzA2Mzk4N2UrNDgsNCwsMSw1MDA7NDYwLDgxMCw5LjA2Nzg4MTg3MTg5MDI5OGUrNDcsMTAsLDEsNDYwOzQ1MCw4MDAsNS45Mjc5MDkzMTYwNTE1MzFlKzQ4LDEwLCwxLDQ1MDt8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMTExMTExMTEwMDExMTExMTAwMDAwMDExMDAxMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTAwMDAxMTAwMDAxMTExMTEwMDExMDAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMDEwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDEwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDEwMTExMTExMTEwMDAwMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTAwMDAxMTAwMTExMTExMDAxMTAwMTEwMDAwMDAwMDAwMDAxMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDExMTExMTExMTEwMDAwMDAwMDExMTExMTExfDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDEwMDAwMTAwMDAwMDExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTAwMDAwMDEwMTExMDAwMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTEwMTExMTExMTExMTEwMDExMTExMTExMDEwMDAwMDB8fENvb2tpZU1vbnN0ZXI6eyJzZXR0aW5ncyI6eyJCb3RCYXIiOjAsIlRpbWVyQmFyIjoxLCJUaW1lckJhclBvcyI6MCwiQnVpbGRDb2xvciI6MCwiQnVsa0J1aWxkQ29sb3IiOjAsIkNvbG9yUFBCdWxrTW9kZSI6MCwiVXBCYXJDb2xvciI6MCwiVXBncmFkZUJhckZpeGVkUG9zIjowLCJDYWxjV3JpbmsiOjAsIkNQU01vZGUiOjEsIkF2Z0NQU0hpc3QiOjMsIkF2Z0NsaWNrc0hpc3QiOjAsIlRvb2xXYXJuQm9uIjowLCJHQ05vdGlmaWNhdGlvbiI6MCwiR0NGbGFzaCI6MCwiR0NTb3VuZCI6MCwiR0NWb2x1bWUiOjEwMCwiR0NTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzY2LzY2NzE3XzkzMTY1NS1scS5tcDMiLCJGb3J0dW5lTm90aWZpY2F0aW9uIjowLCJGb3J0dW5lRmxhc2giOjAsIkZvcnR1bmVTb3VuZCI6MSwiRm9ydHVuZVZvbHVtZSI6MTAwLCJGb3J0dW5lU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNzQvMTc0MDI3XzMyNDI0OTQtbHEubXAzIiwiU2VhTm90aWZpY2F0aW9uIjowLCJTZWFGbGFzaCI6MCwiU2VhU291bmQiOjAsIlNlYVZvbHVtZSI6MTAwLCJTZWFTb3VuZFVSTCI6Imh0dHBzOi8vd3d3LmZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMjEvMTIxMDk5XzIxOTMyNjYtbHEubXAzIiwiR2FyZEZsYXNoIjowLCJHYXJkU291bmQiOjAsIkdhcmRWb2x1bWUiOjEwMCwiR2FyZFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTAzLzEwMzA0Nl84NjE3MTQtbHEubXAzIiwiTWFnaWNOb3RpZmljYXRpb24iOjAsIk1hZ2ljRmxhc2giOjAsIk1hZ2ljU291bmQiOjAsIk1hZ2ljVm9sdW1lIjoxMDAsIk1hZ2ljU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8yMjEvMjIxNjgzXzEwMTUyNDAtbHEubXAzIiwiV3JpbmtsZXJOb3RpZmljYXRpb24iOjAsIldyaW5rbGVyRmxhc2giOjAsIldyaW5rbGVyU291bmQiOjAsIldyaW5rbGVyVm9sdW1lIjoxMDAsIldyaW5rbGVyU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMjQvMTI0MTg2XzgwNDMtbHEubXAzIiwiV3JpbmtsZXJNYXhOb3RpZmljYXRpb24iOjAsIldyaW5rbGVyTWF4Rmxhc2giOjAsIldyaW5rbGVyTWF4U291bmQiOjAsIldyaW5rbGVyTWF4Vm9sdW1lIjoxMDAsIldyaW5rbGVyTWF4U291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNTIvMTUyNzQzXzE1NjYzLWxxLm1wMyIsIlRpdGxlIjoxLCJUb29sdGlwQnVpbGRVcCI6MCwiVG9vbHRpcEFtb3IiOjAsIlRvb2xXYXJuTHVja3kiOjAsIlRvb2xXYXJuTHVja3lGcmVuenkiOjAsIlRvb2xXYXJuQ29uanVyZSI6MCwiVG9vbFdhcm5FZGlmaWNlIjowLCJUb29sV2FyblBvcyI6MSwiVG9vbHRpcEdyaW0iOjEsIlRvb2xXcmluayI6MCwiVG9vbHRpcEx1bXAiOjEsIkRyYWdvbkF1cmFJbmZvIjoxLCJTdGF0cyI6MCwiTWlzc2luZ1VwZ3JhZGVzIjowLCJVcFN0YXRzIjoxLCJUaW1lRm9ybWF0IjowLCJEZXRhaWxlZFRpbWUiOjEsIkdyaW1vaXJlQmFyIjoxLCJTY2FsZSI6MCwiU2NhbGVEZWNpbWFscyI6MiwiU2NhbGVTZXBhcmF0b3IiOjAsIlNjYWxlQ3V0b2ZmIjo5OTk5OTksIkNvbG9ycyI6eyJCbHVlIjoiI2ZmZmYwMCIsIkdyZWVuIjoiIzAwZmYwMCIsIlllbGxvdyI6IiNmZmZmMDAiLCJPcmFuZ2UiOiIjZmY3ZjAwIiwiUmVkIjoiI2ZmMDAwMCIsIlB1cnBsZSI6IiNmZjAwZmYiLCJHcmF5IjoiI2IzYjNiMyIsIlBpbmsiOiIjZmYxNDkzIiwiQnJvd24iOiIjOGI0NTEzIn0sIlNvcnRCdWlsZGluZ3MiOjAsIlNvcnRVcGdyYWRlcyI6MCwiR0NUaW1lciI6MSwiRmF2aWNvbiI6MSwiV3JpbmtsZXJCdXR0b25zIjowLCJIZWFkZXIiOnsiQmFyc0NvbG9ycyI6MSwiQ2FsY3VsYXRpb24iOjEsIk5vdGlmaWNhdGlvbiI6MSwiTm90aWZpY2F0aW9uR0MiOjEsIk5vdGlmaWNhdGlvbkZDIjoxLCJOb3RpZmljYXRpb25TZWEiOjEsIk5vdGlmaWNhdGlvbkdhcmQiOjEsIk5vdGlmaWNhdGlvbk1hZ2kiOjEsIk5vdGlmaWNhdGlvbldyaW5rIjoxLCJOb3RpZmljYXRpb25Xcmlua01heCI6MSwiVG9vbHRpcCI6MSwiU3RhdGlzdGljcyI6MSwiTm90YXRpb24iOjEsIk1pc2NlbGxhbmVvdXMiOjEsIkx1Y2t5IjoxLCJTcGVsbHMiOjEsIkNoYWluIjoxLCJQcmVzdGlnZSI6MSwiV3JpbmsiOjEsIlNlYSI6MSwiTWlzYyI6MSwiTm90aWZpY2F0aW9uR2VuZXJhbCI6MSwiR2FyZGVuIjoxLCJJbmZvVGFiIjoxfSwiVG9vbHRpcEluZm8iOjAsIlRvb2xXYXJuQ29uanVyZUZyZW56eSI6MCwiVGltZXJCYXJPdmVybGF5IjoxLCJQUEV4Y2x1ZGVUb3AiOjAsIlBQU2Vjb25kc0xvd2VyTGltaXQiOjAsIlBQT25seUNvbnNpZGVyQnV5YWJsZSI6MCwiR2VuZXJhbFNvdW5kIjoxLCJUb29sdGlwQnVpbGRVcGdyYWRlIjowLCJUb29sV2FyblVzZXIiOjAsIlRvb2x0aXBXcmluayI6MCwiVG9vbHRpcFBsb3RzIjoxLCJUb29sdGlwQXNjZW5kQnV0dG9uIjoxLCJIZWF2ZW5seUNoaXBzVGFyZ2V0IjoxLCJTaG93TWlzc2VkR0MiOjEsIkJ1bGtCdXlCbG9jayI6MH0sInZlcnNpb24iOiIyLjAzMS41In07%21END%21

**Comment by DanielNoord** [comment]
Should be fixed now!

**Comment by jeffslutzky** [comment]
Yes, appears to be working now - thanks!
