### ISSUE TITLE
Total Wrinkler Reward calculation bug

### ISSUE THREAD

**Issue by Th3F4i1Ur3** [Aktanusa/CookieMonster#669]
Currently the bug shows a ridiculously inflated value for the currently stored cookies to be earned by popping all Wrinklers. in my case it shows that i can get 8 nonillion cookies for popping yet my largest wrinkler only has 48 septillion. even with all wrinklers holding that amount i should only be getting 480 sept, nowhere near the 8 non it shows

**To Reproduce**
The steps needed to reproduce the behavior:
1. have multiple wrinklers
2. turn on calculate with wrinklers

**Screenshots**
![cookieclicker bug](https://user-images.githubusercontent.com/80658819/111096094-c835c180-850c-11eb-876d-43ea4c108128.PNG)

**Save file**
I don't think it's my save file but i'll post it here just in case

Mi4wMzF8fDE0NTc5MzMxMDY1NTg7MTQ1NzkzMzEwNjU2MzsxNjE1Nzc1NjYyMTA5O1dha2UgbiBCYWtlO2VrdWR5fDAwMTEwMTAwMDAxMDAwMDAwMDAxMHw5LjYwMjg0Nzg3OTcwNDYzZSsyNTs0Ljk3NTc2MzY2NTAwNjQ5NWUrMjc7NjQ4ODI7ODE4OzEuMDAyMjk2MjIwODY1ODg3MWUrMjQ7NDYzMzAyOzA7MDswOzM7MTg7MDswOy0xOzA7ODE4OzQuMTYwNjUwOTQ3MzcwNzY3NWUrMjY7MjIyNTsxNDsyODQ7LTE7MDs7NC4wMDcxOTQxODU5MDM0MDVlKzI2OzEwOzA7MDswOzA7MDstMTstMTstMTstMTstMTswOzA7MDswOzA7MDswOzc7MTM1MzsxNjE1NzI3NTU0NjU1OzA7MDs7NDE7MDswOzM0OTExNTI1NjU2ODg4MzEwMDAwMDt8MzU5LDM2NSwxLjMzMjkwMzc0NTA1ODYxOWUrMjQsMzUsLDAsMzU5OzM4MSwzODYsOC4yNzAxMTQ3MzM1NjUyMzNlKzIzLDEsLDAsMzgxOzMxMiwzMTUsNDY2Mzg1MzE5MTMwNjY0MTAwLDksMTYxMzcyMDM4MDAxMDoxOjE1NzEzMjMxOTk2MDA6MTozNjQ6MzY0OjE6MDoxNTMzNTI2ODM3MjQzOiAxMTExMTAwMDExMTExMTAwMDAwMDAwMDExMTAwMTAwMDAwIDA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDoxOjE2OjE6ODg6NDo0NjowOjA6MDowOjA6MDoxOjgzOjA6MDoxOjA6MDowOjA6MDowOjA6MToyNDoxOjE1OjE6NDg6NDo3OjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDosMCwzMTI7Mjk1LDI5OSwxNDYzODEwMjU5MTA1MTQ2MDAwLDEsLDAsMjk1OzI3OCwyODMsNDc0NTIzNTQxNjE0NTc1ODAwMCwxNywsMCwyNzg7MjYxLDI2NSwxMzk5NDE3OTEwNDUxMjYxODAwMCwyLDA6MDoxOjA6MDogMzY3OjQ6LTk2OjY0MTowOjA6MCExNDQ5OjQ6LTM2Ojg4MTowOjA6MCEzMTc4OjQ6LTEwNToxODk6MDowOjAhNjY3NToxOjU2Ojc0MzowOjA6MCEyMDQwOjU6NzM6NTE2OjA6MDowITEwMjk6NDotMTM5OjIwMzowOjA6MCE2NDk0OjE6Mjg6NjQxOjA6MDowITgyODY6MDo5OjU5OTowOjA6MCE2Mjk1OjI6LTU1OjEzOjA6MDowITE2NDg6NDotMTc4OjgxOjA6MDowITExODMwOjU6LTk6MTY4OjA6MDowITEwODM6NDotMTcwOjIwNjowOjA6MCExMzc4NzoxOjEzOjQwODowOjA6MCExNDg2MDoxOjk6Mjc2OjA6MDowITE0NTgxOjU6NTg6NDU0OjA6MDowITEzMDUzOjI6LTQ0OjQ2MTowOjA6MCEgMCwwLDI2MTsyNDIsMjQ1LDYzNjc2NzExNDMzMTkxOTY1MDAwLDIsOC8wLzkgMyAxNjE0NjEwODMyMDEyIDEsMCwyNDI7MjIyLDIyNCwyOTQzNjY5MDMyMjk5ODQ0NDAwMDAsOSw3NSAxMjk4IDEyOTggMSwwLDIyMjsyMDMsMjA4LDg0MzM2MjkzODQ3NDI4MTQwMDAwMCwxLCwwLDIwMzsxODQsMTg5LDQuMDYyMzAxOTAxOTUxMzI1NGUrMjEsMSwsMCwxODQ7MTc3LDE4MCwyLjQyOTQ0MTg0NzYzOTUzNDVlKzIyLDEsLDAsMTc3OzE0OCwxNTUsNi44NDMzNDE0ODY1ODU5MzZlKzIyLDEsLDAsMTQ4OzE0MywxNDcsNC4zMTI4NTUyMDM0MTc2NDZlKzIzLDMsLDAsMTQzOzEzOSwxNDEsMi44MDcxMTg1NzUwODMyNDVlKzI0LDYsLDAsMTM5OzEzNSwxNDAsMS44ODg2NTA3ODM1Mjg0NTFlKzI1LDYsLDAsMTM1OzEzMSwxMzIsMS4xNDA4Njg1NTgyMDI4MzRlKzI2LDE0LCwwLDEzMTsxMDEsMTAzLDIuNzk0NDg0MjY3NDk5ODIxNWUrMjYsMTAsLDAsMTAxOzcxLDcxLDQuMTY4MjE1NzM3MTcxMTUzNGUrMjYsMjIsLDAsNzE7fDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMDAxMTExMTEwMDEwMTExMTExMTExMTExMDAxMTAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTExMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMTExMTAwMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTEwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAxMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAxMTExMTExMTExMTEwMDAwMDAwMDAwMDAxMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMTExMTExMTExMTExMDAwMDAwMDAxMDAwMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMTAxMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMXwxMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMDAxMTExMTAwMDAwMDAwMTExMDExMTExMTExMTExMTExMTExMDAxMTEwMTEwMTAwMTExMTExMTExMTAwMTExMDExMTExMDAwMDAxMTAwMDAwMTExMDExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMTExMTExMDAwMDAwMDAwMTEwMDAwMDAxMTExMTExMTAwMDAwMTEwMDAwMTAwMDAwMDAwMDAwMDExMDExMTExMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDEwMDAwMDAwMDAxMTEwMTExMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMTAxMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDExMTAwMDAwMDAwMDAwMTAwMDEwMTExMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwfHxDb29raWVNb25zdGVyOnsic2V0dGluZ3MiOnsiQm90QmFyIjoxLCJUaW1lckJhciI6MSwiVGltZXJCYXJQb3MiOjAsIlRpbWVyQmFyT3ZlcmxheSI6MiwiQnVpbGRDb2xvciI6MSwiQnVsa0J1aWxkQ29sb3IiOjAsIlVwQmFyQ29sb3IiOjEsIlVwZ3JhZGVCYXJGaXhlZFBvcyI6MSwiQ2FsY1dyaW5rIjoxLCJDUFNNb2RlIjoxLCJBdmdDUFNIaXN0IjozLCJBdmdDbGlja3NIaXN0IjowLCJDb2xvclBQQnVsa01vZGUiOjEsIlBQRXhjbHVkZVRvcCI6MCwiUFBTZWNvbmRzTG93ZXJMaW1pdCI6MCwiUFBPbmx5Q29uc2lkZXJCdXlhYmxlIjowLCJUb29sV2FybkJvbiI6MCwiVGl0bGUiOjEsIkdlbmVyYWxTb3VuZCI6MSwiR0NOb3RpZmljYXRpb24iOjAsIkdDRmxhc2giOjEsIkdDU291bmQiOjAsIkdDVm9sdW1lIjoxMDAsIkdDU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy82Ni82NjcxN185MzE2NTUtbHEubXAzIiwiRm9ydHVuZU5vdGlmaWNhdGlvbiI6MCwiRm9ydHVuZUZsYXNoIjoxLCJGb3J0dW5lU291bmQiOjAsIkZvcnR1bmVWb2x1bWUiOjEwMCwiRm9ydHVuZVNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTc0LzE3NDAyN18zMjQyNDk0LWxxLm1wMyIsIlNlYU5vdGlmaWNhdGlvbiI6MCwiU2VhRmxhc2giOjEsIlNlYVNvdW5kIjoxLCJTZWFWb2x1bWUiOjEwMCwiU2VhU291bmRVUkwiOiJodHRwczovL3d3dy5mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTIxLzEyMTA5OV8yMTkzMjY2LWxxLm1wMyIsIkdhcmRGbGFzaCI6MSwiR2FyZFNvdW5kIjowLCJHYXJkVm9sdW1lIjoxMDAsIkdhcmRTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEwMy8xMDMwNDZfODYxNzE0LWxxLm1wMyIsIk1hZ2ljTm90aWZpY2F0aW9uIjowLCJNYWdpY0ZsYXNoIjoxLCJNYWdpY1NvdW5kIjowLCJNYWdpY1ZvbHVtZSI6MTAwLCJNYWdpY1NvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMjIxLzIyMTY4M18xMDE1MjQwLWxxLm1wMyIsIldyaW5rbGVyTm90aWZpY2F0aW9uIjowLCJXcmlua2xlckZsYXNoIjoxLCJXcmlua2xlclNvdW5kIjowLCJXcmlua2xlclZvbHVtZSI6MTAwLCJXcmlua2xlclNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTI0LzEyNDE4Nl84MDQzLWxxLm1wMyIsIldyaW5rbGVyTWF4Tm90aWZpY2F0aW9uIjowLCJXcmlua2xlck1heEZsYXNoIjoxLCJXcmlua2xlck1heFNvdW5kIjowLCJXcmlua2xlck1heFZvbHVtZSI6MTAwLCJXcmlua2xlck1heFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTUyLzE1Mjc0M18xNTY2My1scS5tcDMiLCJUb29sdGlwQnVpbGRVcGdyYWRlIjoxLCJUb29sdGlwQW1vciI6MCwiVG9vbFdhcm5MdWNreSI6MSwiVG9vbFdhcm5MdWNreUZyZW56eSI6MSwiVG9vbFdhcm5Db25qdXJlIjoxLCJUb29sV2FybkNvbmp1cmVGcmVuenkiOjEsIlRvb2xXYXJuRWRpZmljZSI6MSwiVG9vbFdhcm5Vc2VyIjowLCJUb29sV2FyblBvcyI6MSwiVG9vbHRpcEdyaW0iOjEsIlRvb2x0aXBXcmluayI6MSwiVG9vbHRpcEx1bXAiOjEsIlRvb2x0aXBQbG90cyI6MSwiRHJhZ29uQXVyYUluZm8iOjEsIlRvb2x0aXBBc2NlbmRCdXR0b24iOjEsIlN0YXRzIjoxLCJNaXNzaW5nVXBncmFkZXMiOjEsIlVwU3RhdHMiOjEsIlRpbWVGb3JtYXQiOjAsIkRldGFpbGVkVGltZSI6MSwiR3JpbW9pcmVCYXIiOjEsIkhlYXZlbmx5Q2hpcHNUYXJnZXQiOjEsIlNob3dNaXNzZWRHQyI6MSwiU2NhbGUiOjIsIlNjYWxlRGVjaW1hbHMiOjIsIlNjYWxlU2VwYXJhdG9yIjowLCJTY2FsZUN1dG9mZiI6OTk5OTk5LCJDb2xvcnMiOnsiQmx1ZSI6IiM0YmI4ZjAiLCJHcmVlbiI6IiMwMGZmMDAiLCJZZWxsb3ciOiIjZmZmZjAwIiwiT3JhbmdlIjoiI2ZmN2YwMCIsIlJlZCI6IiNmZjAwMDAiLCJQdXJwbGUiOiIjZmYwMGZmIiwiR3JheSI6IiNiM2IzYjMiLCJQaW5rIjoiI2ZmMTQ5MyIsIkJyb3duIjoiIzhiNDUxMyJ9LCJTb3J0QnVpbGRpbmdzIjowLCJTb3J0VXBncmFkZXMiOjAsIkdDVGltZXIiOjEsIkZhdmljb24iOjEsIldyaW5rbGVyQnV0dG9ucyI6MSwiQnVsa0J1eUJsb2NrIjowLCJIZWFkZXIiOnsiQmFyc0NvbG9ycyI6MSwiQ2FsY3VsYXRpb24iOjEsIk5vdGlmaWNhdGlvbiI6MSwiTm90aWZpY2F0aW9uR2VuZXJhbCI6MSwiTm90aWZpY2F0aW9uR0MiOjEsIk5vdGlmaWNhdGlvbkZDIjoxLCJOb3RpZmljYXRpb25TZWEiOjEsIk5vdGlmaWNhdGlvbkdhcmQiOjEsIk5vdGlmaWNhdGlvbk1hZ2kiOjEsIk5vdGlmaWNhdGlvbldyaW5rIjoxLCJOb3RpZmljYXRpb25Xcmlua01heCI6MSwiVG9vbHRpcCI6MSwiU3RhdGlzdGljcyI6MSwiTm90YXRpb24iOjEsIk1pc2NlbGxhbmVvdXMiOjEsIkx1Y2t5IjoxLCJDaGFpbiI6MSwiU3BlbGxzIjoxLCJHYXJkZW4iOjEsIlByZXN0aWdlIjoxLCJXcmluayI6MSwiU2VhIjoxLCJNaXNjIjoxLCJJbmZvVGFiIjoxfX0sInZlcnNpb24iOiIyLjAzMS41In07%21END%21

**Comment by Th3F4i1Ur3** [comment]
i forgot to mention it earlier because i don't think it's relevant but i have not yet done a single ascension despite running this save for several years so no heavenly upgrades.

**Comment by dhouck** [comment]
Same issue, < 20 day old run with all but one heavenly upgrade.  I saw the number suddenly jump up as a new wrinkler appeared, which it shouldn't do.  I think this has to be only the most recent release.

Also, for steps to reproduce: the part of the section in the screenshot above isn't specific to if wrinklers are included in calculations; this bug shows up both in expected popping and in the calculations with wrinklers.

**Comment by DanielNoord** [comment]
This has now been fixed! I'm getting the same results in calculation between 2.031.5 and 2.031.4 so I believe it is now correct!

**Comment by zelude** [comment]
![Screenshot_20210315_043122](https://user-images.githubusercontent.com/33736218/111133049-14522780-8548-11eb-9d20-498648c35efb.png)
Still happening with me on 2.031.5, but was fixed on refresh

**Comment by DanielNoord** [comment]
Is it still happening when you first open the browser? Or has it been fixed completely?

**Comment by dhouck** [comment]
It seems to work correctly for me now; thanks for the quick fix
