### ISSUE TITLE
Garden info on Stats screen displays incorrect "required" cookies amount.

### ISSUE THREAD

**Issue by sgoldeen** [Aktanusa/CookieMonster#675]
When viewing the Garden section of the Stats screen, the "cookies required for max" values are actually the max reward values. The cookies required for max are considerably higher (33.3x for Bakeberries and Chocoroots, 25x for Queenbeet, 12.5x for Duketater).

The expected rewards when hovering the plants in your garden display the correct calculation is done to show the amount that will be gained based on current bank and CPS.

**Comment by DanielNoord** [comment]
I will take a look at this tonight and hope to push a hot fix tonight.

**Comment by dhouck** [comment]
(FYI: This is not caused by the recent update; I've seen it on .4 but forgot to file a report about it)
