### ISSUE TITLE
Standard option "Alt font OFF/ON" not working with Cookie Monster on

### ISSUE THREAD

**Issue by BigbyBoss** [Aktanusa/CookieMonster#677]
Hi,
As the title says, once i attach Cookie Monster to Cookie Clicker, the game resets to the default font, and turning the option on and off doesn't change it anymore.
![asd](https://user-images.githubusercontent.com/29706850/111222375-0c43c780-85dc-11eb-823e-05be834ba41f.png)

**Comment by DanielNoord** [comment]
This has been fixed! Sorry for the trouble!
