### ISSUE TITLE
The numbers on the bottom bar is jumping too fast

### ISSUE THREAD

**Issue by qingwen-guan** [Aktanusa/CookieMonster#686]
**Describe the function you'd like to see added to CookieMonster**
Let the number jump slower, for example once per second.

**Comment by qingwen-guan** [comment]
using a monospace font on the bottom bar might also make it prettier.

**Comment by DanielNoord** [comment]
Sadly, I won't change the refresh rate of the bottom bar. It is tied to the draw frames per second of the Game and I am not really in favor of displaying numbers that are not correct. By lowering the refresh rate we will lose accuracy.

I will look at some formatting/font of the bottom bar. I have been planning to add some margin between the columns for quite some time.
