### ISSUE TITLE
Documentation/Explanation of stats

### ISSUE THREAD

**Issue by davidak** [Aktanusa/CookieMonster#687]
Is there a documentation about the stats, so i know how to interpret them?

For example _Prestige_:
![Screenshot from 2021-03-16 22-15-11](https://user-images.githubusercontent.com/91113/111381250-bc313780-86a5-11eb-972d-cc963fae3b8a.png)

What does **reset bonus income** mean? There is a ? where i would expect a tooltip, but nothing happens.

How can these stats help me to decide when to ascend?

**Comment by DanielNoord** [comment]
Apparently those tooltips are broken. I will fix this in the next update which I expect in the near future!
