### ISSUE TITLE
Request: add 'heavenly chips earned' to 'rewards of popping your wrinklers' 

### ISSUE THREAD

**Issue by wrincewind** [Aktanusa/CookieMonster#69]
Say I have 1.5 million Heavenly Chips stored up, and i want to reset at or around 3 million. I can see that i'll earn, say, 10 nonillion cookies from popping my wrinklers, but how many heavenly chips will that earn me? I might be able to calculate it, but it would be nice to have this built in to the addon. 

Optimally i want to have my wrinkers wrinkling for as long as possible, then pop them when i'll earn exactly the number of chips i want, then sell everything, then open my chocolate egg, then reset, right?

**Comment by Aktanusa** [comment]
If you go over the ? icon in the Prestige Level stat, it already shows how much you would get with Wrinklers and Chocolate Egg.

The steps IMO are this:

1.  Change to aura to Earth Shatter (if you can)
2.  Sell all buildings (you will auto pop all Wrinklers when you sell all Grandmas)
3.  Buy buildings for achievements (optional)
4.  Buy Chocolate Egg

**Comment by wrincewind** [comment]
oh, so it does! I did not spot that - and yes, I use the Earth shatterer aura, I just missed mentioning that step. Thanks a lot!

**Comment by Aktanusa** [comment]
I should mention because it depends on Chocolate Egg for the MAX Prestige Level, the number fluctuates when you buy expensive buildings/upgrades.
