### ISSUE TITLE
Notation - setting number of decimals

### ISSUE THREAD

**Issue by jeffslutzky** [Aktanusa/CookieMonster#690]
This option does not seem to do anything - the number of decimals seems unchanged. Either that, or I have the wrong idea of what it does. I assumed that if you selected "3 decimals" you would see a number of cookies such as "125.000 trillion," or if you selected "2 decimals" you would see "125.00 trillion" - but in either case, the trailing zeros don't appear.

**Comment by DanielNoord** [comment]
Are you using one of the scales provided by Cookie Monster or are you using the Game's Setting Scale? The setting does not add trailing zero's to the Game's Setting Scale as to not interfere with any of the original code. I will update the description of the setting to tell this.
If you are using a Cookie Monster scale could you paste your save file? The setting seems to be working for my own save.

**Comment by jeffslutzky** [comment]
I'm using the default Game's Setting scale. I guess I don't understand what the decimal setting does.

**Comment by DanielNoord** [comment]
You can see it in action by temporarily changing to one of the other scales. It will work, probably like you expect it to do.
We don't want to mess with the original Game code so we don't check for the decimal setting when the user has set its scale to "Game's Setting Scale". Therefore in your case it is indeed not actually doing anything.

**Comment by jeffslutzky** [comment]
Ah, got it. Thanks!
