### ISSUE TITLE
Mod doesn't show first-highest pp building.

### ISSUE THREAD

**Issue by daman4567** [Aktanusa/CookieMonster#696]
Mod won't show a first-highest pp building anymore, only highlights a building in green with the "ignore 1st best" option enabled.  I have no reproduction steps, but I tried to delete cookie monster's data from my save and re-create it.  This undid my options, but didn't fix the issue so either it's a problem with my save file or it's a bug in the mod.

https://pastebin.com/6Bxa9uGD

**Comment by daman4567** [comment]
https://imgur.com/a/7pwXNeY

Here's a screenshot showing both the option to hide 1st, 2nd, and 3rd best, and the buildings sorted by pp, even though it's supposed to be greying out 3 buildings it's only doing it for 1, as if there were 2 imaginary buildings that it's taking into account as having the best pp of all.

**Comment by DanielNoord** [comment]
I am not behind a computer right now but could you check if there is not a green option in the buy 10 or buy 100 column? If not this is indeed a bug and I will look into fixing it soon!

**Comment by daman4567** [comment]
There is one in the buy 10 column, is this how the mod accommodates buying bulk for achievements?

**Comment by DanielNoord** [comment]
Yes! We changed the code for the colour coding to be more "correct". The Green colour coded building is the option which has the lowest. This could also be a "buy 10" or "buy 100" option. So when you ignore the 1st building it will ignore (for example) buy 1 Bank and then highlight buy 10 Cursors as green.
Hope this has explained it!
