### ISSUE TITLE
Cookies per second derived from clicks per second in statistics screen

### ISSUE THREAD

**Issue by brandonros** [Aktanusa/CookieMonster#698]
**Describe the function you'd like to see added to CookieMonster**

Not sure if this is a noob thing to do but, I only really spam clicking when I am in "clicked a golden cookie, frenzy active mode" or whatever. It'd be really cool to see clicks per second and cookies derived from clicks per second.

**Comment by DanielNoord** [comment]
We show clicks per second in the statistics screen under the "Miscellaneous" tab. 
We could add another line showing the cookies gained from clicking under it. I will plan this next release!
