### ISSUE TITLE
A counter about how many times you ascended (with at least 1 heavenly chip)

### ISSUE THREAD

**Issue by RandomNumbers09** [Aktanusa/CookieMonster#702]
**Describe the function you'd like to see added to CookieMonster**

**Additional files**
Add any other files such as save files or screenshots about the feature request here.

**Comment by DanielNoord** [comment]
I will need to check, but I am not sure if the Game actually stores this values.
If this is not the case Cookie Monster won't be able to add this feature as there is no way of counting ascensions when Cookie Monster is/was not loaded. I will look at the Game code to see if this is stored, but I must say I am not hopeful.

**Comment by davidak** [comment]
@RandomNumbers09 what do you mean? The game shows it under _Legacy started_.

![Screenshot from 2021-03-19 02-46-41](https://user-images.githubusercontent.com/91113/111720099-8931a400-885d-11eb-9a85-85c9173fd46b.png)

I would like to have more detail instead of "a long while ago", but the start date is probably not saved, else they would probably use it.

**Comment by DanielNoord** [comment]
Oh wow, I didn't even check this myself. I will see if the long time ago is actually no saved. I can't imagine it, so I might be able to change that to be more descriptive.

**Comment by mbsaerens** [comment]
That's odd. Mine says
```
legacy started: 3 years, 100 days, 8 hours, 45 minutes, 27 seconds ago, with 107 ascensions
```

**Comment by DanielNoord** [comment]
@davidak Could you share your save? There are some weird calculations and checks going on with this part of the original code and at first glance I don't really understand what it is trying to achieve. Maybe with your save it will become clearer.

**Comment by davidak** [comment]
@DanielNoord sorry for the late response. here it is: [goosecockBakery.txt](https://github.com/Aktanusa/CookieMonster/files/6250696/goosecockBakery.txt)

maybe the feature to show more details was added in a later version. so the data is missing in my save

**Comment by DanielNoord** [comment]
This is indeed the case. Sadly, I don't think there is a way to recover that data...
