### ISSUE TITLE
Create "favourite settings" section

### ISSUE THREAD

**Issue by TakGalaman** [Aktanusa/CookieMonster#727]
There are many options that I never change like font, number format, graphics, and others I change often like whether golden cookies should make a sound. It is annoying to scroll up and down through the options list to adjust those "favorite" options.

My request is to give the user the ability to mark options as "favorite" (probably using a star icon next to the name of the setting) and then a section within the options menu (at the top) where all the favorited options can be adjusted. 

For me I would favorite "Lower limit for PP", "Sort buildings by PP", "Average CPS by <amount of time>", "Ignore non-buyable", Golden cookie notification options, Farm tick notifications.

**Comment by davidak** [comment]
I think adding a star to each setting would clutter the settings even more.

There could be a button that open a dialog where you can select favorite settings that are then shown in a new section at the top.

**Comment by DanielNoord** [comment]
I have implemented this using stars. Could you give me some feedback on it?
You can test it by using the dev-branch version. This is possible by going to "Code", selecting the dev branch and copying the content of `CookieMonster.js` into your browser console.
