### ISSUE TITLE
Red and purple PP color indicators switched

### ISSUE THREAD

**Issue by kevin-pololu** [Aktanusa/CookieMonster#735]
Buildings and upgrades colored red have a **longer** payback period than purple-colored ones, which disagrees with the color legend. The cause appears to be a reversed comparison operator [here](https://github.com/Aktanusa/CookieMonster/blob/aebd62317b561925c1046458c4ff9baf20462213/src/Cache/PP/ColourOfPP.js#L29) (the `>` should be `<`).

**Comment by DanielNoord** [comment]
Good catch, will fix in next update.
