### ISSUE TITLE
Show Cookie clicks (all time)

### ISSUE THREAD

**Issue by davidak** [Aktanusa/CookieMonster#739]
**Describe the function you'd like to see added to CookieMonster**
I would like to see how many times i clicked on the big cookie. It is only shown for the current ascension, not all time (like other stats).

I think that is a very important stat since the game is about clicking the cookie.

Does anyone know why that is not in the game? Was it discussed with the games developers earlier?

Do you know if the data is in the save, so it could be added? (either in the game or this add-on)

**Comment by DanielNoord** [comment]
Sadly we can't do this. The game does not store this data and there is no way to know how many times you clicked the cookie in an ascension when Cookie Monster was not loaded. This means that we would be prone to display incorrect data.
