### ISSUE TITLE
Lucky! deficit warning does not take into account increase following purchase

### ISSUE THREAD

**Issue by Darthkiller2** [Aktanusa/CookieMonster#75]
As an example:
If the purchase of a building induces an increase of 5.31% in CPS, the number of cookies in bank required for optimal Lucky! will also increase by 5.31%. However, the warning does not take into account this increase when computing an eventual deficit. 

So sometimes I buy buildings and end up with a (small) deficit even though the warning wasn't showing. Would it be easy enough to account for that in the calculation of the warning?

**Comment by Aktanusa** [comment]
It's an option in Cookie Monster =).  Check it out.

**Comment by Darthkiller2** [comment]
Ah yes indeed! Thanks :)
Sorry for not having a closer look before writing this!

**Comment by Aktanusa** [comment]
Glad you found it =)
