### ISSUE TITLE
Timer background no longer black

### ISSUE THREAD

**Issue by ChallengerCode** [Aktanusa/CookieMonster#750]
The timer background is no longer black but transparent instead.

Seems to be caused by 02d49dca2e5b63662b1f095916cd414fd7a0c182 which changed the spelling of color stuff from american to british.

CSS and JavaScript both seem to insist on the american spelling though for "background-color", respecively "backgroundColor".

**TimerBar.style.backgroundColour = 'black';**

**Comment by ChallengerCode** [comment]
From the code this would also seem to affect UpgradeBar and BotBar, not sure what they are though.

**Comment by DanielNoord** [comment]
Fixed! Thank you :)

**Comment by ChallengerCode** [comment]
Wow, that was quick! Thank you! :D
