### ISSUE TITLE
Not Loading in Safari

### ISSUE THREAD

**Issue by Silvermann17** [Aktanusa/CookieMonster#753]
Since the latest update, I've been unable to use the bookmark method to activate Cookie Monster.

**Comment by DanielNoord** [comment]
Does it give an error? The link found in the README seems to point to a correct file. What is your bookmark?

**Comment by Silvermann17** [comment]
Doesn't give an error, just doesn't load.

Using the same bookmark as I was previously, the one found on the wiki:
`javascript:(function() {
    Game.LoadMod('https://aktanusa.github.io/CookieMonster/CookieMonster.js');
}());`

**Comment by DanielNoord** [comment]
Which browser are you using?

**Comment by Silvermann17** [comment]
Safari. Didn't know the browser would make a difference

**Comment by DanielNoord** [comment]
Seems to be Safari specific. Hope to fix this asap. In the mean time chrome seems to be working!

**Comment by Silvermann17** [comment]
Okay, thanks!

**Comment by DanielNoord** [comment]
Seems to be due to a bug in one of the imported libraries/modules, namely jscolor.
I'm opening an issue in their repository to see if they understand what is up.

**Comment by DanielNoord** [comment]
This should now be fixed! Can you confirm the mod works again on Safari?

**Comment by Silvermann17** [comment]
Yep, works just fine now, thanks!
