### ISSUE TITLE
Sometimes no building is highlighted as "best"

### ISSUE THREAD

**Issue by TakGalaman** [Aktanusa/CookieMonster#761]
There is always a building that offers the best PP, and I expect cookie monster to identify that building for me, but fairly often there is apparently no building that is highlighted in green

If I switch to "Buy 10" mode then there is a building identified in green.

**To Reproduce**
The steps needed to reproduce the behavior:
1. Look at the buildings on the right.
2. toggle buy mode to 10, 100. You should see that a building is in green only for the buy x10 mode
3. Check out the settings I have applied

**Screenshots**
![image](https://user-images.githubusercontent.com/31801070/113937978-90decb80-97bf-11eb-8096-b02a10d34465.png)

**Save file**
```
[Bakery no buildings green.txt](https://github.com/Aktanusa/CookieMonster/files/6274696/Bakery.no.buildings.green.txt)

**Comment by DanielNoord** [comment]
This means that the "most optimal building" is indeed to buy those 10x, as they have a lower pp value than any of the buy 1x buildings. You can sort the buildings by pp value so even when in buy 1x mode the most optimal building is still at the top of you only want to buy buildings in increments of 1.

**Comment by TakGalaman** [comment]
Is the outcome for me different if I click "buy 1" 10 times as opposed to clicking buy 10?

I see the value in denoting the best single action I could take, but it's not very useful to me if I have to switch to x10 and x100 and back to x1 all the time.

What do you think about having maybe another designation to separate the many yellow buildings visible on the "buy x1" screen. This other designation would be "best building purchase you can make for the current buy mode".

**Comment by DanielNoord** [comment]
No there is no difference.

If you set 'Sort buildings' to 'PP of x1 purchase' it will always put the building that is green at the top, even if you are on the x1 mode and the building is green for x10. This label is incorrect, that is why you probably didn't notice. I will change the label, but know that it does what you want! :)

The other designation is possible if you sort your buildings and is the other option called 'PP of selected bulk mode'.
