### ISSUE TITLE
Beta script not working anymore with 2.001

### ISSUE THREAD

**Issue by dorukayhan** [Aktanusa/CookieMonster#77]
CC Beta got updated to 2.001 today, and the script designed for 1.909 freezes the game.

What's causing the freeze?

**Comment by Aktanusa** [comment]
Surprise beta o_O.  I'll get to it tonight.

**Comment by Aktanusa** [comment]
Sorry for the delay... trying to get a new release out on live first

**Comment by dorukayhan** [comment]
Um, why not just spot the location of the bug and tell it here? That way I or someone else can fix it while you work on live version.

**Comment by Aktanusa** [comment]
I don't think it be that easy.  I'm very close to releasing anyway.  I'm just polishing up some stuff.  Should be tonight.

**Comment by Aktanusa** [comment]
Just an update, I went over the changes tonight and yea, it doesn't seem too easy.  I have to revamp a few things also due to how it works now.

**Comment by kyriene** [comment]
Thanks for the update, kinda figured it was being a bit of a pain.

**Comment by Aktanusa** [comment]
No problem.  I finally have more time to today to hopefully take a look at it.

**Comment by Aktanusa** [comment]
There, it's up for a mostly working version.  I won't close this until it's been fixed with one major bug.

**Comment by Aktanusa** [comment]
There, fixed the major bug, closing.
