### ISSUE TITLE
Suggestion: improved Frenzy calculations

### ISSUE THREAD

**Issue by webxro** [Aktanusa/CookieMonster#78]
I noticed the current calculations for Lucky and Lucky with frenzy don't seem to include the next upgrade/building bought and how much CPS it produces. 

I understand that adding this in the calculations might be confuse some users, perhaps a toggle would be more useful. 

Thanks.

**Comment by Aktanusa** [comment]
The warning includes this already.  It's an option.  I can't predict what one would buy next, so I don't know what to add to Lucky!

**Comment by webxro** [comment]
Ups... i didn't see it the first time i checked the options and here it is now. 

How do i close this suggestion thing ? 

BTW thanks for the quick reply. You rock.

**Comment by Aktanusa** [comment]
Thanks.  You can close it with the close and comment button, or I can close it for you.

**Comment by Aktanusa** [comment]
Thanks to you, I noticed I need to group that option with the two new options coming up relating to calculation.  =)
