### ISSUE TITLE
[Firefox] Sorting upgrades not working

### ISSUE THREAD

**Issue by puggan** [Aktanusa/CookieMonster#780]
**Describe the bug**
Sorting Upgrades seams to not work at all.

**To Reproduce**
The steps needed to reproduce the behavior:
1. Turn Upgrade sorting to PP
2. Wait until you have Blue-PP upgrades, and see that they not sorted before the yellow.

**Screenshots**
![cookie_clicker_bug](https://user-images.githubusercontent.com/866668/116780319-3eba5e80-aa7c-11eb-9dfb-0b39e7d21dc5.png)

**Save file**
[SundragonCookiesBakery.txt](https://github.com/Aktanusa/CookieMonster/files/6409435/SundragonCookiesBakery.txt)

**Comment by DanielNoord** [comment]
I loaded your save but the setting seems to work on my end. However, it does show a different upgrade in the first slot. 
I also have a different building showing on top (as the screenshot shows).
<img width="595" alt="Schermafbeelding 2021-05-01 om 20 06 10" src="https://user-images.githubusercontent.com/13665637/116791145-aee6d580-aab8-11eb-95f4-84b954ded08e.png">

I'm not quite sure what causes the differences in calculation.. Does the console show any errors? Or do you have any other mods loaded?

**Comment by puggan** [comment]
Seams to work when I load it in chrome, but when loading it in Firefox i get the same order as in the screenshot.

**Comment by DanielNoord** [comment]
I can reproduce in firefox.

What a weird bug. The sorting is similar to the one used to sort the buildings, which seems to work fine on firefox. I did a quick check for any weird non-supported elements or css properties but did not find any on first glance.
I will have another look soon, but at the moment don't immediately know what is causing this..

**Comment by tsr488** [comment]
@DanielNoord Not sure exactly why this would cause the issue, but I noticed that the upgrade color is not actually being stored on the upgrade objects before sorting. The payback period is stored, but not the color.

Perhaps the color needs to be stored on line ~74 of src/Disp/BuildingsUpgrades/Upgrades.js.

**Comment by DanielNoord** [comment]
Good catch! I will try to see if this fixes it immediately (probably)!
Let you know in a couple of minutes!

**Comment by DanielNoord** [comment]
Fixed!
I expect to push the new version (with this fix) soon(ish). Hopefully by the end of this weekend!

**Comment by tsr488** [comment]
Indeed, all I can think is that the code was previously doing the sorting based solely on this part of the comparison (line 85):
`: a.pp < b.pp`

And for some reason, Firefox (only) is not reaching that part of the comparison any longer. In any case, thanks for the fix.

**Comment by DanielNoord** [comment]
That was probably the case.
I noticed that there was also a problem with the `ColourOrdering` array, as it did not actually have the correct ordering but chrome did order like it did. I changed it as well. This also points to chrome and safari just ordering based on pp and firefox (silently) throwing an error.
