### ISSUE TITLE
'Time Left' for upgrades buggy

### ISSUE THREAD

**Issue by cyrillFB** [Aktanusa/CookieMonster#79]
Since update 2.5 the time left for the upgrades seems buggy. It always shows the time left when I had frenzy, but it is already gone and the time ticks upwards but in irregular steps...
And while frenzy the tick-steps are also strange...

**Comment by SVendittelli** [comment]
This is because time left in now calculated by average CpS over the past 10m as a default. If you go to options, calculation, you can revert it to current CpS.

**Comment by cyrillFB** [comment]
Ah thank you!
I had only noticed this average CPS in the stats without thinking about the usage.
