### ISSUE TITLE
Show "Time Left" for next prestige level in tooltip

### ISSUE THREAD

**Issue by cyrillFB** [Aktanusa/CookieMonster#80]
Just add the time like in the stats menu.

**Comment by Aktanusa** [comment]
The time in the stats menu is actually calculated with cookies earned with Wrinklers and Chocolate Egg so it wouldn't be the same time.  I could probably put the time left based on current CPS though.

**Comment by Aktanusa** [comment]
And whoops, thanks for pointing out a label bug in the stats menu for me.

**Comment by FayneAldan** [comment]
I'd like to see this too. I didn't even know the Stats menu showed this information in the first place.
