### ISSUE TITLE
Beta: Golden Cookie Timer makes clicking Golden Cookies impossible.

### ISSUE THREAD

**Issue by sugarfrosted** [Aktanusa/CookieMonster#81]
What's on the tin.

Disabling the Golden Cookie Timer does seem to make the issue go away even if the same golden cookie is displayed.

**Comment by Aktanusa** [comment]
Weird, I thought it was working fine.  Lesse what did I bork...

**Comment by Aktanusa** [comment]
It works fine here... though I am on Chrome... Time to test FF.

**Comment by Aktanusa** [comment]
Yea it's a Firefox bug.  A related bug is that the GC doesn't highlight like it is suppose to when there is a timer.

**Comment by Aktanusa** [comment]
Let me know if the fix works.  It's out now.

**Comment by sugarfrosted** [comment]
Yup, it's fixed. Thank you!

**Comment by Aktanusa** [comment]
No problem.  Closing...
