### ISSUE TITLE
Estimated Time doesn't update after an Elder Frenzy in the Beta version of Cookie Monster

### ISSUE THREAD

**Issue by audragon** [Aktanusa/CookieMonster#82]
For example, estimated times will be way shorter during an Elder Frenzy, but they don't go back to normal after the Elder Frenzy is over. I only noticed it during Elder Frenzies, but the issue might be there with regular frenzies and the other new GC effects. However, I can only confirm that it happens in Elder Frenzies for sure.

**Comment by Aktanusa** [comment]
This is normal since time is based on average CPS now.  You can change it in options

**Comment by audragon** [comment]
Oh, ok. Thanks, and sorry for the misunderstanding.

**Comment by Aktanusa** [comment]
No problem.  It's a new feature so it's understandable that it might not be obvious at first.
