### ISSUE TITLE
"Done!" but not enough cookies

### ISSUE THREAD

**Issue by kierendavies** [Aktanusa/CookieMonster#83]
"Time Left" on buildings and upgrades seems to consistently behave weirdly.  Instead of seconds ticking down in real time, I've noticed the time doing these things:

* ticking down too slowly (looks like about half speed)
* ticking up (time left increasing)
* jittering around randomly, mostly within a range of a few seconds but sometimes up to about a minute
* "Done!" when I don't have enough cookies

**Comment by Aktanusa** [comment]
Just like Issue #79 and Issue #82.  This is due to time is calculated with average CPS.  You can change it back in options to what it was before, or shorten the history to minimize the effects.

**Comment by kierendavies** [comment]
Sorry for the partial duplication; I neglected to check closed issues.

**Comment by Aktanusa** [comment]
No problem.  Like I mention in another issue, it's pretty understandable that people didn't notice that now it's based on average CPS now which would cause all the problems (quirks?) above.  But in the end the time is actually more accurate now since it's based on average (including wrinklers and golden cookies).

**Comment by Aktanusa** [comment]
Can I close this?

**Comment by kierendavies** [comment]
Buildings are still being marked "Done!" when I don't have enough cookies.  I'll retitle the issue.

**Comment by Aktanusa** [comment]
Are you sure you don't actually have enough cookies once you pop Wrinklers?  If you don't want to include Wrinklers, there is an option to turn that off.

**Comment by kierendavies** [comment]
That is what it seems to be.  Closing.

I think it's worth making this behaviour clearer, although I'm afraid I can't think how.

**Comment by Aktanusa** [comment]
How about rename the label "Done!" to "Done with Wrinklers!" when the option is enabled?

**Comment by kierendavies** [comment]
Is there enough space in the bottom bar?  What about an icon maybe?

**Comment by Aktanusa** [comment]
Icon might be a better idea as with the new timer format from Issue #85, I wouldn't be able to add "with Wrinklers!"

**Comment by Aktanusa** [comment]
Shall I reopen and change the title?

**Comment by kierendavies** [comment]
Your repo, your call ;)
I suggest creating a new issue though

**Comment by Aktanusa** [comment]
But it's your suggestion.  You should open one.  If you don't want to, I'll open it and give you credit.

**Comment by kierendavies** [comment]
Alright, opening a new issue :)
