### ISSUE TITLE
Timers formatting

### ISSUE THREAD

**Issue by JCBourgo** [Aktanusa/CookieMonster#85]
So timers are always moving all over the place in the bottom bar, and it is frustrating the OCD me. Would it be possible to change the "XXd, XXh, XXm, XXs" to a fixed "XX:XX:XX:XX" so it never moves? Maybe with "in:fi:ni:ty", "90:00:da:ys" and some other things to keep it always stable. Thanks!

**Comment by Aktanusa** [comment]
I guess that would be possible.  I guess the format XX:XX:XX:XX:XX?  This includes years, so if it's over 99 years, change the label?  I'm pretty sure something that is infinity or over 99 years won't changes too often.

**Comment by Aktanusa** [comment]
I'll probably make it an option...

**Comment by JCBourgo** [comment]
That's pretty much what I was hoping for. As long as the timer always keeps the same format (with "00:"s if necessary) I would be happy. I had a code snippet for that but I didn't know where or how to put it in... Either way, thank you!

**Comment by Aktanusa** [comment]
If you don't want to wait for my lazy ass, it's the function CM.Disp.FormatTime (first function of the file) in Disp.js

**Comment by Aktanusa** [comment]
The pun over 9000 will be lost =(

**Comment by JCBourgo** [comment]
We could forget the years and just put "XXXX:XX:XX:XX" and keep the over 9000 though ;)

**Comment by JCBourgo** [comment]
Also, if I want to put it in, in which branch do I do it? And how do I make an option? XD

**Comment by Aktanusa** [comment]
I was thinking you would do it locally, but if you want to contribute, it be going to dev first.  Adding options is a bit harder but basically it be Config.js and the function CM.Disp.AddMenuPref in Disp.js

**Comment by Aktanusa** [comment]
XXXX:... doesn't look good to me, so oh well over 9000 would be lost in the XX:... format, but still there everywhere else.

**Comment by JCBourgo** [comment]
I'll try it if I find the time. Thanks! And yes actually XXXX: seems weird. Sacrificing a pun to get something more stable seems like a good deal though.

**Comment by Aktanusa** [comment]
Added to Version 2.6

**Comment by Aktanusa** [comment]
Hmm, just noticed, is it okay "Done!" is still there?

**Comment by JCBourgo** [comment]
Oh, well. Umm... I'd change it to a full "00:00..." set, but I don't know where and what to change...

**Comment by JCBourgo** [comment]
Thanks for that!
On a side-note, I'd like to thank you for this tool (CM as an add-on), and for the opportunity you gave me to just have fun and contribute. If I can continue to help on the project, I'd be glad to. Thanks also for your patience and your kindness, it was appreciated! :)

**Comment by Aktanusa** [comment]
No problem, and thanks =D
