### ISSUE TITLE
Option to calculate Time Left taking "Lucky" deficit into account

### ISSUE THREAD

**Issue by orangy** [Aktanusa/CookieMonster#87]
When not idling, it would be nice to see time left for specific purchase taking Lucky GC reserve into account.

**Comment by JCBourgo** [comment]
@Aktanusa Add a config to have the calculations take the reserve into account? That's something doable.

**Comment by Aktanusa** [comment]
I think this is a duplicate of Issue #67 ?  Let me know if I'm wrong.

**Comment by orangy** [comment]
Yep, indeed, looks like duplicate. Sorry to bother.

**Comment by Aktanusa** [comment]
Nah, it pushes me to get to it, lol

**Comment by DanielNoord** [comment]
This is a duplicate of #67
