### ISSUE TITLE
Add icon in BottomBar whenever the cookies needed is reached (Done!) with or without wrinklers 

### ISSUE THREAD

**Issue by kierendavies** [Aktanusa/CookieMonster#88]
When a building or upgrade can be purchased but only after popping wrinklers, show an icon next to "Done!".

**Comment by Aktanusa** [comment]
Actually I was thinking of showing icon always with a tooltip that says "Calculated with Wrinklers" whenever the option to calculate with Winklers is on, but I think I like your idea better.  It will convey the information that your bank is big enough to buy the item without Wrinklers.

**Comment by JCBourgo** [comment]
Or you could color the "Done!" in a different color. Yellow if you can buy by popping wrinklers, and green when you can buy without them. That will probably be easier to implement and it stands out more visually in my opinion.

**Comment by Aktanusa** [comment]
Yellow is already used when the timer is getting close to 0.  Sure it can be a different color than that though.  I was thinking of maybe doing Issue #67 and #87 with icons also (maybe) so then you get a lot of information simultaneously.  Honestly there is too many combinations so I really don't know hwo to deal with it yet, lol.

**Comment by DanielNoord** [comment]
To be more specific, we would add an icon on the bottombar display of "Done!" if the "Done!" includes the current WrinklerBank.
This means that even if you have that option turned on you can still see if you can also buy it without Wrinklers.
