### ISSUE TITLE
Option to add countdown to "Bake x amount of cookies with this building" to building tooltips

### ISSUE THREAD

**Issue by Elvarion** [Aktanusa/CookieMonster#89]
Would it be possible to add a tooltip when hovering over a building to see how long you have left until you meet the "Bake x amount of cookies with x building" achievements?

I always find myself checking the achievement page before ascending to see if im close to hitting any of those achievs.

**Comment by Aktanusa** [comment]
Hmm, it be possible indeed, but how should I word it?  I guess I'll make it an option or something also since it doesn't seem to fit well (or so I think).

**Comment by DanielNoord** [comment]
@Chorizorro as you have been able to break almost every future in CookieMonster could you take a look at #384 & #385 and see if you see any bugs?

**Comment by Chorizorro** [comment]
Haha, absolutely, I will get right on it!

**Comment by Chorizorro** [comment]
I've been reviewing and testing #384 before noticing #385 was fixing the bug in #384 😅 
I've left a review in #384 which is... not ideal, as the PR is already merged, so I'll just paste it in here:

Looks fine to me 👌

It may be good to remove the "Production left till next achievement" header or show a message like "You already have all the production achievements for this building" to avoid confusion, what do you think?

Also, the refresh rate of the game's building total production counter is way higher than the refresh rate for "Production left till next achievement"; it may be good to have a refresh rate similar (or closer at list) to the production counter as a future enhancement (I imagine this could take some additional work that is not necessary right now, in my opinion)

**Comment by DanielNoord** [comment]
Good idea!
I will get on that right away.

Your suggestion is also a good one. Would you mind making an issue for that?
