### ISSUE TITLE
Change calulate with Wrinklers default to off

### ISSUE THREAD

**Issue by sgoldeen** [Aktanusa/CookieMonster#91]
When I have Wrinklers on my cookie, the amount displayed for Lucky and Lucky Frenzy cookies is correct, but if I have less than the required amount, the color does not change to red.  Doing some testing I have determined that it is adding the cookies I would get from popping the Wrinkers into the calculation for the color and warning boxes, but not the total shown.

Some screenshots to illustrate:
Set my cookies to 0. Note that the "Lucky!" threshold is green, despite having far fewer than the number shown
<img width="1420" alt="screen shot 2016-05-21 at 1 07 25 pm" src="https://cloud.githubusercontent.com/assets/756007/15450648/2e681d30-1f56-11e6-93bf-17c16509e6b6.png">

When I set the number of cookies to just below what is needed, minus the amount I would get for popping the Wrinklers, the time estimate is 1s:
<img width="1420" alt="screen shot 2016-05-21 at 1 12 22 pm" src="https://cloud.githubusercontent.com/assets/756007/15450651/55ba5ed4-1f56-11e6-9d6f-da66e5da0d78.png">

And finally, a little bit later, the color turns to green, despite still being below the required number:
<img width="1420" alt="screen shot 2016-05-21 at 1 12 28 pm" src="https://cloud.githubusercontent.com/assets/756007/15450657/7a22752c-1f56-11e6-92d3-80ec53eb5a4a.png">

The same issue happens with the Caution and Warning boxes for going under the threshold when buying buildings or upgrades:

**Comment by Aktanusa** [comment]
There is an option to turn off Wrinkler calculation.  I think there are people on both sides of the option, meaning some people would want to include Wrinklers for the bank and/or caution/warning,

**Comment by svschouw** [comment]
I think the game setting defaults should be the most intuitive ones. This includes adding wrinklers and the egg in certain calculations, and using "effective" CPS instead of listed idle-CPS for calculations. I think these options should be considered "expert" and should manually be enabled.

That being said, I wasn't sure if @sgoldeen knew about the option, but reported a bug with it, or reported this bug because he didn't know about the option.

**Comment by Aktanusa** [comment]
@sgoldeen: Any thoughts on our comments?

**Comment by sgoldeen** [comment]
I did not know about the option and now I do. I takes care of the issue for me, but i do kind of agree with @svschouw that maybe it should default to "off" for coloring the numbers that tell you the threshold you need.  It might also be more clear if the warning/caution tooltips would tell you that you'd need to pop some wrinklers to get above the threshold.

**Comment by Aktanusa** [comment]
Maybe I misread, but I thought @svschouw was saying the current defaults are fine.  As for making it more clear, hmm, that might be possible.

**Comment by svschouw** [comment]
No, my point was that the current defaults are not that intuitive given the number of "bug reports" about them. Also, I feel like I wouldn't like them. But I must admit that I haven't played since the "effective cps" version, so I don't really know how that works out in practice.

**Comment by Aktanusa** [comment]
I guess my confusion was that you mention the defaults should be most intuitive and then right away mention those two options, so I thought you meant they were intuitive.  Now I see where my misunderstanding is.  Hmm.... I guess I need to think hard on how useful "effective" CPS is.

**Comment by Aktanusa** [comment]
Added in Version 2.0034.3
