### ISSUE TITLE
Add a "buy most efficient building/upgrade" button

### ISSUE THREAD

**Issue by wbehri01** [Aktanusa/CookieMonster#93]
Hey Aktanusa. Thanks for the great addon. I've been using it since I started playing Cookie Clicker again but there's only one thing I'd like to see added. I have the Octillion Fingers PU so I blast through the early game but I always feel like I'm too slow to buy building and upgrades I try to use Frozen Cookies to autobuy for the early game but it slows my game down to around 5fps which obviously lowers production. I know you don't want anything that automates production but it could be a similar feature to Pop All Wrinklers which requires user intervention to perform the action.

Thanks for taking the time to read through this.

**Comment by Aktanusa** [comment]
Hmm...doing single building buy would be fine, but honestly I use the shift/ctrl shortcuts to buy 10/100 buildings.  I see that as way faster than clicking a button that single buys the most efficient building.  Right now I'm not feeling it's a good idea just yet.  I'll see if anyone else has thoughts on this.

**Comment by DanielNoord** [comment]
If we implement this, the button can also serve as an indicator as requested in #76 
I think it is a good idea.

**Comment by DanielNoord** [comment]
After thinking about this some more I don't think there is a good place to add this.
I don't really know where this button would not be too out of place but also not too intrusive. Therefore, I am closing this.
If the issue comes up in the future we might reconsider it!
