### ISSUE TITLE
<1 CPS time bug

### ISSUE THREAD

**Issue by CatsAreFluffy** [Aktanusa/CookieMonster#96]
Something's wrong with the time estimate.

**Comment by Aktanusa** [comment]
What exactly is wrong with it?  If you are on average CPS mode, it will take time for it to correct itself as it is based on history.

**Comment by CatsAreFluffy** [comment]
Okay, I switched to current CpS mode and it works a lot better. Though it's kinda cool to watch the seconds melt away so quickly.

**Comment by Aktanusa** [comment]
It's a trade off.  So your issue is fixed?

**Comment by Aktanusa** [comment]
Closing due to lack of response.
