### ISSUE TITLE
[Steam Version] Game freezes when any Krumblor upgrade is bought

### ISSUE THREAD

**Issue by Eckyx** [Aktanusa/CookieMonster#960]
**Describe the bug**
Purchasing the "Train Breath of Milk" Krumblor upgrade causes the game to freeze just like issue #946. (Tried loading up CM again with other Krumblor upgrades and the issue still persists.)
Any buildings, upgrades, or even the big cookie will not respond when clicked, game progress is also frozen.
However, it is still possible to navigate to and through the options menu to disable CM. 
Doesn't freeze after disabling CM and restarting the game.

**To Reproduce**
1. Load the steam version of the game with Cookie Monster enabled.
2. Buy any Krumblor upgrade.

**Screenshots**

**Save file**
[Poo.txt](https://github.com/CookieMonsterTeam/CookieMonster/files/7104341/Poo.txt)

**Browser**
Steam version.

**Comment by DanielNoord** [comment]
This might be because the Steam version and it Electron wrapper is using an outdated version of chromium. I can't investigate myself, but a screenshot of the console output would be helpful in diagnosing this!

**Comment by ghost** [comment]
When I load the save provided above then 'Restart with new changes' to enable Cookie Monster the game freeze and I get the following in console:
![image](https://user-images.githubusercontent.com/5361016/131981743-1501155a-fa5c-48cb-86fa-13e7c47bbf12.png)
Dragon.js :
```
/** Functions related to the Dragon */

import Beautify from '../../Disp/BeautifyAndFormatting/Beautify';
import CopyData from '../../Sim/SimulationData/CopyData';
import { SimDoSims, SimObjects } from '../../Sim/VariablesAndData';
import { CacheCostDragonUpgrade, CacheLastDragonLevel } from '../VariablesAndData'; // eslint-disable-line no-unused-vars

/**
 * This functions caches the current cost of upgrading the dragon level so it can be displayed in the tooltip
 */
export default function CacheDragonCost() {
  if (CacheLastDragonLevel !== Game.dragonLevel || SimDoSims) {
    if (
      Game.dragonLevel < 25 &&
      Game.dragonLevels[Game.dragonLevel].buy.toString().includes('sacrifice')
    ) {
      let target = Game.dragonLevels[Game.dragonLevel].buy.toString().match(/Objects\[(.*)\]/)[1]; //<-- This is line 17
      const amount = Game.dragonLevels[Game.dragonLevel].buy
        .toString()
        .match(/sacrifice\((.*?)\)/)[1];
      if (target !== 'i') {
        target = target.replaceAll("'", '');
        if (Game.Objects[target].amount < amount) {
          CacheCostDragonUpgrade = 'Not enough buildings to sell';
        } else {
          let cost = 0;
          CopyData();
          for (let i = 0; i < amount; i++) {
            let price =
              SimObjects[target].basePrice *
              Game.priceIncrease **
                Math.max(0, SimObjects[target].amount - 1 - SimObjects[target].free);
            price = Game.modifyBuildingPrice(SimObjects[target], price);
            price = Math.ceil(price);
            cost += price;
            SimObjects[target].amount -= 1;
          }
          CacheCostDragonUpgrade = `Cost to rebuy: ${Beautify(cost)}`;
        }
      } else {
        let cost = 0;
        CopyData();
        Object.keys(Game.Objects).forEach((j) => {
          target = j;
          if (Game.Objects[target].amount < amount) {
            CacheCostDragonUpgrade = 'Not enough buildings to sell';
            return;
          }
          for (let i = 0; i < amount; i++) {
            let price =
              SimObjects[target].basePrice *
              Game.priceIncrease **
                Math.max(0, SimObjects[target].amount - 1 - SimObjects[target].free);
            price = Game.modifyBuildingPrice(SimObjects[target], price);
            price = Math.ceil(price);
            cost += price;
            SimObjects[target].amount -= 1;
          }
          CacheCostDragonUpgrade = `Cost to rebuy: ${Beautify(cost)}`;
        });
      }
    }
    CacheLastDragonLevel = Game.dragonLevel;
  }
}
```

**Comment by DanielNoord** [comment]
Hmm maybe the string had been changed?
It doesn't throw an error on `match()` so regex seems to be available but the string which is being searched might have been changed. Perhaps because of the localisation that is now included?

**Comment by uecasm** [comment]
Oddly, when I get this, while you can still go through the menu to disable CM, it doesn't actually save that change and CM will still load on next startup.  Fortunately the version warning popup lets you prevent CM from loading, which then allows you to actually disable it.

**Comment by scaredtodeaf** [comment]
I have gotten this error as well and game refuses to load CM - Hope this gets resolved soon.

**Comment by Reaver01** [comment]
Looks like the old output of `Game.dragonLevels[Game.dragonLevel].buy.toString()` is `'function(){for (var i in Game.Objects){Game.Objects[i].sacrifice(200);}}'`
The new one is: `"function() {
                            building.sacrifice(100);
                        }"`

**Comment by Reaver01** [comment]
I got this to at least work on my fork to the point it doesn't crash: https://reaver01.github.io/CookieMonster/dist/CookieMonster.js

I don't know the code enough to fix it at almost 1am my time rn. I broke some sort of check, so it'll always say not enough buildings. Hope that at least helps I guess...

Game.dragonLevels[Game.dragonLevel].costStr() outputs the cost so like "100 cursors" which now that I say that is probably the issue because it's Cursor not cursors...

**Comment by Urganot** [comment]
They removed the Object part of the function.
you can get it to run by using my dev link:
Game.registerMod("cookie monster",{
	init:function(){
		Game.LoadMod('https://urganot.github.io/CookieMonster/dist/CookieMonsterDev.js');
	},
});

**Comment by DanielNoord** [comment]
Would you be willing to create a PR?

**Comment by Urganot** [comment]
sure. let me just test it a bit.
there are also some graphical glitches i want to take a look at

**Comment by DanielNoord** [comment]
Did they also change this for the browser version? Or is it just on Steam?

**Comment by Urganot** [comment]
currently, just steam. but the change shouldnt break the web version

**Comment by Urganot** [comment]
@DanielNoord the pr seems to be be failing a check. could you take a look at this? im not really good at this stuff

**Comment by jakyle** [comment]
can confirm, got the dragon the hatch and now I can't use the mod at all on the Steam version of the game.

**Comment by BurnJ** [comment]
Am I able to to use Urganot's dragon fix for my current steam save? Or must I wait for it to merge into the official mod?

**Comment by TFHatGuy** [comment]
> 
> 
> They removed the Object part of the function.
> you can get it to run by using my dev link:
> Game.registerMod("cookie monster",{
> init:function(){
> Game.LoadMod('https://urganot.github.io/CookieMonster/dist/CookieMonsterDev.js');
> },
> });

This allows the game to function after buying a Krumblor upgrade, but the sounds and flashes upon Golden Cookie spawn, or other building events, no longer work.

**Comment by Urganot** [comment]
As far as I can tell this shouldnt have anything to do with the fix.
@DanielNoord Is it possible the game caches the scripts? even after pushing a new version the dev tools still show the old code

**Comment by TFHatGuy** [comment]
> 
> 
> As far as I can tell this shouldnt have anything to do with the fix.

All I know is, the sounds and flashes were working before, when I used @JichouP's temp fix from #973, and now that I've changed it to your version that fixes Krumblor, the sounds and flashes are broken again. I'm not sure what's wrong, because that issue seems to have been fixed as it was, but it's definitely back.

**Comment by Pyrite19** [comment]
I assume the fork was before that hotfix, so if he could refork the current version we might have a close to working version?

**Comment by Urganot** [comment]
That might be the problem. I forked it a few days ago

**Comment by DanielNoord** [comment]
This might now be fixed. Please let me know if the current version works on Steam!

**Comment by Eckyx** [comment]
Yep, it indeed is working fine now on Steam, thank you very much!
