### ISSUE TITLE
[Steam] Changing game settings duplicates Cookie Monster settings

### ISSUE THREAD

**Issue by MyHatStinks** [Aktanusa/CookieMonster#961]
Bit of a strange one here, changing any standard game setting in the Options menu duplicates the Cookie Monster Mod Family menu and the Cookie Monster sub-menu. Duplicates vanish when collapsing or expanding any of the menus.

Issue occurs when changing any standard game setting through the options menu, including the volume sliders; does not occur with the save buttons, mod management buttons, or any button within the Cookie Monster settings.

I'm running on Steam, game version v. 2.04.

Recording attached: 
![2021-09-03_10-40-26](https://user-images.githubusercontent.com/2471776/131985413-5f2de0b9-2711-4f09-aef7-33b50d91af94.gif)

**Comment by DanielNoord** [comment]
Initial thought:
Normally every change to a setting calls `Game.UpdateMenu()` or something like that. This completely rewrites the menu. Cookie Monster then has an event listener looking for changes to the menu `div` and adds its menu.
Perhaps the new situation is that only the `div` of the changed option is updated instead of redrawing the menu. This would still call the event listener of CM and therefore we will append our menu. This might be the problem.

**Comment by DanielNoord** [comment]
This should now be fixed! Let me know if there are any remaining problems!

**Comment by Benna96** [comment]
Not OP, simply happened to find this just now.
On Steam, 2.042.

It's a little bit worse now. There's a Cookie Monster dropdown, and below that there's a Cookie Monster Mod Family dropdown, previously only the Mod Family dropdown existed.
![CookieMonsterBug](https://user-images.githubusercontent.com/23498000/135336707-fda49827-5e3d-43bf-92d0-b4112f042f69.PNG)

The Cookie Monster dropdown is fine, but the Mod Family dropdown still duplicates as before.
![CookieMonsterBug](https://user-images.githubusercontent.com/23498000/135336992-576b96e7-dd4f-41ca-9434-745cb84eb199.PNG)

Perhaps you meant to comment out createMenuOptions from Initialization.js in addition to createMenuInfo? You did add something to do with createMenuOptions into AddMenus.js, after all, pulling from the same file... Idk, just a thought.

**Comment by DanielNoord** [comment]
I commented out `createMenuOptions` from `Initialization.js` all ready but this didn't seem to fix it.

I have pushed a new version with another fix. Can you check if this works?

**Comment by Benna96** [comment]
Working now!
