### ISSUE TITLE
[Steam] Building Information shows at start despite turned OFF

### ISSUE THREAD

**Issue by MeisterJohnny** [Aktanusa/CookieMonster#964]
I like Cookie Monster, but I prefer to play without the Building Information at the bottom, so I turn it off. But every time I import a savefile or restart the game it pops up again, even though the option is still turned off.

I always have to turn it on and off again to fix the issue... nothing critical, but it gets bothersome fast.

I'm running on Steam, game version v. 2.04.

Recording attached:
![BuildingInformationOption](https://user-images.githubusercontent.com/90041188/132007988-dda76696-db7c-49b4-ae4c-47c87c30de64.gif)

(P.S. and the "Third-Party Achievement Unlocked" pops up every time too, even though it isn't even in the Steam Version ^^)

(P.P.S. I can't seem to add the Bug label retroactively... sorry, I just registered here...)

**Comment by 13xforever** [comment]
it's a side effect of #959

**Comment by DanielNoord** [comment]
As #959 is now fixed, has this also been fixed?

**Comment by 13xforever** [comment]
I personally never had any issues with delayed mod load

**Comment by DanielNoord** [comment]
But this was a side-effect of it right? Or did you mean to tag another issue?

**Comment by MeisterJohnny** [comment]
Seems to be fixed. Thanks :)

**Comment by 13xforever** [comment]
Yes, without delay (or fixed mod loading on the game side) lots of stuff got broken, including missing UI elements and broken settings restore, but with delay I had not experienced any issues

**Comment by DanielNoord** [comment]
Good to hear!
