### ISSUE TITLE
[Steam] Upon Importing a Savefile all active buffs vanish and golden cookie timer jumps to 900s

### ISSUE THREAD

**Issue by MeisterJohnny** [Aktanusa/CookieMonster#965]
**Describe the bug**
I played Cookie Clicker for 24h without Cookie Monster and I noticed that exporting and importing a savefile will let you continue exactly where you left off. With all active buffs and I guess the golden cookie timer will stay the way it was upon exporting the savefile. You don't have to wait 15 minutes until the next one appears.

I like Cookie Monster very much. But with Cookie Monster exporting and importing a savefile will remove the active buffs and set the golden cookie timer to ~900 seconds. Can be really bothersome and hinder my progress instead... :'-(

**Browser**
I'm running on Steam, game version v. 2.04.

**Recordings**

Exporting and Importing Savefile without Cookie Monster:
![BuffsStay](https://user-images.githubusercontent.com/90041188/132010543-46e56a90-81bf-4783-a1c6-3ea094ea1476.gif)

Exporting and Importing Savefile with Cookie Monster:
![BuffsVanish](https://user-images.githubusercontent.com/90041188/132010472-321827c4-2364-4de6-9b24-9acd5b4febc0.gif)

**Comment by DanielNoord** [comment]
I can't reproduce this on the browser and don't have a windows computer myself.
I will need to rely on somebody else to investigate this, sorry!

**Comment by NickHam13** [comment]
Also playing on Steam and am unable to replicate this. Can you confirm if it still happens to you?

**Comment by MeisterJohnny** [comment]
Seems to be fixed now. Thanks :)

**Comment by DanielNoord** [comment]
Good to hear!
