### ISSUE TITLE
Option to calculate PP with current CPS including wrinklers

### ISSUE THREAD

**Issue by hypraman** [Aktanusa/CookieMonster#97]
I prefer using calculations using the 'current' CPS rather than the 'average' one as i dislike having number drastically change everytime i click a golden cookie because of the sudden change in the average CPS.

But in this mode, even when the calculations with wrinklers is ON, the 'time left' to purchase only checks at the base CPS without the wrinklers bonus, making it twice as long, but counting down ~12 seconds... every real time seconds...
Example: I should be getting this last kitten upgrade in 233 days from what it says. ( it is normally 117 days, if I pop all 12 wrinklers. )... but the seconds are counting down 12/sec, so the real time is about 19 days. 
So... it doesn't REALLY do the calculation with the wrinklers, like the option is for... right? 
I wish the remaining time would use the current CPS with the wrinkler bonus, but without the drastically changing numbers of when using 'average CPS'. o.o

**Comment by Aktanusa** [comment]
I get what you mean.  It probably isn't hard to implement but I was wondering would it be okay if frenzy still changes the time?

**Comment by hypraman** [comment]
Frenzy already affect the 'time left' calculations by dividing it by 7, and i'm 100% fine with it. 
It just bothers me to see seconds that actually are 1/12th of seconds. 
I know this can be fixed by using 'average CPS' instead, but it doesn't give me an accurate reading since golden cookies doesn't always give the same drops, and cookie-filled golden cookies makes the average number go erratic everytime i take one, giving me even less an accurate reading of the real 'time left'.
Again, i 'could' use the 30minute average to make the average less erratic, but then it means i would need to be clicking Gcookies for at least 30 minute to have a decent reading.

**Comment by Aktanusa** [comment]
That's the point of average CPS.  It really depends how active you are.  If you keep active, the time would be accurate to active play.  If you keep idle, the time would be accurate to idle play.  Etc etc.

Anyway, you answered my question if it's fine that frenzy changes everything.  That's all I needed to know.

**Comment by The-furf-of-July** [comment]
This is still very much an issue, I'm reporting the same problem and I'm unaware if it's related to using average cps or not.

**Comment by DanielNoord** [comment]
If I understand this correctly the request is to add an option to calculate PP based on current CPS that also includes the CPS of Wrinklers, which apparently it does not right now.

**Comment by DanielNoord** [comment]
Please also see #401 which reports on a bug in the same section of code and which could possibly be solved at the same time.
