### ISSUE TITLE
Make the height of the BottomBar resizable

### ISSUE THREAD

**Issue by MackTuesday** [Aktanusa/CookieMonster#98]
![cm](https://cloud.githubusercontent.com/assets/5552036/17070769/76cf09e6-5023-11e6-986d-0741a54090cc.PNG)

Cookie Monster's frame is too short to fit its entire height. I can understand needing to scroll left-right, but this particular issue could be fixed (I think) simply by making CM's frame resizable.

This is in Chrome Version 51.0.2704.103 m.

**Comment by Aktanusa** [comment]
Yea I was hoping to not have to make the bar bigger as I had hoped most people had a big enough screen, lol.  As for a solution, I rather not make the bar taller honestly, but I know there is a problem.
