### ISSUE TITLE
Incompatible with CC Version 2.002

### ISSUE THREAD

**Issue by DanHulton** [Aktanusa/CookieMonster#99]
Cookie Clicker just released a new update, and Cookie Monster does not work at all. =/

**Comment by Aktanusa** [comment]
Yep, I know, the beta script works for it if you want to use that for now until I have time to do some cleanup and move it to live.

**Comment by fallerallera** [comment]
How do you load the beta?

**Comment by Aktanusa** [comment]
Fixed in Version 2.002.1
