### ISSUE TITLE
[Steam] Border colors, buff bars, flash notifications and sounds missing

### ISSUE THREAD

**Issue by razorzerox** [Aktanusa/CookieMonster#993]
### Bug description

From one day to the next the following appeared to happen after the gamer loaded:

1. The bottom bar has no color indication what is the most efficient building.
2. The hover boxes have no color bar whatsoever
3. The upgrade boxes are missing their colored indicator what is the most efficient upgrade
4. The top left bar which should indicate when the next cookie appears does not show anything  
5. No flashes are played (not even when testing flashes from the settings tab)
6. No sounds are played whern golden cookies appear or other cookiemonster actions (no sound either when testing sounds from settings tab)

Number 1-3 you can temporarily fix until the next start of the game if you change the color of a flash notification in the settings tab.
Number 4 you can temporarily fix until the next start of the game if you change the position of the timer bar in the settings tab.

I tried deleting the mod data and changing the order of loading the mods but the problem persisted.

### To reproduce

The steps needed to reproduce:
1. Load the attached save game
2. Problems occur on startup

### Screenshot

![bug](https://user-images.githubusercontent.com/90597634/133033873-c2ae788b-69c5-431f-95ac-c6d5ce4adaf7.png)

### Save file

```Mi4wNDJ8fDE2MzE0Njg3NDAzMzE7MTYzMDg1Njc3NDIyMDsxNjMxNTEwODU5NTcyO0xpY2h0c2NoaW1tZXIncyBHdXRlIFN0dWJlO3B1dnhvfDExMTExMTAxMTAwMTAxMTEwMTAxMDEwMDAwfDE4NTU1Mzc2MjEuNDI4MzYxNDsxOTI4Mzk1NTAwLjQwNDUwODg7NjMwOzkxOTsxODQzMzQyLjE5NTg5OTU2Mzs3OTQ7MDswOzUyODk4NTQwNTk0OTIyMDEwMDAwMDswOzA7MDswOzA7MTs4OzA7MDswOzA7LTE7MDs7MDswOzgwODszNjg7NDQwOzA7MDsxMDg7LTE7LTE7LTE7LTE7MjswOzA7MDsyNTswOzA7Mzs0MTsxNjMxNDY0MDgwMjIwOzA7MDs7MTAwOzA7MDsyMjQzNzkuMDQxNzQzODEwODQ7MDt8NTQsNTQsNzQ2NjUyNzYsMSwsMCw1NDs0NSw0NSwyMDkwMzc3NDksMCwsMSw0NTszMCwzMCw3MTc3MjY3MTMsNywxNjMxNTExMTQ1OTA5OjA6MTYzMTQ2ODc0MDM5MjowOjc6MjAzOjE6MDoxNjMxNDY4NzQwMzkyOiAxMTExMTAxMTEwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwIDA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDoxNDo1MTowOjA6MTM6MTc6MDowOjE0OjQzOjA6MDowOjA6MDowOjA6MDowOjA6MTQ6NTA6MDowOjE0OjUxOjE0OjQ0OjA6MDowOjA6MDowOjA6MDoxNDozNTowOjA6MDowOjA6MDowOjA6MDowOjE0OjQ0OjA6MDoxNDo1MToxNDo1MToxNDoyNzosMCwzMDsxOSwxOSw1MDAzODI2NjQsMCwsMSwxOTszLDMsMjExMDU3NTU4LDAsLDEsMzswLDAsMCwxLDA6MDoxOjA6MTogMjc1NToxOjQ5OjcxMzowOjA6MCE1MDU1OjE6NzA6NDg6MDowOjAhNTk5NToxOjUyOjgwMjowOjA6MCE2MTIzOjE6NTc6NDIxOjA6MTowITQ4ODU6MDotODo0NDA6MDoxOjAhNjQyMDowOi00OjQxNzowOjE6MCE5ODk4OjE6Njk6NTUyOjA6MTowITQ5MjI6MjotNDM6MjQ0OjA6MTowITgyOTY6NTo3OjI5OjA6MTowITM1ODc6NDotMTMzOjI2NTowOjE6MCExMTA3NjowOjEyOjM4ODowOjE6MCExMDEzODoyOi0zNzoxMzI6MDoxOjAhMTA0NDU6MjotMTk6Mjc2OjA6MTowITEwODI2OjI6LTY4OjE2MjowOjE6MCExNTUxNToxOjE0OjM5NjowOjE6MCExNjQzMzoxOjExOjM3OjA6MTowISAwLDAsMDswLDAsMCwxLC0xLy0xLy0xIDMgMTYzMTQ2ODc0MDQwNCAwLDAsMDswLDAsMCwxLDUgMCAxODggMCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDEsLDAsMDswLDAsMCwyLCwwLDA7MCwwLDAsMSwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMSwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwO3wxMTExMTExMTEwMDAwMDExMTExMTExMTExMTEwMDAwMDExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMTAxMDEwMTAxMDEwMTAxMDEwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMTAxMDAwMDAxMTExMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMTExMTAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMTAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMTB8MTExMTExMTExMTExMTAwMDExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMDExMDExMDExMDAwMDExMTAwMTExMTExMTExMTExMTAxMTEwMTAxMDAwMDAwMDExMTAwMTEwMDAwMDAwMDExMTAwMDAwMTEwMDAwMDAwMTEwMDAwMDAwMDAwMDExMDAxMTExMDAwMDAwMTExMDAwMDAwMDAxMTExMTExMTAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTAwMDAwMDAwMTExMDAwMDAwMDAwMDAwMDAwMDAxMTAxMTAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMHx8Q0NTRTp7InZlcnNpb24iOiIyLjAyNiIsIkFjaGlldmVtZW50cyI6eyJDYXJkIG1pbm5vdyI6eyJ3b24iOjF9LCJDYXJkIHRyb3V0Ijp7IndvbiI6MH0sIkNhcmQgc2hhcmsiOnsid29uIjowfSwiRml2ZSBjYXJkIHN0dWQiOnsid29uIjowfSwiV2h5IGNhbid0IEkgaG9sZCBhbGwgdGhlc2UgY2FyZHM/Ijp7IndvbiI6MH0sIkFjZSB1cCB5b3VyIHNsZWV2ZSI6eyJ3b24iOjB9LCJQYWlkIG9mZiB0aGUgZGVhbGVyIjp7IndvbiI6MH0sIkRlYWwgd2l0aCB0aGUgRGV2aWwiOnsid29uIjowfSwiQmxhY2tqYWNrISI6eyJ3b24iOjF9LCJJIGxpa2UgdG8gbGl2ZSBkYW5nZXJvdXNseSI6eyJ3b24iOjB9LCJJIGFsc28gbGlrZSB0byBsaXZlIGRhbmdlcm91c2x5Ijp7IndvbiI6MH19LCJVcGdyYWRlcyI6eyJSYWlzZSB0aGUgc3Rha2VzIjp7InVubG9ja2VkIjoxLCJib3VnaHQiOjB9LCJIaWdoIHJvbGxlciEiOnsidW5sb2NrZWQiOjAsImJvdWdodCI6MH0sIk1hdGggbGVzc29ucyI6eyJ1bmxvY2tlZCI6MCwiYm91Z2h0IjowfSwiQ291bnRpbmcgY2FyZHMiOnsidW5sb2NrZWQiOjAsImJvdWdodCI6MH0sIlRpZWJyZWFrZXIiOnsidW5sb2NrZWQiOjAsImJvdWdodCI6MH0sIkkgbWFrZSBteSBvd24gbHVjayI6eyJ1bmxvY2tlZCI6MCwiYm91Z2h0IjowfSwiSW5maW5pdGUgSW1wcm9iYWJpbGl0eSBEcml2ZSI6eyJ1bmxvY2tlZCI6MCwiYm91Z2h0IjowfSwiRG91YmxlIG9yIG5vdGhpbmciOnsidW5sb2NrZWQiOjAsImJvdWdodCI6MH0sIlN0b25lZCBjb3dzIjp7InVubG9ja2VkIjowLCJib3VnaHQiOjB9LCJBY3R1YWxseSwgZG8gdGVsbCBtZSB0aGUgb2RkcyI6eyJ1bmxvY2tlZCI6MCwiYm91Z2h0IjowfX0sIkJ1aWxkaW5ncyI6e30sIkJ1ZmZzIjp7Imh1cnJpY2FuZSBzdWdhciI6eyJuYW1lIjoiSHVycmktQ2FuZSBTdWdhciIsIm1heFRpbWUiOjAsInRpbWUiOjAsImFyZzEiOjAsImFyZzIiOjAsImFyZzMiOjB9fSwiU2Vhc29ucyI6e30sIk90aGVyTW9kcyI6eyJDYXNpbm8iOiIwXzBfMjhfMF8wXzFfMV8tNDY4OTQ3NjY2MTY4NDk1MDBfMF83NTAgMF8xNjMxNTEwODYwMTg0XzBfMF8yMjQxNTQuNjYyNzAyMDY2OTRfMCAgIDEtMi0zLTQtNS02LTctOC05LTEwLTExLTEyLTEzLTE0LTE1LTE2LTE3LTE4LTE5LTIwLTIxLTIyLTIzLTI0LTI1LTI2LTI3LTI4LTI5LTMwLTMxLTMyLTMzLTM0LTM1LTM2LTM3LTM4LTM5LTQwLTQxLTQyLTQzLTQ0LTQ1LTQ2LTQ3LTQ4LTQ5LTUwLTUxLTUyLTEtMi0zLTQtNS02LTctOC05LTEwLTExLTEyLTEzLTE0LTE1LTE2LTE3LTE4LTE5LTIwLTIxLTIyLTIzLTI0LTI1LTI2LTI3LTI4LTI5LTMwLTMxLTMyLTMzLTM0LTM1LTM2LTM3LTM4LTM5LTQwLTQxLTQyLTQzLTQ0LTQ1LTQ2LTQ3LTQ4LTQ5LTUwLTUxLTUyLTEtMi0zLTQtNS02LTctOC05LTEwLTExLTEyLTEzLTE0LTE1LTE2LTE3LTE4LTE5LTIwLTIxLTIyLTIzLTI0LTI1LTI2LTI3LTI4LTI5LTMwLTMxLTMyLTMzLTM0LTM1LTM2LTM3LTM4LTM5LTQwLTQxLTQyLTQzLTQ0LTQ1LTQ2LTQ3LTQ4LTQ5LTUwLTUxLTUyLTEtMi0zLTQtNS02LTctOC05LTEwLTExLTEyLTEzLTE0LTE1LTE2LTE3LTE4LTE5LTIwLTIxLTIyLTIzLTI0LTI1LTI2LTI3LTI4LTI5LTMwLTMxLTMyLTMzLTM0LTM1LTM2LTM3LTM4LTM5LTQwLTQxLTQyLTQzLTQ0LTQ1LTQ2LTQ3LTQ4LTQ5LTUwLTUxLTUyIDEwMDAwMDAwMTAwIDEwMDAwMDAwMDAwMDAwMDAwMDAwIn0sInZhdWx0IjpbXSwicGVybWFuZW50VXBncmFkZXMiOlstMSwtMSwtMSwtMSwtMV19O0hvcnRpY29va2llOnsiYXV0b0hhcnZlc3QiOjAsImFsbEltbW9ydGFsIjoxLCJhY2NlbEdhcmRlbiI6MX07SWRsZSBUcmFkaW5nOnsiZ29vZHMiOlt7ImFjdGl2ZSI6dHJ1ZSwiYnV5VGhyZXNoIjoxMCwic2VsbFRocmVzaCI6MzQsIm1pblByaWNlIjoxLjk5LCJtYXhQcmljZSI6MzYuOTF9LHsiYWN0aXZlIjp0cnVlLCJidXlUaHJlc2giOjYsInNlbGxUaHJlc2giOjM4LCJtaW5QcmljZSI6MS45LCJtYXhQcmljZSI6NTMuNjN9LHsiYWN0aXZlIjp0cnVlLCJidXlUaHJlc2giOjE2LCJzZWxsVGhyZXNoIjo0MCwibWluUHJpY2UiOjE1LjA2LCJtYXhQcmljZSI6NjguNjR9LHsiYWN0aXZlIjp0cnVlLCJidXlUaHJlc2giOjM4LCJzZWxsVGhyZXNoIjo2MCwibWluUHJpY2UiOjIuODYsIm1heFByaWNlIjo2Ni40NX0seyJhY3RpdmUiOnRydWUsImJ1eVRocmVzaCI6MjAsInNlbGxUaHJlc2giOjcxLCJtaW5QcmljZSI6MTYuMzcsIm1heFByaWNlIjo4NC40OH0seyJhY3RpdmUiOnRydWUsImJ1eVRocmVzaCI6MjIsInNlbGxUaHJlc2giOjc1LCJtaW5QcmljZSI6MjEuNDQsIm1heFByaWNlIjo5NS45M30seyJhY3RpdmUiOnRydWUsImJ1eVRocmVzaCI6LTEsInNlbGxUaHJlc2giOi0xLCJtaW5QcmljZSI6NDguODYsIm1heFByaWNlIjoxMDAuNTl9LHsiYWN0aXZlIjp0cnVlLCJidXlUaHJlc2giOjQwLCJzZWxsVGhyZXNoIjo5NSwibWluUHJpY2UiOjM5LjQxLCJtYXhQcmljZSI6MTAzLjMxfSx7ImFjdGl2ZSI6dHJ1ZSwiYnV5VGhyZXNoIjo1OCwic2VsbFRocmVzaCI6OTgsIm1pblByaWNlIjo1NC4yOCwibWF4UHJpY2UiOjExOC4yM30seyJhY3RpdmUiOnRydWUsImJ1eVRocmVzaCI6OCwic2VsbFRocmVzaCI6MTEwLCJtaW5QcmljZSI6My40OSwibWF4UHJpY2UiOjEyMi40fSx7ImFjdGl2ZSI6dHJ1ZSwiYnV5VGhyZXNoIjo3OSwic2VsbFRocmVzaCI6OTgsIm1pblByaWNlIjo3MS40LCJtYXhQcmljZSI6MTE5LjQ3fSx7ImFjdGl2ZSI6dHJ1ZSwiYnV5VGhyZXNoIjo5Miwic2VsbFRocmVzaCI6MTI1LCJtaW5QcmljZSI6ODkuMzYsIm1heFByaWNlIjoxMzguNzd9LHsiYWN0aXZlIjp0cnVlLCJidXlUaHJlc2giOjI1LCJzZWxsVGhyZXNoIjoxMzUsIm1pblByaWNlIjoxOS40NiwibWF4UHJpY2UiOjE1NC4wN30seyJhY3RpdmUiOnRydWUsImJ1eVRocmVzaCI6MzAsInNlbGxUaHJlc2giOjEyNSwibWluUHJpY2UiOjI0LjczLCJtYXhQcmljZSI6MTcyLjE1fSx7ImFjdGl2ZSI6dHJ1ZSwiYnV5VGhyZXNoIjotMSwic2VsbFRocmVzaCI6LTEsIm1pblByaWNlIjoxMTcuMDIsIm1heFByaWNlIjoxNTkuNTZ9LHsiYWN0aXZlIjp0cnVlLCJidXlUaHJlc2giOjcwLCJzZWxsVGhyZXNoIjoxNDUsIm1pblByaWNlIjo2Ny4xLCJtYXhQcmljZSI6MTY4Ljc5fV0sImF1dG9CdXkiOjEsImF1dG9TZWxsIjoxfTtDb29raWVNb25zdGVyOnsic2V0dGluZ3MiOnsiQ1BTTW9kZSI6MSwiQXZnQ1BTSGlzdCI6MywiQXZnQ2xpY2tzSGlzdCI6MCwiQ2FsY1dyaW5rIjowLCJTY2FsZSI6MiwiU2NhbGVEZWNpbWFscyI6MiwiU2NhbGVTZXBhcmF0b3IiOjAsIlNjYWxlQ3V0b2ZmIjo5OTk5OTksIlRpbWVGb3JtYXQiOjAsIkRldGFpbGVkVGltZSI6MSwiUFBEaXNwbGF5VGltZSI6MCwiQnVpbGRDb2xvdXIiOjEsIlBQT25seUNvbnNpZGVyQnV5YWJsZSI6MCwiUFBFeGNsdWRlVG9wIjowLCJQUFJpZ2lkZWxNb2RlIjowLCJQUFNlY29uZHNMb3dlckxpbWl0IjowLCJDb2xvdXJCbHVlIjoiIzRiYjhmMCIsIkNvbG91ckdyZWVuIjoiIzAwZmYwMCIsIkNvbG91clllbGxvdyI6IiNmZmZmMDAiLCJDb2xvdXJPcmFuZ2UiOiIjZmY3ZjAwIiwiQ29sb3VyUmVkIjoiI2ZmMDAwMCIsIkNvbG91clB1cnBsZSI6IiNmZjAwZmYiLCJDb2xvdXJHcmF5IjoiI2IzYjNiMyIsIkNvbG91clBpbmsiOiIjZmYxNDkzIiwiQ29sb3VyQnJvd24iOiIjOGI0NTEzIiwiQm90QmFyIjoxLCJUaW1lckJhciI6MSwiVGltZXJCYXJQb3MiOjAsIlRpbWVyQmFyT3ZlcmxheSI6MiwiQXV0b3NhdmVUaW1lckJhciI6MCwiVXBCYXJDb2xvdXIiOjEsIlVwZ3JhZGVCYXJGaXhlZFBvcyI6MSwiU29ydEJ1aWxkaW5ncyI6MCwiU29ydFVwZ3JhZGVzIjowLCJVcGdyYWRlc05ldmVyQ29sbGFwc2UiOjAsIkRyYWdvbkF1cmFJbmZvIjoxLCJHcmltb2lyZUJhciI6MSwiR0NUaW1lciI6MSwiRmF2aWNvbiI6MSwiV3JpbmtsZXJCdXR0b25zIjoxLCJIaWRlU2VjdGlvbnNCdXR0b25zIjowLCJUb29sdGlwQnVpbGRVcGdyYWRlIjoxLCJUb29sdGlwQW1vciI6MCwiVG9vbFdhcm5MdWNreSI6MSwiVG9vbFdhcm5MdWNreUZyZW56eSI6MSwiVG9vbFdhcm5Db25qdXJlIjoxLCJUb29sV2FybkNvbmp1cmVGcmVuenkiOjEsIlRvb2xXYXJuRWRpZmljZSI6MSwiVG9vbFdhcm5Vc2VyIjowLCJUb29sV2FybkJvbiI6MSwiVG9vbFdhcm5Qb3MiOjEsIlRvb2x0aXBHcmltIjoxLCJUb29sdGlwV3JpbmsiOjEsIlRvb2x0aXBMdW1wIjoxLCJUb29sdGlwUGxvdHMiOjEsIlRvb2x0aXBQYW50aGVvbiI6MSwiVG9vbHRpcEFzY2VuZEJ1dHRvbiI6MSwiU3RhdHMiOjEsIk1pc3NpbmdVcGdyYWRlcyI6MSwiTWlzc2luZ0FjaGlldmVtZW50cyI6MCwiVXBTdGF0cyI6MSwiSGVhdmVubHlDaGlwc1RhcmdldCI6MSwiU2hvd01pc3NlZEdDIjoxLCJUaXRsZSI6MSwiR2VuZXJhbFNvdW5kIjoxLCJHQ05vdGlmaWNhdGlvbiI6MCwiR0NGbGFzaCI6MSwiQ29sb3VyR0NGbGFzaCI6IiNmZmZmZmYiLCJHQ1NvdW5kIjoxLCJHQ1ZvbHVtZSI6MTAwLCJHQ1NvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvNjYvNjY3MTdfOTMxNjU1LWxxLm1wMyIsIkZvcnR1bmVOb3RpZmljYXRpb24iOjAsIkZvcnR1bmVGbGFzaCI6MSwiQ29sb3VyRm9ydHVuZUZsYXNoIjoiI2ZmZmZmZiIsIkZvcnR1bmVTb3VuZCI6MSwiRm9ydHVuZVZvbHVtZSI6MTAwLCJGb3J0dW5lU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNzQvMTc0MDI3XzMyNDI0OTQtbHEubXAzIiwiU2VhTm90aWZpY2F0aW9uIjowLCJTZWFGbGFzaCI6MSwiQ29sb3VyU2VhRmxhc2giOiIjZmZmZmZmIiwiU2VhU291bmQiOjEsIlNlYVZvbHVtZSI6MTAwLCJTZWFTb3VuZFVSTCI6Imh0dHBzOi8vd3d3LmZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMjEvMTIxMDk5XzIxOTMyNjYtbHEubXAzIiwiR2FyZEZsYXNoIjoxLCJDb2xvdXJHYXJkRmxhc2giOiIjZmZmZmZmIiwiR2FyZFNvdW5kIjoxLCJHYXJkVm9sdW1lIjoxMDAsIkdhcmRTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEwMy8xMDMwNDZfODYxNzE0LWxxLm1wMyIsIk1hZ2ljTm90aWZpY2F0aW9uIjowLCJNYWdpY0ZsYXNoIjoxLCJDb2xvdXJNYWdpY0ZsYXNoIjoiI2ZmZmZmZiIsIk1hZ2ljU291bmQiOjEsIk1hZ2ljVm9sdW1lIjoxMDAsIk1hZ2ljU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8yMjEvMjIxNjgzXzEwMTUyNDAtbHEubXAzIiwiV3JpbmtsZXJOb3RpZmljYXRpb24iOjAsIldyaW5rbGVyRmxhc2giOjEsIkNvbG91cldyaW5rbGVyRmxhc2giOiIjZmZmZmZmIiwiV3JpbmtsZXJTb3VuZCI6MSwiV3JpbmtsZXJWb2x1bWUiOjEwMCwiV3JpbmtsZXJTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyNC8xMjQxODZfODA0My1scS5tcDMiLCJXcmlua2xlck1heE5vdGlmaWNhdGlvbiI6MCwiV3JpbmtsZXJNYXhGbGFzaCI6MSwiQ29sb3VyV3JpbmtsZXJNYXhGbGFzaCI6IiNmZmZmZmYiLCJXcmlua2xlck1heFNvdW5kIjoxLCJXcmlua2xlck1heFZvbHVtZSI6MTAwLCJXcmlua2xlck1heFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTUyLzE1Mjc0M18xNTY2My1scS5tcDMiLCJCdWxrQnV5QmxvY2siOjEsIkZhdm91cml0ZVNldHRpbmdzIjoxfSwiaGVhZGVycyI6eyJGYXZvdXJpdGUiOjEsIkNhbGN1bGF0aW9uIjoxLCJOb3RhdGlvbiI6MSwiQ29sb3VycyI6MSwiQmFyc0Rpc3BsYXkiOjEsIlRvb2x0aXAiOjEsIlN0YXRpc3RpY3MiOjEsIk5vdGlmaWNhdGlvbiI6MSwiTm90aWZpY2F0aW9uR2VuZXJhbCI6MSwiTm90aWZpY2F0aW9uR0MiOjEsIk5vdGlmaWNhdGlvbkZDIjoxLCJOb3RpZmljYXRpb25TZWEiOjEsIk5vdGlmaWNhdGlvbkdhcmQiOjEsIk5vdGlmaWNhdGlvbk1hZ2kiOjEsIk5vdGlmaWNhdGlvbldyaW5rIjoxLCJOb3RpZmljYXRpb25Xcmlua01heCI6MSwiTWlzY2VsbGFuZW91cyI6MSwiTHVja3kiOjEsIkNoYWluIjoxLCJTcGVsbHMiOjEsIkdhcmRlbiI6MSwiUHJlc3RpZ2UiOjEsIldyaW5rIjoxLCJTZWEiOjEsIkFjaGlldnMiOjEsIk1pc2MiOjEsImluZm9NZW51IjoxLCJvcHRpb25zTWVudSI6MX0sImZhdm91cml0ZVNldHRpbmdzIjpbXSwidmVyc2lvbiI6IjIuMDMxLjEwIn07Y29va2llTW9uc3RlckZyYW1ld29yazp7InNldHRpbmdzIjp7fSwiaGVhZGVycyI6eyJpbmZvTWVudSI6MSwib3B0aW9uc01lbnUiOjF9LCJmYXZvdXJpdGVTZXR0aW5ncyI6W119O01FVEE6Q0NTRSxDYXNpbm8sSG9ydGljb29raWUsSHVycmljYW5lIFN1Z2FyLElkbGUgVHJhZGluZyxTdGVhbSBBY2hpZXZlbWVudCBFbmFibGVyLGNvb2tpZSBtb25zdGVyOw%3D%3D%21END%21```

### Browser / Steam / Version

Steam Version 2.042

**Comment by razorzerox** [comment]
I found the culprit :)

Don't load CookieMonster together with the Casino Mod. Once I disabled the Casino Mod everything worked again.
Its strange though that the combination worked for a week and then randomly the problems began.

**Comment by DanielNoord** [comment]
Do you have a link to the Casino Mod for me? I want to check something! :)
