### ISSUE TITLE
Cookie clicker get stuck on loading

### ISSUE THREAD

**Issue by lopsbud** [Aktanusa/CookieMonster#996]
### Bug description

Cookie clicker gets stuck on the loading screen only if I have the mod installed

### To reproduce

Launch the game with the mod installed

### Save file

Mi4wNDJ8fDE2MzE2NDM2MDYzNDU7MTYzMDQ1MjMxODE0NjsxNjMxNzA4NjgyOTY2O2xvcHNidWQ7emF2dmF8MTExMTExMTExMDAxMDExMTAxMTEwMTEwMDB8NDAyNDA0NTM5MzkxNzk4NTAwOzQ5NDEwNDIwMjQxMDQ4NTgwMDA7NDA0OzEwMzU7MTYxNDY2NTY4MDI2Mzg3MTAwOzIyMTk7MDswOzg1NDYzNDU3MTg5ODYwMjAwMDAwOzA7MDswOzY4OzUzMDY7MTs3NDswOzA7MDswOzA7MDs7MDswOzQ0MDswOzQ0MDswOzA7MTA4Oy0xOy0xOy0xOy0xOzk7MTswOzA7MTAwOzA7MDsyOzE0OzE2MzE3MDA3NDcwODA7MDswOzsxMDA7MDswOzYyMDE1NzM0MjI2ODA2OC44OzA7fDE4MiwyODIsMTU5OTYxMjQ1Nzc3NTU3LDEsLDAsMTgyOzIxNiwzMTYsMTc5Mjk1NzYxNDA3MjA0NywxLCwwLDIxNjsxMjksMjI5LDk1NTU1MTEyMjAxNiwzLDE2MzE3MDg4NTk5NzA6MToxNjMxNjQ2NjYxMzYzOjA6OTo4OToxOjA6MTYzMTY0MzYwNjM1NzogMTExMTEwMTAwMDAwMDEwMDAwMDAwMDAxMDAwMDAwMDAwMCAwOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDosMCwxMjk7MTEzLDIxMywzMDk4MTc4Njg5OTk2LDAsLDAsMTEzOzk3LDk3LDYzNDg3ODQ3MDA0NTQsMSwsMCw5Nzs4NSw4NiwyNjY3NjMwMDA1MzE0OSwxLDA6MDowOjA6MDogMjgwNzoxOjIyOjI4NzowOjA6MCE1MTg0OjE6NTA6MTM5OjA6MDowITI1OTY6NTotNTY6NzA2OjA6MDowITk2MzoyOi02NTo2MDg6MDowOjAhNjM3Nzo1OjM0OjEzMzowOjA6MCE5NjQ6NDotODU6NTg0OjA6MDowITcxMDc6MDotNToxNTI6MDowOjAhOTU5NToxOjQ0OjQwOjA6MDowITEwMzM1OjU6NjI6MzEyOjA6MDowITEwNDk5OjE6OTo4NDE6MDowOjAhODMyNjoyOi02ODoyOTk6MDowOjAhNDAxNDo0Oi0yMTY6MzE2OjA6MDowITEzNTExOjE6MTc6NDQyOjA6MDowITMyNjk6NDotMjE0OjUyNDowOjA6MCExNTU2MjoxOjEyOjIxNDowOjE6MCExNjQ3NDoxOjE2OjE3MzowOjE6MCEgMCwwLDg1Ozc2LDc2LDExOTc1MjM2NzA0ODkyMywxLC0xLy0xLy0xIDMgMTYzMTY0MzYwNjM2NCAwLDAsNzY7NjcsNjcsNTMzMzUxODAzNTI1NTU4LDEsNDEgNSAxNDMgMSwwLDY3OzYwLDYxLDIyNTYyMzA3OTU4MDQ4NTcsMCwsMCw2MDs0OCw0OCw2NTY1ODM2NzE1MDU2ODI4LDAsLDAsNDg7NDMsNDMsMzMwNDMwNDQwMzYxNTE3NzAsMCwsMCw0MzszNywzOSwxNjgxOTQwNjI3OTE5MDIxMDAsMCwsMCwzNzszMywzMyw2NDA1NzgzMTM2NjAyNzk3MDAsMCwsMCwzMzsyMywyMywxMjg4NTAwMTIyMTM2MjU1MjAwLDAsLDAsMjM7MTQsMTQsMTYzMzgzMzE3MzgyNTc0MTAwMCwwLCwwLDE0OzQsNCw3Njc5NTg1MzgxODUyMzQ2MDAsMCwsMCw0OzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7fDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDExMTExMTExMDAxMTExMDAwMDAwMDAxMTAwMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMDAxMTExMDAxMTAwMDAwMDAwMDAxMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTAwMDAwMDExMDAwMDAwMDAwMDAwMTAwMDAwMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTEwMDAwMTExMTExMTEwMDAwMTExMTExMTEwMDAwMTExMTExMTExMTExMTExMTExMTExMDEwMTAxMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDExMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMXwxMTExMTExMTExMTEwMDAwMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTEwMTEwMDAwMTExMDExMTExMTEwMDAxMDExMDExMTAxMDAwMDAwMDAwMTExMTAxMDAwMDAwMDAwMTExMDAwMDAxMDAwMDAwMDAxMTAwMDAwMDAwMDAwMTEwMDExMDEwMDAwMDAxMTEwMDAwMDAwMDExMTExMDExMTAwMTExMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTEwMDAwMDAwMDAxMTEwMDAwMDAwMDAwMDAwMDAwMDExMDEwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwfDAsNDYyMCw0MzA3LDc7fENvb2tpZU1vbnN0ZXI6eyJzZXR0aW5ncyI6eyJDUFNNb2RlIjoxLCJBdmdDUFNIaXN0IjozLCJBdmdDbGlja3NIaXN0IjowLCJDYWxjV3JpbmsiOjAsIlNjYWxlIjowLCJTY2FsZURlY2ltYWxzIjoyLCJTY2FsZVNlcGFyYXRvciI6MCwiU2NhbGVDdXRvZmYiOjk5OTk5OSwiVGltZUZvcm1hdCI6MSwiRGV0YWlsZWRUaW1lIjoxLCJQUERpc3BsYXlUaW1lIjowLCJCdWlsZENvbG91ciI6MSwiUFBPbmx5Q29uc2lkZXJCdXlhYmxlIjowLCJQUEV4Y2x1ZGVUb3AiOjAsIlBQUmlnaWRlbE1vZGUiOjAsIlBQU2Vjb25kc0xvd2VyTGltaXQiOjAsIkNvbG91ckJsdWUiOiIjNGJiOGYwIiwiQ29sb3VyR3JlZW4iOiIjMDBmZjAwIiwiQ29sb3VyWWVsbG93IjoiI2ZmZmYwMCIsIkNvbG91ck9yYW5nZSI6IiNmZjdmMDAiLCJDb2xvdXJSZWQiOiIjZmYwMDAwIiwiQ29sb3VyUHVycGxlIjoiI2ZmMDBmZiIsIkNvbG91ckdyYXkiOiIjYjNiM2IzIiwiQ29sb3VyUGluayI6IiNmZjE0OTMiLCJDb2xvdXJCcm93biI6IiM4YjQ1MTMiLCJCb3RCYXIiOjAsIlRpbWVyQmFyIjoxLCJUaW1lckJhclBvcyI6MCwiVGltZXJCYXJPdmVybGF5IjoyLCJBdXRvc2F2ZVRpbWVyQmFyIjowLCJVcEJhckNvbG91ciI6MSwiVXBncmFkZUJhckZpeGVkUG9zIjoxLCJTb3J0QnVpbGRpbmdzIjowLCJTb3J0VXBncmFkZXMiOjAsIlVwZ3JhZGVzTmV2ZXJDb2xsYXBzZSI6MCwiRHJhZ29uQXVyYUluZm8iOjEsIkdyaW1vaXJlQmFyIjoxLCJHQ1RpbWVyIjoxLCJGYXZpY29uIjoxLCJXcmlua2xlckJ1dHRvbnMiOjEsIkhpZGVTZWN0aW9uc0J1dHRvbnMiOjAsIlRvb2x0aXBCdWlsZFVwZ3JhZGUiOjEsIlRvb2x0aXBBbW9yIjowLCJUb29sV2Fybkx1Y2t5IjoxLCJUb29sV2Fybkx1Y2t5RnJlbnp5IjoxLCJUb29sV2FybkNvbmp1cmUiOjEsIlRvb2xXYXJuQ29uanVyZUZyZW56eSI6MSwiVG9vbFdhcm5FZGlmaWNlIjoxLCJUb29sV2FyblVzZXIiOjAsIlRvb2xXYXJuQm9uIjoxLCJUb29sV2FyblBvcyI6MSwiVG9vbHRpcEdyaW0iOjEsIlRvb2x0aXBXcmluayI6MSwiVG9vbHRpcEx1bXAiOjEsIlRvb2x0aXBQbG90cyI6MSwiVG9vbHRpcFBhbnRoZW9uIjoxLCJUb29sdGlwQXNjZW5kQnV0dG9uIjoxLCJTdGF0cyI6MSwiTWlzc2luZ1VwZ3JhZGVzIjowLCJNaXNzaW5nQWNoaWV2ZW1lbnRzIjowLCJVcFN0YXRzIjoxLCJIZWF2ZW5seUNoaXBzVGFyZ2V0IjoxLCJTaG93TWlzc2VkR0MiOjEsIlRpdGxlIjoxLCJHZW5lcmFsU291bmQiOjEsIkdDTm90aWZpY2F0aW9uIjoxLCJHQ0ZsYXNoIjoxLCJDb2xvdXJHQ0ZsYXNoIjoiI2ZmZmZmZiIsIkdDU291bmQiOjEsIkdDVm9sdW1lIjoxMDAsIkdDU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy82Ni82NjcxN185MzE2NTUtbHEubXAzIiwiRm9ydHVuZU5vdGlmaWNhdGlvbiI6MCwiRm9ydHVuZUZsYXNoIjoxLCJDb2xvdXJGb3J0dW5lRmxhc2giOiIjZmZmZmZmIiwiRm9ydHVuZVNvdW5kIjoxLCJGb3J0dW5lVm9sdW1lIjoxMDAsIkZvcnR1bmVTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzE3NC8xNzQwMjdfMzI0MjQ5NC1scS5tcDMiLCJTZWFOb3RpZmljYXRpb24iOjAsIlNlYUZsYXNoIjoxLCJDb2xvdXJTZWFGbGFzaCI6IiNmZmZmZmYiLCJTZWFTb3VuZCI6MSwiU2VhVm9sdW1lIjoxMDAsIlNlYVNvdW5kVVJMIjoiaHR0cHM6Ly93d3cuZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyMS8xMjEwOTlfMjE5MzI2Ni1scS5tcDMiLCJHYXJkRmxhc2giOjEsIkNvbG91ckdhcmRGbGFzaCI6IiNmZmZmZmYiLCJHYXJkU291bmQiOjEsIkdhcmRWb2x1bWUiOjEwMCwiR2FyZFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMzg3LzM4NzA4M182NTEyOTczLWxxLm1wMyIsIk1hZ2ljTm90aWZpY2F0aW9uIjowLCJNYWdpY0ZsYXNoIjoxLCJDb2xvdXJNYWdpY0ZsYXNoIjoiI2ZmZmZmZiIsIk1hZ2ljU291bmQiOjEsIk1hZ2ljVm9sdW1lIjoxMDAsIk1hZ2ljU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8yMjEvMjIxNjgzXzEwMTUyNDAtbHEubXAzIiwiV3JpbmtsZXJOb3RpZmljYXRpb24iOjAsIldyaW5rbGVyRmxhc2giOjEsIkNvbG91cldyaW5rbGVyRmxhc2giOiIjZmZmZmZmIiwiV3JpbmtsZXJTb3VuZCI6MSwiV3JpbmtsZXJWb2x1bWUiOjEwMCwiV3JpbmtsZXJTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyNC8xMjQxODZfODA0My1scS5tcDMiLCJXcmlua2xlck1heE5vdGlmaWNhdGlvbiI6MCwiV3JpbmtsZXJNYXhGbGFzaCI6MSwiQ29sb3VyV3JpbmtsZXJNYXhGbGFzaCI6IiNmZmZmZmYiLCJXcmlua2xlck1heFNvdW5kIjoxLCJXcmlua2xlck1heFZvbHVtZSI6MTAwLCJXcmlua2xlck1heFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTUyLzE1Mjc0M18xNTY2My1scS5tcDMiLCJCdWxrQnV5QmxvY2siOjEsIkZhdm91cml0ZVNldHRpbmdzIjoxfSwiaGVhZGVycyI6eyJGYXZvdXJpdGUiOjEsIkNhbGN1bGF0aW9uIjoxLCJOb3RhdGlvbiI6MSwiQ29sb3VycyI6MSwiQmFyc0Rpc3BsYXkiOjEsIlRvb2x0aXAiOjEsIlN0YXRpc3RpY3MiOjEsIk5vdGlmaWNhdGlvbiI6MSwiTm90aWZpY2F0aW9uR2VuZXJhbCI6MSwiTm90aWZpY2F0aW9uR0MiOjEsIk5vdGlmaWNhdGlvbkZDIjoxLCJOb3RpZmljYXRpb25TZWEiOjEsIk5vdGlmaWNhdGlvbkdhcmQiOjEsIk5vdGlmaWNhdGlvbk1hZ2kiOjEsIk5vdGlmaWNhdGlvbldyaW5rIjoxLCJOb3RpZmljYXRpb25Xcmlua01heCI6MSwiTWlzY2VsbGFuZW91cyI6MSwiTHVja3kiOjEsIkNoYWluIjoxLCJTcGVsbHMiOjEsIkdhcmRlbiI6MSwiUHJlc3RpZ2UiOjEsIldyaW5rIjoxLCJTZWEiOjEsIkFjaGlldnMiOjEsIk1pc2MiOjEsImluZm9NZW51IjoxLCJvcHRpb25zTWVudSI6MX0sImZhdm91cml0ZVNldHRpbmdzIjpbXSwibG9ja2VkTWluaWdhbWVzIjpbXSwidmVyc2lvbiI6IjIuMDMxLjEwIn07Y29va2llTW9uc3RlckZyYW1ld29yazp7InNldHRpbmdzIjp7fSwiaGVhZGVycyI6eyJpbmZvTWVudSI6MSwib3B0aW9uc01lbnUiOjF9LCJmYXZvdXJpdGVTZXR0aW5ncyI6W119O01FVEE6KmNvb2xlciBzYW1wbGUgbW9kLCpsYW5nIHNhbXBsZSBtb2QsKnNhbXBsZSBtb2QsOw%3D%3D%21END%21

### Browser / Steam / Version

Steam, version 2.042

**Comment by lopsbud** [comment]
Oh and I forgot to add it worked perfectly until now

**Comment by DanielNoord** [comment]
Do you use any other mods?

**Comment by lopsbud** [comment]
> Do you use any other mods?

I don't have any other mods

**Comment by Yakasuki** [comment]
Do you have "AllowSteamAchievs": 1 in the info.txt? cause having it enabled causes infinite loading.

**Comment by lopsbud** [comment]
> Do you have "AllowSteamAchievs": 1 in the info.txt? cause having it enabled causes infinite loading.

I removed it and I still get stuck on loading.
Here's my info.txt
`{
	“Name”: “Cookie Monster”,
	“ID”: “cookie monster”,
	“Author”: “Jan Odvarko – East Desire”,
	“Description”: “Cookie Monster is an addon you can load into Cookie Clicker, that offers a wide range of tools and statistics to enhance the game.”,
	“ModVersion”: 2.031,
	“GameVersion”: 2.031,
	“Date”: “25/07/2021”,
	“Dependencies”: [],
	“Disabled”: 1
}`

and my main.js
`Game.LoadMod("https://cookiemonsterteam.github.io/CookieMonster/dist/CookieMonster.js");`

**Comment by lopsbud** [comment]
ok I fixed it,
I just remade the files and it fixed itself.
