### ISSUE TITLE
Game freezes when Options menu is opened

### ISSUE THREAD

**Issue by Tony1PointO** [Aktanusa/CookieMonster#999]
### Bug description

I'm using Chrome, and when I enter the Options menu with Cookie Monster running, or when I start Cookie Monster while in the Options menu, the game freezes.

This is in Chrome.

### To reproduce

Enter options menu.

### Browser / Steam / Version

Chrome Version 93.0.4577.82

**Comment by DanielNoord** [comment]
Do you know how to open your browser console? And if so can you see if it produces any errors?

**Comment by Tony1PointO** [comment]
I can no longer reproduce this issue. Closing case.
